var hierarchy =
[
    [ "UnityEditor.AssetModificationProcessor", null, [
      [ "ES3Postprocessor", "classES3Postprocessor.html", null ]
    ] ],
    [ "Attribute", null, [
      [ "ES3NonSerializable", "classES3NonSerializable.html", null ],
      [ "ES3Serializable", "classES3Serializable.html", null ]
    ] ],
    [ "System.Attribute", null, [
      [ "ES3Types.ES3PropertiesAttribute", "classES3Types_1_1ES3PropertiesAttribute.html", null ]
    ] ],
    [ "BackupCrewData", "structBackupCrewData.html", null ],
    [ "BlueprintRoomSaveData", "classBlueprintRoomSaveData.html", null ],
    [ "BlueprintSaveData", "classBlueprintSaveData.html", null ],
    [ "BlueprintSlotSaveWrapper", "classBlueprintSlotSaveWrapper.html", null ],
    [ "BlueprintWeaponSaveData", "classBlueprintWeaponSaveData.html", null ],
    [ "CombatUIController", "classCombatUIController.html", null ],
    [ "CrewCardSaveData", "classCrewCardSaveData.html", null ],
    [ "CrewData", "classCrewData.html", null ],
    [ "CrewEffect", "classCrewEffect.html", null ],
    [ "CrewInfoWrapper", "classCrewInfoWrapper.html", null ],
    [ "RoomDatabase.CrewQuartersDataEntry", "classRoomDatabase_1_1CrewQuartersDataEntry.html", null ],
    [ "CrewRaceOption", "classCrewRaceOption.html", null ],
    [ "ShipTemplate.CrewTemplate", "classShipTemplate_1_1CrewTemplate.html", null ],
    [ "DamageHitPointPair", "classDamageHitPointPair.html", null ],
    [ "Dictionary", null, [
      [ "ES3Internal.ES3SerializableDictionary< TKey, TVal >", "classES3Internal_1_1ES3SerializableDictionary.html", null ]
    ] ],
    [ "DoorData.DoorLevel", "classDoorData_1_1DoorLevel.html", null ],
    [ "DoorPosition", "structDoorPosition.html", null ],
    [ "UnityEditor.Editor", null, [
      [ "ES3Editor.AddES3Prefab", "classES3Editor_1_1AddES3Prefab.html", null ],
      [ "ES3Editor.RemoveES3Prefab", "classES3Editor_1_1RemoveES3Prefab.html", null ],
      [ "ES3EditorUtility", "classES3EditorUtility.html", null ],
      [ "ES3InspectorInfoEditor", "classES3InspectorInfoEditor.html", null ],
      [ "ES3Internal.ES3AutoSaveEditor", "classES3Internal_1_1ES3AutoSaveEditor.html", null ],
      [ "ES3Internal.ES3AutoSaveMgrEditor", "classES3Internal_1_1ES3AutoSaveMgrEditor.html", null ],
      [ "ES3Internal.ES3GameObjectEditor", "classES3Internal_1_1ES3GameObjectEditor.html", null ],
      [ "ES3Internal.ES3GlobalReferencesEditor", "classES3Internal_1_1ES3GlobalReferencesEditor.html", null ],
      [ "ES3PrefabEditor", "classES3PrefabEditor.html", null ],
      [ "ES3ReferenceMgrEditor", "classES3ReferenceMgrEditor.html", null ],
      [ "EnableES3AssemblyDefinitions", "classEnableES3AssemblyDefinitions.html", null ]
    ] ],
    [ "ES3Editor.EditorStyle", "classES3Editor_1_1EditorStyle.html", null ],
    [ "EditorWindow", null, [
      [ "ES3Editor.ES3Window", "classES3Editor_1_1ES3Window.html", null ],
      [ "ES3Internal.SetReferenceID", "classES3Internal_1_1SetReferenceID.html", null ]
    ] ],
    [ "ES3Internal.EncryptionAlgorithm", "classES3Internal_1_1EncryptionAlgorithm.html", [
      [ "ES3Internal.AESEncryptionAlgorithm", "classES3Internal_1_1AESEncryptionAlgorithm.html", null ]
    ] ],
    [ "EquipmentStats", "classEquipmentStats.html", null ],
    [ "ES3", "classES3.html", null ],
    [ "ES3Internal.ES3Data", "structES3Internal_1_1ES3Data.html", null ],
    [ "ES3File", "classES3File.html", null ],
    [ "ES3Internal.ES3Member", "classES3Internal_1_1ES3Member.html", null ],
    [ "ES3Reader.ES3ReaderPropertyEnumerator", "classES3Reader_1_1ES3ReaderPropertyEnumerator.html", null ],
    [ "ES3Reader.ES3ReaderRawEnumerator", "classES3Reader_1_1ES3ReaderRawEnumerator.html", null ],
    [ "ES3Ref", "classES3Ref.html", null ],
    [ "ES3Internal.ES3Reflection.ES3ReflectedMember", "structES3Internal_1_1ES3Reflection_1_1ES3ReflectedMember.html", null ],
    [ "ES3Internal.ES3Reflection.ES3ReflectedMethod", "classES3Internal_1_1ES3Reflection_1_1ES3ReflectedMethod.html", null ],
    [ "ES3ScriptingDefineSymbols", "classES3ScriptingDefineSymbols.html", null ],
    [ "ES3Internal.ES3SerializableDictionary< long, UnityEngine.Object >", "classES3Internal_1_1ES3SerializableDictionary.html", [
      [ "ES3Internal.ES3IdRefDictionary", "classES3Internal_1_1ES3IdRefDictionary.html", null ]
    ] ],
    [ "ES3Internal.ES3SerializableDictionary< UnityEngine.Object, long >", "classES3Internal_1_1ES3SerializableDictionary.html", [
      [ "ES3Internal.ES3RefIdDictionary", "classES3Internal_1_1ES3RefIdDictionary.html", null ]
    ] ],
    [ "ES3Spreadsheet", "classES3Spreadsheet.html", null ],
    [ "ES3Types.ES3Type", "classES3Types_1_1ES3Type.html", [
      [ "ES3Types.ES3CollectionType", "classES3Types_1_1ES3CollectionType.html", [
        [ "ES3Types.ES32DArrayType", "classES3Types_1_1ES32DArrayType.html", null ],
        [ "ES3Types.ES33DArrayType", "classES3Types_1_1ES33DArrayType.html", null ],
        [ "ES3Types.ES3ArrayType", "classES3Types_1_1ES3ArrayType.html", [
          [ "ES3Types.ES3Type_AudioClipArray", "classES3Types_1_1ES3Type__AudioClipArray.html", null ],
          [ "ES3Types.ES3Type_BigIntegerArray", "classES3Types_1_1ES3Type__BigIntegerArray.html", null ],
          [ "ES3Types.ES3Type_BoneWeightArray", "classES3Types_1_1ES3Type__BoneWeightArray.html", null ],
          [ "ES3Types.ES3Type_BoundsArray", "classES3Types_1_1ES3Type__BoundsArray.html", null ],
          [ "ES3Types.ES3Type_BurstArray", "classES3Types_1_1ES3Type__BurstArray.html", null ],
          [ "ES3Types.ES3Type_Color32Array", "classES3Types_1_1ES3Type__Color32Array.html", null ],
          [ "ES3Types.ES3Type_ColorArray", "classES3Types_1_1ES3Type__ColorArray.html", null ],
          [ "ES3Types.ES3Type_DateTimeArray", "classES3Types_1_1ES3Type__DateTimeArray.html", null ],
          [ "ES3Types.ES3Type_ES3RefArray", "classES3Types_1_1ES3Type__ES3RefArray.html", null ],
          [ "ES3Types.ES3Type_FlareArray", "classES3Types_1_1ES3Type__FlareArray.html", null ],
          [ "ES3Types.ES3Type_FontArray", "classES3Types_1_1ES3Type__FontArray.html", null ],
          [ "ES3Types.ES3Type_GameObjectArray", "classES3Types_1_1ES3Type__GameObjectArray.html", null ],
          [ "ES3Types.ES3Type_GradientAlphaKeyArray", "classES3Types_1_1ES3Type__GradientAlphaKeyArray.html", null ],
          [ "ES3Types.ES3Type_GradientColorKeyArray", "classES3Types_1_1ES3Type__GradientColorKeyArray.html", null ],
          [ "ES3Types.ES3Type_GuidArray", "classES3Types_1_1ES3Type__GuidArray.html", null ],
          [ "ES3Types.ES3Type_IntPtrArray", "classES3Types_1_1ES3Type__IntPtrArray.html", null ],
          [ "ES3Types.ES3Type_KeyframeArray", "classES3Types_1_1ES3Type__KeyframeArray.html", null ],
          [ "ES3Types.ES3Type_MaterialArray", "classES3Types_1_1ES3Type__MaterialArray.html", null ],
          [ "ES3Types.ES3Type_Matrix4x4Array", "classES3Types_1_1ES3Type__Matrix4x4Array.html", null ],
          [ "ES3Types.ES3Type_MeshColliderArray", "classES3Types_1_1ES3Type__MeshColliderArray.html", null ],
          [ "ES3Types.ES3Type_MeshFilterArray", "classES3Types_1_1ES3Type__MeshFilterArray.html", null ],
          [ "ES3Types.ES3Type_MeshRendererArray", "classES3Types_1_1ES3Type__MeshRendererArray.html", null ],
          [ "ES3Types.ES3Type_PhysicMaterialArray", "classES3Types_1_1ES3Type__PhysicMaterialArray.html", null ],
          [ "ES3Types.ES3Type_PhysicsMaterial2DArray", "classES3Types_1_1ES3Type__PhysicsMaterial2DArray.html", null ],
          [ "ES3Types.ES3Type_PolygonCollider2DArray", "classES3Types_1_1ES3Type__PolygonCollider2DArray.html", null ],
          [ "ES3Types.ES3Type_QuaternionArray", "classES3Types_1_1ES3Type__QuaternionArray.html", null ],
          [ "ES3Types.ES3Type_RandomArray", "classES3Types_1_1ES3Type__RandomArray.html", null ],
          [ "ES3Types.ES3Type_RenderTextureArray", "classES3Types_1_1ES3Type__RenderTextureArray.html", null ],
          [ "ES3Types.ES3Type_ShaderArray", "classES3Types_1_1ES3Type__ShaderArray.html", null ],
          [ "ES3Types.ES3Type_SkinnedMeshRendererArray", "classES3Types_1_1ES3Type__SkinnedMeshRendererArray.html", null ],
          [ "ES3Types.ES3Type_SpriteRendererArray", "classES3Types_1_1ES3Type__SpriteRendererArray.html", null ],
          [ "ES3Types.ES3Type_StringArray", "classES3Types_1_1ES3Type__StringArray.html", null ],
          [ "ES3Types.ES3Type_Texture2DArray", "classES3Types_1_1ES3Type__Texture2DArray.html", null ],
          [ "ES3Types.ES3Type_TextureArray", "classES3Types_1_1ES3Type__TextureArray.html", null ],
          [ "ES3Types.ES3Type_UIntPtrArray", "classES3Types_1_1ES3Type__UIntPtrArray.html", null ],
          [ "ES3Types.ES3Type_Vector2Array", "classES3Types_1_1ES3Type__Vector2Array.html", null ],
          [ "ES3Types.ES3Type_Vector3Array", "classES3Types_1_1ES3Type__Vector3Array.html", null ],
          [ "ES3Types.ES3Type_Vector4Array", "classES3Types_1_1ES3Type__Vector4Array.html", null ],
          [ "ES3Types.ES3Type_boolArray", "classES3Types_1_1ES3Type__boolArray.html", null ],
          [ "ES3Types.ES3Type_charArray", "classES3Types_1_1ES3Type__charArray.html", null ],
          [ "ES3Types.ES3Type_decimalArray", "classES3Types_1_1ES3Type__decimalArray.html", null ],
          [ "ES3Types.ES3Type_doubleArray", "classES3Types_1_1ES3Type__doubleArray.html", null ],
          [ "ES3Types.ES3Type_floatArray", "classES3Types_1_1ES3Type__floatArray.html", null ],
          [ "ES3Types.ES3Type_intArray", "classES3Types_1_1ES3Type__intArray.html", null ],
          [ "ES3Types.ES3Type_longArray", "classES3Types_1_1ES3Type__longArray.html", null ],
          [ "ES3Types.ES3Type_sbyteArray", "classES3Types_1_1ES3Type__sbyteArray.html", null ],
          [ "ES3Types.ES3Type_shortArray", "classES3Types_1_1ES3Type__shortArray.html", null ],
          [ "ES3Types.ES3Type_uintArray", "classES3Types_1_1ES3Type__uintArray.html", null ],
          [ "ES3Types.ES3Type_ulongArray", "classES3Types_1_1ES3Type__ulongArray.html", null ],
          [ "ES3Types.ES3Type_ushortArray", "classES3Types_1_1ES3Type__ushortArray.html", null ],
          [ "ES3Types.ES3UserType_AmmunitionRoomArray", "classES3Types_1_1ES3UserType__AmmunitionRoomArray.html", null ],
          [ "ES3Types.ES3UserType_AmmunitionRoomDataArray", "classES3Types_1_1ES3UserType__AmmunitionRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_AmmunitionRoomLevelArray", "classES3Types_1_1ES3UserType__AmmunitionRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_ArrayListArray", "classES3Types_1_1ES3UserType__ArrayListArray.html", null ],
          [ "ES3Types.ES3UserType_CockpitRoomArray", "classES3Types_1_1ES3UserType__CockpitRoomArray.html", null ],
          [ "ES3Types.ES3UserType_CockpitRoomDataArray", "classES3Types_1_1ES3UserType__CockpitRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_CockpitRoomLevelArray", "classES3Types_1_1ES3UserType__CockpitRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_CorridorRoomArray", "classES3Types_1_1ES3UserType__CorridorRoomArray.html", null ],
          [ "ES3Types.ES3UserType_CorridorRoomDataArray", "classES3Types_1_1ES3UserType__CorridorRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_CorridorRoomLevelArray", "classES3Types_1_1ES3UserType__CorridorRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_CrewHealthBarArray", "classES3Types_1_1ES3UserType__CrewHealthBarArray.html", null ],
          [ "ES3Types.ES3UserType_CrewMemberArray", "classES3Types_1_1ES3UserType__CrewMemberArray.html", null ],
          [ "ES3Types.ES3UserType_CrewQuartersRoomArray", "classES3Types_1_1ES3UserType__CrewQuartersRoomArray.html", null ],
          [ "ES3Types.ES3UserType_CrewQuartersRoomDataArray", "classES3Types_1_1ES3UserType__CrewQuartersRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_CrewQuartersRoomLevelArray", "classES3Types_1_1ES3UserType__CrewQuartersRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_CrewSystemArray", "classES3Types_1_1ES3UserType__CrewSystemArray.html", null ],
          [ "ES3Types.ES3UserType_DoorPositionArray", "classES3Types_1_1ES3UserType__DoorPositionArray.html", null ],
          [ "ES3Types.ES3UserType_EngineRoomArray", "classES3Types_1_1ES3UserType__EngineRoomArray.html", null ],
          [ "ES3Types.ES3UserType_EngineRoomDataArray", "classES3Types_1_1ES3UserType__EngineRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_EngineRoomLevelArray", "classES3Types_1_1ES3UserType__EngineRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_EquipmentItemArray", "classES3Types_1_1ES3UserType__EquipmentItemArray.html", null ],
          [ "ES3Types.ES3UserType_HitPointSystemArray", "classES3Types_1_1ES3UserType__HitPointSystemArray.html", null ],
          [ "ES3Types.ES3UserType_LifeSupportRoomArray", "classES3Types_1_1ES3UserType__LifeSupportRoomArray.html", null ],
          [ "ES3Types.ES3UserType_LifeSupportRoomDataArray", "classES3Types_1_1ES3UserType__LifeSupportRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_LifeSupportRoomDataEntryArray", "classES3Types_1_1ES3UserType__LifeSupportRoomDataEntryArray.html", null ],
          [ "ES3Types.ES3UserType_LifeSupportRoomLevelArray", "classES3Types_1_1ES3UserType__LifeSupportRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_MedBayRoomArray", "classES3Types_1_1ES3UserType__MedBayRoomArray.html", null ],
          [ "ES3Types.ES3UserType_MedBayRoomDataArray", "classES3Types_1_1ES3UserType__MedBayRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_MedBayRoomLevelArray", "classES3Types_1_1ES3UserType__MedBayRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_MoraleEffectDataArray", "classES3Types_1_1ES3UserType__MoraleEffectDataArray.html", null ],
          [ "ES3Types.ES3UserType_MoraleIconArray", "classES3Types_1_1ES3UserType__MoraleIconArray.html", null ],
          [ "ES3Types.ES3UserType_MoraleSystemArray", "classES3Types_1_1ES3UserType__MoraleSystemArray.html", null ],
          [ "ES3Types.ES3UserType_OuterHullArray", "classES3Types_1_1ES3UserType__OuterHullArray.html", null ],
          [ "ES3Types.ES3UserType_OuterHullDataArray", "classES3Types_1_1ES3UserType__OuterHullDataArray.html", null ],
          [ "ES3Types.ES3UserType_OuterHullLevelArray", "classES3Types_1_1ES3UserType__OuterHullLevelArray.html", null ],
          [ "ES3Types.ES3UserType_OuterHullSystemArray", "classES3Types_1_1ES3UserType__OuterHullSystemArray.html", null ],
          [ "ES3Types.ES3UserType_OxygenLevelArray", "classES3Types_1_1ES3UserType__OxygenLevelArray.html", null ],
          [ "ES3Types.ES3UserType_OxygenRoomArray", "classES3Types_1_1ES3UserType__OxygenRoomArray.html", null ],
          [ "ES3Types.ES3UserType_OxygenRoomDataArray", "classES3Types_1_1ES3UserType__OxygenRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_OxygenSystemArray", "classES3Types_1_1ES3UserType__OxygenSystemArray.html", null ],
          [ "ES3Types.ES3UserType_PlanetArray", "classES3Types_1_1ES3UserType__PlanetArray.html", null ],
          [ "ES3Types.ES3UserType_PlanetDataArray", "classES3Types_1_1ES3UserType__PlanetDataArray.html", null ],
          [ "ES3Types.ES3UserType_PlanetEffectArray", "classES3Types_1_1ES3UserType__PlanetEffectArray.html", null ],
          [ "ES3Types.ES3UserType_PlayerDataArray", "classES3Types_1_1ES3UserType__PlayerDataArray.html", null ],
          [ "ES3Types.ES3UserType_PowerRoomArray", "classES3Types_1_1ES3UserType__PowerRoomArray.html", null ],
          [ "ES3Types.ES3UserType_PowerRoomDataArray", "classES3Types_1_1ES3UserType__PowerRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_PowerRoomLevelArray", "classES3Types_1_1ES3UserType__PowerRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_PowerSystemArray", "classES3Types_1_1ES3UserType__PowerSystemArray.html", null ],
          [ "ES3Types.ES3UserType_QuestObjectiveArray", "classES3Types_1_1ES3UserType__QuestObjectiveArray.html", null ],
          [ "ES3Types.ES3UserType_QuestRewardArray", "classES3Types_1_1ES3UserType__QuestRewardArray.html", null ],
          [ "ES3Types.ES3UserType_RandomQuestArray", "classES3Types_1_1ES3UserType__RandomQuestArray.html", null ],
          [ "ES3Types.ES3UserType_ResourcesDataArray", "classES3Types_1_1ES3UserType__ResourcesDataArray.html", null ],
          [ "ES3Types.ES3UserType_RigidbodyArray", "classES3Types_1_1ES3UserType__RigidbodyArray.html", null ],
          [ "ES3Types.ES3UserType_RoomDamageRatesArray", "classES3Types_1_1ES3UserType__RoomDamageRatesArray.html", null ],
          [ "ES3Types.ES3UserType_RoomDataEntryArray", "classES3Types_1_1ES3UserType__RoomDataEntryArray.html", null ],
          [ "ES3Types.ES3UserType_RoomLevelArray", "classES3Types_1_1ES3UserType__RoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_ShieldRoomArray", "classES3Types_1_1ES3UserType__ShieldRoomArray.html", null ],
          [ "ES3Types.ES3UserType_ShieldRoomDataArray", "classES3Types_1_1ES3UserType__ShieldRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_ShieldRoomLevelArray", "classES3Types_1_1ES3UserType__ShieldRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_ShieldSystemArray", "classES3Types_1_1ES3UserType__ShieldSystemArray.html", null ],
          [ "ES3Types.ES3UserType_ShipArray", "classES3Types_1_1ES3UserType__ShipArray.html", null ],
          [ "ES3Types.ES3UserType_ShipWeaponArray", "classES3Types_1_1ES3UserType__ShipWeaponArray.html", null ],
          [ "ES3Types.ES3UserType_ShipWeaponDataArray", "classES3Types_1_1ES3UserType__ShipWeaponDataArray.html", null ],
          [ "ES3Types.ES3UserType_SkillValueArray", "classES3Types_1_1ES3UserType__SkillValueArray.html", null ],
          [ "ES3Types.ES3UserType_StorageRoomAnimalArray", "classES3Types_1_1ES3UserType__StorageRoomAnimalArray.html", null ],
          [ "ES3Types.ES3UserType_StorageRoomBaseLevelArray", "classES3Types_1_1ES3UserType__StorageRoomBaseLevelArray.html", null ],
          [ "ES3Types.ES3UserType_StorageRoomDataEntryArray", "classES3Types_1_1ES3UserType__StorageRoomDataEntryArray.html", null ],
          [ "ES3Types.ES3UserType_StorageRoomRegularArray", "classES3Types_1_1ES3UserType__StorageRoomRegularArray.html", null ],
          [ "ES3Types.ES3UserType_StorageRoomTemperatureArray", "classES3Types_1_1ES3UserType__StorageRoomTemperatureArray.html", null ],
          [ "ES3Types.ES3UserType_StorageSystemArray", "classES3Types_1_1ES3UserType__StorageSystemArray.html", null ],
          [ "ES3Types.ES3UserType_TeleportRoomArray", "classES3Types_1_1ES3UserType__TeleportRoomArray.html", null ],
          [ "ES3Types.ES3UserType_TeleportRoomDataArray", "classES3Types_1_1ES3UserType__TeleportRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_TeleportRoomLevelArray", "classES3Types_1_1ES3UserType__TeleportRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_TradingItemArray", "classES3Types_1_1ES3UserType__TradingItemArray.html", null ],
          [ "ES3Types.ES3UserType_TradingItemDataArray", "classES3Types_1_1ES3UserType__TradingItemDataArray.html", null ],
          [ "ES3Types.ES3UserType_WarpNodeDataArray", "classES3Types_1_1ES3UserType__WarpNodeDataArray.html", null ],
          [ "ES3Types.ES3UserType_WeaponControlRoomArray", "classES3Types_1_1ES3UserType__WeaponControlRoomArray.html", null ],
          [ "ES3Types.ES3UserType_WeaponControlRoomDataArray", "classES3Types_1_1ES3UserType__WeaponControlRoomDataArray.html", null ],
          [ "ES3Types.ES3UserType_WeaponControlRoomLevelArray", "classES3Types_1_1ES3UserType__WeaponControlRoomLevelArray.html", null ],
          [ "ES3Types.ES3UserType_WeaponSystemArray", "classES3Types_1_1ES3UserType__WeaponSystemArray.html", null ],
          [ "ES3Types.ES3UserType_WorldNodeArray", "classES3Types_1_1ES3UserType__WorldNodeArray.html", null ],
          [ "ES3Types.ES3UserType_WorldNodeDataArray", "classES3Types_1_1ES3UserType__WorldNodeDataArray.html", null ]
        ] ],
        [ "ES3Types.ES3HashSetType", "classES3Types_1_1ES3HashSetType.html", null ],
        [ "ES3Types.ES3IListGenericType", "classES3Types_1_1ES3IListGenericType.html", null ],
        [ "ES3Types.ES3ListType", "classES3Types_1_1ES3ListType.html", null ],
        [ "ES3Types.ES3NativeArrayType", "classES3Types_1_1ES3NativeArrayType.html", null ],
        [ "ES3Types.ES3QueueType", "classES3Types_1_1ES3QueueType.html", null ],
        [ "ES3Types.ES3StackType", "classES3Types_1_1ES3StackType.html", null ]
      ] ],
      [ "ES3Types.ES3ConcurrentDictionaryType", "classES3Types_1_1ES3ConcurrentDictionaryType.html", null ],
      [ "ES3Types.ES3DictionaryType", "classES3Types_1_1ES3DictionaryType.html", [
        [ "ES3Types.ES3Type_ES3RefDictionary", "classES3Types_1_1ES3Type__ES3RefDictionary.html", null ]
      ] ],
      [ "ES3Types.ES3GenericType", "classES3Types_1_1ES3GenericType.html", null ],
      [ "ES3Types.ES3ObjectType", "classES3Types_1_1ES3ObjectType.html", [
        [ "ES3Types.ES3Type_ArrayList", "classES3Types_1_1ES3Type__ArrayList.html", null ],
        [ "ES3Types.ES3Type_PhysicMaterial", "classES3Types_1_1ES3Type__PhysicMaterial.html", null ],
        [ "ES3Types.ES3Type_PhysicsMaterial2D", "classES3Types_1_1ES3Type__PhysicsMaterial2D.html", null ],
        [ "ES3Types.ES3Type_Random", "classES3Types_1_1ES3Type__Random.html", null ],
        [ "ES3Types.ES3Type_RenderTexture", "classES3Types_1_1ES3Type__RenderTexture.html", null ],
        [ "ES3Types.ES3UnityObjectType", "classES3Types_1_1ES3UnityObjectType.html", [
          [ "ES3Types.ES3ComponentType", "classES3Types_1_1ES3ComponentType.html", [
            [ "ES3Types.ES3Type_BoxCollider", "classES3Types_1_1ES3Type__BoxCollider.html", null ],
            [ "ES3Types.ES3Type_BoxCollider2D", "classES3Types_1_1ES3Type__BoxCollider2D.html", null ],
            [ "ES3Types.ES3Type_Camera", "classES3Types_1_1ES3Type__Camera.html", null ],
            [ "ES3Types.ES3Type_CapsuleCollider", "classES3Types_1_1ES3Type__CapsuleCollider.html", null ],
            [ "ES3Types.ES3Type_Light", "classES3Types_1_1ES3Type__Light.html", null ],
            [ "ES3Types.ES3Type_MeshCollider", "classES3Types_1_1ES3Type__MeshCollider.html", null ],
            [ "ES3Types.ES3Type_MeshFilter", "classES3Types_1_1ES3Type__MeshFilter.html", null ],
            [ "ES3Types.ES3Type_MeshRenderer", "classES3Types_1_1ES3Type__MeshRenderer.html", null ],
            [ "ES3Types.ES3Type_ParticleSystem", "classES3Types_1_1ES3Type__ParticleSystem.html", null ],
            [ "ES3Types.ES3Type_PolygonCollider2D", "classES3Types_1_1ES3Type__PolygonCollider2D.html", null ],
            [ "ES3Types.ES3Type_RectTransform", "classES3Types_1_1ES3Type__RectTransform.html", null ],
            [ "ES3Types.ES3Type_Rigidbody", "classES3Types_1_1ES3Type__Rigidbody.html", null ],
            [ "ES3Types.ES3Type_SkinnedMeshRenderer", "classES3Types_1_1ES3Type__SkinnedMeshRenderer.html", null ],
            [ "ES3Types.ES3Type_SphereCollider", "classES3Types_1_1ES3Type__SphereCollider.html", null ],
            [ "ES3Types.ES3Type_SpriteRenderer", "classES3Types_1_1ES3Type__SpriteRenderer.html", null ],
            [ "ES3Types.ES3Type_Transform", "classES3Types_1_1ES3Type__Transform.html", null ],
            [ "ES3Types.ES3UserType_AmmunitionRoom", "classES3Types_1_1ES3UserType__AmmunitionRoom.html", null ],
            [ "ES3Types.ES3UserType_CockpitRoom", "classES3Types_1_1ES3UserType__CockpitRoom.html", null ],
            [ "ES3Types.ES3UserType_CorridorRoom", "classES3Types_1_1ES3UserType__CorridorRoom.html", null ],
            [ "ES3Types.ES3UserType_CrewHealthBar", "classES3Types_1_1ES3UserType__CrewHealthBar.html", null ],
            [ "ES3Types.ES3UserType_CrewMember", "classES3Types_1_1ES3UserType__CrewMember.html", null ],
            [ "ES3Types.ES3UserType_CrewQuartersRoom", "classES3Types_1_1ES3UserType__CrewQuartersRoom.html", null ],
            [ "ES3Types.ES3UserType_EngineRoom", "classES3Types_1_1ES3UserType__EngineRoom.html", null ],
            [ "ES3Types.ES3UserType_LifeSupportRoom", "classES3Types_1_1ES3UserType__LifeSupportRoom.html", null ],
            [ "ES3Types.ES3UserType_MedBayRoom", "classES3Types_1_1ES3UserType__MedBayRoom.html", null ],
            [ "ES3Types.ES3UserType_MoraleIcon", "classES3Types_1_1ES3UserType__MoraleIcon.html", null ],
            [ "ES3Types.ES3UserType_OuterHull", "classES3Types_1_1ES3UserType__OuterHull.html", null ],
            [ "ES3Types.ES3UserType_OxygenRoom", "classES3Types_1_1ES3UserType__OxygenRoom.html", null ],
            [ "ES3Types.ES3UserType_Planet", "classES3Types_1_1ES3UserType__Planet.html", null ],
            [ "ES3Types.ES3UserType_PowerRoom", "classES3Types_1_1ES3UserType__PowerRoom.html", null ],
            [ "ES3Types.ES3UserType_ShieldRoom", "classES3Types_1_1ES3UserType__ShieldRoom.html", null ],
            [ "ES3Types.ES3UserType_Ship", "classES3Types_1_1ES3UserType__Ship.html", null ],
            [ "ES3Types.ES3UserType_ShipWeapon", "classES3Types_1_1ES3UserType__ShipWeapon.html", null ],
            [ "ES3Types.ES3UserType_StorageRoomAnimal", "classES3Types_1_1ES3UserType__StorageRoomAnimal.html", null ],
            [ "ES3Types.ES3UserType_StorageRoomRegular", "classES3Types_1_1ES3UserType__StorageRoomRegular.html", null ],
            [ "ES3Types.ES3UserType_StorageRoomTemperature", "classES3Types_1_1ES3UserType__StorageRoomTemperature.html", null ],
            [ "ES3Types.ES3UserType_TeleportRoom", "classES3Types_1_1ES3UserType__TeleportRoom.html", null ],
            [ "ES3Types.ES3UserType_TradingItem", "classES3Types_1_1ES3UserType__TradingItem.html", null ],
            [ "ES3Types.ES3UserType_WeaponControlRoom", "classES3Types_1_1ES3UserType__WeaponControlRoom.html", null ],
            [ "ES3Types.ES3UserType_WorldNode", "classES3Types_1_1ES3UserType__WorldNode.html", null ]
          ] ],
          [ "ES3Types.ES3ScriptableObjectType", "classES3Types_1_1ES3ScriptableObjectType.html", [
            [ "ES3Types.ES3UserType_AmmunitionRoomData", "classES3Types_1_1ES3UserType__AmmunitionRoomData.html", null ],
            [ "ES3Types.ES3UserType_CockpitRoomData", "classES3Types_1_1ES3UserType__CockpitRoomData.html", null ],
            [ "ES3Types.ES3UserType_CorridorRoomData", "classES3Types_1_1ES3UserType__CorridorRoomData.html", null ],
            [ "ES3Types.ES3UserType_CrewQuartersRoomData", "classES3Types_1_1ES3UserType__CrewQuartersRoomData.html", null ],
            [ "ES3Types.ES3UserType_EngineRoomData", "classES3Types_1_1ES3UserType__EngineRoomData.html", null ],
            [ "ES3Types.ES3UserType_EquipmentItem", "classES3Types_1_1ES3UserType__EquipmentItem.html", null ],
            [ "ES3Types.ES3UserType_LifeSupportRoomData", "classES3Types_1_1ES3UserType__LifeSupportRoomData.html", null ],
            [ "ES3Types.ES3UserType_MedBayRoomData", "classES3Types_1_1ES3UserType__MedBayRoomData.html", null ],
            [ "ES3Types.ES3UserType_OuterHullData", "classES3Types_1_1ES3UserType__OuterHullData.html", null ],
            [ "ES3Types.ES3UserType_OxygenRoomData", "classES3Types_1_1ES3UserType__OxygenRoomData.html", null ],
            [ "ES3Types.ES3UserType_PowerRoomData", "classES3Types_1_1ES3UserType__PowerRoomData.html", null ],
            [ "ES3Types.ES3UserType_ShieldRoomData", "classES3Types_1_1ES3UserType__ShieldRoomData.html", null ],
            [ "ES3Types.ES3UserType_ShipWeaponData", "classES3Types_1_1ES3UserType__ShipWeaponData.html", null ],
            [ "ES3Types.ES3UserType_TeleportRoomData", "classES3Types_1_1ES3UserType__TeleportRoomData.html", null ],
            [ "ES3Types.ES3UserType_TradingItemData", "classES3Types_1_1ES3UserType__TradingItemData.html", null ],
            [ "ES3Types.ES3UserType_WeaponControlRoomData", "classES3Types_1_1ES3UserType__WeaponControlRoomData.html", null ]
          ] ],
          [ "ES3Types.ES3Type_AudioClip", "classES3Types_1_1ES3Type__AudioClip.html", null ],
          [ "ES3Types.ES3Type_Font", "classES3Types_1_1ES3Type__Font.html", null ],
          [ "ES3Types.ES3Type_GameObject", "classES3Types_1_1ES3Type__GameObject.html", null ],
          [ "ES3Types.ES3Type_Material", "classES3Types_1_1ES3Type__Material.html", null ],
          [ "ES3Types.ES3Type_Mesh", "classES3Types_1_1ES3Type__Mesh.html", null ],
          [ "ES3Types.ES3Type_Sprite", "classES3Types_1_1ES3Type__Sprite.html", null ],
          [ "ES3Types.ES3Type_Texture2D", "classES3Types_1_1ES3Type__Texture2D.html", null ]
        ] ],
        [ "ES3Types.ES3UserType_AmmunitionRoomLevel", "classES3Types_1_1ES3UserType__AmmunitionRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_CockpitRoomLevel", "classES3Types_1_1ES3UserType__CockpitRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_CorridorRoomLevel", "classES3Types_1_1ES3UserType__CorridorRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_CrewQuartersRoomLevel", "classES3Types_1_1ES3UserType__CrewQuartersRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_CrewSystem", "classES3Types_1_1ES3UserType__CrewSystem.html", null ],
        [ "ES3Types.ES3UserType_EngineRoomLevel", "classES3Types_1_1ES3UserType__EngineRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_HitPointSystem", "classES3Types_1_1ES3UserType__HitPointSystem.html", null ],
        [ "ES3Types.ES3UserType_LifeSupportRoomDataEntry", "classES3Types_1_1ES3UserType__LifeSupportRoomDataEntry.html", null ],
        [ "ES3Types.ES3UserType_LifeSupportRoomLevel", "classES3Types_1_1ES3UserType__LifeSupportRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_MedBayRoomLevel", "classES3Types_1_1ES3UserType__MedBayRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_MoraleEffectData", "classES3Types_1_1ES3UserType__MoraleEffectData.html", null ],
        [ "ES3Types.ES3UserType_MoraleSystem", "classES3Types_1_1ES3UserType__MoraleSystem.html", null ],
        [ "ES3Types.ES3UserType_OuterHullLevel", "classES3Types_1_1ES3UserType__OuterHullLevel.html", null ],
        [ "ES3Types.ES3UserType_OuterHullSystem", "classES3Types_1_1ES3UserType__OuterHullSystem.html", null ],
        [ "ES3Types.ES3UserType_OxygenLevel", "classES3Types_1_1ES3UserType__OxygenLevel.html", null ],
        [ "ES3Types.ES3UserType_OxygenSystem", "classES3Types_1_1ES3UserType__OxygenSystem.html", null ],
        [ "ES3Types.ES3UserType_PlanetData", "classES3Types_1_1ES3UserType__PlanetData.html", null ],
        [ "ES3Types.ES3UserType_PlanetEffect", "classES3Types_1_1ES3UserType__PlanetEffect.html", null ],
        [ "ES3Types.ES3UserType_PlayerData", "classES3Types_1_1ES3UserType__PlayerData.html", null ],
        [ "ES3Types.ES3UserType_PowerRoomLevel", "classES3Types_1_1ES3UserType__PowerRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_PowerSystem", "classES3Types_1_1ES3UserType__PowerSystem.html", null ],
        [ "ES3Types.ES3UserType_QuestObjective", "classES3Types_1_1ES3UserType__QuestObjective.html", null ],
        [ "ES3Types.ES3UserType_QuestReward", "classES3Types_1_1ES3UserType__QuestReward.html", null ],
        [ "ES3Types.ES3UserType_RandomQuest", "classES3Types_1_1ES3UserType__RandomQuest.html", null ],
        [ "ES3Types.ES3UserType_ResourcesData", "classES3Types_1_1ES3UserType__ResourcesData.html", null ],
        [ "ES3Types.ES3UserType_RoomDamageRates", "classES3Types_1_1ES3UserType__RoomDamageRates.html", null ],
        [ "ES3Types.ES3UserType_RoomDataEntry", "classES3Types_1_1ES3UserType__RoomDataEntry.html", null ],
        [ "ES3Types.ES3UserType_RoomLevel", "classES3Types_1_1ES3UserType__RoomLevel.html", null ],
        [ "ES3Types.ES3UserType_ShieldRoomLevel", "classES3Types_1_1ES3UserType__ShieldRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_ShieldSystem", "classES3Types_1_1ES3UserType__ShieldSystem.html", null ],
        [ "ES3Types.ES3UserType_SkillValue", "classES3Types_1_1ES3UserType__SkillValue.html", null ],
        [ "ES3Types.ES3UserType_StorageRoomBaseLevel", "classES3Types_1_1ES3UserType__StorageRoomBaseLevel.html", null ],
        [ "ES3Types.ES3UserType_StorageRoomDataEntry", "classES3Types_1_1ES3UserType__StorageRoomDataEntry.html", null ],
        [ "ES3Types.ES3UserType_StorageSystem", "classES3Types_1_1ES3UserType__StorageSystem.html", null ],
        [ "ES3Types.ES3UserType_TeleportRoomLevel", "classES3Types_1_1ES3UserType__TeleportRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_WarpNodeData", "classES3Types_1_1ES3UserType__WarpNodeData.html", null ],
        [ "ES3Types.ES3UserType_WeaponControlRoomLevel", "classES3Types_1_1ES3UserType__WeaponControlRoomLevel.html", null ],
        [ "ES3Types.ES3UserType_WeaponSystem", "classES3Types_1_1ES3UserType__WeaponSystem.html", null ],
        [ "ES3Types.ES3UserType_WorldNodeData", "classES3Types_1_1ES3UserType__WorldNodeData.html", null ]
      ] ],
      [ "ES3Types.ES3TupleType", "classES3Types_1_1ES3TupleType.html", null ],
      [ "ES3Types.ES3Type_AnimationCurve", "classES3Types_1_1ES3Type__AnimationCurve.html", null ],
      [ "ES3Types.ES3Type_BigInteger", "classES3Types_1_1ES3Type__BigInteger.html", null ],
      [ "ES3Types.ES3Type_BoneWeight", "classES3Types_1_1ES3Type__BoneWeight.html", null ],
      [ "ES3Types.ES3Type_Bounds", "classES3Types_1_1ES3Type__Bounds.html", null ],
      [ "ES3Types.ES3Type_Burst", "classES3Types_1_1ES3Type__Burst.html", null ],
      [ "ES3Types.ES3Type_CollisionModule", "classES3Types_1_1ES3Type__CollisionModule.html", null ],
      [ "ES3Types.ES3Type_Color", "classES3Types_1_1ES3Type__Color.html", null ],
      [ "ES3Types.ES3Type_Color32", "classES3Types_1_1ES3Type__Color32.html", null ],
      [ "ES3Types.ES3Type_ColorBySpeedModule", "classES3Types_1_1ES3Type__ColorBySpeedModule.html", null ],
      [ "ES3Types.ES3Type_ColorOverLifetimeModule", "classES3Types_1_1ES3Type__ColorOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_DateTime", "classES3Types_1_1ES3Type__DateTime.html", null ],
      [ "ES3Types.ES3Type_ES3Prefab", "classES3Types_1_1ES3Type__ES3Prefab.html", null ],
      [ "ES3Types.ES3Type_ES3PrefabInternal", "classES3Types_1_1ES3Type__ES3PrefabInternal.html", null ],
      [ "ES3Types.ES3Type_ES3Ref", "classES3Types_1_1ES3Type__ES3Ref.html", null ],
      [ "ES3Types.ES3Type_EmissionModule", "classES3Types_1_1ES3Type__EmissionModule.html", null ],
      [ "ES3Types.ES3Type_ExternalForcesModule", "classES3Types_1_1ES3Type__ExternalForcesModule.html", null ],
      [ "ES3Types.ES3Type_Flare", "classES3Types_1_1ES3Type__Flare.html", null ],
      [ "ES3Types.ES3Type_ForceOverLifetimeModule", "classES3Types_1_1ES3Type__ForceOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_Gradient", "classES3Types_1_1ES3Type__Gradient.html", null ],
      [ "ES3Types.ES3Type_GradientAlphaKey", "classES3Types_1_1ES3Type__GradientAlphaKey.html", null ],
      [ "ES3Types.ES3Type_GradientColorKey", "classES3Types_1_1ES3Type__GradientColorKey.html", null ],
      [ "ES3Types.ES3Type_Guid", "classES3Types_1_1ES3Type__Guid.html", null ],
      [ "ES3Types.ES3Type_InheritVelocityModule", "classES3Types_1_1ES3Type__InheritVelocityModule.html", null ],
      [ "ES3Types.ES3Type_IntPtr", "classES3Types_1_1ES3Type__IntPtr.html", null ],
      [ "ES3Types.ES3Type_Keyframe", "classES3Types_1_1ES3Type__Keyframe.html", null ],
      [ "ES3Types.ES3Type_LayerMask", "classES3Types_1_1ES3Type__LayerMask.html", null ],
      [ "ES3Types.ES3Type_LightsModule", "classES3Types_1_1ES3Type__LightsModule.html", null ],
      [ "ES3Types.ES3Type_LimitVelocityOverLifetimeModule", "classES3Types_1_1ES3Type__LimitVelocityOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_MainModule", "classES3Types_1_1ES3Type__MainModule.html", null ],
      [ "ES3Types.ES3Type_Matrix4x4", "classES3Types_1_1ES3Type__Matrix4x4.html", null ],
      [ "ES3Types.ES3Type_MinMaxCurve", "classES3Types_1_1ES3Type__MinMaxCurve.html", null ],
      [ "ES3Types.ES3Type_MinMaxGradient", "classES3Types_1_1ES3Type__MinMaxGradient.html", null ],
      [ "ES3Types.ES3Type_NoiseModule", "classES3Types_1_1ES3Type__NoiseModule.html", null ],
      [ "ES3Types.ES3Type_Nullable", "classES3Types_1_1ES3Type__Nullable.html", null ],
      [ "ES3Types.ES3Type_Quaternion", "classES3Types_1_1ES3Type__Quaternion.html", null ],
      [ "ES3Types.ES3Type_Rect", "classES3Types_1_1ES3Type__Rect.html", null ],
      [ "ES3Types.ES3Type_RotationBySpeedModule", "classES3Types_1_1ES3Type__RotationBySpeedModule.html", null ],
      [ "ES3Types.ES3Type_RotationOverLifetimeModule", "classES3Types_1_1ES3Type__RotationOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_Shader", "classES3Types_1_1ES3Type__Shader.html", null ],
      [ "ES3Types.ES3Type_ShapeModule", "classES3Types_1_1ES3Type__ShapeModule.html", null ],
      [ "ES3Types.ES3Type_SizeBySpeedModule", "classES3Types_1_1ES3Type__SizeBySpeedModule.html", null ],
      [ "ES3Types.ES3Type_SizeOverLifetimeModule", "classES3Types_1_1ES3Type__SizeOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_SubEmittersModule", "classES3Types_1_1ES3Type__SubEmittersModule.html", null ],
      [ "ES3Types.ES3Type_Texture", "classES3Types_1_1ES3Type__Texture.html", null ],
      [ "ES3Types.ES3Type_TextureSheetAnimationModule", "classES3Types_1_1ES3Type__TextureSheetAnimationModule.html", null ],
      [ "ES3Types.ES3Type_TrailModule", "classES3Types_1_1ES3Type__TrailModule.html", null ],
      [ "ES3Types.ES3Type_TriggerModule", "classES3Types_1_1ES3Type__TriggerModule.html", null ],
      [ "ES3Types.ES3Type_Type", "classES3Types_1_1ES3Type__Type.html", null ],
      [ "ES3Types.ES3Type_UIntPtr", "classES3Types_1_1ES3Type__UIntPtr.html", null ],
      [ "ES3Types.ES3Type_Vector2", "classES3Types_1_1ES3Type__Vector2.html", null ],
      [ "ES3Types.ES3Type_Vector3", "classES3Types_1_1ES3Type__Vector3.html", null ],
      [ "ES3Types.ES3Type_Vector4", "classES3Types_1_1ES3Type__Vector4.html", null ],
      [ "ES3Types.ES3Type_VelocityOverLifetimeModule", "classES3Types_1_1ES3Type__VelocityOverLifetimeModule.html", null ],
      [ "ES3Types.ES3Type_bool", "classES3Types_1_1ES3Type__bool.html", null ],
      [ "ES3Types.ES3Type_byte", "classES3Types_1_1ES3Type__byte.html", null ],
      [ "ES3Types.ES3Type_byteArray", "classES3Types_1_1ES3Type__byteArray.html", null ],
      [ "ES3Types.ES3Type_char", "classES3Types_1_1ES3Type__char.html", null ],
      [ "ES3Types.ES3Type_decimal", "classES3Types_1_1ES3Type__decimal.html", null ],
      [ "ES3Types.ES3Type_double", "classES3Types_1_1ES3Type__double.html", null ],
      [ "ES3Types.ES3Type_enum", "classES3Types_1_1ES3Type__enum.html", null ],
      [ "ES3Types.ES3Type_float", "classES3Types_1_1ES3Type__float.html", null ],
      [ "ES3Types.ES3Type_int", "classES3Types_1_1ES3Type__int.html", null ],
      [ "ES3Types.ES3Type_long", "classES3Types_1_1ES3Type__long.html", null ],
      [ "ES3Types.ES3Type_sbyte", "classES3Types_1_1ES3Type__sbyte.html", null ],
      [ "ES3Types.ES3Type_short", "classES3Types_1_1ES3Type__short.html", null ],
      [ "ES3Types.ES3Type_string", "classES3Types_1_1ES3Type__string.html", null ],
      [ "ES3Types.ES3Type_uint", "classES3Types_1_1ES3Type__uint.html", null ],
      [ "ES3Types.ES3Type_ulong", "classES3Types_1_1ES3Type__ulong.html", null ],
      [ "ES3Types.ES3Type_ushort", "classES3Types_1_1ES3Type__ushort.html", null ],
      [ "ES3Types.ES3UserType_DoorPosition", "classES3Types_1_1ES3UserType__DoorPosition.html", null ]
    ] ],
    [ "ES3Internal.ES3WebClass", "classES3Internal_1_1ES3WebClass.html", [
      [ "ES3Cloud", "classES3Cloud.html", null ]
    ] ],
    [ "ES3XMLReader", "classES3XMLReader.html", null ],
    [ "ES3XMLWriter", "classES3XMLWriter.html", null ],
    [ "EventChoice", "classEventChoice.html", null ],
    [ "EventCrewEffectHandler", "classEventCrewEffectHandler.html", null ],
    [ "EventOutcome", "classEventOutcome.html", null ],
    [ "EventPlanetEffectHandler", "classEventPlanetEffectHandler.html", null ],
    [ "EventResourceEffectHandler", "classEventResourceEffectHandler.html", null ],
    [ "FileStream", null, [
      [ "ES3Internal.ES3FileStream", "classES3Internal_1_1ES3FileStream.html", null ]
    ] ],
    [ "ES3Editor.AutoSaveWindow.HierarchyItem", "classES3Editor_1_1AutoSaveWindow_1_1HierarchyItem.html", null ],
    [ "HullPlacementInfo", "classHullPlacementInfo.html", null ],
    [ "OuterHullSystem.HullPlacementInfo", "classOuterHullSystem_1_1HullPlacementInfo.html", null ],
    [ "IBeginDragHandler", null, [
      [ "RoomInventoryButton", "classRoomInventoryButton.html", null ],
      [ "TradingItem", "classTradingItem.html", null ],
      [ "WeaponInventoryButton", "classWeaponInventoryButton.html", null ]
    ] ],
    [ "IBlueprintPlaceable", "interfaceIBlueprintPlaceable.html", [
      [ "BlueprintRoom", "classBlueprintRoom.html", null ],
      [ "BlueprintWeapon", "classBlueprintWeapon.html", null ]
    ] ],
    [ "System.ICloneable", null, [
      [ "ES3Settings", "classES3Settings.html", [
        [ "ES3SerializableSettings", "classES3SerializableSettings.html", null ]
      ] ]
    ] ],
    [ "System.IDisposable", null, [
      [ "ES3Reader", "classES3Reader.html", [
        [ "ES3Internal.ES3JSONReader", "classES3Internal_1_1ES3JSONReader.html", null ]
      ] ],
      [ "ES3Writer", "classES3Writer.html", null ],
      [ "InputSystem_Actions", "classInputSystem__Actions.html", null ]
    ] ],
    [ "IDraggableSystem", "interfaceIDraggableSystem.html", null ],
    [ "IDragHandler", null, [
      [ "RoomInventoryButton", "classRoomInventoryButton.html", null ],
      [ "TradingItem", "classTradingItem.html", null ],
      [ "WeaponInventoryButton", "classWeaponInventoryButton.html", null ]
    ] ],
    [ "IEndDragHandler", null, [
      [ "RoomInventoryButton", "classRoomInventoryButton.html", null ],
      [ "TradingItem", "classTradingItem.html", null ],
      [ "WeaponInventoryButton", "classWeaponInventoryButton.html", null ]
    ] ],
    [ "IGameStateMachine", "interfaceIGameStateMachine.html", null ],
    [ "IGridPlaceable", "interfaceIGridPlaceable.html", [
      [ "TradingItem", "classTradingItem.html", null ]
    ] ],
    [ "IInputActionCollection2", null, [
      [ "InputSystem_Actions", "classInputSystem__Actions.html", null ]
    ] ],
    [ "ES3Spreadsheet.Index", "structES3Spreadsheet_1_1Index.html", null ],
    [ "InputSystem_Actions.IPlayerActions", "interfaceInputSystem__Actions_1_1IPlayerActions.html", null ],
    [ "IPointerClickHandler", null, [
      [ "BuyItemInfoPanel", "classBuyItemInfoPanel.html", null ],
      [ "InventoryItemUI", "classInventoryItemUI.html", null ],
      [ "PlanetItemUI", "classPlanetItemUI.html", null ],
      [ "RaceButtonController", "classRaceButtonController.html", null ],
      [ "SellItemInfoPanel", "classSellItemInfoPanel.html", null ],
      [ "TradingItem", "classTradingItem.html", null ],
      [ "WarpNode", "classWarpNode.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "EnemyCamInteraction", "classEnemyCamInteraction.html", null ],
      [ "RoomInventoryButton", "classRoomInventoryButton.html", null ],
      [ "WeaponInventoryButton", "classWeaponInventoryButton.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "InventoryItemUI", "classInventoryItemUI.html", null ],
      [ "MoraleEffect", "classMoraleEffect.html", null ],
      [ "PlanetItemUI", "classPlanetItemUI.html", null ],
      [ "RaceButtonController", "classRaceButtonController.html", null ],
      [ "TooltipPanelBase", "classTooltipPanelBase.html", [
        [ "BuyItemInfoPanel", "classBuyItemInfoPanel.html", null ],
        [ "CrewInfoPanel", "classCrewInfoPanel.html", null ],
        [ "EquipmentInfoPanel", "classEquipmentInfoPanel.html", null ],
        [ "IconInteraction", "classIconInteraction.html", null ],
        [ "MoraleIcon", "classMoraleIcon.html", null ],
        [ "QuestInfoPanel", "classQuestInfoPanel.html", null ],
        [ "SellItemInfoPanel", "classSellItemInfoPanel.html", null ],
        [ "ShipInfoPanel", "classShipInfoPanel.html", null ],
        [ "StorageInfoPanel", "classStorageInfoPanel.html", null ]
      ] ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "InventoryItemUI", "classInventoryItemUI.html", null ],
      [ "MoraleEffect", "classMoraleEffect.html", null ],
      [ "PlanetItemUI", "classPlanetItemUI.html", null ],
      [ "RaceButtonController", "classRaceButtonController.html", null ],
      [ "TooltipPanelBase", "classTooltipPanelBase.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "EnemyCamInteraction", "classEnemyCamInteraction.html", null ]
    ] ],
    [ "ISerializationCallbackReceiver", null, [
      [ "ES3AutoSave", "classES3AutoSave.html", null ],
      [ "ES3Internal.ES3SerializableDictionary< TKey, TVal >", "classES3Internal_1_1ES3SerializableDictionary.html", null ],
      [ "RoomDamageRates", "classRoomDamageRates.html", null ]
    ] ],
    [ "IShipStatContributor", "interfaceIShipStatContributor.html", [
      [ "Room< AmmunitionRoomData, AmmunitionRoomData.AmmunitionRoomLevel >", "classRoom.html", [
        [ "AmmunitionRoom", "classAmmunitionRoom.html", null ]
      ] ],
      [ "Room< CockpitRoomData, CockpitRoomData.CockpitRoomLevel >", "classRoom.html", [
        [ "CockpitRoom", "classCockpitRoom.html", null ]
      ] ],
      [ "Room< CorridorRoomData, CorridorRoomData.CorridorRoomLevel >", "classRoom.html", [
        [ "CorridorRoom", "classCorridorRoom.html", null ]
      ] ],
      [ "Room< CrewQuartersRoomData, CrewQuartersRoomData.CrewQuartersRoomLevel >", "classRoom.html", [
        [ "CrewQuartersRoom", "classCrewQuartersRoom.html", null ]
      ] ],
      [ "Room< EngineRoomData, EngineRoomData.EngineRoomLevel >", "classRoom.html", [
        [ "EngineRoom", "classEngineRoom.html", null ]
      ] ],
      [ "Room< LifeSupportRoomData, LifeSupportRoomData.LifeSupportRoomLevel >", "classRoom.html", [
        [ "LifeSupportRoom", "classLifeSupportRoom.html", null ]
      ] ],
      [ "Room< MedBayRoomData, MedBayRoomData.MedBayRoomLevel >", "classRoom.html", [
        [ "MedBayRoom", "classMedBayRoom.html", null ]
      ] ],
      [ "Room< OxygenRoomData, OxygenRoomData.OxygenLevel >", "classRoom.html", [
        [ "OxygenRoom", "classOxygenRoom.html", null ]
      ] ],
      [ "Room< PowerRoomData, PowerRoomData.PowerRoomLevel >", "classRoom.html", [
        [ "PowerRoom", "classPowerRoom.html", null ]
      ] ],
      [ "Room< ShieldRoomData, ShieldRoomData.ShieldRoomLevel >", "classRoom.html", [
        [ "ShieldRoom", "classShieldRoom.html", null ]
      ] ],
      [ "Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >", "classRoom.html", [
        [ "StorageRoomBase", "classStorageRoomBase.html", [
          [ "StorageRoomAnimal", "classStorageRoomAnimal.html", null ],
          [ "StorageRoomRegular", "classStorageRoomRegular.html", null ],
          [ "StorageRoomTemperature", "classStorageRoomTemperature.html", null ]
        ] ]
      ] ],
      [ "Room< TeleportRoomData, TeleportRoomData.TeleportRoomLevel >", "classRoom.html", [
        [ "TeleportRoom", "classTeleportRoom.html", null ]
      ] ],
      [ "Room< WeaponControlRoomData, WeaponControlRoomData.WeaponControlRoomLevel >", "classRoom.html", [
        [ "WeaponControlRoom", "classWeaponControlRoom.html", null ]
      ] ],
      [ "CrewBase", "classCrewBase.html", [
        [ "CrewMember", "classCrewMember.html", null ]
      ] ],
      [ "OuterHull", "classOuterHull.html", null ],
      [ "Room< TData, TLevel >", "classRoom.html", null ]
    ] ],
    [ "ISpecialEffectHandler", "interfaceISpecialEffectHandler.html", [
      [ "AddQuestEffectHandler", "classAddQuestEffectHandler.html", null ],
      [ "BattleEffectHandler", "classBattleEffectHandler.html", null ],
      [ "EventNextEventEffectHandler", "classEventNextEventEffectHandler.html", null ],
      [ "RoomDamageEffectHandler", "classRoomDamageEffectHandler.html", null ],
      [ "TeleportEffectHandler", "classTeleportEffectHandler.html", null ]
    ] ],
    [ "ItemShape", "classItemShape.html", null ],
    [ "InputSystem_Actions.IUIActions", "interfaceInputSystem__Actions_1_1IUIActions.html", null ],
    [ "IUIController", "interfaceIUIController.html", null ],
    [ "RoomDatabase.LifeSupportRoomDataEntry", "classRoomDatabase_1_1LifeSupportRoomDataEntry.html", null ],
    [ "LocalizationManager.LocalizationEntry", "classLocalizationManager_1_1LocalizationEntry.html", null ],
    [ "MemoryStream", null, [
      [ "ES3Internal.UnbufferedCryptoStream", "classES3Internal_1_1UnbufferedCryptoStream.html", null ]
    ] ],
    [ "MonoBehaviour", null, [
      [ "Room< AmmunitionRoomData, AmmunitionRoomData.AmmunitionRoomLevel >", "classRoom.html", null ],
      [ "Room< CockpitRoomData, CockpitRoomData.CockpitRoomLevel >", "classRoom.html", null ],
      [ "Room< CorridorRoomData, CorridorRoomData.CorridorRoomLevel >", "classRoom.html", null ],
      [ "Room< CrewQuartersRoomData, CrewQuartersRoomData.CrewQuartersRoomLevel >", "classRoom.html", null ],
      [ "Room< EngineRoomData, EngineRoomData.EngineRoomLevel >", "classRoom.html", null ],
      [ "Room< LifeSupportRoomData, LifeSupportRoomData.LifeSupportRoomLevel >", "classRoom.html", null ],
      [ "Room< MedBayRoomData, MedBayRoomData.MedBayRoomLevel >", "classRoom.html", null ],
      [ "Room< OxygenRoomData, OxygenRoomData.OxygenLevel >", "classRoom.html", null ],
      [ "Room< PowerRoomData, PowerRoomData.PowerRoomLevel >", "classRoom.html", null ],
      [ "Room< ShieldRoomData, ShieldRoomData.ShieldRoomLevel >", "classRoom.html", null ],
      [ "Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >", "classRoom.html", null ],
      [ "Room< TeleportRoomData, TeleportRoomData.TeleportRoomLevel >", "classRoom.html", null ],
      [ "Room< WeaponControlRoomData, WeaponControlRoomData.WeaponControlRoomLevel >", "classRoom.html", null ],
      [ "AimBeam", "classAimBeam.html", null ],
      [ "AnimationCleanser", "classAnimationCleanser.html", null ],
      [ "AudioManager", "classAudioManager.html", null ],
      [ "AudioTester", "classAudioTester.html", null ],
      [ "BPPreviewArea", "classBPPreviewArea.html", null ],
      [ "BPPreviewCamera", "classBPPreviewCamera.html", null ],
      [ "BlueprintCategoryButtonHandler", "classBlueprintCategoryButtonHandler.html", null ],
      [ "BlueprintDragManager", "classBlueprintDragManager.html", null ],
      [ "BlueprintHullLevelInventoryUI", "classBlueprintHullLevelInventoryUI.html", null ],
      [ "BlueprintInventoryUI", "classBlueprintInventoryUI.html", null ],
      [ "BlueprintRoom", "classBlueprintRoom.html", null ],
      [ "BlueprintRoomDragHandler", "classBlueprintRoomDragHandler.html", null ],
      [ "BlueprintShip", "classBlueprintShip.html", null ],
      [ "BlueprintSlotManager", "classBlueprintSlotManager.html", null ],
      [ "BlueprintWeapon", "classBlueprintWeapon.html", null ],
      [ "BlueprintWeaponDragHandler", "classBlueprintWeaponDragHandler.html", null ],
      [ "BlueprintWeaponInventoryUI", "classBlueprintWeaponInventoryUI.html", null ],
      [ "BuyCheckPanel", "classBuyCheckPanel.html", null ],
      [ "CameraZoomController", "classCameraZoomController.html", null ],
      [ "CombatEndingUI", "classCombatEndingUI.html", null ],
      [ "CombatManager", "classCombatManager.html", null ],
      [ "CrewBase", "classCrewBase.html", null ],
      [ "CrewCardUI", "classCrewCardUI.html", null ],
      [ "CrewFactory", "classCrewFactory.html", null ],
      [ "CrewHealthBar", "classCrewHealthBar.html", null ],
      [ "CrewIconButton", "classCrewIconButton.html", null ],
      [ "CrewInfoLoader", "classCrewInfoLoader.html", null ],
      [ "CrewMovementValidator", "classCrewMovementValidator.html", null ],
      [ "CrewPathfinder", "classCrewPathfinder.html", null ],
      [ "CrewUIHandler", "classCrewUIHandler.html", null ],
      [ "Crosshair", "classCrosshair.html", null ],
      [ "CustomPointer", "classCustomPointer.html", null ],
      [ "CustomizeShipUIHandler", "classCustomizeShipUIHandler.html", null ],
      [ "Customize_0_Controller", "classCustomize__0__Controller.html", null ],
      [ "Customize_1_Controller", "classCustomize__1__Controller.html", null ],
      [ "Customize_2_Controller", "classCustomize__2__Controller.html", null ],
      [ "Door", "classDoor.html", null ],
      [ "ES3AutoSave", "classES3AutoSave.html", null ],
      [ "ES3AutoSaveMgr", "classES3AutoSaveMgr.html", null ],
      [ "ES3GameObject", "classES3GameObject.html", null ],
      [ "ES3GlobalManager", "classES3GlobalManager.html", null ],
      [ "ES3InspectorInfo", "classES3InspectorInfo.html", null ],
      [ "ES3Internal.ES3DefaultSettings", "classES3Internal_1_1ES3DefaultSettings.html", null ],
      [ "ES3Internal.ES3Prefab", "classES3Internal_1_1ES3Prefab.html", null ],
      [ "ES3Internal.ES3ReferenceMgrBase", "classES3Internal_1_1ES3ReferenceMgrBase.html", [
        [ "ES3ReferenceMgr", "classES3ReferenceMgr.html", null ]
      ] ],
      [ "EmployController", "classEmployController.html", null ],
      [ "EndingInfoDisplay", "classEndingInfoDisplay.html", null ],
      [ "EndingResultDisplay", "classEndingResultDisplay.html", null ],
      [ "EndingSceneTestDataInjector", "classEndingSceneTestDataInjector.html", null ],
      [ "EnemyCamInteraction", "classEnemyCamInteraction.html", null ],
      [ "EnemyController", "classEnemyController.html", null ],
      [ "EnemyInfoPanel", "classEnemyInfoPanel.html", null ],
      [ "EnemyShipFactory", "classEnemyShipFactory.html", null ],
      [ "EquipmentApplyHandler", "classEquipmentApplyHandler.html", null ],
      [ "EquipmentButton", "classEquipmentButton.html", null ],
      [ "EquipmentIconButton", "classEquipmentIconButton.html", null ],
      [ "EquipmentManager", "classEquipmentManager.html", null ],
      [ "EquipmentUIHandler", "classEquipmentUIHandler.html", null ],
      [ "EventManager", "classEventManager.html", null ],
      [ "EventNode", "classEventNode.html", null ],
      [ "EventPanelController", "classEventPanelController.html", null ],
      [ "EventTestTrigger", "classEventTestTrigger.html", null ],
      [ "EventTreeMap", "classEventTreeMap.html", null ],
      [ "EventUIManager", "classEventUIManager.html", null ],
      [ "FuelPanelUI", "classFuelPanelUI.html", null ],
      [ "GameInitializer", "classGameInitializer.html", null ],
      [ "GameManager", "classGameManager.html", null ],
      [ "GameObjectFactory", "classGameObjectFactory.html", null ],
      [ "GameStateManager", "classGameStateManager.html", null ],
      [ "GridPlacer", "classGridPlacer.html", null ],
      [ "IdleHUDController", "classIdleHUDController.html", null ],
      [ "InventoryItemUI", "classInventoryItemUI.html", null ],
      [ "InventoryUI", "classInventoryUI.html", null ],
      [ "ItemFactory", "classItemFactory.html", null ],
      [ "ItemMapController", "classItemMapController.html", null ],
      [ "LocalizedText", "classLocalizedText.html", null ],
      [ "MainMenuUIController", "classMainMenuUIController.html", null ],
      [ "ManagerSceneLoader", "classManagerSceneLoader.html", null ],
      [ "MapPanelController", "classMapPanelController.html", null ],
      [ "MaterialInit", "classMaterialInit.html", null ],
      [ "MenuUI", "classMenuUI.html", null ],
      [ "MenuUIManager", "classMenuUIManager.html", null ],
      [ "MiddlePanelUI", "classMiddlePanelUI.html", null ],
      [ "MoraleEffect", "classMoraleEffect.html", null ],
      [ "MoraleManager", "classMoraleManager.html", null ],
      [ "MyProjectile", "classMyProjectile.html", null ],
      [ "NodePlacementMap", "classNodePlacementMap.html", null ],
      [ "OuterHull", "classOuterHull.html", null ],
      [ "PSDestroy", "classPSDestroy.html", null ],
      [ "ParallaxLayer", "classParallaxLayer.html", null ],
      [ "PlanetItemUI", "classPlanetItemUI.html", null ],
      [ "PlanetTooltip", "classPlanetTooltip.html", null ],
      [ "PlanetUI", "classPlanetUI.html", null ],
      [ "Projectile", "classProjectile.html", null ],
      [ "ProjectileManager", "classProjectileManager.html", null ],
      [ "QuestList", "classQuestList.html", null ],
      [ "QuestListItem", "classQuestListItem.html", null ],
      [ "QuestManager", "classQuestManager.html", null ],
      [ "QuestPanel", "classQuestPanel.html", null ],
      [ "RTSSelectionManager", "classRTSSelectionManager.html", null ],
      [ "RaceButtonController", "classRaceButtonController.html", null ],
      [ "RaceTooltip", "classRaceTooltip.html", null ],
      [ "RandomPlanetArrival", "classRandomPlanetArrival.html", null ],
      [ "RepairAlert", "classRepairAlert.html", null ],
      [ "ResourceManager", "classResourceManager.html", null ],
      [ "Room< TData, TLevel >", "classRoom.html", null ],
      [ "RoomFactory", "classRoomFactory.html", null ],
      [ "RoomInventoryButton", "classRoomInventoryButton.html", null ],
      [ "RoomSelectionHandler", "classRoomSelectionHandler.html", null ],
      [ "SceneChanger", "classSceneChanger.html", null ],
      [ "ScrollingBackground", "classScrollingBackground.html", null ],
      [ "SettingsPanelController", "classSettingsPanelController.html", null ],
      [ "Ship", "classShip.html", null ],
      [ "ShipCamera", "classShipCamera.html", null ],
      [ "ShipCustomizationManager", "classShipCustomizationManager.html", null ],
      [ "ShipFactory", "classShipFactory.html", null ],
      [ "ShipFollowCamera", "classShipFollowCamera.html", null ],
      [ "ShipPathDebugVisualizer", "classShipPathDebugVisualizer.html", null ],
      [ "ShipTemplateLoader", "classShipTemplateLoader.html", null ],
      [ "ShipTemplateSaver", "classShipTemplateSaver.html", null ],
      [ "ShipWeapon", "classShipWeapon.html", null ],
      [ "ShipWeaponFactory", "classShipWeaponFactory.html", null ],
      [ "SlidePanelController", "classSlidePanelController.html", null ],
      [ "Storage", "classStorage.html", null ],
      [ "StorageHighlightManager", "classStorageHighlightManager.html", null ],
      [ "TestStorageItemAdder", "classTestStorageItemAdder.html", null ],
      [ "TooltipPanelBase", "classTooltipPanelBase.html", null ],
      [ "TradeManager", "classTradeManager.html", null ],
      [ "TradeUIController", "classTradeUIController.html", null ],
      [ "TradeUIManager", "classTradeUIManager.html", null ],
      [ "TradingItem", "classTradingItem.html", null ],
      [ "TradingItemDragHandler", "classTradingItemDragHandler.html", null ],
      [ "TradingItemHighlighter", "classTradingItemHighlighter.html", null ],
      [ "UIManager", "classUIManager.html", null ],
      [ "UITopLayersCanvasHandler", "classUITopLayersCanvasHandler.html", null ],
      [ "UnityObjectType", "classUnityObjectType.html", null ],
      [ "WarpNode", "classWarpNode.html", null ],
      [ "WeaponFrameFunction", "classWeaponFrameFunction.html", null ],
      [ "WeaponInventoryButton", "classWeaponInventoryButton.html", null ],
      [ "WeaponPanel", "classWeaponPanel.html", null ],
      [ "WorldNode", "classWorldNode.html", null ],
      [ "YearDisplayUI", "classYearDisplayUI.html", null ]
    ] ],
    [ "MoraleEffectData", "classMoraleEffectData.html", null ],
    [ "NodeMapHelper", "classNodeMapHelper.html", null ],
    [ "OuterHullData.OuterHullLevel", "classOuterHullData_1_1OuterHullLevel.html", null ],
    [ "OuterShipCombatController", "classOuterShipCombatController.html", null ],
    [ "PlanetData", "classPlanetData.html", null ],
    [ "PlanetEffect", "classPlanetEffect.html", null ],
    [ "PlanetNamesData", "classPlanetNamesData.html", null ],
    [ "PlanetSpriteInfo", "classPlanetSpriteInfo.html", null ],
    [ "InputSystem_Actions.PlayerActions", "structInputSystem__Actions_1_1PlayerActions.html", null ],
    [ "PlayerData", "classPlayerData.html", null ],
    [ "PriorityQueue< T >", "classPriorityQueue.html", null ],
    [ "ProjectileData", "classProjectileData.html", null ],
    [ "QuestObjective", "classQuestObjective.html", null ],
    [ "QuestReward", "classQuestReward.html", null ],
    [ "CrewDatabase.RaceStat", "classCrewDatabase_1_1RaceStat.html", null ],
    [ "CrewRaceStat.RaceStat", "classCrewRaceStat_1_1RaceStat.html", null ],
    [ "CrewDatabase.RaceStatData", "classCrewDatabase_1_1RaceStatData.html", null ],
    [ "RandomQuest", "classRandomQuest.html", null ],
    [ "ResourceEffect", "classResourceEffect.html", null ],
    [ "ResourcesData", "classResourcesData.html", null ],
    [ "RoomBackupData", "structRoomBackupData.html", null ],
    [ "RoomDatabase.RoomDataEntry", "classRoomDatabase_1_1RoomDataEntry.html", null ],
    [ "RoomData< T >.RoomLevel", "classRoomData_1_1RoomLevel.html", null ],
    [ "RoomLevel", null, [
      [ "AmmunitionRoomData.AmmunitionRoomLevel", "classAmmunitionRoomData_1_1AmmunitionRoomLevel.html", null ],
      [ "CockpitRoomData.CockpitRoomLevel", "classCockpitRoomData_1_1CockpitRoomLevel.html", null ],
      [ "CorridorRoomData.CorridorRoomLevel", "classCorridorRoomData_1_1CorridorRoomLevel.html", null ],
      [ "CrewQuartersRoomData.CrewQuartersRoomLevel", "classCrewQuartersRoomData_1_1CrewQuartersRoomLevel.html", null ],
      [ "EngineRoomData.EngineRoomLevel", "classEngineRoomData_1_1EngineRoomLevel.html", null ],
      [ "LifeSupportRoomData.LifeSupportRoomLevel", "classLifeSupportRoomData_1_1LifeSupportRoomLevel.html", null ],
      [ "MedBayRoomData.MedBayRoomLevel", "classMedBayRoomData_1_1MedBayRoomLevel.html", null ],
      [ "OxygenRoomData.OxygenLevel", "classOxygenRoomData_1_1OxygenLevel.html", null ],
      [ "PowerRoomData.PowerRoomLevel", "classPowerRoomData_1_1PowerRoomLevel.html", null ],
      [ "ShieldRoomData.ShieldRoomLevel", "classShieldRoomData_1_1ShieldRoomLevel.html", null ],
      [ "StorageRoomBaseData.StorageRoomBaseLevel", "classStorageRoomBaseData_1_1StorageRoomBaseLevel.html", null ],
      [ "TeleportRoomData.TeleportRoomLevel", "classTeleportRoomData_1_1TeleportRoomLevel.html", null ],
      [ "WeaponControlRoomData.WeaponControlRoomLevel", "classWeaponControlRoomData_1_1WeaponControlRoomLevel.html", null ]
    ] ],
    [ "ShipTemplate.RoomTemplate", "classShipTemplate_1_1RoomTemplate.html", null ],
    [ "ScriptableObject", null, [
      [ "RoomData< AmmunitionRoomData.AmmunitionRoomLevel >", "classRoomData.html", [
        [ "AmmunitionRoomData", "classAmmunitionRoomData.html", null ]
      ] ],
      [ "RoomData< CockpitRoomData.CockpitRoomLevel >", "classRoomData.html", [
        [ "CockpitRoomData", "classCockpitRoomData.html", null ]
      ] ],
      [ "RoomData< CorridorRoomData.CorridorRoomLevel >", "classRoomData.html", [
        [ "CorridorRoomData", "classCorridorRoomData.html", null ]
      ] ],
      [ "RoomData< CrewQuartersRoomData.CrewQuartersRoomLevel >", "classRoomData.html", [
        [ "CrewQuartersRoomData", "classCrewQuartersRoomData.html", null ]
      ] ],
      [ "RoomData< EngineRoomData.EngineRoomLevel >", "classRoomData.html", [
        [ "EngineRoomData", "classEngineRoomData.html", null ]
      ] ],
      [ "RoomData< LifeSupportRoomData.LifeSupportRoomLevel >", "classRoomData.html", [
        [ "LifeSupportRoomData", "classLifeSupportRoomData.html", null ]
      ] ],
      [ "RoomData< MedBayRoomData.MedBayRoomLevel >", "classRoomData.html", [
        [ "MedBayRoomData", "classMedBayRoomData.html", null ]
      ] ],
      [ "RoomData< OxygenRoomData.OxygenLevel >", "classRoomData.html", [
        [ "OxygenRoomData", "classOxygenRoomData.html", null ]
      ] ],
      [ "RoomData< PowerRoomData.PowerRoomLevel >", "classRoomData.html", [
        [ "PowerRoomData", "classPowerRoomData.html", null ]
      ] ],
      [ "RoomData< ShieldRoomData.ShieldRoomLevel >", "classRoomData.html", [
        [ "ShieldRoomData", "classShieldRoomData.html", null ]
      ] ],
      [ "RoomData< StorageRoomBaseData.StorageRoomBaseLevel >", "classRoomData.html", [
        [ "StorageRoomBaseData", "classStorageRoomBaseData.html", null ]
      ] ],
      [ "RoomData< TeleportRoomData.TeleportRoomLevel >", "classRoomData.html", [
        [ "TeleportRoomData", "classTeleportRoomData.html", null ]
      ] ],
      [ "RoomData< WeaponControlRoomData.WeaponControlRoomLevel >", "classRoomData.html", [
        [ "WeaponControlRoomData", "classWeaponControlRoomData.html", null ]
      ] ],
      [ "CrewDatabase", "classCrewDatabase.html", null ],
      [ "CrewRaceStat", "classCrewRaceStat.html", null ],
      [ "DoorData", "classDoorData.html", null ],
      [ "ES3Defaults", "classES3Defaults.html", null ],
      [ "ES3Internal.ES3GlobalReferences", "classES3Internal_1_1ES3GlobalReferences.html", null ],
      [ "EnemyShipDatabase", "classEnemyShipDatabase.html", null ],
      [ "EnemyShipTemplate", "classEnemyShipTemplate.html", null ],
      [ "EquipmentDatabase", "classEquipmentDatabase.html", null ],
      [ "EquipmentItem", "classEquipmentItem.html", null ],
      [ "EventDatabase", "classEventDatabase.html", null ],
      [ "OuterHullData", "classOuterHullData.html", null ],
      [ "RandomEvent", "classRandomEvent.html", null ],
      [ "RoomData< T >", "classRoomData.html", null ],
      [ "RoomDatabase", "classRoomDatabase.html", null ],
      [ "ShipStatSettings", "classShipStatSettings.html", null ],
      [ "ShipWeaponData", "classShipWeaponData.html", null ],
      [ "ShipWeaponDatabase", "classShipWeaponDatabase.html", null ],
      [ "ShipWeaponTypeData", "classShipWeaponTypeData.html", null ],
      [ "TradingItemData", "classTradingItemData.html", null ],
      [ "TradingItemDataBase", "classTradingItemDataBase.html", null ],
      [ "WarheadTypeData", "classWarheadTypeData.html", null ],
      [ "WeaponEffectData", "classWeaponEffectData.html", null ]
    ] ],
    [ "ScrollRect", null, [
      [ "InvertedHorizontalScroll", "classInvertedHorizontalScroll.html", null ],
      [ "NonDraggableScrollRect", "classNonDraggableScrollRect.html", null ]
    ] ],
    [ "CrewDatabase.SerializableRaceStatData", "classCrewDatabase_1_1SerializableRaceStatData.html", null ],
    [ "ShipGridHelper", "classShipGridHelper.html", null ],
    [ "ShipSaveInfo", "classShipSaveInfo.html", null ],
    [ "ShipSystem", "classShipSystem.html", [
      [ "CrewSystem", "classCrewSystem.html", null ],
      [ "HitPointSystem", "classHitPointSystem.html", null ],
      [ "MoraleSystem", "classMoraleSystem.html", null ],
      [ "OuterHullSystem", "classOuterHullSystem.html", null ],
      [ "OxygenSystem", "classOxygenSystem.html", null ],
      [ "PowerSystem", "classPowerSystem.html", null ],
      [ "ShieldSystem", "classShieldSystem.html", null ],
      [ "StorageSystem", "classStorageSystem.html", null ],
      [ "WeaponSystem", "classWeaponSystem.html", null ]
    ] ],
    [ "ShipTemplate", "classShipTemplate.html", null ],
    [ "ShipValidationHelper", "classShipValidationHelper.html", null ],
    [ "SkillSpritePair", "classSkillSpritePair.html", null ],
    [ "CrewDatabase.SkillValue", "classCrewDatabase_1_1SkillValue.html", null ],
    [ "CrewRaceStat.SkillValue", "classCrewRaceStat_1_1SkillValue.html", null ],
    [ "SpecialEffectHandlerFactory", "classSpecialEffectHandlerFactory.html", null ],
    [ "ShipStatSettings.StatLimit", "classShipStatSettings_1_1StatLimit.html", null ],
    [ "RoomDatabase.StorageRoomDataEntry", "classRoomDatabase_1_1StorageRoomDataEntry.html", null ],
    [ "Storage.StoredItem", "classStorage_1_1StoredItem.html", null ],
    [ "ES3Editor.SubWindow", "classES3Editor_1_1SubWindow.html", [
      [ "ES3Editor.AutoSaveWindow", "classES3Editor_1_1AutoSaveWindow.html", null ],
      [ "ES3Editor.HomeWindow", "classES3Editor_1_1HomeWindow.html", null ],
      [ "ES3Editor.ReferencesWindow", "classES3Editor_1_1ReferencesWindow.html", null ],
      [ "ES3Editor.SettingsWindow", "classES3Editor_1_1SettingsWindow.html", null ],
      [ "ES3Editor.ToolsWindow", "classES3Editor_1_1ToolsWindow.html", null ],
      [ "ES3Editor.TypesWindow", "classES3Editor_1_1TypesWindow.html", null ]
    ] ],
    [ "ES3Editor.TypesWindow.TypeListItem", "classES3Editor_1_1TypesWindow_1_1TypeListItem.html", null ],
    [ "InputSystem_Actions.UIActions", "structInputSystem__Actions_1_1UIActions.html", null ],
    [ "ValidationResult", "classValidationResult.html", null ],
    [ "WarpNodeData", "classWarpNodeData.html", null ],
    [ "WeaponBackupData", "structWeaponBackupData.html", null ],
    [ "ShipTemplate.WeaponTemplate", "classShipTemplate_1_1WeaponTemplate.html", null ],
    [ "WorldNodeData", "classWorldNodeData.html", null ]
];