MoraleIcon
CrewRace MoraleIcon.race
종족 유형
Referenced by Initialize, SetToolTipText, UpdateSprite.
int MoraleIcon.totalValue
아이콘에 표시되는 총 사기 변화량
Referenced by ClearEffectData, Initialize, RecalculateTotalValue, SetToolTipText, UpdateSprite.
Image MoraleIcon.iconImage
이미지 컴포넌트 (UI)
Referenced by Initialize, UpdateSprite.
List<MoraleEffectData> MoraleIcon.effectDataList
이 아이콘을 통해 표시되는 개별 사기 효과들의 목록
Referenced by AddEffectData, ClearEffectData, RecalculateTotalValue, RemoveEffectData, SetToolTipText.
override void MoraleIcon.Start()
override void MoraleIcon.SetToolTipText()
툴팁 텍스트 업데이트 (TooltipPanelBase에서 상속)
References TooltipPanelBase.currentToolTip, GameManager.CurrentYear, effectDataList, GameManager.Instance, race, totalValue, MoraleEffectData.value.
void MoraleIcon.Initialize(CrewRace race)
아이콘 초기화
References TooltipPanelBase.currentToolTip, iconImage, race, totalValue, UpdateSprite.
Referenced by MoraleManager.CreateRaceIcons.
void MoraleIcon.AddEffectData(MoraleEffectData data)
사기 효과 데이터 추가
References effectDataList, RecalculateTotalValue, UpdateSprite.
void MoraleIcon.RemoveEffectData(MoraleEffectData data)
사기 효과 데이터 제거
References effectDataList, RecalculateTotalValue, UpdateSprite.
void MoraleIcon.ClearEffectData()
모든 데이터 제거
References effectDataList, totalValue, UpdateSprite.
Referenced by MoraleManager.ReapplyLoadedEffects, MoraleManager.ResetAllMorale.
void MoraleIcon.RecalculateTotalValue()
전체 사기 값 재계산
References effectDataList, totalValue, MoraleEffectData.value.
Referenced by AddEffectData, RemoveEffectData.
void MoraleIcon.UpdateSprite()
스프라이트 업데이트
References iconImage, race, totalValue.
Referenced by AddEffectData, ClearEffectData, Initialize, RemoveEffectData.