Door
DoorData Door.doorData
문의 데이터
Referenced by CheckPowerRequirement, CloseDoor, Initialize, InitializeDoor, TryOpenDoor.
int Door.currentLevel
현재 문 레벨
Referenced by CheckPowerRequirement, CloseDoor, Initialize, InitializeDoor, TryOpenDoor.
DoorDirection Door.direction
문의 방향
Referenced by Initialize, RotateDirectionClockwise, SetDirection, SetDoorRotation.
bool Door.isOpen
현재 문이 열려있는지 여부
Referenced by CheckPowerRequirement, CloseDoor, TryOpenDoor.
Vector2Int Door.originalGridPosition
문의 원래 그리드 위치 (방 회전 전)
Referenced by SetGridPosition.
DoorDirection Door.originalDirection
문의 원래 방향 (방 회전 전)
Referenced by Initialize.
float Door.passTimer
문 통과 쿨다운 타이머
Referenced by TryOpenDoor.
int Door.currentHitPoint
문의 현재 내구도
SpriteRenderer Door.spriteRenderer
문 스프라이트 렌더러
Animator Door.animator
문 애니메이터
Referenced by CloseDoor, TryOpenDoor.
AudioSource Door.audioSource
문 오디오 소스
Referenced by CloseDoor, TryOpenDoor.
DoorDirection Door.Direction
문의 방향 프로퍼티
Vector2Int Door.OriginalGridPosition
원래 그리드 위치 프로퍼티
DoorDirection Door.OriginalDirection
원래 방향 프로퍼티
void Door.Awake()
void Door.Start()
void Door.Update()
void Door.InitializeDoor()
문의 초기화
References currentLevel, doorData, DoorData.DoorLevel.doorSprite, DoorData.GetDoorData, SetDoorRotation.
Referenced by Initialize.
void Door.SetDoorRotation()
문의 방향에 따라 회전 설정
References direction.
Referenced by InitializeDoor, SetDirection.
void Door.CheckPowerRequirement()
전력 요구사항 체크
References CloseDoor, currentLevel, doorData, DoorData.GetDoorData, HasEnoughPower, isOpen, DoorData.DoorLevel.powerRequirement.
bool Door.HasEnoughPower()
전력이 충분한지 체크 (함선의 전력 시스템과 연동 필요)
Referenced by CheckPowerRequirement, TryOpenDoor.
void Door.Initialize(DoorData doorData, int level, DoorDirection dir)
외부에서 문 초기화
References currentLevel, direction, doorData, InitializeDoor, originalDirection.
void Door.SetDirection(DoorDirection newDirection)
문의 방향 설정
References direction, SetDoorRotation.
Referenced by RotateDirectionClockwise.
void Door.RotateDirectionClockwise()
방향을 반시계 방향으로 90도 회전
References direction, SetDirection.
void Door.SetGridPosition(Vector2Int newPosition)
문의 위치 설정
References originalGridPosition.
bool Door.TryOpenDoor(bool bypassCooldown=false)
문 열기 시도
References animator, audioSource, currentLevel, doorData, DoorData.GetDoorData, HasEnoughPower, isOpen, DoorData.DoorLevel.openSound, DoorData.DoorLevel.passThroughDelay, passTimer, DoorData.DoorLevel.powerRequirement.
void Door.CloseDoor()
문 닫기
References animator, audioSource, DoorData.DoorLevel.closeSound, currentLevel, doorData, DoorData.GetDoorData, isOpen.
Referenced by CheckPowerRequirement.