EnemyShipFactory
EnemyShipDatabase EnemyShipFactory.shipDatabase
Ship EnemyShipFactory.SpawnPirateShip(string templateName, Vector2Int position=new())
제공된 템플릿 이름을 기반으로 해적선을 생성합니다
templateName 사용할 해적선 템플릿 이름 position 배를 생성할 월드 위치 생성된 배 인스턴스
References CreateDefaultShip, FindShipByName, GeneratePirateCrew, GameManager.GetPlayerShip, EnemyShipTemplate.GetTemplatePath, GameManager.Instance, ShipTemplateLoader.LoadShipFromResources, Ship.MoveShipToFacingTargetShip.
Ship EnemyShipFactory.FindShipByName(string shipName)
이름으로 Ship 컴포넌트가 있는 게임오브젝트를 찾습니다
Referenced by SpawnPirateShip.
Ship EnemyShipFactory.CreateDefaultShip(EnemyShipTemplate template, Vector2Int position)
기본 배를 수동으로 생성합니다
References ApplyDefaultShipSettings, GeneratePirateCrew, Ship.GetWorldPositionFromGrid.
Referenced by SpawnPirateShip.
void EnemyShipFactory.ApplyDefaultShipSettings(Ship ship)
기본 배 설정을 적용합니다 (템플릿 로드 실패 시)
Referenced by CreateDefaultShip.
static void EnemyShipFactory.GeneratePirateCrew(Ship ship, EnemyShipTemplate template)
템플릿 설정을 기반으로 해적선에 대한 무작위 선원을 생성합니다
References Ship.AddCrew, GeneratePirateName, Ship.GetCrewCount, Ship.RemoveAllCrews, SelectRace.
Referenced by CreateDefaultShip, SpawnPirateShip.
static CrewRace EnemyShipFactory.SelectRace(List< CrewRaceOption > options, List< CrewRace > usedRaces)
가중치 및 다양성 설정에 따라 선원 종족 선택
References WeightedRandomRace.
Referenced by GeneratePirateCrew.
static CrewRace EnemyShipFactory.WeightedRandomRace(List< CrewRaceOption > options)
가중치에 따라 무작위 종족 선택
Referenced by SelectRace.
static string EnemyShipFactory.GeneratePirateName(CrewRace race)
종족에 따른 해적 이름 생성
Referenced by GeneratePirateCrew.