DoorData
List<DoorLevel> DoorData.doorLevels
문의 레벨별 데이터
Referenced by GetDoorData, InitializeDefaultLevels, OnEnable.
void DoorData.OnEnable()
ScriptableObject가 활성화될 때 호출되며, 필요한 경우 기본 데이터를 초기화합니다.
References doorLevels, InitializeDefaultLevels.
void DoorData.InitializeDefaultLevels()
기본 문 레벨 데이터 초기화
References doorLevels.
Referenced by OnEnable.
DoorLevel DoorData.GetDoorData(int level)
지정된 레벨의 문 데이터 반환
References doorLevels.
Referenced by Door.CheckPowerRequirement, Door.CloseDoor, Door.InitializeDoor, Door.TryOpenDoor.