TradeManager
float TradeManager.playerCOMA
플레이어의 현재 재화(COMA)입니다. 초기값은 1000입니다.
Referenced by BuyItem, SellItem.
float TradeManager.GetTotalPrice(TradingItemData itemData, int quantity)
지정된 아이템과 수량에 대한 총 가격을 계산합니다.
itemData 거래할 TradingItemData quantity 수량 총 가격(COMAs)
References CalculatePrice.
Referenced by BuyItem.
float TradeManager.CalculatePrice(TradingItemData itemData)
아이템의 현재 단가를 계산합니다. (기본은 basePrice 그대로 반환) 추후 이벤트 또는 행성 특성에 따라 가중치를 부여할 수 있습니다.
itemData 가격 계산할 아이템 계산된 단가
Referenced by GetTotalPrice, SellItem.
bool TradeManager.BuyItem(TradingItemData itemData, int quantity)
지정한 아이템을 구매 시도합니다. 성공 시 COMA를 차감하고 아이템을 창고에 추가합니다.
itemData 구매할 아이템 데이터 quantity 구매 수량 구매 성공 여부
References Storage.AddItem, Storage.CanAddItem, GetTotalPrice, playerCOMA.
Referenced by MiddlePanelUI.OnBuyClicked.
bool TradeManager.SellItem(TradingItemData itemData, int quantity)
지정한 아이템을 판매 시도합니다. 성공 시 아이템을 제거하고 COMA를 증가시킵니다.
itemData 판매할 아이템 데이터 quantity 판매 수량 판매 성공 여부
References CalculatePrice, Storage.HasItem, playerCOMA, Storage.RemoveItem.
Referenced by MiddlePanelUI.OnSellClicked.