NonDraggableScrollRect
bool NonDraggableScrollRect.IsScrollbarHandle(PointerEventData eventData)
현재 포인터가 스크롤바 핸들 위에 있는지 여부를 판단합니다.
eventData 이벤트 데이터. 스크롤바 핸들 위라면 true.
Referenced by OnBeginDrag, OnDrag, OnEndDrag.
override void NonDraggableScrollRect.OnBeginDrag(PointerEventData eventData)
드래그 시작 시 호출됩니다. 스크롤바 핸들 위일 경우에만 기본 드래그 동작을 수행합니다.
eventData 이벤트 데이터.
References IsScrollbarHandle.
override void NonDraggableScrollRect.OnDrag(PointerEventData eventData)
드래그 중 호출됩니다. 스크롤바 핸들 위일 경우에만 기본 드래그 동작을 수행합니다.
eventData 이벤트 데이터.
References IsScrollbarHandle.
override void NonDraggableScrollRect.OnEndDrag(PointerEventData eventData)
드래그 종료 시 호출됩니다. 스크롤바 핸들 위일 경우에만 기본 드래그 동작을 수행합니다.
eventData 이벤트 데이터.
References IsScrollbarHandle.
override void NonDraggableScrollRect.OnScroll(PointerEventData data)
마우스 휠 스크롤 이벤트를 허용합니다.
data 이벤트 데이터.