InventoryUI
Transform InventoryUI.contentPanel
ScrollView의 Content 패널을 참조합니다. (Hierarchy에서 Drag & Drop)
Referenced by PopulateInventory.
GameObject InventoryUI.inventoryItemPrefab
인벤토리 아이템 프리팹을 참조합니다. (Project에서 Drag & Drop)
Referenced by PopulateInventory.
Storage InventoryUI.storage
플레이어의 창고를 관리하는 Storage 컴포넌트를 참조합니다.
Referenced by PopulateInventory, Start.
void InventoryUI.Start()
MonoBehaviour의 Start 메서드로, 초기화 작업을 수행하고 인벤토리 UI를 생성합니다.
References PopulateInventory, storage.
void InventoryUI.PopulateInventory(bool makeInteractable=true)
Storage에 저장된 모든 아이템을 기반으로 UI를 동적으로 생성합니다. 기존의 아이템 UI를 제거한 후 새롭게 생성하여 중복 생성을 방지합니다.
makeInteractable 생성된 슬롯의 클릭 가능 여부 설정
References contentPanel, Storage.GetAllItems, inventoryItemPrefab, InventoryItemUI.Setup, storage.
Referenced by MiddlePanelUI.OnBuyClicked, MiddlePanelUI.OnSellClicked, TradeUIManager.OpenSellPanel, Start, TestStorageItemAdder.Start.
void InventoryUI.CloseSelfPanel()
인벤토리 패널을 비활성화합니다.