OxygenSystem
float OxygenSystem.currentOxygenRate
현재 산소 수치 (% 단위, 0 ~ 100).
Referenced by GetOxygenRate, Update.
OxygenLevel OxygenSystem.currentOxygenLevel
현재 산소 레벨 (총 5단계)
Referenced by GetOxygenLevel, Update.
float OxygenSystem.damageCheckInterval
override void OxygenSystem.Initialize(Ship ship)
시스템을 초기화하고 산소 수치를 100로 설정합니다.
ship 초기화할 대상 함선 객체.
Referenced by Ship.InitializeSystems.
override void OxygenSystem.Refresh()
override void OxygenSystem.Update(float deltaTime)
매 프레임마다 호출되어 산소 수치를 갱신합니다. 산소 생성량과 소비량을 계산하여 변화량을 적용합니다.
deltaTime 경과 시간 (초).
References CalculateOxygenChange, currentOxygenLevel, currentOxygenRate, Ship.GetAllCrew, ShipSystem.parentShip.
Referenced by Ship.Update.
float OxygenSystem.CalculateOxygenChange()
현재 산소 변화량을 계산합니다. 산소 생성량에서 소비량을 뺀 값을 반환합니다.
1초당 산소 변화량.
References ShipSystem.GetShipStat.
Referenced by Update.
float OxygenSystem.GetOxygenRate()
현재 산소량을 반환합니다.
현재 산소량.
References currentOxygenRate.
Referenced by Ship.GetOxygenRate.
OxygenLevel OxygenSystem.GetOxygenLevel()
현재 산소 레벨을 반환합니다.
현재 산소 레벨.
References currentOxygenLevel.
Referenced by Ship.GetOxygenLevel.