BlueprintHullLevelInventoryUI
BlueprintShip BlueprintHullLevelInventoryUI.blueprintShip
BlueprintWeaponDragHandler BlueprintHullLevelInventoryUI.weaponDragHandler
Transform BlueprintHullLevelInventoryUI.contentRoot
GameObject BlueprintHullLevelInventoryUI.levelButtonPrefab
Color BlueprintHullLevelInventoryUI.selectedColor
Color BlueprintHullLevelInventoryUI.unselectedColor
Color BlueprintHullLevelInventoryUI.selectedTextColor
Color BlueprintHullLevelInventoryUI.unselectedTextColor
List<Button> BlueprintHullLevelInventoryUI.levelButtons
int BlueprintHullLevelInventoryUI.currentLevel
void BlueprintHullLevelInventoryUI.Start()
void BlueprintHullLevelInventoryUI.UpdateButtonVisuals(Button button, bool isSelected)
버튼 시각 효과
Referenced by LoadHullLevelButtons, SetHullLevel.
void BlueprintHullLevelInventoryUI.LoadHullLevelButtons()
외갑판 레벨 버튼 생성
References SetHullLevel, UpdateButtonVisuals.
Referenced by BlueprintCategoryButtonHandler.ShowHull.
void BlueprintHullLevelInventoryUI.SetHullLevel(int level)
외갑판 레벨 선택
References BlueprintShip.SetHullLevel, UpdateButtonVisuals.
Referenced by LoadHullLevelButtons.
int BlueprintHullLevelInventoryUI.GetCurrentHullLevel()