CrewFactory
GameObject CrewFactory.crewPrefab
List<string> CrewFactory.humanNamePool
List<string> CrewFactory.amorphousNamePool
List<string> CrewFactory.beastNamePool
List<string> CrewFactory.insectNamePool
List<string> CrewFactory.mechSupNamePool
List<string> CrewFactory.mechTankNamePool
int CrewFactory.nextCrewId
CrewDatabase CrewFactory.crewDatabase
void CrewFactory.Awake()
void CrewFactory.InitializeCrewStats(CrewBase crew)
선원의 스탯과 스킬을 종족 정보에 따라 초기화합니다.
crew 초기화할 선원 객체
References EquipmentManager.defaultAssistant, EquipmentManager.defaultShield, EquipmentManager.defaultWeapon, CrewBase.equipAdditionalSkills, CrewDatabase.RaceStat.GetMaxSkillValueDictionary, CrewDatabase.GetRaceStat, CrewDatabase.RaceStat.initialPilotSkill, EquipmentManager.Instance, CrewBase.maxHealth, CrewBase.maxSkillValueArray, CrewBase.race, CrewBase.skills.
Referenced by CreateCrewInstance.
void CrewFactory.InitializeCrewCollider(CrewBase crew)
RTS 조작을 위해 선원의 collider 설정
crew
References CrewBase.race.
Referenced by CreateCrewInstance.
void CrewFactory.InitializeCrewAnimator(CrewBase crew)
종족 별 animator 연결
crew
Referenced by CreateCrewInstance.
CrewDatabase.RaceStat CrewFactory.GetRaceStat(CrewRace race)
특정 종족의 스탯 정보 반환
race 종족 타입 종족 스탯 정보
References CrewDatabase.GetRaceStat.
CrewBase CrewFactory.CreateCrewInstance(CrewRace race, string name=null, bool isPlayerControlled=true)
새로운 선원 객체 생성
race 선원 종족 name 선원 이름 (지정하지 않을 경우 자동 생성) isPlayerControlled 플레이어 소속 여부 생성된 선원 객체
References GenerateRandomName, InitializeCrewAnimator, InitializeCrewCollider, InitializeCrewStats.
Referenced by ShipFactory.CloneShip, ShipFactory.CreateShipFromTemplate, EmployController.OnClickBuy, CrewSystem.RestoreCrewAfterBuild, RestoreCrewFromES3, CrewSystem.RevertOriginalCrews.
CrewBase CrewFactory.CreateCrewObject(CrewBase crew)
CrewBase CrewFactory.RestoreCrewFromES3(string savedKey, string filename)
저장 데이터에서 선원 복원
data 선원 직렬화 데이터 복원된 선원 객체 저장 데이터에서 선원 복원 (Easy Save 3 사용) savedData ES3 저장 키 또는 파일 경로 복원된 선원 객체
References CreateCrewInstance, ES3.FileExists, ES3.KeyExists, ES3.Load.
string CrewFactory.GenerateRandomName(CrewRace race)
종족에 맞는 랜덤 이름 생성
race 선원 종족 생성된 이름
Referenced by CreateCrewInstance, EmployController.PopulateRandomCrewCardsAndSave.
void CrewFactory.InitializeNamePools()
모든 이름 풀 초기화