Room
RoomData Room< TData, TLevel >.roomData
방의 데이터 ScriptableObject 참조.
Referenced by Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.GetHealthPercentage, Room< TData, TLevel >.GetMaxHitPoints, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetPowerConsumption, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, Room< TData, TLevel >.GetSize, Room< TData, TLevel >.GetStatContributions, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.Repair, Room< TData, TLevel >.Start, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.UpdateRoomLevelData, Room< TData, TLevel >.UpdateRoomVisual.
int Room< TData, TLevel >.currentLevel
현재 방의 업그레이드 레벨.
Referenced by Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.GetCurrentLevel, Room< TData, TLevel >.GetHealthPercentage, Room< TData, TLevel >.GetMaxHitPoints, Room< TData, TLevel >.GetNextLevelStatContributions, Room< TData, TLevel >.GetPowerConsumption, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, Room< TData, TLevel >.GetSize, Room< TData, TLevel >.GetStatContributions, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.Repair, Room< TData, TLevel >.Start, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.UpdateEffects, Room< TData, TLevel >.UpdateRoomLevelData, Room< TData, TLevel >.UpdateRoomVisual, Room< TData, TLevel >.Upgrade.
List<Room> Room< TData, TLevel >.adjacentRooms
인접한 방 리스트.
List<Door> Room< TData, TLevel >.connectedDoors
이 방에 연결된 문들
ParticleSystem Room< TData, TLevel >.roomParticles
방 작동 시 시각 효과 파티클.
Referenced by Room< TData, TLevel >.UpdateEffects.
AudioSource Room< TData, TLevel >.roomSound
방 작동 시 사운드 효과.
Referenced by Room< TData, TLevel >.UpdateEffects.
SpriteRenderer Room< TData, TLevel >.roomRenderer
방의 시각적 렌더러.
Referenced by Room< TData, TLevel >.Initialize, Room< TData, TLevel >.UpdateEffects, Room< TData, TLevel >.UpdateRoomVisual.
TLevel Room< TData, TLevel >.currentRoomLevelData
현재 방 레벨에 해당하는 데이터 캐시.
Referenced by Room< TData, TLevel >.GetCurrentLevelData, Room< TData, TLevel >.UpdateRoomLevelData.
Vector2Int Room< TData, TLevel >.position
격자상의 방 위치 (좌측 상단 기준).
Referenced by Ship.AddRoom, Ship.AddRoomToGrid, CrewMovementValidator.AreRoomsConnectedThroughDoors, CombatManager.BackToTheHome, Ship.BackupAllCrews, Ship.BackupCurrentShip, ShipValidationHelper.CheckAllRoomsPathConnectedByDoors, ShipValidationHelper.CheckWeaponConnectivity, Room< TData, TLevel >.CopyFrom, CrewMovementValidator.CorridorRoomConnectionValid, ShipFactory.CreateShipFromTemplate, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, Ship.MoveShipToFacingTargetShip, ShipCustomizationManager.PlaceSavedRoom, Room< TData, TLevel >.UpdateRoomVisual, OuterHullSystem.UpdateVisuals, ShipValidationHelper.ValidateWeaponAttachmentDirection.
float Room< TData, TLevel >.currentHitPoints
현재 체력.
Referenced by Ship.AddRoom, CrewMember.Attack, Ship.BackupCurrentShip, CrewMember.CombatRoutine, Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.FullRepair, Room< TData, TLevel >.GetHealthPercentage, Room< TData, TLevel >.Initialize, Ship.IsFullHitPoint, Room< TData, TLevel >.Repair, Room< TData, TLevel >.TakeDamage, EnemyController.Update, EnemyController.WhereToGo, EnemyController.WhereToGo.
RoomType Room< TData, TLevel >.roomType
방의 타입.
Referenced by CrewSystem.AddCrew, CrewMovementValidator.AreTilesConnected, Room< TData, TLevel >.CopyFrom, CrewMember.FollowPathCoroutine, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.InitializeIsDamageable, ShipCustomizationManager.PlaceSavedRoom, Ship.RemoveRoom, CrewSystem.RestoreCrewAfterBuild, EnemyController.Update, EnemyController.WhereToGo.
Constants.Rotations.Rotation Room< TData, TLevel >.currentRotation
방의 현재 회전 값
Referenced by Ship.AddRoom, Ship.AddRoomToGrid, CrewMovementValidator.AreRoomsConnectedThroughDoors, Ship.BackupCurrentShip, ShipValidationHelper.CheckAllRoomsPathConnectedByDoors, Room< TData, TLevel >.CopyFrom, CrewMovementValidator.CorridorRoomConnectionValid, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, TradingItem.Rotate, CrewMember.TryWork, TradingItemDragHandler.UpdatePreviewBoxSprite, OuterHullSystem.UpdateVisuals.
List<CrewMember> Room< TData, TLevel >.crewInRoom
현재 방에 존재하는 선원 목록.
Referenced by Room< TData, TLevel >.GetCrewCount, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.OnCrewEnter, Room< TData, TLevel >.OnCrewExit.
bool Room< TData, TLevel >.isActive
방이 활성화되어 있는지 여부.
Referenced by Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.OnDisabled, CrewMember.TryWork.
bool Room< TData, TLevel >.isPowered
전력이 공급되고 있는지 여부.
Referenced by Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.GetIsPowered, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.SetPowerStatus.
bool Room< TData, TLevel >.isPowerRequested
전력 공급이 요청되었는지 여부.
Referenced by Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.GetIsPowerRequested, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.SetPowerStatus.
Ship Room< TData, TLevel >.parentShip
소속된 Ship 참조.
Referenced by Room< TData, TLevel >.Initialize, Room< TData, TLevel >.UpdateRoomVisual.
DamageLevel Room< TData, TLevel >.damageCondition
데미지 입은 정도
summary> 수리가 필요한 상태인지 확인합니다.
Referenced by Room< TData, TLevel >.FullRepair, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.Repair, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.UpdateRoomVisual.
Vector2Int Room< TData, TLevel >.workDirection
작업 방향
Referenced by CrewMember.TryWork.
bool Room< TData, TLevel >.isDamageable
이 방이 데미지를 받을 수 있는지 여부.
Referenced by Room< TData, TLevel >.GetIsDamageable, Room< TData, TLevel >.InitializeIsDamageable, Room< TData, TLevel >.TakeDamage.
SpriteRenderer Room< TData, TLevel >.icon
Vector2Int Room< TData, TLevel >.gridSize
방의 그리드 크기 (에디터 전용).
Referenced by Room< TData, TLevel >.Initialize.
CrewMember Room< TData, TLevel >._workingCrew
Action<Room> Room< TData, TLevel >.OnRoomStateChanged
방의 상태가 변경되었을 때 호출되는 이벤트.
Referenced by Room< TData, TLevel >.NotifyStateChanged.
CrewMember Room< TData, TLevel >.workingCrew
new TData Room< TData, TLevel >.roomData
방의 RoomData를 명확한 제네릭 타입으로 재정의한 프로퍼티.
virtual void Room< TData, TLevel >.Start()
각 방에 collider 추가, isTrigger = true 설정을 통해 선원 충돌 방해 제거
References Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.roomData.
virtual void Room< TData, TLevel >.UpdateRoom()
방의 상태를 매 프레임 업데이트합니다.
Referenced by Room< TData, TLevel >.Update, Room< TData, TLevel >.Upgrade.
virtual void Room< TData, TLevel >.UpdateEffects()
방의 이펙트(색상, 파티클 등)를 업데이트합니다.
References Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.roomParticles, Room< TData, TLevel >.roomRenderer, Room< TData, TLevel >.roomSound.
Referenced by Room< TData, TLevel >.SetPowerStatus.
virtual void Room< TData, TLevel >.OnDisabled()
방이 작동 불능 상태가 되었을 때 호출됩니다.
References Room< TData, TLevel >.isActive, Room< TData, TLevel >.NotifyStateChanged.
virtual void Room< TData, TLevel >.UpdateRoomLevelData()
레벨 데이터 캐시를 갱신합니다. roomData에서 현재 레벨에 맞는 데이터를 가져오고, 시각적 요소도 함께 갱신됩니다.
References Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.currentRoomLevelData, Room< TData, TLevel >.roomData, Room< TData, TLevel >.UpdateRoomVisual.
Referenced by Room< TData, TLevel >.Initialize, Room< TData, TLevel >.Start, Room< TData, TLevel >.Upgrade.
override void Room< TData, TLevel >.Start()
Start 시 roomData가 유효하다면 초기화 및 레벨 데이터 갱신을 수행합니다.
References Room< TData, TLevel >.roomData, Room< TData, TLevel >.UpdateRoomLevelData.
virtual void Room< TData, TLevel >.Update()
매 프레임마다 방의 상태를 업데이트합니다.
References Room< TData, TLevel >.UpdateRoom.
virtual bool Room< TData, TLevel >.CanBePlaced(Vector2Int newPosition, Ship ship)
방이 배치 가능한 위치인지 검사합니다.
newPosition 새 위치. ship 함선 참조.
virtual void Room< TData, TLevel >.OnCrewEnter(CrewMember crew)
선원이 방에 진입할 때 호출됩니다.
References Room< TData, TLevel >.crewInRoom.
Referenced by CrewSystem.AddCrew, CrewMember.FollowPathCoroutine, CrewSystem.RestoreCrewAfterBuild, CrewMember.TeleportAfterDelay.
virtual void Room< TData, TLevel >.OnCrewExit(CrewMember crew)
선원이 방에서 나갈 때 호출됩니다.
References Room< TData, TLevel >.crewInRoom.
List< Vector2Int > Room< TData, TLevel >.GetRotatedCrewEntryGridPriority()
방의 우선순위 타일에 따른 그리드에서의 위치 반환 (회전각 적용)
References RoomData< T >.RoomLevel.crewEntryGridPriority, Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.currentRotation, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.position, Room< TData, TLevel >.roomData.
Referenced by CrewSystem.AddCrew, CrewMember.GetCurrentTilePriorityIndex, CrewSystem.RestoreCrewAfterBuild, CrewMember.TeleportAfterDelay.
virtual void Room< TData, TLevel >.CopyFrom(Room other)
다른 방의 속성을 복사합니다.
other 복사할 소스 방
References Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.currentRotation, Room< TData, TLevel >.GetCurrentLevel, Room< TData, TLevel >.GetIsPowered, Room< TData, TLevel >.GetIsPowerRequested, Room< TData, TLevel >.isActive, Room< TData, TLevel >.isPowered, Room< TData, TLevel >.isPowerRequested, Room< TData, TLevel >.position, Room< TData, TLevel >.roomData, Room< TData, TLevel >.roomType.
Referenced by RoomFactory.CreateRoomObject.
void Room< TData, TLevel >.InitializeIsDamageable()
이 방이 데미지를 받을 수 있는지 여부를 초기화합니다.
References Room< TData, TLevel >.isDamageable, Room< TData, TLevel >.roomType.
Referenced by Room< TData, TLevel >.Initialize.
RoomData Room< TData, TLevel >.GetRoomData()
RoomType Room< TData, TLevel >.GetRoomType()
void Room< TData, TLevel >.SetRoomData(RoomData roomData)
bool Room< TData, TLevel >.GetIsPowered()
이 방이 전력 공급 중인지 확인합니다.
References Room< TData, TLevel >.isPowered.
Referenced by Room< TData, TLevel >.CopyFrom.
bool Room< TData, TLevel >.GetIsPowerRequested()
전력 공급 요청 여부를 확인합니다.
References Room< TData, TLevel >.isPowerRequested.
Referenced by Room< TData, TLevel >.CopyFrom.
bool Room< TData, TLevel >.GetIsDamageable()
이 방이 데미지를 받을 수 있는지 확인합니다.
References Room< TData, TLevel >.isDamageable.
Referenced by Ship.AddRoom, CrewMember.CombatRoutine, Ship.GetRandomTargettableRoom, EnemyController.Update, EnemyController.WhereToGo, EnemyController.WhereToGo.
bool Room< TData, TLevel >.isActionConnected()
virtual void Room< TData, TLevel >.Initialize(int level)
방을 초기화합니다.
References Room< TData, TLevel >.crewInRoom, Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.GetPowerConsumption, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.gridSize, RoomData< T >.RoomLevel.hitPoint, Room< TData, TLevel >.InitializeIsDamageable, Room< TData, TLevel >.isPowerRequested, Room< TData, TLevel >.parentShip, Room< TData, TLevel >.roomData, Room< TData, TLevel >.roomRenderer, Room< TData, TLevel >.roomType, RoomData< T >.RoomLevel.size.
Referenced by Ship.AddRoom, RoomFactory.CreateLifeSupportRoomInstance, RoomFactory.CreateRoomInstance, RoomFactory.CreateRoomObject.
int Room< TData, TLevel >.GetCrewCount()
현재 방에 있는 선원 수를 반환합니다.
References Room< TData, TLevel >.crewInRoom.
bool Room< TData, TLevel >.HasEnoughCrew()
필요한 선원이 충분한지 확인합니다.
bool Room< TData, TLevel >.IsOperational()
방이 작동 가능한 상태인지 확인합니다.
References Room< TData, TLevel >.damageCondition, Room< TData, TLevel >.isActive, Room< TData, TLevel >.isPowered, Room< TData, TLevel >.isPowerRequested.
Referenced by CrewMember.FollowPathCoroutine, Room< TData, TLevel >.GetStatContributions, Room< TData, TLevel >.UpdateEffects, Room< TData, TLevel >.UpdateRoomVisual.
virtual void Room< TData, TLevel >.SetPowerStatus(bool powered, bool requested)
전력 공급 상태를 설정합니다.
References Room< TData, TLevel >.isPowered, Room< TData, TLevel >.isPowerRequested, Room< TData, TLevel >.NotifyStateChanged, Room< TData, TLevel >.UpdateEffects.
Referenced by PowerSystem.RequestPowerForRoom.
void Room< TData, TLevel >.BlackOut()
float Room< TData, TLevel >.GetHealthPercentage()
체력 퍼센티지를 반환합니다.
References Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.hitPoint, Room< TData, TLevel >.roomData.
Referenced by Ship.GetRandomTargettableRoom.
virtual Dictionary< ShipStat, float > Room< TData, TLevel >.GetStatContributions()
방이 함선 스탯에 기여하는 값을 반환합니다.
References Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.hitPoint, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.roomData.
Referenced by Room< TData, TLevel >.GetNextLevelStatContributions, Ship.RecalculateAllStats.
virtual Dictionary< ShipStat, float > Room< TData, TLevel >.GetNextLevelStatContributions()
다음 레벨에서의 스탯 기여도를 반환합니다.
References Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.GetStatContributions.
virtual bool Room< TData, TLevel >.Upgrade()
방을 업그레이드합니다.
References Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.NotifyStateChanged, Room< TData, TLevel >.UpdateRoom.
virtual void Room< TData, TLevel >.NotifyStateChanged()
상태 변경을 알립니다.
References CrewMember.BackToThePeace, Room< TData, TLevel >.OnRoomStateChanged, CrewMember.WalkOut.
Referenced by Ship.AddRoom, Room< TData, TLevel >.OnDisabled, Room< TData, TLevel >.Repair, Room< TData, TLevel >.SetPowerStatus, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.Upgrade.
int Room< TData, TLevel >.GetCurrentLevel()
현재 업그레이드 레벨을 반환합니다.
References Room< TData, TLevel >.currentLevel.
Referenced by Ship.AddRoom, CrewMovementValidator.AreRoomsConnectedThroughDoors, Ship.BackupCurrentShip, ShipValidationHelper.CheckAllRoomsPathConnectedByDoors, Room< TData, TLevel >.CopyFrom, CrewMovementValidator.CorridorRoomConnectionValid, RoomFactory.CreateRoomObject, Room< TData, TLevel >.GetOccupiedTiles, Ship.GetTotalShipValue.
void Room< TData, TLevel >.SetCurrentLevel(int level)
float Room< TData, TLevel >.GetPowerConsumption()
최대 업그레이드 레벨을 반환합니다.
현재 전력 요구량을 반환합니다.
References Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.powerRequirement, Room< TData, TLevel >.roomData.
Referenced by Room< TData, TLevel >.Initialize, PowerSystem.RequestPowerForRoom.
Vector2Int Room< TData, TLevel >.GetSize()
방의 크기를 반환합니다.
References Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.roomData, RoomData< T >.RoomLevel.size.
Referenced by ShipValidationHelper.CheckWeaponConnectivity, Ship.RemoveRoom, OuterHullSystem.UpdateVisuals, ShipValidationHelper.ValidateWeaponAttachmentDirection.
float Room< TData, TLevel >.GetMaxHitPoints()
최대 체력을 반환합니다.
References Room< TData, TLevel >.currentLevel, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.hitPoint, Room< TData, TLevel >.roomData.
Referenced by Ship.IsFullHitPoint.
List< Vector2Int > Room< TData, TLevel >.GetOccupiedTiles()
회전각을 고려하여 방의 점유 타일 반환
References Room< TData, TLevel >.currentRotation, Room< TData, TLevel >.GetCurrentLevel, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.position, Room< TData, TLevel >.roomData, RoomData< T >.RoomLevel.size.
Referenced by ShipValidationHelper.CheckWeaponConnectivity, CameraZoomController.GetCameraStartPositionToOriginShip, Ship.GetRandomTargetPosition, CrewMovementValidator.GetRoomAtTile, ShipGridHelper.GetShipRotationOffset, CrewMovementValidator.Initialize, Room< TData, TLevel >.OccupiesTile, Room< TData, TLevel >.UpdateRoomVisual, ShipValidationHelper.ValidateWeaponAttachmentDirection.
bool Room< TData, TLevel >.OccupiesTile(Vector2Int tile)
인자 타일이 방의 일부인지 여부 반환
tile
References Room< TData, TLevel >.GetOccupiedTiles.
Referenced by ShipValidationHelper.ValidateWeaponPlacement.
List< Door > Room< TData, TLevel >.GetConnectedDoors()
List< CrewMember > Room< TData, TLevel >.GetTotalCrewsInRoom()
void Room< TData, TLevel >.UpdateRoomVisual()
현재 레벨의 시각적 요소 (스프라이트 등)를 갱신합니다.
References Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.damageCondition, Room< TData, TLevel >.GetOccupiedTiles, RoomData< T >.GetRoomDataByLevel, Ship.GetWorldPositionFromGrid, Room< TData, TLevel >.IsOperational, Room< TData, TLevel >.parentShip, Room< TData, TLevel >.position, Room< TData, TLevel >.roomData, RoomData< T >.RoomLevel.roomIconPrefab.
Referenced by Ship.AddRoom, Ship.AddRoom, Room< TData, TLevel >.FullRepair, Room< TData, TLevel >.Repair, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.UpdateRoomLevelData.
bool Room< TData, TLevel >.NeedsRepair()
virtual void Room< TData, TLevel >.TakeDamage(float damage)
지정된 피해만큼 체력을 감소시킵니다.
References Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.damageCondition, RoomData< T >.RoomLevel.damageHitPointRate, RoomData< T >.GetRoomDataByLevel, Room< TData, TLevel >.isDamageable, Room< TData, TLevel >.NotifyStateChanged, Room< TData, TLevel >.roomData, Room< TData, TLevel >.UpdateRoomVisual.
Referenced by CrewMember.Attack.
virtual void Room< TData, TLevel >.DownDamageCondition()
void Room< TData, TLevel >.Repair(float amount)
지정된 양만큼 체력을 회복시킵니다.
References Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentLevel, Room< TData, TLevel >.damageCondition, RoomData< T >.RoomLevel.damageHitPointRate, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.hitPoint, Room< TData, TLevel >.NotifyStateChanged, Room< TData, TLevel >.roomData, Room< TData, TLevel >.UpdateRoomVisual.
Referenced by CrewMember.RepairFacility.
void Room< TData, TLevel >.FullRepair(float amount)
100% 수리
amount
References Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.damageCondition, Room< TData, TLevel >.UpdateRoomVisual.
virtual bool Room< TData, TLevel >.CanITouch(CrewMember crew)
void Room< TData, TLevel >.SetIsActive(bool activate)
TLevel Room< TData, TLevel >.GetCurrentLevelData()
현재 방의 레벨에 해당하는 TLevel 데이터를 반환합니다. 내부적으로 필요 시 데이터를 갱신합니다.
현재 레벨의 방 데이터.
References Room< TData, TLevel >.currentRoomLevelData.
Referenced by Room< TData, TLevel >.UpdateRoomVisual.
override bool Room< TData, TLevel >.Upgrade()
방을 업그레이드한 후 레벨 데이터도 갱신합니다.
업그레이드 성공 여부.
References Room< TData, TLevel >.UpdateRoomLevelData.
override void Room< TData, TLevel >.Initialize(int level)
방 초기화 시 기본 초기화 이후 레벨 데이터도 갱신합니다.
References Room< TData, TLevel >.crewInRoom, Room< TData, TLevel >.InitializeIsDamageable, Room< TData, TLevel >.roomData, Room< TData, TLevel >.UpdateRoomLevelData.
void Room< TData, TLevel >.UpdateRoomVisual()
현재 레벨의 시각적 요소 (스프라이트 등)를 갱신합니다.
References Room< TData, TLevel >.GetCurrentLevelData, Room< TData, TLevel >.roomRenderer.
void Room< TData, TLevel >.InitializeDoor()
void Room< TData, TLevel >.OnDestroy()