GameManager
Ship GameManager.playerShip
현재 플레이어가 조종 중인 함선입니다.
Referenced by CombatManager.BackToTheHome, SceneChanger.BackToTheHome, CheckItemQuests, BlueprintShip.CreateOuterHull, GetPlayerShip, TradeUIController.InitializeSellPanel, RTSSelectionManager.IssueMoveCommand, LoadPlayerData, TradeUIController.OnBuyCancelButtonClicked, EmployController.OnClickBuy, EmployController.OnClickCrewCard, Customize_1_Controller.OnClickSave, EquipmentApplyHandler.OnClickStatApplyButton, Customize_1_Controller.OnDisable, Customize_0_Controller.OnEnable, Customize_1_Controller.OnEnable, Customize_2_Controller.OnEnable, EquipmentApplyHandler.PopulateEquipmentIcons, SavePlayerData, TradeUIController.SellItem, BlueprintShip.SetBPHullLevel, SetPlayerShip, CombatManager.Start, Customize_0_Controller.Start, Customize_1_Controller.Start, GridPlacer.Start, RTSSelectionManager.Start, CrewMember.TeleportAfterDelay, Customize_1_Controller.Update.
Ship GameManager.currentEnemyShip
현재 전투 중인 적 함선입니다.
Referenced by CombatManager.BackToTheHome, GetCurrentEnemyShip, SetCurrentEnemyShip, CrewMember.TeleportAfterDelay.
PlayerData GameManager.playerData
엔딩 조건과 관련된 플레이어 데이터
Referenced by AddCompletedMysteryEvent, LoadPlayerData, SavePlayerData, EndingInfoDisplay.ShowPlayerSummary.
Vector2 GameManager.normalizedPlayerPosition
현재 행성맵에서의 유저의 위치
Referenced by PlanetData.SetRandomPosition.
Dictionary<int, List<CrewCardSaveData> > GameManager.employCardsPerPlanet
bool GameManager.isBoughtEquipment
List<PlanetData> GameManager.planetDataList
현재 게임의 행성 데이터들
Referenced by CheckItemQuests, CheckPirateQuests.
List<WorldNodeData> GameManager.worldNodeDataList
월드맵의 노드 데이터
List<WarpNodeData> GameManager.warpNodeDataList
워프맵의 노드 데이터
int GameManager.currentWarpNodeId
현재 워프 노드의 ID
int GameManager.currentWarpTargetPlanetId
현재 워프 목표 행성 ID
GameState GameManager.currentState
현재 게임 상태입니다.
Referenced by ChangeGameState, ContinueGame, LoadPlayerData, SavePlayerData.
int GameManager.currentYear
현재 게임 연도입니다.
Referenced by AddYear, LoadPlayerData, SavePlayerData.
List<int> GameManager.completedMysteryEventIds
완료된 미스터리 이벤트 ID 목록 (한 번 뜬 미스터리 이벤트는 다시 나오지 않음)
Referenced by AddCompletedMysteryEvent, IsMysteryEventCompleted, LoadPlayerData.
Action<int> GameManager.OnYearChanged
Action GameManager.OnShipInitialized
GameStateChangedHandler GameManager.OnGameStateChanged
게임 상태 변경 시 호출되는 이벤트입니다.
Referenced by ChangeGameState.
Action<int> GameManager.OnlyWarpEffect
GameState GameManager.CurrentState
int GameManager.CurrentYear
현재 연도 (읽기 전용).
Referenced by QuestManager.AddQuest, EventPlanetEffectHandler.ApplyEffects, MoraleManager.RegisterMoraleEffect, EventManager.SelectAppropriateEvent, MoraleIcon.SetToolTipText, FuelPanelUI.Start, FuelPanelUI.Update.
int GameManager.CurrentGlobalWeaponLevel
int GameManager.CurrentGlobalShieldLevel
GameManager GameManager.Instance
싱글턴 인스턴스입니다.
Referenced by QuestManager.AddQuest, EventCrewEffectHandler.ApplyEffects, EventPlanetEffectHandler.ApplyEffects, Awake, CombatManager.BackToTheHome, SceneChanger.BackToTheHome, TradeUIController.BuyItem, BlueprintShip.CreateOuterHull, PlanetData.CreateRandomData, EventManager.GetAvailableCrewRaces, ShipWeapon.GetTargetShip, TradeUIController.InitializeBuyPanel, TradeUIController.InitializeSellPanel, RTSSelectionManager.IssueMoveCommand, LoadPlayerData, SceneChanger.LoadScene, TradeUIController.OnBuyCancelButtonClicked, EmployController.OnClickBuy, EmployController.OnClickCrewCard, Customize_1_Controller.OnClickSave, EquipmentApplyHandler.OnClickStatApplyButton, CrewUIHandler.OnCreateButtonClicked, Customize_1_Controller.OnDisable, Customize_0_Controller.OnEnable, Customize_1_Controller.OnEnable, Customize_2_Controller.OnEnable, CrewUIHandler.OnSubmitButtonClicked, EmployController.PopulateCardsFromSavedData, EquipmentApplyHandler.PopulateEquipmentIcons, EmployController.PopulateRandomCrewCardsAndSave, EventManager.ProcessChoice, EventManager.ProcessNextEvent, EquipmentManager.PurchaseAndEquipGlobal, MoraleManager.RegisterMoraleEffect, EventManager.SelectAppropriateEvent, EventTestTrigger.SelectTestEvent, TradeUIController.SellItem, BlueprintShip.SetBPHullLevel, PlanetData.SetRandomPosition, MoraleIcon.SetToolTipText, EventPanelController.ShowEvent, EndingInfoDisplay.ShowPlayerSummary, EnemyShipFactory.SpawnPirateShip, CombatManager.Start, Customize_0_Controller.Start, Customize_1_Controller.Start, GridPlacer.Start, RTSSelectionManager.Start, FuelPanelUI.Start, CrewMember.TeleportAfterDelay, Customize_1_Controller.Update, FuelPanelUI.Update, TradeUIController.UpdateBuyPanel, OuterShipCombatController.WeaponFire.
List<PlanetData> GameManager.PlanetDataList
List<WorldNodeData> GameManager.WorldNodeDataList
List<WarpNodeData> GameManager.WarpNodeDataList
int GameManager.CurrentWarpTargetPlanetId
int GameManager.CurrentWarpNodeId
List<int> GameManager.CompletedMysteryEventIds
완료된 미스터리 이벤트 ID 목록을 반환합니다 (읽기 전용)
Referenced by EventManager.SelectAppropriateEvent.
delegate void GameManager.GameStateChangedHandler(GameState newState)
게임 상태 변경 이벤트 델리게이트입니다.
Ship GameManager.CreateDefaultPlayerShip()
void GameManager.CreateDefaultEnemyShip(Ship enemyShip)
void GameManager.CreateDefaultEnemyShip2(Ship enemyShip)
Ship GameManager.GetPlayerShip()
현재 플레이어 함선을 반환합니다.
References playerShip.
Referenced by EventCrewEffectHandler.ApplyEffects, EventManager.GetAvailableCrewRaces, ShipWeapon.GetTargetShip, CrewUIHandler.OnCreateButtonClicked, CrewUIHandler.OnSubmitButtonClicked, EquipmentManager.PurchaseAndEquipGlobal, EventTestTrigger.SelectTestEvent, EnemyShipFactory.SpawnPirateShip.
Ship GameManager.SetPlayerShip(Ship ship)
플레이어 함선을 설정합니다.
References playerShip.
Ship GameManager.GetCurrentEnemyShip()
현재 적 함선을 반환합니다.
References currentEnemyShip.
Referenced by ShipWeapon.GetTargetShip, OuterShipCombatController.WeaponFire.
void GameManager.SetCurrentEnemyShip(Ship enemyShip)
적 함선을 설정합니다.
References currentEnemyShip.
Referenced by CombatManager.Start.
void GameManager.ChangeGameState(GameState newState)
게임 상태를 변경하고 상태에 따라 관련 처리를 수행합니다.
newState 변경할 게임 상태.
References currentState, HandleGameOver, OnGameStateChanged.
Referenced by SceneChanger.BackToTheHome.
void GameManager.OnEventCompleted()
이벤트 처리 완료 후 호출됩니다. 현재는 빈 함수이며, 후속 처리 로직을 연결할 수 있습니다.
void GameManager.AddYear()
워프 실행 시 1년을 경과시키고, 관련 효과나 이벤트를 처리합니다.
References currentYear.
void GameManager.WarpEffect()
void GameManager.StartNewGame()
메인 화면에서 새로운 시작을 누르면 호출되는 함수. 행성 데이터를 삭제 후 게임 시작
void GameManager.ContinueGame()
메인 화면에서 이어하기를 누르면 호출되는 함수. 행성 데이터를 로드 후 게임 시작
References currentState, SceneChanger.LoadScene.
void GameManager.SaveGameData()
게임 전체를 저장하는 함수. 워프를 할 때마다 떠야할 것이다.
References SavePlayerData.
Referenced by SceneChanger.BackToTheHome, SceneChanger.LoadScene.
void GameManager.LoadGameData()
게임 전체를 불러오는 함수.
References LoadPlayerData.
void GameManager.DeleteGameData()
void GameManager.SavePlayerData()
엔딩과 관련된 플레이어 데이터를 저장하는 함수.
References MoraleManager.activeEffects, currentState, currentYear, playerData, playerShip, ES3.Save, SaveBlueprintData.
Referenced by SaveGameData.
void GameManager.LoadPlayerData()
엔딩과 관련된 플레이어 데이터를 불러오는 함수.
References completedMysteryEventIds, currentState, currentYear, ES3.FileExists, Instance, ES3.KeyExists, ES3.Load, LoadBlueprintData, playerData, playerShip, MoraleManager.ReapplyLoadedEffects.
Referenced by LoadGameData.
void GameManager.DeletePlayerData()
void GameManager.SaveWorldMap()
void GameManager.LoadWorldMap()
void GameManager.DeleteWorldMap()
PlanetData GameManager.GetRandomPlanetData()
void GameManager.SaveWarpMap()
void GameManager.LoadWarpMap()
void GameManager.DeleteWarpMap()
void GameManager.SetCurrentWarpMap(List< WarpNodeData > nodes, int targetPlanetId)
void GameManager.SetCurrentWarpNodeId(int nodeId)
void GameManager.ClearCurrentWarpMap()
void GameManager.SetCurrentWarpTargetPlanetId(int planetId)
void GameManager.LandOnPlanet()
void GameManager.ShowEnding()
PlanetData GameManager.WhereIAm()
void GameManager.OnPirateKilled()
void GameManager.CheckPirateQuests()
해적 처치 시 모든 해적 잡기 퀘스트를 체크합니다.
References RandomQuest.objectives, planetDataList, PlanetData.questList.
void GameManager.CheckItemQuests()
모든 아이템 관련 퀘스트를 체크합니다.
References RandomQuest.objectives, planetDataList, playerShip, PlanetData.questList.
void GameManager.SaveBlueprintData()
Blueprint 데이터를 JSON 파일로 저장합니다.
References BlueprintSlotManager.appliedSlotIndex, BlueprintSlotManager.Instance, BlueprintSlotManager.isValidBP, BlueprintSlotManager.occupiedTilesPerSlot.
Referenced by SavePlayerData.
void GameManager.LoadBlueprintData()
Blueprint 데이터를 JSON 파일에서 로드합니다.
References BlueprintSlotManager.Instance, BlueprintSlotManager.isValidBP, BlueprintSlotManager.occupiedTilesPerSlot.
Referenced by LoadPlayerData.
void GameManager.DeleteBlueprintData()
Blueprint 데이터 파일을 삭제하고 SlotManager 데이터를 초기화합니다.
References BlueprintSlotManager.Instance, BlueprintSlotManager.isValidBP, BlueprintSlotManager.occupiedTilesPerSlot.
void GameManager.AddCompletedMysteryEvent(int eventId)
미스터리 이벤트 완료 시 호출하여 ID를 기록합니다
eventId 완료된 미스터리 이벤트 ID
References completedMysteryEventIds, playerData.
Referenced by EventManager.ProcessChoice.
bool GameManager.IsMysteryEventCompleted(int eventId)
특정 미스터리 이벤트가 이미 완료되었는지 확인합니다
eventId 확인할 이벤트 ID 완료된 경우 true
References completedMysteryEventIds.
void GameManager.Awake()
게임 상태 변경 이벤트 델리게이트입니다.
References InitializeGame, Instance.
void GameManager.Start()
void GameManager.OnEnable()
void GameManager.OnDestroy()
void GameManager.OnLanguageChanged(SystemLanguage newLanguage)
void GameManager.InitializeGame()
게임 초기화 로직을 수행합니다.
References WaitForManagers.
Referenced by Awake.
IEnumerator GameManager.WaitForManagers()
다른 중요 매니저가 초기화될 때까지 대기합니다.
Referenced by InitializeGame.
void GameManager.HandleGameOver()
게임 오버 상태 진입 시 호출됩니다. UI 업데이트, 점수 계산 등 게임 오버 관련 처리를 담당합니다.
Referenced by ChangeGameState.
IEnumerator GameManager.DelayedStartNewGame()
void GameManager.GeneratePlanetsData()