OuterHullSystem
HullType
List<OuterHull> OuterHullSystem.currentOuterHulls
int OuterHullSystem.currentOuterHullLevel
외부 선체 시스템의 현재 레벨을 나타냅니다. 이 레벨은 들어오는 공격에 대해 적용되는 피해 감소량에 영향을 줄 수 있습니다.
Referenced by GetOuterHullLevel, SetOuterHullLevel.
override void OuterHullSystem.Initialize(Ship ship)
시스템 초기화
ship 소유 함선
Referenced by Ship.InitializeSystems.
override void OuterHullSystem.Update(float deltaTime)
매 프레임마다 호출되어 시스템 상태를 갱신합니다.
deltaTime 경과 시간 (초).
Referenced by Ship.Update.
float OuterHullSystem.ReduceDamage(float damage)
외부 선체의 피해 감소율을 적용하여 실질적인 피해량을 계산합니다.
damage 입력된 원래 피해량. 피해 감소가 적용된 최종 피해량.
References Ship.GetStat, ShipSystem.parentShip.
Referenced by Ship.TakeAttack.
int OuterHullSystem.GetOuterHullLevel()
외부 선체 시스템의 현재 레벨을 반환합니다.
외부 선체 시스템의 현재 레벨.
References currentOuterHullLevel.
Referenced by Ship.GetOuterHullLevel, Ship.UpdateOuterHullVisuals.
void OuterHullSystem.SetOuterHullLevel(int level)
함선의 외갑판 레벨을 설정합니다. 모든 무기의 외형도 함께 업데이트합니다.
level 설정할 외갑판 레벨 (0-2)
References ShipWeapon.ApplyRotationSprite, currentOuterHullLevel, Ship.GetAllWeapons, ShipSystem.parentShip, OuterHull.SetLevel.
Referenced by Ship.SetOuterHullLevel.
void OuterHullSystem.UpdateVisuals(int level)
외갑판의 시각적 표현을 업데이트합니다. 방 주변에 외갑판을 생성하고, 필요한 위치에 내부 모서리 외갑판도 생성합니다.
level 적용할 외갑판 레벨 (0-2)
References AddPlacementIfNotDuplicate, CalculateSpriteIndex, ClearExistingHulls, CreateOuterHull, Room< TData, TLevel >.currentRotation, Ship.GetAllRooms, Ship.GetOuterHullData, Ship.GetOuterHullPrefab, Room< TData, TLevel >.GetSize, IsOutOfBounds, ShipSystem.parentShip, Room< TData, TLevel >.position.
Referenced by Ship.UpdateOuterHullVisuals.
void OuterHullSystem.ClearExistingHulls()
기존 외갑판 객체들을 모두 제거합니다.
References ShipSystem.parentShip.
Referenced by Ship.ClearExistingHulls, Customize_2_Controller.OnClickBuy, UpdateVisuals.
bool OuterHullSystem.IsOutOfBounds(Vector2Int pos)
그리드 범위를 벗어났는지 확인
References ShipSystem.parentShip.
Referenced by UpdateVisuals.
void OuterHullSystem.AddPlacementIfNotDuplicate(List< HullPlacementInfo > placements, HullPlacementInfo newInfo)
중복 검사 후 배치 정보 추가
Referenced by UpdateVisuals.
int OuterHullSystem.CalculateSpriteIndex(HullPlacementInfo info)
외갑판 배치 정보에 따른 스프라이트 인덱스 계산
Referenced by UpdateVisuals.
void OuterHullSystem.CreateOuterHull(Vector2Int hullPosition, int spriteIndex, int level, OuterHullData hullData, GameObject hullPrefab, HullType hullType)
지정된 위치에 외갑판을 생성합니다.
hullPosition 외갑판 위치 spriteIndex 스프라이트 인덱스 (0-3: 하좌상우 기본, 4-7: 하좌상우 변형, 8-11: 외부 모서리, 12-15: 내부 모서리) level 외갑판 레벨 (0-2) hullData 외갑판 데이터 hullPrefab 외갑판 프리팹 hullType 외갑판 유형
References OuterHullData.GetSpecificHullSprite, Ship.GetWorldPositionFromGrid, OuterHull.Initialize, ShipSystem.parentShip, OuterHull.SetOuterHullData.
Referenced by UpdateVisuals.