ES3Cloud
int ES3Cloud.timeout
byte [] ES3Cloud._data
System.Text.Encoding ES3Cloud.encoding
The encoding to use when encoding and decoding data as strings.
byte [] ES3Cloud.data
Any downloaded data, if applicable. This may also contain an error message, so you should check the 'ifError' variable before reading data.
string ES3Cloud.text
The downloaded data as text, decoded using the encoding specified by the 'encoding' variable.
string [] ES3Cloud.filenames
An array of filenames downloaded from the server. This must only be accessed after calling the 'DownloadFilenames' routine.
DateTime ES3Cloud.timestamp
A UTC DateTime object representing the date and time a file on the server was last updated. This should only be called after calling the 'DownloadTimestamp' routine.
ES3Cloud.ES3Cloud(string url, string apiKey)
Constructs an new ES3Cloud object with the given URL to an ES3.php file.
url The URL of the ES3.php file on your server you want to use.
ES3Cloud.ES3Cloud(string url, string apiKey, int timeout)
IEnumerator ES3Cloud.Sync()
Synchronises the default file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
References Sync.
Referenced by Sync, Sync, Sync, Sync, Sync, Sync, Sync.
IEnumerator ES3Cloud.Sync(string filePath)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the local file we want to synchronise.
References Sync.
IEnumerator ES3Cloud.Sync(string filePath, string user)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the local file we want to synchronise. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References Sync.
IEnumerator ES3Cloud.Sync(string filePath, string user, string password)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the local file we want to synchronise. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References Sync.
IEnumerator ES3Cloud.Sync(string filePath, ES3Settings settings)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the local file we want to synchronise. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References Sync.
IEnumerator ES3Cloud.Sync(string filePath, string user, ES3Settings settings)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the file we want to use. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References Sync.
IEnumerator ES3Cloud.Sync(string filePath, string user, string password, ES3Settings settings)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
filePath The relative or absolute path of the local file we want to synchronise. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References Sync.
IEnumerator ES3Cloud.UploadFile()
Uploads the default file to the server, overwriting any existing file.
References UploadFile.
Referenced by Sync, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile, UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath, string user)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath, string user, string password)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath, ES3Settings settings)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use. settings The settings we want to use to override the default settings.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath, string user, ES3Settings settings)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(string filePath, string user, string password, ES3Settings settings)
Uploads a local file to the server, overwriting any existing file.
filePath The relative or absolute path of the file we want to use. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(ES3File es3File)
Uploads a local file to the server, overwriting any existing file.
es3File An ES3File containing the data we want to upload.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(ES3File es3File, string user)
Uploads a local file to the server, overwriting any existing file.
es3File An ES3File containing the data we want to upload. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(ES3File es3File, string user, string password)
Uploads a local file to the server, overwriting any existing file.
es3File An ES3File containing the data we want to upload. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References UploadFile.
IEnumerator ES3Cloud.UploadFile(ES3Settings settings, string user, string password)
Uploads a local file to the server, overwriting any existing file.
user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References ES3.LoadRawBytes, UploadFile.
IEnumerator ES3Cloud.UploadFile(byte[] bytes, ES3Settings settings, string user, string password)
IEnumerator ES3Cloud.DownloadFile()
Downloads the default file from the server and saves it locally, overwriting the existing local default file. An error is returned if the file does not exist.
References DownloadFile.
Referenced by DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, DownloadFile, Sync.
IEnumerator ES3Cloud.DownloadFile(string filePath)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(string filePath, string user)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(string filePath, string user, string password)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(string filePath, ES3Settings settings)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download. settings The settings we want to use to override the default settings.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(string filePath, string user, ES3Settings settings)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(string filePath, string user, string password, ES3Settings settings)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
filePath The relative or absolute path of the file we want to download. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(ES3File es3File)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
es3File The ES3File we want to load our data into. The filename in the settings of the ES3File will be used when downloading.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(ES3File es3File, string user)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
es3File The ES3File we want to load our data into. The filename in the settings of the ES3File will be used when downloading. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References DownloadFile.
IEnumerator ES3Cloud.DownloadFile(ES3File es3File, string user, string password)
Downloads a file from the server and saves it locally, overwriting any existing local file. An error is returned if the file does not exist.
es3File The ES3File we want to load our data into. The filename in the settings of the ES3File will be used when downloading. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References DownloadFile.
IEnumerator ES3Cloud.DeleteFile()
Deletes the default file from the server. An error is not returned if the file does not exist.
References DeleteFile.
Referenced by DeleteFile, DeleteFile, DeleteFile, DeleteFile, DeleteFile, DeleteFile, DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete.
References DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath, string user)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath, string user, string password)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath, ES3Settings settings)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. settings The settings we want to use to override the default settings.
References DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath, string user, ES3Settings settings)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References DeleteFile.
IEnumerator ES3Cloud.DeleteFile(string filePath, string user, string password, ES3Settings settings)
Deletes a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References DeleteFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete.
References RenameFile.
Referenced by RenameFile, RenameFile, RenameFile, RenameFile, RenameFile, RenameFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath, string user)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References RenameFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath, string user, string password)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References RenameFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath, ES3Settings settings)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. settings The settings we want to use to override the default settings.
References RenameFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath, string user, ES3Settings settings)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References RenameFile.
IEnumerator ES3Cloud.RenameFile(string filePath, string newFilePath, string user, string password, ES3Settings settings)
Renames a file from the server. An error is not returned if the file does not exist.
filePath The relative or absolute path of the file we want to delete. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References RenameFile.
IEnumerator ES3Cloud.DownloadFilenames(string user="", string password="")
Downloads the names of all of the files on the server. Downloaded filenames are stored in the 'filenames' variable of the ES3Cloud object.
user The unique name of the user we want to find the filenames of. password The password of the user we want to find the filenames of.
IEnumerator ES3Cloud.SearchFilenames(string searchPattern, string user="", string password="")
Downloads the names of all of the files on the server. Downloaded filenames are stored in the 'filenames' variable of the ES3Cloud object.
user The unique name of the user we want to find the filenames of. password The password of the user we want to find the filenames of. searchPattern A search pattern containing '' or '_' wildcards where '' represents zero, one, or multiple characters, and '_' represents a single character.
IEnumerator ES3Cloud.DownloadTimestamp()
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
References DownloadTimestamp.
Referenced by DownloadTimestamp, DownloadTimestamp, DownloadTimestamp, DownloadTimestamp, DownloadTimestamp, DownloadTimestamp, DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of.
References DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath, string user)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of. user The unique name of the user this file belongs to, if the file isn't globally accessible.
References DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath, string user, string password)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath, ES3Settings settings)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of. settings The settings we want to use to override the default settings.
References DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath, string user, ES3Settings settings)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of. user The unique name of the user this file belongs to, if the file isn't globally accessible. settings The settings we want to use to override the default settings.
References DownloadTimestamp.
IEnumerator ES3Cloud.DownloadTimestamp(string filePath, string user, string password, ES3Settings settings)
Downloads the timestamp representing when the server file was last updated. The downloaded timestamp is stored in the 'timestamp' variable of the ES3Cloud object.
filePath The relative or absolute path of the file we want to get the timestamp of. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to. settings The settings we want to use to override the default settings.
References DownloadTimestamp.
IEnumerator ES3Cloud.Sync(ES3Settings settings, string user, string password)
Synchronises a local file with a file on the server. If the file on the server is newer than the local copy, the local file will be overwritten by the file on the server. Otherwise, the file on the server will be overwritten.
settings The settings we want to use to override the default settings. user The unique name of the user this file belongs to, if the file isn't globally accessible. password The password of the user this file belongs to.
References DownloadFile, ES3Internal.ES3WebClass.errorCode, ES3.FileExists, UploadFile.
IEnumerator ES3Cloud.UploadFile(byte[] bytes, ES3Settings settings, string user, string password, long fileTimestamp)
IEnumerator ES3Cloud.DownloadFile(ES3File es3File, string user, string password, long timestamp)
IEnumerator ES3Cloud.DownloadFile(ES3Settings settings, string user, string password, long timestamp)
IEnumerator ES3Cloud.DeleteFile(ES3Settings settings, string user, string password)
IEnumerator ES3Cloud.RenameFile(ES3Settings settings, ES3Settings newSettings, string user, string password)
IEnumerator ES3Cloud.DownloadTimestamp(ES3Settings settings, string user, string password)
long ES3Cloud.DateTimeToUnixTimestamp(DateTime dt)
long ES3Cloud.GetFileTimestamp(ES3Settings settings)
override void ES3Cloud.Reset()