TradingItem
TradingItemData TradingItem.itemData
SpriteRenderer TradingItem.boxRenderer
SpriteRenderer TradingItem.itemRenderer
SpriteRenderer TradingItem.frameRenderer
float TradingItem.frameOffsetY
Sprite [] TradingItem.boxSprites
float? TradingItem.cachedPrice
bool TradingItem.priceInitialized
Constants.Rotations.Rotation TradingItem.rotation
bool [][] TradingItem.boxGrid
StorageRoomBase TradingItem.parentStorage
Vector2Int TradingItem.gridPosition
bool TradingItem.isDragging
bool TradingItem.isDragMode
void TradingItem.Start()
void TradingItem.UpdateColliderSize()
boxGrid 정보를 기반으로 아이템 모양에 맞게 BoxCollider2D를 생성합니다. 창고의 회전도 고려하여 실제 표시되는 모양에 맞게 콜라이더를 생성합니다.
Referenced by Rotate, SetDragMode.
void TradingItem.Initialize(TradingItemData data, int quantity, ItemState state=ItemState.Normal)
void TradingItem.CopyFrom(TradingItem other)
float TradingItem.GetCurrentPrice()
현재 가격을 반환합니다. 아직 초기화되지 않았다면 RecalculatePrice()를 호출하여 basePrice ± fluctuation 범위에서 랜덤으로 결정한 후, 동일한 값을 반환합니다.
현재 계산된 가격
References RecalculatePrice.
void TradingItem.RecalculatePrice()
외부에서 가격을 갱신할 필요가 있을 때 호출합니다. basePrice ± fluctuation 범위 내에서 새로 랜덤으로 가격을 계산합니다. 음수가 되지 않도록 보정합니다.
References GetBasePrice.
Referenced by GetCurrentPrice.
float TradingItem.GetBasePrice()
원본 가격(BasePrice)을 반환합니다. 변동폭이나 기타 가격 계산 로직과 무관하게, JSON에 정의된 기본 가격을 그대로 반환합니다. 인벤토리 아이템의 가격을 나타낼 때 사용됩니다.
아이템의 기본 가격(basePrice)
Referenced by RecalculatePrice.
TradingItemData TradingItem.GetItemData()
void TradingItem.ShowItemFrame()
void TradingItem.HideItemFrame()
Sprite TradingItem.GetItemSprite()
Vector2 TradingItem.GetWorldPosition()
void TradingItem.Rotate(Constants.Rotations.Rotation newRotation)
오브젝트 회전
rotation 새 회전 상태
References Room< TData, TLevel >.currentRotation, UpdateColliderSize.
Referenced by TradingItemDragHandler.CancelDragging, TradingItemDragHandler.EndDragging, StorageRoomBase.RotateItem, SetParentStorage.
object TradingItem.GetRotation()
현재 회전 상태
Vector2Int TradingItem.GetGridPosition()
그리드 위치
void TradingItem.SetGridPosition(Vector2Int position)
그리드 위치 설정
position 새 그리드 위치
void TradingItem.SetParentStorage(StorageRoomBase storage)
부모 창고 설정 시 회전도 함께 적용
References Rotate.
void TradingItem.OnPointerClick(PointerEventData eventData)
void TradingItem.OnBeginDrag(PointerEventData eventData)
void TradingItem.OnDrag(PointerEventData eventData)
void TradingItem.OnEndDrag(PointerEventData eventData)
void TradingItem.SetDragMode(bool isDragging)
드래그 모드 설정 (프리뷰 사용 중일 때 원본 아이템의 가시성 설정)
References UpdateColliderSize.
Referenced by StorageRoomBase.AddItem, TradingItemDragHandler.CancelDragging, TradingItemDragHandler.EndDragging, TradingItemDragHandler.ResetAllItemsInteractivity, TradingItemDragHandler.StartDragging.
SpriteRenderer TradingItem.GetBoxRenderer()
void TradingItem.PositionFrameAtGridCenter()
bool TradingItem.GetIsDragMode()
int TradingItem.GetItemId()
ItemState TradingItem.GetItemState()
void TradingItem.SetItemState(ItemState state)
ItemPlanet TradingItem.GetItemPlanet()
ItemTierLevel TradingItem.GetItemTierLevel()
string TradingItem.GetItemName()
ItemCategory TradingItem.GetItemCategory()
int TradingItem.GetItemShape()
float TradingItem.GetTemperaturMin()
float TradingItem.GetTemperaturMax()
int TradingItem.GetCapacity()
int TradingItem.GetCostMin()
int TradingItem.GetCostMax()
string TradingItem.GetDescription()
float TradingItem.GetCostChangeRate()
int TradingItem.GetRandomCost()
StorageRoomBase TradingItem.GetParentStorage()