TradeUIController
ShipFollowCamera TradeUIController.shipFollowCamera
배의 위치 렌더링 조정을 위해 필요한 카메라 참조
Referenced by CameraTransitionCoroutine, Start, TransitionCameraToPosition.
Vector2 TradeUIController.buyPanelOpenedShipPosition
구매 패널이 열려있을 때 배가 위치해야하는 정규화된 위치
Referenced by SlideBuyOpen.
Vector2 TradeUIController.sellPanelOpenedShipPosition
판매 패널이 열려있을 때 배가 위치해야하는 정규화된 위치
Referenced by SlideSellOpen.
TextMeshProUGUI TradeUIController.COMAText
COMA 보유량 텍스트
TextMeshProUGUI TradeUIController.fuelText
연료 보유량 텍스트
TextMeshProUGUI TradeUIController.missileText
미사일 보유량 텍스트
TextMeshProUGUI TradeUIController.hypersonicText
초음속탄 보유량 텍스트
TextMeshProUGUI TradeUIController.COMAChangeText
COMA 변동량 텍스트
Referenced by ShowChangeText.
TextMeshProUGUI TradeUIController.fuelChangeText
연료 변동량 텍스트
Referenced by ShowChangeText.
TextMeshProUGUI TradeUIController.missileChangeText
미사일 변동량 텍스트
Referenced by ShowChangeText.
TextMeshProUGUI TradeUIController.hypersonicChangeText
초음속탄 변동량 텍스트
Referenced by ShowChangeText.
Button TradeUIController.buttonBuy
구매 패널을 여는 버튼
Referenced by AddButtonListeners, SlideBuyClose, SlideBuyOpen.
Button TradeUIController.buttonSell
판매 패널을 여는 버튼
Referenced by AddButtonListeners, SlideSellClose, SlideSellOpen.
GameObject TradeUIController.panelBuy
구매 패널
Referenced by AddButtonListeners, OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked, OnPanelButtonClicked, SlideBuyClose, SlideBuyOpen, Start, Update.
GameObject TradeUIController.panelSell
판매 패널
Referenced by AddButtonListeners, OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked, OnPanelButtonClicked, SlideSellClose, SlideSellOpen, Start, Update.
GameObject TradeUIController.buyPanelContent
아이템 구매 패널에 표시될 정보를 담는 곳
Referenced by InitializeBuyPanel.
GameObject TradeUIController.buyItemInfoPrefab
아이템 구매 패널에 담기는 정보 게임 오브젝트 프리팹
Referenced by InitializeBuyPanel.
Transform TradeUIController.itemMapBuyPosition
구매 중일 때의 아이템 맵 위치
Referenced by ShowBuyItemMap.
BuyCheckPanel TradeUIController.buyCheckPanel
구매 확인창 패널
Referenced by OnBuyCheckBuyButtonClicked, ShowBuyCheckPanel, Update.
Button TradeUIController.buyConfirmButton
구매 확정 버튼
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked.
Button TradeUIController.buyCancelButton
구매 취소 버튼
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked.
Camera TradeUIController.mainCamera
임시 창고의 위치를 계산하기 위한 메인 카메라 참조
Referenced by MoveShipToPoint.
Ship TradeUIController.tradeShip
임시 창고를 설치할 창고용 배
Referenced by MoveShipToPoint, OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked, Start.
Vector2 TradeUIController.normalizedTradeShipPosition
임시 창고의 정규화된 좌표 (뷰포트를 따름)
Referenced by MoveShipToPoint.
TextMeshProUGUI TradeUIController.notEmptyWarningText
임시 창고가 비어있지 않다는 경고 텍스트
Referenced by OnBuyConfirmButtonClicked.
TextMeshProUGUI TradeUIController.dontPlaceItemHereText
임시 창고에 함선을 두지 마라는 경고 텍스트
Referenced by OnBuyCancelButtonClicked.
BuyItemInfoPanel TradeUIController.selectedBuyItemInfoPanel
선택 중인 구매 아이템 정보 오브젝트 참조
List<BuyItemInfoPanel> TradeUIController.buyItemInfoPanelInstance
모든 구매 아이템 정보 오브젝트 리스트
Referenced by InitializeBuyPanel, UpdateBuyPanel.
bool TradeUIController.isBuyPanelInitialized
구매 패널이 초기화 되었는지 여부
Referenced by InitializeBuyPanel, Start.
StorageRoomBase TradeUIController.tradeStorage
거래용 임시 창고 참조
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked, Start.
TradingItem TradeUIController.itemInstance
거래 중인 아이템 참조
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked.
GameObject TradeUIController.sellPanelContent
아이템 판매 패널에 표시될 정보를 담는 곳
Referenced by InitializeSellPanel.
GameObject TradeUIController.sellItemInfoPrefab
아이템 판매 패널에 담기는 정보 오브젝트 프리팹
Referenced by InitializeSellPanel.
Transform TradeUIController.itemMapSellPosition
아이템 판매 중일 때 아이템 맵의 위치
Referenced by ShowSellItemMap.
SellItemInfoPanel TradeUIController.selectedSellItemInfoPanel
선택 중인 아이템 판매 정보 오브젝트 참조
Referenced by HideItemMap.
List<SellItemInfoPanel> TradeUIController.sellItemInfoPanelInstance
모든 아이템 판매 정보 오브젝트 리스트
Referenced by InitializeSellPanel.
EquipmentDatabase TradeUIController.equipmentDatabase
GameObject TradeUIController.equipmentItemInfoPrefab
EquipmentInfoPanel TradeUIController.equipmentLeftInstance
EquipmentInfoPanel TradeUIController.equipmentRightInstance
EquipmentInfoPanel TradeUIController.equipmentMiddleInstance
GameObject TradeUIController.equipmentLeftContainer
GameObject TradeUIController.equipmentMiddleContainer
GameObject TradeUIController.equipmentRightContainer
GameObject TradeUIController.equipmentSoldOutPrefab
GameObject TradeUIController.equipmentLeftSoldOutInstance
GameObject TradeUIController.equipmentRightSoldOutInstance
GameObject TradeUIController.equipmentMiddleSoldOutInstance
GameObject TradeUIController.equipmentGlobalApplyAllPanel
EquipmentItem TradeUIController.recentBoughtEquipment
Button TradeUIController.fuelBuyButton
연료 구매 버튼
Button TradeUIController.missileBuyButton
미사일 구매 버튼
Button TradeUIController.hypersonicBuyButton
초음속탄 구매 버튼
TextMeshProUGUI TradeUIController.fuelPrice
연료 가격
TextMeshProUGUI TradeUIController.missilePrice
미사일 가격
TextMeshProUGUI TradeUIController.hypersonicPrice
미사일 가격
TextMeshProUGUI TradeUIController.notEnoughFuelCapacityText
Transform TradeUIController.buyPanelOpenedPosition
구매 패널이 열려야되는 위치
Referenced by SlideBuyOpen.
Transform TradeUIController.SellPanelOpenendPosition
판매 패널이 열려야되는 위치
Referenced by SlideSellOpen.
float TradeUIController.slideSpeed
패널들이 열리는 속도
Referenced by CameraTransitionCoroutine, SlideToPosition.
ItemMapController TradeUIController.itemMapPanel
아이템 맵 패널
Referenced by HideItemMap, SellItem, ShowBuyItemMap, ShowSellItemMap.
Button TradeUIController.exitButton
씬 나가기 버튼
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked.
TextMeshProUGUI TradeUIController.notEnoughCOMAText
돈 부족 알림 텍스트
Referenced by OnBuyCheckBuyButtonClicked.
Vector3 TradeUIController.buyPanelClosedPosition
구매 패널의 닫혀있는 위치 참조
Referenced by SlideBuyClose, Start.
Vector3 TradeUIController.sellPanelClosedPosition
판매 패널의 닫혀있는 위치 참조
Referenced by SlideSellClose, Start.
Coroutine TradeUIController.buySlideCoroutine
구매 패널이 슬라이드 되는 코루틴
Referenced by SlideBuyClose, SlideBuyOpen.
Coroutine TradeUIController.sellSlideCoroutine
판매 패널이 슬라이드 되는 코루틴
Referenced by SlideSellClose, SlideSellOpen.
Vector2 TradeUIController.originalCameraPosition
카메라 최초 위치 참조
Referenced by SlideBuyClose, SlideSellClose, Start.
Coroutine TradeUIController.cameraTransitionCoroutine
패널이 열릴 때 카메라의 위치를 조정하기 위한 코루틴
Referenced by TransitionCameraToPosition.
bool TradeUIController.isBuyPanelOpen
구매 패널이 열려있는지 여부
Referenced by SlideBuyClose, SlideBuyOpen, Update.
bool TradeUIController.isSellPanelOpen
판매 패널이 열려있는지 여부
Referenced by SlideSellClose, SlideSellOpen, Update.
void TradeUIController.Start()
거래용 임시 배 및 창고를 초기화하고 각종 UI들의 위치 관계와 버튼의 Listener를 추가함.
References AddButtonListeners, Ship.AddRoom, buyPanelClosedPosition, RoomFactory.CreateStorageRoomInstance, InitializeResourcesText, isBuyPanelInitialized, originalCameraPosition, panelBuy, panelSell, sellPanelClosedPosition, shipFollowCamera, tradeShip, tradeStorage.
void TradeUIController.Update()
패널 외 다른 부분을 클릭하는지 검사하고, 클릭했다면 패널을 닫는다.
References buyCheckPanel, isBuyPanelOpen, IsClickingOnSelf, isSellPanelOpen, panelBuy, panelSell, SlideBuyClose, SlideSellClose.
void TradeUIController.OnEnable()
자원 변화 효과를 위해 ResourceManager 의 OnResourceChanged 를 구독.
References SetResourcesText.
void TradeUIController.AddButtonListeners()
각 패널을 여는 버튼들에 Listners 추가.
References buttonBuy, buttonSell, OnPanelButtonClicked, panelBuy, panelSell.
Referenced by Start.
bool TradeUIController.IsClickingOnSelf(GameObject currentPanel)
스스로를 클릭하는 여부를 반환하는 함수
currentPanel 확인하고픈 패널 스스로를 클릭 중인지 여부
Referenced by Update.
void TradeUIController.SlideBuyOpen()
구매 패널을 여는 함수.
References buttonBuy, buyPanelOpenedPosition, buyPanelOpenedShipPosition, buySlideCoroutine, isBuyPanelOpen, MoveShipToPoint, panelBuy, SlideToPosition, TransitionCameraToPosition.
Referenced by OnPanelButtonClicked.
void TradeUIController.SlideSellOpen()
판매 패널을 여는 함수
References buttonSell, isSellPanelOpen, panelSell, sellPanelOpenedShipPosition, SellPanelOpenendPosition, sellSlideCoroutine, SlideToPosition, TransitionCameraToPosition.
Referenced by OnPanelButtonClicked.
void TradeUIController.SlideBuyClose()
구매 패널을 닫는 함수
References buttonBuy, buyPanelClosedPosition, buySlideCoroutine, isBuyPanelOpen, originalCameraPosition, panelBuy, SlideToPosition, TransitionCameraToPosition.
Referenced by Update.
void TradeUIController.SlideSellClose()
판매 패널을 닫는 함수
References buttonSell, isSellPanelOpen, originalCameraPosition, panelSell, sellPanelClosedPosition, sellSlideCoroutine, SlideToPosition, TransitionCameraToPosition.
Referenced by Update.
IEnumerator TradeUIController.SlideToPosition(GameObject targetPanel, Vector3 targetPosition, Action onComplete=null)
패널을 원하는 위치로 슬라이드(개폐)하는 함수
targetPanel 열고 닫을 패널 targetPosition 목표 위치 onComplete 완료했을 때의 콜백 코루틴
References slideSpeed.
Referenced by SlideBuyClose, SlideBuyOpen, SlideSellClose, SlideSellOpen.
void TradeUIController.TransitionCameraToPosition(Vector2 targetPosition)
패널을 열고 닫을 때 배가 적절한 위치에 렌더링되기 위해 카메라를 이동시키는 함수
targetPosition 목표 위치
References cameraTransitionCoroutine, CameraTransitionCoroutine, shipFollowCamera.
Referenced by SlideBuyClose, SlideBuyOpen, SlideSellClose, SlideSellOpen.
IEnumerator TradeUIController.CameraTransitionCoroutine(Vector2 targetPosition)
카메라를 목표 위치로 이동시키는 코루틴
targetPosition 목표 위치 코루틴
References shipFollowCamera, slideSpeed.
Referenced by TransitionCameraToPosition.
void TradeUIController.ShowChangeText(ResourceType type, float diff)
재화의 변화량을 표시하는 함수
type 재화의 타입 diff 변화량
References COMAChangeText, fuelChangeText, HideChangeText, hypersonicChangeText, missileChangeText.
Referenced by SetResourcesText.
IEnumerator TradeUIController.HideChangeText(TextMeshProUGUI text, float delay)
텍스트를 몇 초 있다가 없어지게 하는 코루틴
text 해당 텍스트 참조 delay 기다릴 시간 코루틴
Referenced by OnBuyCancelButtonClicked, OnBuyCheckBuyButtonClicked, OnBuyConfirmButtonClicked, ShowChangeText.
void TradeUIController.BuyFuel()
void TradeUIController.BuyMissile()
void TradeUIController.BuyHypersonic()
void TradeUIController.OnPanelButtonClicked(GameObject targetPanel)
각 패널을 여는 버튼들의 기능.
targetPanel
References InitializeBuyPanel, InitializeSellPanel, panelBuy, panelSell, SlideBuyOpen, SlideSellOpen.
Referenced by AddButtonListeners.
void TradeUIController.OnGoBackButtonClicked()
나가기 버튼이 눌렸을 때 호출됨. 행성 씬으로 돌아간다.
References SceneChanger.LoadScene.
void TradeUIController.InitializeResourcesText()
재화 패널의 텍스트들을 초기화한다.
Referenced by InitializeBuyPanel, InitializeSellPanel, SetResourcesText, Start.
void TradeUIController.SetResourcesText(ResourceType type, float amount)
재화 패널의 텍스트를 업데이트하고, 변화값을 표시한다.
type amount
References InitializeResourcesText, ShowChangeText.
Referenced by OnEnable.
void TradeUIController.InitializeBuyPanel()
구매 패널을 초기화한다. 현재 거래량에 따라 정해진 행성에서 판매하는 아이템의 목록을 미리 불러오고 구매 패널에 추가한다.
References buyItemInfoPanelInstance, buyItemInfoPrefab, buyPanelContent, InitializeResourcesText, GameManager.Instance, isBuyPanelInitialized, PlanetData.itemsTier1, PlanetData.itemsTier2, PlanetData.itemsTier3, UpdateBuyPanel.
Referenced by OnPanelButtonClicked.
void TradeUIController.UpdateBuyPanel()
구매 패널을 갱신한다.
References buyItemInfoPanelInstance, PlanetData.CurrentTier, GameManager.Instance.
Referenced by BuyItem, InitializeBuyPanel.
void TradeUIController.ShowBuyItemMap(TradingItemData selectedItem)
구매 패널의 아이템 맵을 보여준다. 구매 패널의 아이템맵을 가격 비교를 현재 행성에서 판매하는 가격을 다른 행성과 비교한다.
selectedItem 선택한 아이템
References itemMapBuyPosition, itemMapPanel.
void TradeUIController.ShowBuyCheckPanel(TradingItemData selectedItem)
구매 확인 창을 띄우는 함수
selectedItem 선택한 아이템
References buyCheckPanel.
void TradeUIController.OnBuyCheckBuyButtonClicked(TradingItemData selectedItem)
구매 승인 버튼을 누를 때 호출되는 함수
selectedItem 선택한 아이템
References StorageRoomBase.AddItem, buyCancelButton, buyCheckPanel, buyConfirmButton, exitButton, HideChangeText, itemInstance, notEnoughCOMAText, panelBuy, panelSell, tradeShip, tradeStorage.
void TradeUIController.OnBuyConfirmButtonClicked()
아이템을 임시 창고에서 꺼내 배치하고 구매를 최종적으로 확정하는 버튼을 눌렀을 때 호출되는 함수. 만약 임시 창고에 아이템이 남아있으면 경고 문구를 출력한다. 임시 창고에 아이템이 비어있다면 정상적으로 구매를 진행한다.
References buyCancelButton, buyConfirmButton, BuyItem, exitButton, HideChangeText, itemInstance, notEmptyWarningText, panelBuy, panelSell, StorageRoomBase.storedItems, tradeShip, tradeStorage.
void TradeUIController.OnBuyCancelButtonClicked()
구매를 취소하는 버튼을 누르면 호출되는 함수.
References Ship.allRooms, buyCancelButton, buyConfirmButton, dontPlaceItemHereText, exitButton, HideChangeText, GameManager.Instance, itemInstance, panelBuy, panelSell, GameManager.playerShip, StorageRoomBase.RemoveItem, StorageRoomBase.storedItems, tradeShip, tradeStorage.
void TradeUIController.BuyItem(TradingItemData selectedItem)
구매에 관련된 처리 함수. 구매한 아이템값을 제거하고, 행성의 총 구매액에 추가한다.
selectedItem
References PlanetData.currentRevenue, GameManager.Instance, UpdateBuyPanel.
Referenced by OnBuyConfirmButtonClicked.
void TradeUIController.MoveShipToPoint()
임시 창고용 배를 원하는 지점으로 옮긴다.
References mainCamera, normalizedTradeShipPosition, tradeShip.
Referenced by SlideBuyOpen.
void TradeUIController.InitializeSellPanel()
판매 패널을 초기화한다.
References InitializeResourcesText, GameManager.Instance, GameManager.playerShip, sellItemInfoPanelInstance, sellItemInfoPrefab, sellPanelContent.
Referenced by OnPanelButtonClicked, SellItem.
void TradeUIController.ShowSellItemMap(TradingItemData selectedItem)
판매 패널의 아이템 맵을 표시한다.
selectedItem 선택한 아이템
References itemMapPanel, itemMapSellPosition.
void TradeUIController.HideItemMap()
아이템 맵을 숨기는 함수
References itemMapPanel, selectedSellItemInfoPanel.
void TradeUIController.SellItem(TradingItemData selectedItem)
판매 처리를 진행하는 함수. 현재 아이템의 시세에 맞게 아이템을 판매하고, 그만큼의 액수를 자금에 추가한다.
selectedItem 선택한 아이템
References Ship.GetAllRooms, InitializeSellPanel, GameManager.Instance, itemMapPanel, GameManager.playerShip, StorageRoomBase.storedItems.
void TradeUIController.InitializeEquipmentPanel()
void TradeUIController.UpdateEquipmentPanel()
void TradeUIController.OnClickRandomEquipmentPanel()
void TradeUIController.OnClickWeaponEquipmentPanel()
void TradeUIController.OnClickShieldEquipmentPanel()
void TradeUIController.BuyEquipment(EquipmentItem item)
void TradeUIController.BuyRandomEquipment(EquipmentItem item)
void TradeUIController.OnClickApplyGlobalEquipmentConfirmButton()
void TradeUIController.InitializeResourceBuyPanel()
void TradeUIController.OnClickFuelBuyButton()
void TradeUIController.OnClickMissileBuyButton()
void TradeUIController.OnClickHypersonicBuyButton()