EventDatabase
List<RandomEvent> EventDatabase.allEvents
모든 이벤트 데이터 목록
Referenced by GetAllEvents, GetEventByDebugName, GetEventsForCOMA, GetEventsForYear, GetEventsRequiringRace, GetFilteredEvents, InitializeEventDictionary, InitializeEventsByOutcomeType, InitializeEventsByType.
Dictionary<int, RandomEvent> EventDatabase.eventDictionary
Dictionary<EventType, List<RandomEvent> > EventDatabase.eventsByType
Dictionary<EventOutcomeType, List<RandomEvent> > EventDatabase.eventsByOutcomeType
void EventDatabase.Initialize()
데이터베이스를 초기화합니다.
References InitializeEventDictionary, InitializeEventsByOutcomeType, InitializeEventsByType.
Referenced by GetEvent, GetEventsByOutcomeType, GetEventsByType, OnEnable, ReloadEvents.
List< RandomEvent > EventDatabase.GetAllEvents()
모든 이벤트 목록을 반환합니다.
References allEvents.
RandomEvent EventDatabase.GetEvent(int id)
ID로 이벤트를 검색합니다.
id 이벤트 ID 이벤트 또는 null
References Initialize.
Referenced by EventManager.GetEventById, EventManager.TriggerEventById.
RandomEvent EventDatabase.GetEventByDebugName(string debugName)
디버그 이름으로 이벤트를 검색합니다.
debugName 이벤트 디버그 이름 이벤트 또는 null
References allEvents.
List< RandomEvent > EventDatabase.GetEventsByType(EventType type)
특정 이벤트 타입의 모든 이벤트를 반환합니다.
type 이벤트 타입 해당 타입의 이벤트 목록
References Initialize.
List< RandomEvent > EventDatabase.GetEventsByOutcomeType(EventOutcomeType outcomeType)
특정 결과 타입의 모든 이벤트를 반환합니다.
outcomeType 이벤트 결과 타입 해당 결과 타입의 이벤트 목록
References Initialize.
List< RandomEvent > EventDatabase.GetEventsForYear(int year)
최소 발생 년도 이상의 이벤트를 반환합니다.
year 현재 게임 년도 발생 가능한 이벤트 목록
References allEvents, RandomEvent.minimumYear.
List< RandomEvent > EventDatabase.GetEventsForCOMA(int coma)
최소 COMA 이상의 이벤트를 반환합니다.
coma 현재 COMA 값 발생 가능한 이벤트 목록
References allEvents, RandomEvent.minimumCOMA.
List< RandomEvent > EventDatabase.GetEventsRequiringRace(CrewRace race)
특정 선원 종족이 필요한 이벤트를 반환합니다.
race 선원 종족 해당 종족이 필요한 이벤트 목록
References allEvents, RandomEvent.requiredCrewRace.
List< RandomEvent > EventDatabase.GetFilteredEvents(EventType type, int year, int coma, float fuel, List< CrewRace > availableRaces)
특정 조건에 맞는 이벤트를 필터링하여 반환합니다.
type 이벤트 타입 year 현재 년도 coma 현재 COMA availableRaces 보유 중인 선원 종족 목록 조건에 맞는 이벤트 목록
References allEvents, RandomEvent.minimumCOMA, RandomEvent.minimumFuel, RandomEvent.minimumYear, RandomEvent.requiredCrewRace.
Referenced by GetRandomEvent, EventManager.SelectAppropriateEvent.
RandomEvent EventDatabase.GetRandomEvent(EventType type, int year, int coma, float fuel, List< CrewRace > availableRaces)
주어진 조건에서 발생 가능한 랜덤 이벤트를 선택합니다.
type 이벤트 타입 year 현재 년도 coma 현재 COMA availableRaces 보유 중인 선원 종족 목록 선택된 랜덤 이벤트 또는 null
References GetFilteredEvents.
void EventDatabase.ReloadEvents()
데이터베이스를 초기화하고 모든 이벤트를 다시 로드합니다.
References Initialize.
void EventDatabase.InitializeEventDictionary()
이벤트 ID 기반 딕셔너리를 초기화합니다.
References allEvents.
Referenced by Initialize.
void EventDatabase.InitializeEventsByType()
이벤트 타입별 목록을 초기화합니다.
References allEvents.
Referenced by Initialize.
void EventDatabase.InitializeEventsByOutcomeType()
이벤트 결과 타입별 목록을 초기화합니다.
References allEvents.
Referenced by Initialize.
void EventDatabase.OnEnable()
Unity 이벤트: ScriptableObject가 로드될 때 호출됨
References Initialize.