MoraleManager
MoraleManager MoraleManager.Instance
GameObject MoraleManager.moraleIconPrefab
RectTransform MoraleManager.moraleStatusPanel
Dictionary<CrewRace, MoraleIcon> MoraleManager.raceIcons
List<MoraleEffectData> MoraleManager.activeEffects
현재 적용 중인 사기 효과 데이터
Referenced by CheckEventExpirations, PrintAllMorale, ReapplyLoadedEffects, RegisterMoraleEffect, ResetAllMorale, GameManager.SavePlayerData, UpdateRaceIcon.
float MoraleManager.humanMorale
종족별 사기
Referenced by GetRaceMorale, ReapplyLoadedEffects, ResetAllMorale, SetRaceMorale.
float MoraleManager.amorphousMorale
float MoraleManager.mechanicTankMorale
float MoraleManager.mechanicSupMorale
float MoraleManager.beastMorale
float MoraleManager.insectMorale
float MoraleManager.globalMorale
전체 선원 적용 사기
Referenced by ApplyMoraleEffectValue, GetTotalMoraleBonus, ReapplyLoadedEffects, RemoveMoraleEffectValue, ResetAllMorale, SetAllCrewMorale.
void MoraleManager.Awake()
void MoraleManager.Start()
void MoraleManager.OnEnable()
void MoraleManager.OnDisable()
void MoraleManager.OnSceneLoaded(Scene scene, LoadSceneMode mode)
void MoraleManager.CreateRaceIcons()
종족별 아이콘 생성
References MoraleIcon.Initialize.
void MoraleManager.ApplyMoraleEffectValue(MoraleEffectData effect)
사기 효과 값 적용
References GetRaceMorale, globalMorale, SetAllCrewMorale, SetRaceMorale, MoraleEffectData.targetRace, MoraleEffectData.value.
Referenced by ReapplyLoadedEffects, RegisterMoraleEffect.
void MoraleManager.RemoveMoraleEffectValue(MoraleEffectData effect)
사기 효과 값 제거
References GetRaceMorale, globalMorale, SetAllCrewMorale, SetRaceMorale, MoraleEffectData.targetRace, MoraleEffectData.value.
Referenced by CheckEventExpirations.
void MoraleManager.UpdateRaceIcon(CrewRace race)
종족별 아이콘 업데이트
References activeEffects.
Referenced by CheckEventExpirations, ReapplyLoadedEffects, RegisterMoraleEffect, UpdateAllRaceIcons.
void MoraleManager.UpdateAllRaceIcons()
모든 종족 아이콘 업데이트
References UpdateRaceIcon.
float MoraleManager.GetRaceMorale(CrewRace race)
종족 별 사기 반환
References humanMorale.
Referenced by ApplyMoraleEffectValue, GetTotalMoraleBonus, RemoveMoraleEffectValue.
float MoraleManager.GetTotalMoraleBonus(CrewMember crew)
선원의 총 사기 반환
References GetRaceMorale, globalMorale, CrewBase.race.
Referenced by CrewMember.GetCrewSkillValue.
void MoraleManager.SetRaceMorale(CrewRace race, float value)
종족별 사기 설정
References humanMorale.
Referenced by ApplyMoraleEffectValue, RemoveMoraleEffectValue.
void MoraleManager.SetAllCrewMorale(float value)
전체 선원 사기 한 번에 할당
References globalMorale.
Referenced by ApplyMoraleEffectValue, Ship.RecalculateAllStats, RemoveMoraleEffectValue.
void MoraleManager.ResetAllMorale()
전체 사기 초기화
References activeEffects, MoraleIcon.ClearEffectData, globalMorale, humanMorale.
void MoraleManager.RegisterMoraleEffect(MoraleEffectData effectData)
새로운 사기 효과 등록
References activeEffects, ApplyMoraleEffectValue, MoraleEffectData.targetRace, UpdateRaceIcon.
Referenced by EventCrewEffectHandler.ApplyEffects, RegisterMoraleEffect.
void MoraleManager.RegisterMoraleEffect(CrewEffect crewEffect)
CrewEffect에서 MoraleEffectData 생성 및 등록
References CrewEffect.changeAmount, CrewEffect.conditionAmount, GameManager.CurrentYear, CrewEffect.effectType, GameManager.Instance, CrewEffect.raceType, RegisterMoraleEffect.
void MoraleManager.ReapplyLoadedEffects()
저장된 사기 효과들을 다시 적용합니다 (로드 후 호출용)
References activeEffects, ApplyMoraleEffectValue, MoraleIcon.ClearEffectData, globalMorale, humanMorale, MoraleEffectData.targetRace, UpdateRaceIcon.
Referenced by GameManager.LoadPlayerData.
void MoraleManager.CheckEventExpirations(int currentYear)
현재 이벤트 상태를 확인하고 만료된 효과를 제거합니다
References activeEffects, MoraleEffectData.EndYear, RemoveMoraleEffectValue, MoraleEffectData.targetRace, UpdateRaceIcon.
void MoraleManager.PrintAllMorale()
전체 사기 상태 출력 (디버깅용)
References activeEffects.