CrewUIHandler
CrewUIHandler CrewUIHandler.Instance
싱글턴 인스턴스입니다.
Referenced by Awake, RaceButtonController.OnPointerClick.
GameObject CrewUIHandler.mainUIScreen
선원 생성 메인 화면입니다.
Referenced by GetCurrentActiveUI, OnBackButtonClicked, OnSubmitButtonClicked, ShowUI.
GameObject CrewUIHandler.createUIScreen
선원 생성 요청 화면입니다.
Referenced by GetCurrentActiveUI, OnCreateButtonClicked, OnSubmitButtonClicked.
GameObject CrewUIHandler.customizeShipUIScreen
함선 커스터마이즈 UI 화면입니다.
Referenced by GetCurrentActiveUI, OnCustomizeButtonClicked.
GameObject CrewUIHandler.addEquipmentUIScreen
장비 구매 UI 화면입니다.
Referenced by GetCurrentActiveUI, OnAddEquipmentButtonClicked, OnBackButtonClicked.
GameObject CrewUIHandler.fullCrewUIScreen
선원 최대 수용 시 표시되는 UI 화면입니다.
Referenced by ActiveFullCrewUI, InActiveFullCrewUI.
EquipmentUIHandler CrewUIHandler.equipmentUIHandler
장비 UI 핸들러 참조입니다.
Referenced by ResetEquipmentUI.
RaceButtonController [] CrewUIHandler.raceButtonControllers
각 종족 선택 버튼 컨트롤러 배열입니다.
Button CrewUIHandler.submitButton
최종 제출 버튼입니다.
Button CrewUIHandler.humanButton
인간형 종족 선택 버튼입니다.
Button CrewUIHandler.amorphousButton
부정형(아모르프) 종족 선택 버튼입니다.
Button CrewUIHandler.mechanicTankButton
돌격 기계형 종족 선택 버튼입니다.
Button CrewUIHandler.mechanicSupButton
지원 기계형 종족 선택 버튼입니다.
Button CrewUIHandler.beastButton
짐승형 종족 선택 버튼입니다.
Button CrewUIHandler.insectButton
곤충형 종족 선택 버튼입니다.
Ship CrewUIHandler.playerShip
유저 함선
Referenced by DisableCrews, EnableCrews.
TMP_InputField CrewUIHandler.nameInputField
선원 이름 입력 필드입니다.
Referenced by OnCreateButtonClicked, OnSubmitButtonClicked, Update.
RaceButtonController CrewUIHandler.currentSelectedButton
현재 선택된 종족 버튼입니다.
Referenced by OnCreateButtonClicked, OnRaceButtonClicked, ResetCrewCreateUI.
CrewRace CrewUIHandler.selectedRace
현재 선택된 종족 정보입니다.
Referenced by OnRaceButtonClicked, OnSubmitButtonClicked, ResetCrewCreateUI, Update.
string CrewUIHandler.inputName
선원 이름
Referenced by OnSubmitButtonClicked.
Stack<GameObject> CrewUIHandler.uiHistory
UI 화면 이동 이력을 저장하는 스택 구조입니다. 뒤로 가기 기능에 사용됩니다.
Referenced by OnBackButtonClicked, ShowUI.
void CrewUIHandler.Awake()
싱글턴 인스턴스를 초기화합니다.
References Instance.
void CrewUIHandler.Start()
UI 초기 상태를 설정합니다. Submit 버튼을 비활성화하며, 버튼 이벤트 연결은 에디터에서 처리합니다.
void CrewUIHandler.Update()
종족, 이름 모두 입력 시 submit 버튼 활성화
References nameInputField, selectedRace.
void CrewUIHandler.ResetCrewCreateUI()
선원 생성 시 UI 초기화
References currentSelectedButton, selectedRace, RaceButtonController.SetHighlighted.
Referenced by OnCreateButtonClicked, OnSubmitButtonClicked.
void CrewUIHandler.ActiveFullCrewUI()
수용 가능 선원 꽉 참 UI 생성
References DisableCrews, fullCrewUIScreen.
Referenced by OnCreateButtonClicked.
void CrewUIHandler.InActiveFullCrewUI()
수용 가능 선원 꽉 참 UI 해제
References EnableCrews, fullCrewUIScreen.
void CrewUIHandler.DisableCrews()
UI 진입 시 선원 임시 비활성화
References Ship.allCrews, playerShip.
Referenced by ActiveFullCrewUI, OnAddEquipmentButtonClicked, OnCreateButtonClicked, OnCustomizeButtonClicked.
void CrewUIHandler.EnableCrews()
UI 탈출 시 선원 재활성화
References Ship.allCrews, playerShip.
Referenced by InActiveFullCrewUI, OnBackButtonClicked, OnSubmitButtonClicked.
void CrewUIHandler.ResetEquipmentUI()
장비 구매 물어보는 UI 해제
References equipmentUIHandler, EquipmentUIHandler.itemBuyPanel.
Referenced by OnBackButtonClicked.
GameObject CrewUIHandler.GetCurrentActiveUI()
현재 활성화 되어 있는 UI 반환
References addEquipmentUIScreen, createUIScreen, customizeShipUIScreen, mainUIScreen.
Referenced by OnBackButtonClicked, ShowUI.
void CrewUIHandler.ShowUI(GameObject targetUI)
인자로 받은 UI 활성화
targetUI
References MenuUIManager.ForceCloseMenu, GetCurrentActiveUI, mainUIScreen, uiHistory.
Referenced by OnAddEquipmentButtonClicked, OnCreateButtonClicked, OnCustomizeButtonClicked.
void CrewUIHandler.OnBackButtonClicked()
UIHistory 개념으로 인터넷 뒤로 가기 버튼과 동일한 기능
References addEquipmentUIScreen, EnableCrews, GetCurrentActiveUI, mainUIScreen, ResetEquipmentUI, uiHistory.
void CrewUIHandler.OnRaceButtonClicked(RaceButtonController clickedButton)
종족 선택하는 버튼 클릭 시 호출
clickedButton
References currentSelectedButton, RaceButtonController.raceType, selectedRace, RaceButtonController.SetHighlighted.
Referenced by RaceButtonController.OnPointerClick.
void CrewUIHandler.OnCustomizeButtonClicked()
함선 커스터마이즈를 위한 버튼 클릭 시 호출
References customizeShipUIScreen, DisableCrews, ShowUI.
void CrewUIHandler.OnCreateButtonClicked()
선원 추가를 위한 UI로 이동 버튼 클릭 시 호출
References ActiveFullCrewUI, createUIScreen, currentSelectedButton, DisableCrews, Ship.GetCrewCount, Ship.GetMaxCrew, GameManager.GetPlayerShip, GameManager.Instance, nameInputField, ResetCrewCreateUI, ShowUI.
void CrewUIHandler.OnSubmitButtonClicked()
선원 정보 입력 후 실제 생성하는 버튼 클릭 시 호출
References Ship.AddCrew, createUIScreen, EnableCrews, GameManager.GetPlayerShip, inputName, GameManager.Instance, mainUIScreen, nameInputField, ResetCrewCreateUI, selectedRace.
void CrewUIHandler.OnAddEquipmentButtonClicked()
장비 구매 UI로의 이동 버튼 클릭 시 호출
References addEquipmentUIScreen, DisableCrews, ShowUI.