Ship
bool Ship.isPlayerShip
유저의 함선인지 여부 (true : 유저 함선, false : 적 함선)
Referenced by MedBayRoom.Update.
string Ship.shipName
List<Room> Ship.allRooms
함선을 이루고 있는 이미 배치된 모든 룸 객체 리스트.
Referenced by AddRoom, AddRoom, BackupCurrentShip, GetAllRooms, GetRandomTargetPosition, GetRoomOfType< T >, GetTotalShipValue, IsFullHitPoint, MoveShipToFacingTargetShip, TradeUIController.OnBuyCancelButtonClicked, OnDestroy, RecalculateAllStats, RemoveRoom, ReplaceShipFromBlueprint, RevertToOriginalShip.
List<ShipWeapon> Ship.allWeapons
전체 함선 무기 리스트
Referenced by WeaponSystem.AddWeapon, WeaponSystem.FireAllReadyWeapons, WeaponSystem.FireWeapon, WeaponSystem.FireWeaponsByType, GetAllWeapons, GetTotalShipValue, WeaponSystem.GetWeaponByIndex, WeaponSystem.GetWeaponCount, WeaponSystem.GetWeapons, WeaponSystem.GetWeaponsByType, WeaponSystem.GetWeaponsByWarheadType, WeaponSystem.IsEveryWeaponReady, WeaponSystem.RemoveAllWeapons, ReplaceShipFromBlueprint, WeaponSystem.ResetAllWeaponStats, RevertToOriginalShip, WeaponSystem.Update, WeaponSystem.UpdateWeaponCooldowns.
List<CrewMember> Ship.allCrews
전체 아군 선원 리스트
Referenced by CrewSystem.AddCrew, CombatManager.BackToTheHome, BackupAllCrews, CrewMember.Die, CrewUIHandler.DisableCrews, CustomizeShipUIHandler.DisableCrews, CrewUIHandler.EnableCrews, CustomizeShipUIHandler.EnableCrews, CrewSystem.GetCrewCount, CrewSystem.GetCrews, EquipmentUIHandler.PopulateCrewIcons, RemoveAllCrews, CrewSystem.RemoveAllCrews, CrewSystem.RemoveCrew, ReplaceShipFromBlueprint, CrewSystem.RestoreCrewAfterBuild, CrewSystem.RevertOriginalCrews, UpdateCrewList.
List<CrewMember> Ship.allEnemies
내 배의 전체 적군 선원 리스트
Referenced by CombatManager.BackToTheHome, CrewMember.Die, CrewSystem.GetCrews, CrewSystem.RemoveAllCrews, CrewSystem.RemoveCrew.
HashSet<EquipmentItem> Ship.unUsedItems
아직 선원에게 적용시키지 않은 장비 목록
Referenced by EquipmentUIHandler.OnClickBuy, EquipmentApplyHandler.OnClickStatApplyButton, EquipmentUIHandler.OnClickStatApplyButton, EquipmentApplyHandler.PopulateEquipmentIcons, EquipmentUIHandler.PopulateEquipmentIcons.
OuterHullData Ship.outerHullData
외갑판 데이터
Referenced by GetOuterHullData, RecalculateAllStats, BlueprintShip.SetBPHullLevel.
GameObject Ship.outerHullPrefab
외갑판 prefab
Referenced by GetOuterHullPrefab.
Transform Ship.outerHulls
Dictionary<ShipStat, float> Ship.currentStats
현재 함선의 스탯 상태를 저장하는 딕셔너리. 예: 산소 생성량, 연료 효율, 쉴드 최대치 등.
Referenced by GetMaxCrew, GetStat, InitializeBaseStats, PrintDebugStatInfo, RecalculateAllStats.
List<RoomBackupData> Ship.backupRoomDatas
백업해 둘 방 정보들
Referenced by BackupCurrentShip, RevertToOriginalShip.
List<WeaponBackupData> Ship.backupWeapons
백업해 둘 함선 무기 정보들
Referenced by BackupCurrentShip, RevertToOriginalShip.
List<BackupCrewData> Ship.backupCrewDatas
백업해 둘 선원 정보들
Referenced by BackupAllCrews, CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, Customize_1_Controller.OnClickSave, ShipValidationHelper.ValidateShipLayout.
List<OuterHull> Ship.outerHullList
Vector2Int Ship.gridSize
함선의 격자 크기 (방 배치 제한 범위).
bool Ship.showDebugInfo
디버그용 스탯 및 상태 정보를 출력할지 여부입니다.
Referenced by CalculateWarpFuelCost, OnRoomStateChanged, RecalculateAllStats.
readonly Dictionary<Vector2Int, Room> Ship.roomGrid
각 격자 좌표에 배치된 룸 정보를 저장하는 그리드 맵.
Referenced by AddRoomToGrid, GetRoomAtPosition, RemoveRoom, ReplaceShipFromBlueprint, TakeAttack.
DoorData Ship.doorData
int Ship.doorLevel
함선의 모든 문에 대한 레벨 (전체 적용)
Referenced by GetDoorLevel.
readonly Dictionary<RoomType, List<Room> > Ship.roomsByType
룸 타입별로 분류된 룸 리스트 딕셔너리. 예: LifeSupport, Engine, Cockpit 등.
Referenced by AddRoom, AddRoom, GetRoomsByType, RemoveRoom, ReplaceShipFromBlueprint.
readonly Dictionary<string, Dictionary<ShipStat, float> > Ship.roomContributions
각 룸이 기여한 스탯 값을 저장하는 디버그용 데이터. 룸 이름을 키로 사용하여 스탯 기여도를 추적합니다.
Referenced by GetRoomContributions, PrintDebugStatInfo, RecalculateAllStats.
Dictionary<Type, ShipSystem> Ship.systems
함선에 등록된 모든 시스템들. 타입을 키로 하여 각 ShipSystem 서브클래스를 관리합니다.
OuterHullSystem Ship.outerHullSystem
WeaponSystem Ship.weaponSystem
OxygenSystem Ship.oxygenSystem
CrewSystem Ship.crewSystem
HitPointSystem Ship.hitpointSystem
MoraleSystem Ship.moraleSystem
PowerSystem Ship.powerSystem
StorageSystem Ship.storageSystem
ShieldSystem Ship.shieldSystem
OuterHullSystem Ship.OuterHullSystem
WeaponSystem Ship.WeaponSystem
OxygenSystem Ship.OxygenSystem
CrewSystem Ship.CrewSystem
HitPointSystem Ship.HitpointSystem
MoraleSystem Ship.MoraleSystem
PowerSystem Ship.PowerSystem
StorageSystem Ship.StorageSystem
ShieldSystem Ship.ShieldSystem
Action Ship.OnStatsChanged
Action Ship.OnRoomChanged
Action<Ship> Ship.shipExplosion
Action Ship.powerCheckNeed
Action Ship.InfoPanelChanged
EnemyInfoPanel 갱신을 위한 이벤트
Referenced by TakeAttack, TakeDamage.
void Ship.Awake()
함선의 초기 상태를 설정합니다. 기본 스탯 설정 및 시스템 초기화를 수행합니다.
void Ship.Start()
게임 시작 시 호출되며, 테스트 룸 배치 및 시스템 초기화를 수행합니다.
void Ship.Update()
게임 시작 시 호출되며, 테스트 룸 배치 및 시스템 초기화를 수행합니다.
References CrewSystem.Update, HitPointSystem.Update, MoraleSystem.Update, OuterHullSystem.Update, OxygenSystem.Update, PowerSystem.Update, ShieldSystem.Update, StorageSystem.Update, WeaponSystem.Update.
void Ship.OnDestroy()
Ship 오브젝트가 파괴될 때 호출됩니다. 모든 룸의 이벤트 구독을 해제하여 메모리 누수나 오류를 방지합니다.
References allRooms, OnRoomStateChanged.
void Ship.AddRoomToGrid(Room room, Vector2Int size)
그리드에 룸을 추가합니다.
References Room< TData, TLevel >.currentRotation, Room< TData, TLevel >.position, roomGrid.
Referenced by AddRoom, AddRoom.
Room Ship.AddRoomComponent(GameObject roomObject, RoomType roomType, RoomData roomData)
룸 타입에 맞는 컴포넌트를 추가합니다.
Referenced by AddRoom.
void Ship.InitializeSystems()
함선에 필요한 시스템들을 초기화하고 등록합니다. 모든 ShipSystem 서브클래스를 수동으로 등록해야 합니다.
References CrewSystem.Initialize, HitPointSystem.Initialize, MoraleSystem.Initialize, OuterHullSystem.Initialize, OxygenSystem.Initialize, PowerSystem.Initialize, ShieldSystem.Initialize, ShipSystem.Initialize, StorageSystem.Initialize.
void Ship.InitializeBaseStats()
함선의 기본 스탯을 초기화합니다. 모든 ShipStat 값을 0으로 설정하여 이후 계산의 기준을 만듭니다.
References currentStats.
Referenced by RecalculateAllStats.
bool Ship.IsAdditiveStatType(ShipStat statType)
주어진 ShipStat이 가산형(덧셈 방식) 스탯인지 여부를 반환합니다. 예: 쉴드 최대량, 산소 생성량 등은 단순 덧셈으로 누적됩니다.
statType 확인할 스탯 타입. 가산형이면 true, 아니면 false.
Referenced by RecalculateAllStats.
bool Ship.IsMultiplicativeStatType(ShipStat statType)
주어진 ShipStat이 배율형(곱셈 방식) 스탯인지 여부를 반환합니다. 예: 회피율 보너스 %, 데미지 증폭 % 등이 해당됩니다. 현재는 정의된 곱셈 스탯이 없습니다.
statType 확인할 스탯 타입. 배율형이면 true, 아니면 false.
Referenced by RecalculateAllStats.
void Ship.PrintDebugStatInfo()
현재 함선의 스탯과 룸별 스탯 기여도를 콘솔에 출력합니다. 디버깅 모드가 활성화된 경우에만 호출되며, 전체 스탯 상태를 확인할 수 있습니다.
References currentStats, roomContributions.
Referenced by RecalculateAllStats.
Room Ship.GetRandomTargettableRoom()
공격 대상으로 선택 가능한 방 중 하나를 무작위로 반환합니다. 피해를 받을 수 있고 체력이 남아 있는 방만 대상이 됩니다.
타겟팅 가능한 방 객체. 없으면 null.
References GetAllRooms, Room< TData, TLevel >.GetHealthPercentage, Room< TData, TLevel >.GetIsDamageable.
void Ship.ApplyDamageToCrewsInRoom(Room room, float damage)
지정된 방에 있는 모든 크루에게 피해를 적용합니다.
room 대상 방. damage 적용할 피해량.
References CrewMember.TakeDamage.
void Ship.ApplyDamageToCrewsAtPosition(Vector2Int position, float damage)
지정된 위치에 있는 크루에게 데미지를 적용합니다.
position 피격된 격자 좌표. damage 적용할 원 피해량.
References CrewSystem.GetCrewsAtPosition, CrewMember.TakeDamage.
Referenced by ApplyDamageToCrewsInArea.
void Ship.ApplyDamageToCrewsInArea(Vector2Int position, float damage, bool isSplash)
해당하는 좌표에 있는 크루에게 데미지를 적용합니다. 만약 스플래쉬 데미지일 경우 중심 좌표를 기준으로 3x3 영역(주위 8칸)에는 80의 데미지를 입힙니다.
position 피격된 격자 좌표. damage 적용할 원 피해량. isSplash 스플래쉬 데미지 여부.
References ApplyDamageToCrewsAtPosition.
Referenced by TakeAttack.
void Ship.Initialize()
void Ship.ReconnectAction()
bool Ship.AddRoom(int level, RoomData roomData, Vector2Int position, Constants.Rotations.Rotation rotation, float hitPoints)
룸을 생성하고 배치하며, 초기화는 Room의 Initialize 메서드를 사용합니다.
References AddRoomComponent, AddRoomToGrid, allRooms, Room< TData, TLevel >.currentHitPoints, RoomData< T >.RoomLevel.damageHitPointRate, Room< TData, TLevel >.GetIsDamageable, RoomData< T >.GetRoomDataByLevel, GetWorldPositionFromGrid, Room< TData, TLevel >.Initialize, Room< TData, TLevel >.NotifyStateChanged, RecalculateAllStats, roomsByType, RoomData< T >.RoomLevel.size, Room< TData, TLevel >.UpdateRoomVisual.
Referenced by ShipFactory.CreateShipFromTemplate, ReplaceShipFromBlueprint, RevertToOriginalShip, TradeUIController.Start.
Room Ship.AddRoom(Room room, Vector2Int position=new(), Constants.Rotations.Rotation rotation=Constants.Rotations.Rotation.Rotation0)
룸 생성 및 그리드 배치
room position rotation
References AddRoomToGrid, allRooms, Room< TData, TLevel >.currentRotation, Room< TData, TLevel >.GetCurrentLevel, RoomData< T >.GetRoomDataByLevel, GetWorldPositionFromGrid, OnRoomStateChanged, Room< TData, TLevel >.position, RecalculateAllStats, roomsByType, RoomData< T >.RoomLevel.size, Room< TData, TLevel >.UpdateRoomVisual.
Room Ship.GetRoomAtPosition(Vector2Int position)
지정된 그리드 위치에 있는 룸을 반환합니다.
References roomGrid.
Referenced by CrewMember.FollowPathCoroutine.
bool Ship.RemoveRoom(Room room)
지정한 룸을 함선에서 제거합니다.
room 제거할 룸 객체. 제거 성공 여부.
References allRooms, Room< TData, TLevel >.GetSize, OnRoomStateChanged, RecalculateAllStats, roomGrid, roomsByType, Room< TData, TLevel >.roomType.
void Ship.RemoveAllRooms()
int Ship.GetTotalShipValue()
현재 함선에 포함된 모든 방의 가격 합을 반환
모든 방 가격의 합
References allRooms, allWeapons, RoomData< T >.RoomLevel.cost, ShipWeaponData.cost, Room< TData, TLevel >.GetCurrentLevel, RoomData< T >.GetRoomDataByLevel, ShipWeapon.weaponData.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, Customize_2_Controller.OnEnable, CustomizeShipUIHandler.Update.
bool Ship.IsFullHitPoint()
현재 함선의 모든 방에 대해 내구도 100인지 여부 반환
내구도 100% 여부
References allRooms, Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.GetMaxHitPoints.
Referenced by Customize_2_Controller.OnEnable, CustomizeShipUIHandler.Update.
void Ship.BackupAllCrews()
설계도 작업 전, 기존 선원 백업
References allCrews, backupCrewDatas, CrewBase.crewName, CrewBase.currentRoom, CrewBase.needsOxygen, CrewBase.position, Room< TData, TLevel >.position, CrewBase.race.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, Customize_1_Controller.OnClickSave.
void Ship.BackupCurrentShip()
설계도 교체 작업 전, 기존 함선 백업
References allRooms, backupRoomDatas, backupWeapons, Room< TData, TLevel >.currentHitPoints, Room< TData, TLevel >.currentRotation, GetAllWeapons, ShipWeapon.GetAttachedDirection, Room< TData, TLevel >.GetCurrentLevel, ShipWeapon.GetGridPosition, Room< TData, TLevel >.position, ShipWeapon.weaponData.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_1_Controller.OnClickSave.
void Ship.RevertToOriginalShip()
유효성 검사 실패, 기존 함선으로 복구
References AddRoom, allRooms, allWeapons, backupRoomDatas, backupWeapons.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_1_Controller.OnClickSave.
void Ship.ReplaceShipFromBlueprint(BlueprintShip bpShip)
현재 설계도 함선을 실제 함선 구조로 반영 - bpship 버전 (방뿐 아니라 무기도 함께 적용)
bpShip 설계도 함선
References AddRoom, allCrews, allRooms, allWeapons, ShipWeapon.ApplyRotationSprite, BlueprintWeapon.bpAttachedDirection, BlueprintRoom.bpLevelIndex, BlueprintRoom.bpPosition, BlueprintWeapon.bpPosition, BlueprintRoom.bpRoomData, BlueprintRoom.bpRotation, BlueprintWeapon.bpWeaponData, GetOuterHullLevel, RoomData< T >.GetRoomDataByLevel, RoomData< T >.RoomLevel.hitPoint, ShipWeaponData.id, roomGrid, roomsByType, SetOuterHullLevel.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, Customize_1_Controller.OnClickSave, ShipTemplateSaver.SaveShipTemplate.
void Ship.SetShipContentsActive(bool isActive)
함선 내 모든 오브젝트 활성화 / 비활성화
isActive
References GetAllRooms, GetAllWeapons.
Referenced by Customize_2_Controller.OnClickBuy, Customize_1_Controller.OnClickSave, Customize_1_Controller.OnDisable, Customize_0_Controller.OnEnable, Customize_1_Controller.OnEnable, Customize_2_Controller.OnEnable, Customize_1_Controller.ReloadBlueprintFromSlot, Customize_0_Controller.Start.
T Ship.GetRoomOfType< T >()
특정 타입의 방(Room)을 검색하여 반환합니다. 해당 타입의 첫 번째 방만 반환되며, 없으면 null입니다.
T 찾고자 하는 Room 타입. 해당 타입의 Room 또는 null.
References allRooms.
List< Room > Ship.GetRoomsByType(RoomType type)
특정 룸 타입(RoomType)에 해당하는 모든 방을 반환합니다.
type 조회할 룸 타입. 해당 타입의 방 리스트.
References roomsByType.
Referenced by CanWarp.
void Ship.RecalculateAllStats()
현재 함선의 모든 스탯을 다시 계산합니다. 방, 시스템, 선원의 기여도를 반영합니다.
References allRooms, MoraleSystem.CalculateGlobalMorale, currentStats, OuterHullData.OuterHullLevel.damageReduction, CrewSystem.GetCrews, OuterHullData.GetOuterHullData, GetOuterHullLevel, CrewBase.GetStatContributions, Room< TData, TLevel >.GetStatContributions, InitializeBaseStats, IsAdditiveStatType, IsMultiplicativeStatType, outerHullData, PrintDebugStatInfo, roomContributions, MoraleManager.SetAllCrewMorale, showDebugInfo.
Referenced by CrewSystem.AddCrew, AddRoom, AddRoom, CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, OnRoomStateChanged, RemoveRoom, PowerSystem.RequestPowerForRoom, CrewMember.WalkOut.
void Ship.RefreshAllSystems()
void Ship.ActionReconnect()
float Ship.GetStat(ShipStat statType)
특정 스탯 값을 반환합니다.
statType 조회할 스탯. 스탯 값. 없으면 0.
References currentStats.
Referenced by CalculateWarpFuelCost, ShipSystem.GetShipStat, EmployController.OnClickCrewCard, OuterHullSystem.ReduceDamage.
Dictionary< ShipStat, float > Ship.GetRoomContributions(string roomName)
지정한 룸이 기여한 스탯 정보를 반환합니다. 주로 디버깅 또는 UI 용도로 사용됩니다.
roomName 조회할 룸의 이름. 해당 룸이 기여한 ShipStat 딕셔너리. 존재하지 않으면 빈 딕셔너리를 반환합니다.
References roomContributions.
void Ship.OnRoomStateChanged(Room room)
룸의 상태가 변경되었을 때 호출되는 콜백 함수입니다. 디버그 로그를 출력하고 전체 스탯을 다시 계산합니다.
room 상태가 변경된 룸 객체.
References RecalculateAllStats, showDebugInfo.
Referenced by AddRoom, OnDestroy, RemoveRoom.
bool Ship.IsPowerCheckNeedConnected()
void Ship.OnShipDestroyed()
함선이 파괴되었을 때 호출되는 함수입니다. 게임 오버 로직 등을 처리할 수 있습니다.
Referenced by TakeDamage.
bool Ship.CanWarp()
워프가 가능한지 여부를 반환합니다.
워프가 가능한지 여부
References CalculateWarpFuelCost, GetRoomsByType.
float Ship.CalculateWarpFuelCost()
워프 시 필요한 연료 소모량을 계산합니다.
연료 비용.
References GetStat, showDebugInfo.
Referenced by CanWarp.
int Ship.GetCrewCount()
현재 탑승 중인 크루 수를 반환합니다.
References CrewSystem.GetCrewCount.
Referenced by MoraleSystem.CalculateGlobalMorale, EnemyShipFactory.GeneratePirateCrew, CrewUIHandler.OnCreateButtonClicked, UITopLayersCanvasHandler.Update.
int Ship.GetMaxCrew()
최대 크루 수(수용 가능 인원)를 반환합니다.
References currentStats.
Referenced by CrewUIHandler.OnCreateButtonClicked, UITopLayersCanvasHandler.Update.
List< CrewMember > Ship.GetAllCrew()
현재 함선에 탑승 중인 모든 크루를 반환합니다.
CrewMember 객체들의 리스트.
References CrewSystem.GetCrews.
Referenced by EventCrewEffectHandler.ApplyEffects, EventManager.GetAvailableCrewRaces, EquipmentManager.PurchaseAndEquipGlobal, EventTestTrigger.SelectTestEvent, OxygenSystem.Update, UpdateCrewList, EnemyController.WhereToGo.
void Ship.UpdateCrewList()
유저의 선원 리스트 업데이트
References allCrews, GetAllCrew.
Referenced by RemoveAllCrews.
bool Ship.AddCrew(CrewBase newCrew)
새로운 승무원을 함선에 추가합니다.
newCrew 함선에 추가할 승무원 정보. 이름, 종족, 속성 등을 포함합니다. 승무원이 성공적으로 추가되었으면 True, 그렇지 않으면 False를 반환합니다.
References CrewSystem.AddCrew.
Referenced by ShipFactory.CreateShipFromTemplate, EnemyShipFactory.GeneratePirateCrew, EmployController.OnClickBuy, CrewUIHandler.OnSubmitButtonClicked.
void Ship.RemoveCrew(CrewMember crew)
선원 제거
crew
References CrewSystem.RemoveCrew.
void Ship.RemoveAllCrews()
모든 선원 제거
References allCrews, UpdateCrewList.
Referenced by EnemyShipFactory.GeneratePirateCrew, Customize_0_Controller.OnClickExit.
List< Room > Ship.GetAllRooms()
모든 룸 정보를 반환합니다.
References allRooms.
Referenced by CrewSystem.AddCrew, MoraleSystem.CalculateGlobalMorale, ShipValidationHelper.CheckWeaponConnectivity, CameraZoomController.GetCameraStartPositionToOriginShip, GridPlacer.GetCameraStartPositionToOriginShip, GetRandomRoom, GetRandomTargettableRoom, RTSSelectionManager.RefreshMovementData, CrewSystem.RestoreCrewAfterBuild, CrewSystem.RevertOriginalCrews, TradeUIController.SellItem, CustomizeShipUIHandler.SetPlayerShipCollidersActive, SetShipContentsActive, CrewMember.TeleportAfterDelay, EnemyController.Update, OuterHullSystem.UpdateVisuals, ShipValidationHelper.ValidateShipLayout, ShipValidationHelper.ValidateWeaponAttachmentDirection, ShipValidationHelper.ValidateWeaponPlacement, CrewMember.WalkOut, EnemyController.WhereToGo, EnemyController.WhereToGo.
Room Ship.GetRandomRoom()
랜덤한 방 반환
References GetAllRooms.
void Ship.AllFreeze()
List< ShipWeapon > Ship.GetAllWeapons()
현재 탑재 중인 모든 무기를 반환합니다.
References allWeapons.
Referenced by BackupCurrentShip, ShipValidationHelper.CheckWeaponConnectivity, CameraZoomController.GetCameraStartPositionToOriginShip, GridPlacer.GetCameraStartPositionToOriginShip, OuterHullSystem.SetOuterHullLevel, SetShipContentsActive, ShipValidationHelper.ValidateWeaponAttachmentDirection, ShipValidationHelper.ValidateWeaponPlacement.
void Ship.RemoveAllWeapons()
float Ship.GetActualDamage(float damage)
무기 시스템 수정자를 적용한 후의 실제 피해량을 계산합니다.
damage 수정 전 원래 피해 값. 무기 특유 효과를 고려한 수정된 피해 값.
References WeaponSystem.GetActualDamage.
Referenced by ShipWeapon.Fire, OuterShipCombatController.WeaponFire.
int Ship.GetWeaponCount()
void Ship.RemoveWeapon(ShipWeapon shipWeapon)
ShipWeapon Ship.AddWeapon(int weaponId, Vector2Int gridPosition, ShipWeaponAttachedDirection attachDirection=ShipWeaponAttachedDirection.East)
ShipWeapon Ship.AddWeapon(ShipWeapon shipWeapon)
float Ship.GetCurrentHitPoints()
현재 함선의 내구도(Hit Point)를 반환합니다.
현재 남아 있는 함선의 체력 값.
References HitPointSystem.GetHitPoint.
Referenced by EnemyInfoPanel.UpdateInfoPanel.
Vector2Int Ship.GetRandomTargetPosition()
무작위로 타겟팅 가능한 방의 위치를 반환합니다. 방이 없는 경우 (모두 파괴되었거나 타겟 불가) Vector2Int.zero를 반환합니다.
타겟팅 가능한 방의 격자 좌표.
References allRooms, Room< TData, TLevel >.GetOccupiedTiles.
Referenced by ShipWeapon.Fire, OuterShipCombatController.WeaponFire.
void Ship.TakeAttack(float damage, ShipWeaponType shipWeaponType, Vector2Int hitPosition)
무기 및 외부 방어 시스템을 포함한 실제 피해 계산 및 적용을 수행합니다.
damage 입력된 피해량. shipWeaponType 공격한 무기 타입. hitPosition 피격된 좌표.
References ApplyDamageToCrewsInArea, InfoPanelChanged, ShieldSystem.IsShieldActive, OuterHullSystem.ReduceDamage, roomGrid, TakeDamage, ShieldSystem.TakeDamage.
Referenced by ShipWeapon.OnProjectileHit.
void Ship.TakeDamage(float damage)
함선에 직접 피해를 적용합니다. 체력을 감소시키고, 파괴되었는지 확인합니다.
damage 적용할 피해량.
References HitPointSystem.ChangeHitPoint, HitPointSystem.GetHitPoint, InfoPanelChanged, OnShipDestroyed.
Referenced by CrewMember.Attack, TakeAttack.
void Ship.RepairDamage(float repair)
float Ship.GetOxygenRate()
현재 산소량을 반환합니다.
현재 산소량.
References OxygenSystem.GetOxygenRate.
OxygenLevel Ship.GetOxygenLevel()
현재 산소 레벨을 반환합니다.
현재 산소 레벨.
References OxygenSystem.GetOxygenLevel.
Referenced by CrewBase.ApplyOxygenDamage.
DoorData Ship.GetDoorData()
문 데이터를 반환합니다.
문과 관련된 정보 및 구성 데이터를 포함하는 DoorData 객체를 반환합니다.
int Ship.GetDoorLevel()
현재 함선의 문 레벨을 반환합니다.
현재 문 레벨 값.
References doorLevel.
DoorData.DoorLevel Ship.GetCurrentDoorData()
Vector2Int Ship.WorldToGridPosition(Vector2 worldPos)
월드 좌표를 그리드 좌표로 변환합니다.
Vector3 Ship.GridToWorldPosition(Vector2Int gridPos)
그리드 좌표를 월드 좌표로 변환 ((0, 0) ~ (60, 60) 그리드 내 좌표라 local relative 좌표임)
gridPos
Referenced by GetWorldPositionFromGrid, GetWorldPositionFromGrid.
Vector3 Ship.GridToWorldPosition(Vector2 gridPos)
그리드 좌표를 월드 좌표로 변환 ((0, 0) ~ (60, 60) 그리드 내 좌표라 local relative 좌표임)
gridPos
Vector3 Ship.GetWorldPositionFromGrid(Vector2Int gridPos)
실제 월드 위치 반환
gridPos
References GridToWorldPosition.
Referenced by CrewSystem.AddCrew, AddRoom, AddRoom, WeaponSystem.AddWeapon, EnemyShipFactory.CreateDefaultShip, OuterHullSystem.CreateOuterHull, BlueprintShip.CreateOuterHull, ShipWeapon.Fire, CrewMember.FollowPathCoroutine, CameraZoomController.GetCameraStartPositionToOriginShip, CrewSystem.RestoreCrewAfterBuild, CrewSystem.RevertOriginalCrews, Room< TData, TLevel >.UpdateRoomVisual, OuterShipCombatController.WeaponFire.
Vector3 Ship.GetWorldPositionFromGrid(Vector2 gridPos)
실제 월드 위치 반환
gridPos
References GridToWorldPosition.
Vector2Int Ship.GetGridSize()
List< TradingItem > Ship.GetAllItems()
void Ship.RemoveAllItems()
void Ship.RemoveItem(TradingItem item)
OuterHullData Ship.GetOuterHullData()
외갑판 데이터를 반환합니다.
외갑판 데이터
References outerHullData.
Referenced by OuterHullSystem.UpdateVisuals.
GameObject Ship.GetOuterHullPrefab()
외갑판 프리팹을 반환합니다.
외갑판 프리팹
References outerHullPrefab.
Referenced by OuterHullSystem.UpdateVisuals.
int Ship.GetOuterHullLevel()
현재 함선의 외갑판 레벨을 반환합니다.
현재 외갑판 레벨 (0-2)
References OuterHullSystem.GetOuterHullLevel.
Referenced by WeaponSystem.AddWeapon, RecalculateAllStats, ReplaceShipFromBlueprint.
void Ship.SetOuterHullLevel(int level)
함선의 외갑판 레벨을 설정합니다.
level 설정할 외갑판 레벨 (0-2)
References OuterHullSystem.SetOuterHullLevel.
Referenced by Customize_2_Controller.OnClickBuy, ReplaceShipFromBlueprint.
void Ship.UpdateOuterHullVisuals()
외갑판 시각 효과를 업데이트합니다.
References OuterHullSystem.GetOuterHullLevel, OuterHullSystem.UpdateVisuals.
Referenced by Customize_2_Controller.OnClickBuy, Customize_1_Controller.OnDisable, CustomizeShipUIHandler.OnDisable, ShipTemplateSaver.SaveShipTemplate.
void Ship.ClearExistingHulls()
기존 외갑판 객체들을 모두 제거합니다.
References OuterHullSystem.ClearExistingHulls.
Referenced by Customize_1_Controller.OnEnable, CustomizeShipUIHandler.OnEnable.
void Ship.MoveShipToFacingTargetShip(Ship targetShip)
이 함선을 targetShip과 마주보도록 설정하면서 x축으로 offset만큼 띄운 위치로 이동시킴. 회전은 180도, y 중심 정렬 유지.
targetShip 대상 유저 함선 xOffset x축 거리 (보통 80)
References allRooms, Room< TData, TLevel >.position.
Referenced by EnemyShipFactory.SpawnPirateShip.
void Ship.BackToTheDefaultShip()