ShipWeapon
float ShipWeapon.currentCooldown
현재 쿨타임.
Referenced by GetCooldownPercentage, IsReady, ResetCooldown, ResetCooldown, UpdateCooldown.
ShipWeaponData ShipWeapon.weaponData
이 무기에 해당하는 무기 데이터입니다.
Referenced by ApplyRotationSprite, Ship.BackupCurrentShip, Fire, GetDamage, Ship.GetTotalShipValue, GetWeaponName, GetWeaponType.
Vector2Int ShipWeapon.gridSize
Transform ShipWeapon.firePoint
무기의 발사 지점 Transform입니다.
Referenced by GetFirePosition.
Vector2Int ShipWeapon.gridPosition
무기의 그리드 상 좌표입니다.
Referenced by GetGridPosition, SetGridPosition.
ShipWeaponAttachedDirection ShipWeapon.attachedDirection
무기가 시설과 연결되어있는 방향(회전 상태)입니다. 회전 상태는 East → South → North → East 순으로 순환합니다.
Referenced by GetAttachedDirection, GetDirectionIndex, RotateWeapon, SetAttachedDirection.
SpriteRenderer ShipWeapon.spriteRenderer
SpriteRenderer 컴포넌트 참조 (회전 시 스프라이트 갱신용)
Referenced by ApplyRotationSprite.
int ShipWeapon.hits
적중 횟수 (통계용)
Referenced by AddHit, GetHits, SetHits.
float ShipWeapon.totalDamageDealt
입힌 총 피해량 (통계용)
Referenced by AddDamageDealt, GetTotalDamageDealt, SetTotalDamageDealt.
bool ShipWeapon.isEnabled
무기 활성화 상태
Referenced by IsEnabled, SetEnabled, TryAutoFire, TryFire.
Ship ShipWeapon.ownerShip
이 무기를 소유한 함선
Referenced by Fire, GetTargetShip, TryAutoFire.
Action ShipWeapon.updateWeaponPanel
void ShipWeapon.Awake()
void ShipWeapon.Start()
int ShipWeapon.GetDirectionIndex()
현재 부착 방향에 따른 인덱스 반환 (0: North, 1: East, 2: South)
References attachedDirection.
Referenced by ApplyRotationSprite.
void ShipWeapon.TryAutoFire()
쿨다운 완료 시 자동 발사 시도
References GetTargetShip, isEnabled, ownerShip, TryFire.
bool ShipWeapon.Fire(Ship targetShip)
무기 발사 실행
targetShip 목표 함선 발사 성공 여부
References ProjectileManager.FireProjectile, Ship.GetActualDamage, GetDamage, GetFirePosition, Ship.GetRandomTargetPosition, Ship.GetWorldPositionFromGrid, OnProjectileHit, ownerShip, ResetCooldown, weaponData.
Referenced by TryFire.
void ShipWeapon.OnProjectileHit(Ship target, Vector2Int hitPosition, float damage)
투사체가 목표에 도달했을 때 호출
References AddDamageDealt, AddHit, GetWeaponType, Ship.TakeAttack.
Referenced by Fire.
Ship ShipWeapon.GetTargetShip()
타겟 함선 결정
References GameManager.GetCurrentEnemyShip, GameManager.GetPlayerShip, GameManager.Instance, ownerShip.
Referenced by TryAutoFire, TryFire.
void ShipWeapon.Initialize()
무기 초기화 (무기 생성 후 필요한 추가 설정)
Referenced by ShipWeaponFactory.CreateWeaponInstance.
void ShipWeapon.SetAttachedDirection(ShipWeaponAttachedDirection newDirection)
무기 방향 변경 시 스프라이트 업데이트
newDirection 새 방향
References attachedDirection.
Referenced by WeaponSystem.AddWeapon.
bool ShipWeapon.IsEnabled()
무기 활성화 상태 반환
References isEnabled.
Referenced by WeaponSystem.IsEveryWeaponReady.
void ShipWeapon.SetEnabled(bool enabled)
무기 활성화/비활성화
References isEnabled.
int ShipWeapon.GetHits()
적중 횟수 반환
References hits.
void ShipWeapon.SetHits(int value)
적중 횟수 설정
References hits.
Referenced by WeaponSystem.ResetAllWeaponStats.
void ShipWeapon.AddHit()
적중 추가 (적 타격 시 호출)
References hits.
Referenced by OnProjectileHit.
float ShipWeapon.GetTotalDamageDealt()
입힌 총 피해량 반환
References totalDamageDealt.
void ShipWeapon.SetTotalDamageDealt(float value)
입힌 총 피해량 설정
References totalDamageDealt.
Referenced by WeaponSystem.ResetAllWeaponStats.
void ShipWeapon.AddDamageDealt(float damage)
피해량 추가 (적 타격 시 호출)
References totalDamageDealt.
Referenced by OnProjectileHit.
void ShipWeapon.UpdateCooldown(float deltaTime)
매 프레임 호출되어 쿨다운 시간을 감소시킵니다.
deltaTime 경과 시간 (초).
References currentCooldown.
void ShipWeapon.UpdateCooldownWithBonus(float deltaTime, float reloadBonus)
bool ShipWeapon.IsReady()
무기가 발사 가능한 상태인지 확인합니다.
쿨다운이 완료되었으면 true.
References currentCooldown.
Referenced by WeaponSystem.IsEveryWeaponReady, WeaponFrameFunction.SetFireButton, TryFire, WeaponSystem.Update, OuterShipCombatController.WeaponFire.
void ShipWeapon.ResetCooldown()
무기의 쿨다운을 기본값으로 초기화합니다.
References currentCooldown.
Referenced by Fire.
void ShipWeapon.ResetCooldown(float cooldown)
무기의 쿨다운을 지정한 값으로 설정합니다.
cooldown 설정할 쿨다운 시간.
References currentCooldown.
string ShipWeapon.GetWeaponName()
무기 이름을 반환합니다.
무기 이름 문자열.
References ShipWeaponData.GetWeaponName, weaponData.
float ShipWeapon.GetDamage()
무기의 피해량을 반환합니다.
피해량 값.
References ShipWeaponData.GetDamage, weaponData.
Referenced by Fire, OuterShipCombatController.WeaponFire.
float ShipWeapon.GetCooldownPerSecond()
ShipWeaponType ShipWeapon.GetWeaponType()
무기의 타입을 반환합니다.
무기 타입 enum 값.
References ShipWeaponData.GetWeaponType, weaponData.
Referenced by WeaponSystem.FireWeaponsByType, OnProjectileHit, TryFire.
Transform ShipWeapon.GetFirePosition()
무기 투사체의 발사 위치를 반환합니다.
무기 투사체 발사 위치 Transform.
References firePoint.
Referenced by Fire.
Vector2Int ShipWeapon.GetGridPosition()
무기의 그리드 상 위치를 반환합니다.
그리드 상의 좌표.
References gridPosition.
Referenced by Ship.BackupCurrentShip, ShipValidationHelper.CheckWeaponConnectivity, CameraZoomController.GetCameraStartPositionToOriginShip, ShipValidationHelper.ValidateWeaponAttachmentDirection, ShipValidationHelper.ValidateWeaponPlacement.
void ShipWeapon.SetGridPosition(Vector2Int position)
무기의 그리드 상 위치를 설정합니다.
position 설정할 그리드 위치.
References gridPosition.
Referenced by WeaponSystem.AddWeapon.
ShipWeaponAttachedDirection ShipWeapon.GetAttachedDirection()
무기가 시설과 연결된 방향(회전 상태)을 반환합니다.
무기가 연결된 방향.
References attachedDirection.
Referenced by Ship.BackupCurrentShip, ShipValidationHelper.ValidateWeaponAttachmentDirection.
bool ShipWeapon.TryFire()
무기 발사 시도
발사 성공 여부
References Fire, GetTargetShip, GetWeaponType, isEnabled, IsReady.
Referenced by WeaponSystem.FireAllReadyWeapons, WeaponSystem.FireWeapon, WeaponSystem.FireWeaponsByType, TryAutoFire, WeaponSystem.Update, WeaponFrameFunction.UpdateWeaponPanel.
void ShipWeapon.RotateWeapon()
우클릭 시 호출되어 무기의 회전(힌지 회전) 상태를 변경합니다. 회전 상태는 East → South → North → East 순으로 순환합니다.
References ApplyRotationSprite, attachedDirection.
void ShipWeapon.ApplyRotationSprite(int hullLevel=0)
현재 attachedDirection에 맞는 스프라이트를 SpriteRenderer에 적용합니다. 인덱스 매핑: 0 - Up (North), 1 - Right (East), 2 - Down (South)
hullLevel 함선의 외갑판 레벨 (0: 레벨 1, 1: 레벨 2, 2: 레벨 3)
References ShipWeaponData.flattenedSprites, GetDirectionIndex, spriteRenderer, weaponData, ShipWeaponData.weaponIcon.
Referenced by WeaponSystem.AddWeapon, Ship.ReplaceShipFromBlueprint, RotateWeapon, OuterHullSystem.SetOuterHullLevel.
void ShipWeapon.CopyFrom(ShipWeapon other)
void ShipWeapon.DisconnectAction()
float ShipWeapon.GetCooldownPercentage()
현재 무기가 충전된 정도를 백분율로 반환 (0~1)
References currentCooldown.
Referenced by WeaponFrameFunction.UpdateWeaponPanel.