OuterHull
OuterHullData OuterHull.outerHullData
외갑판 데이터 (레벨별 스탯 포함).
Referenced by Initialize, Initialize, SetLevel, SetOuterHullData, UpdateSpriteByLevelAndDirection, Upgrade.
int OuterHull.currentLevel
현재 외갑판의 레벨입니다.
Referenced by GetCurrentLevel, Initialize, Initialize, SetLevel, SetOuterHullData, Upgrade.
OuterHullData.OuterHullLevel OuterHull.currentLevelData
현재 레벨에 해당하는 외갑판 상세 데이터입니다.
Referenced by GetStatContributions, Initialize, Initialize, SetLevel, SetOuterHullData, Upgrade.
SpriteRenderer OuterHull.spriteRenderer
스프라이트 렌더러 컴포넌트
Referenced by Awake, UpdateSprite.
Ship OuterHull.parentShip
a소속된 함선 참조
Referenced by Initialize.
Vector2Int OuterHull.gridPosition
외갑판의 그리드 위치
Referenced by Initialize.
int OuterHull.direction
외갑판 타일의 방향 (0-3: 하좌상우, 4-7: 하좌/상좌/상우/하우 모서리, 8-11: 내부 모서리)
Referenced by Initialize, SetLevel, Upgrade.
void OuterHull.Awake()
컴포넌트가 활성화될 때 외갑판을 초기화합니다.
References Initialize, spriteRenderer.
void OuterHull.Initialize()
외갑판 레벨 데이터를 초기화합니다.
References currentLevel, currentLevelData, OuterHullData.GetOuterHullData, outerHullData.
Referenced by Awake, OuterHullSystem.CreateOuterHull.
void OuterHull.Initialize(Vector2Int position, int level, int dir, Sprite sprite, Ship ship)
외갑판 타일 초기화
position 그리드 위치 level 외갑판 레벨 dir 방향 (0-3: 하좌상우, 4-7: 모서리, 8-11: 내부 모서리) sprite 사용할 스프라이트 ship 소속 함선
References currentLevel, currentLevelData, direction, OuterHullData.GetOuterHullData, gridPosition, outerHullData, parentShip, UpdateSprite.
void OuterHull.SetOuterHullData(OuterHullData data)
외갑판 데이터를 설정합니다.
data 외갑판 데이터
References currentLevel, currentLevelData, OuterHullData.GetOuterHullData, outerHullData.
Referenced by OuterHullSystem.CreateOuterHull.
void OuterHull.UpdateSprite(Sprite sprite)
외갑판 스프라이트 업데이트
sprite 새 스프라이트
References spriteRenderer.
Referenced by Initialize, SetLevel, UpdateSpriteByLevelAndDirection, Upgrade.
void OuterHull.UpdateSpriteByLevelAndDirection(int level, int directionIndex)
외갑판 레벨과 방향에 따른 스프라이트 업데이트
level 레벨 (0-2) directionIndex 방향 인덱스 (0-3: 하좌상우, 4-7: 모서리, 8-11: 내부 모서리)
References OuterHullData.GetSpecificHullSprite, outerHullData, UpdateSprite.
Dictionary< ShipStat, float > OuterHull.GetStatContributions()
외갑판이 함선에 기여하는 스탯을 반환합니다. 현재는 피해 감소(DamageReduction) 스탯만 제공됩니다.
스탯 종류와 수치가 담긴 딕셔너리.
References currentLevelData.
bool OuterHull.Upgrade()
외갑판을 한 단계 업그레이드합니다. 다음 레벨의 데이터가 존재하면 업그레이드에 성공합니다.
업그레이드 성공 시 true, 실패 시 false.
References currentLevel, currentLevelData, direction, OuterHullData.GetOuterHullData, OuterHullData.GetSpecificHullSprite, outerHullData, UpdateSprite.
int OuterHull.GetCurrentLevel()
현재 외갑판의 레벨을 반환합니다.
현재 레벨 값.
References currentLevel.
void OuterHull.SetLevel(int level)
외갑판 레벨 설정
level 새 레벨
References currentLevel, currentLevelData, direction, OuterHullData.GetOuterHullData, OuterHullData.GetSpecificHullSprite, outerHullData, UpdateSprite.
Referenced by OuterHullSystem.SetOuterHullLevel.