StorageHighlightManager
TradingItemHighlighter [] StorageHighlightManager.allHighlighters
void StorageHighlightManager.Awake()
Awake 시점에 한 번만 씬에서 TradingItemHighlighter를 찾아 캐싱합니다.
void StorageHighlightManager.HighlightItem(string itemName)
전달된 itemName과 일치하는 TradingItem만 강조(on)하고, 나머지는 강조를 해제(off)합니다.
itemName 하이라이트할 아이템 이름
Referenced by InventoryItemUI.OnPointerClick, TradeUIManager.OnSellItemSelected.
void StorageHighlightManager.ClearHighlights()
모든 TradingItem의 강조를 해제합니다.
Referenced by TradeUIManager.OnBackPressed.