MenuUIManager
RectTransform MenuUIManager.mainUI
Button MenuUIManager.menuButton
float MenuUIManager.slideSpeed
bool MenuUIManager.isMenuOpen
Vector2 MenuUIManager.hiddenPosition
Vector2 MenuUIManager.visiblePosition
Coroutine MenuUIManager.slideCoroutine
MenuUIManager MenuUIManager.Instance
void MenuUIManager.Start()
메뉴 UI의 초기 설정을 하고, 메뉴 버튼에 클릭 이벤트를 추가합니다.
References ToggleMenu.
IEnumerator MenuUIManager.SlideMenu(Vector2 targetPosition)
Menu UI 클릭 시 UI가 애니메이션 형태로 우에서 좌로 Slide되어 나타납니다.
targetPosition
Referenced by ForceCloseMenu, ToggleMenu.
void MenuUIManager.ForceCloseMenu()
열려있는 Menu UI를 강제로 닫습니다.
References SlideMenu.
Referenced by CrewUIHandler.ShowUI.
void MenuUIManager.ToggleMenu()
Menu UI를 토글형식으로 열었다가 닫을 수 있습니다.
References SlideMenu.
Referenced by Start.