Customize_0_Controller
Ship Customize_0_Controller.playerShip
BlueprintShip Customize_0_Controller.bpShip
GameObject Customize_0_Controller.customize0Panel
GameObject Customize_0_Controller.customize1Panel
GameObject Customize_0_Controller.customize2Panel
Button Customize_0_Controller.exitButton
Button Customize_0_Controller.editButton
Button Customize_0_Controller.slot1Button
Button Customize_0_Controller.slot2Button
Button Customize_0_Controller.slot3Button
Button Customize_0_Controller.slot4Button
List<Image> Customize_0_Controller.appliedTags
Button Customize_0_Controller.applyButton
BPPreviewArea Customize_0_Controller.bpPreviewArea
List<Button> Customize_0_Controller.slotButtons
void Customize_0_Controller.Start()
button 클릭 함수 연결
References BlueprintSlotManager.Instance, GameManager.Instance, OnClickApply, OnClickEdit, OnClickExit, OnClickSlot, GameManager.playerShip, Ship.SetShipContentsActive.
void Customize_0_Controller.OnEnable()
적용 중인 도안 표시
References BlueprintSlotManager.appliedSlotIndex, BlueprintSlotManager.Instance, GameManager.Instance, GameManager.playerShip, Ship.SetShipContentsActive.
IEnumerator Customize_0_Controller.DelayedLoadShipAndScene()
void Customize_0_Controller.CheckApplyAvailable()
실제 함선으로 교체 버튼 활성화 체크
References BlueprintSlotManager.Instance, BlueprintSlotManager.isValidBP.
Referenced by OnClickSlot.
void Customize_0_Controller.OnClickExit()
Planet scene으로 전환
References BlueprintSlotManager.Instance, Ship.RemoveAllCrews.
Referenced by Start.
void Customize_0_Controller.OnClickApply()
함선 교체 버튼 (도안 실제 적용시키겠다)
Referenced by Start.
void Customize_0_Controller.OnClickEdit()
도안 편집
References BlueprintSlotManager.Instance, Customize_1_Controller.ReloadBlueprintFromSlot.
Referenced by Start.
void Customize_0_Controller.UpdateSlotButtonColor(int index, bool isValid)
도안 유효성에 따른 slot button 갱신
index isValid
References BlueprintSlotManager.GetBlueprintAt, BlueprintSlotManager.Instance.
Referenced by BlueprintSlotManager.InitializeSlotButtonColor, Customize_1_Controller.OnClickSave.
void Customize_0_Controller.OnClickSlot(int slotIndex)
슬롯 버튼 클릭
slotIndex
References CheckApplyAvailable, BPPreviewArea.Clear, BlueprintShip.ClearRooms, BlueprintSlotManager.GetBlueprintAt, BlueprintSlotManager.Instance, Customize_2_Controller.MakeBPShipWithSaveData, Customize_2_Controller.previewOuterHullPrefab, BlueprintShip.SetBPHullLevel, BPPreviewArea.UpdateAndShow.
Referenced by Customize_1_Controller.OnClickBack, Customize_2_Controller.OnClickBuy, Start.