ShipStatSettings
List<StatLimit> ShipStatSettings.StatLimits
해당 스탯에 대한 설명 또는 메모.
Referenced by InitializeCache, InitializeDefaultValues, OnEnable.
float ShipStatSettings.defaultMaxValue
설정되지 않은 스탯에 대한 기본 최대값.
Referenced by GetMaxValue.
float ShipStatSettings.defaultMinValue
설정되지 않은 스탯에 대한 기본 최소값.
Referenced by GetMinValue.
Dictionary<ShipStat, StatLimit> ShipStatSettings._limitsCache
빠른 조회를 위한 내부 캐시 딕셔너리.
Referenced by GetMaxValue, GetMinValue, HasMinLimit, InitializeCache.
void ShipStatSettings.OnEnable()
ScriptableObject가 활성화될 때 자동으로 호출됩니다. 기본값과 캐시 초기화를 수행합니다.
References InitializeCache, InitializeDefaultValues, StatLimits.
void ShipStatSettings.InitializeCache()
내부 캐시를 초기화합니다.
References _limitsCache, ShipStatSettings.StatLimit.Stat, StatLimits.
Referenced by GetMaxValue, GetMinValue, HasMinLimit, OnEnable.
void ShipStatSettings.InitializeDefaultValues()
기본 스탯 제한 값들을 설정합니다. StatLimits가 비어 있는 경우에만 호출됩니다.
References HasMinLimit, StatLimits.
Referenced by OnEnable.
float ShipStatSettings.GetMaxValue(ShipStat stat)
특정 스탯의 최대값을 반환합니다.
stat 조회할 스탯. 최대값.
References _limitsCache, defaultMaxValue, InitializeCache.
Referenced by ClampValue.
float ShipStatSettings.GetMinValue(ShipStat stat)
특정 스탯의 최소값을 반환합니다.
References _limitsCache, defaultMinValue, InitializeCache.
Referenced by ClampValue.
bool ShipStatSettings.HasMinLimit(ShipStat stat)
특정 스탯이 최소값 제한이 있는지 확인합니다.
References _limitsCache, InitializeCache.
Referenced by ClampValue, InitializeDefaultValues.
float ShipStatSettings.ClampValue(ShipStat stat, float value)
주어진 스탯 값이 최소값과 최대값 사이에 있도록 제한합니다.
References GetMaxValue, GetMinValue, HasMinLimit.