EquipmentManager
EquipmentManager EquipmentManager.Instance
싱글턴 인스턴스입니다.
Referenced by Awake, CrewFactory.InitializeCrewStats, EquipmentUIHandler.OnClickBuy, EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip, EquipmentApplyHandler.OnClickStatApplyButton, EquipmentUIHandler.OnClickStatApplyButton.
EquipmentDatabase EquipmentManager.equipmentDatabase
EquipmentItem EquipmentManager.defaultWeapon
기본 장착 무기 장비
Referenced by GetDefaultEquipment, CrewFactory.InitializeCrewStats, EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip.
EquipmentItem EquipmentManager.defaultShield
기본 장착 방어구 장비
Referenced by GetDefaultEquipment, CrewFactory.InitializeCrewStats, EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip.
EquipmentItem EquipmentManager.defaultAssistant
기본 장착 보조 장비
Referenced by GetDefaultEquipment, CrewFactory.InitializeCrewStats, EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip, EquipmentApplyHandler.OnClickStatApplyButton, EquipmentUIHandler.OnClickStatApplyButton.
EquipmentItem EquipmentManager.globalWeaponLevel1
EquipmentItem EquipmentManager.globalWeaponLevel2
EquipmentItem EquipmentManager.globalWeaponLevel3
EquipmentItem EquipmentManager.globalShieldLevel1
EquipmentItem EquipmentManager.globalShieldLevel2
EquipmentItem EquipmentManager.globalShieldLevel3
EquipmentItem [] EquipmentManager.availableGlobalEquipments
UI에서 선택 가능한 전역 장비 목록입니다. (무기, 방어구 등)
EquipmentItem [] EquipmentManager.availableAssistantEquipments
UI에서 선택 가능한 보조 장비 목록입니다.
void EquipmentManager.Awake()
인스턴스를 초기화합니다. 중복 객체는 제거됩니다.
References Instance.
void EquipmentManager.PurchaseAndEquipGlobal(EquipmentItem eqItem)
전 크루에게 적용되는 전역 장비 구매 및 장착 처리.
eqItem 구매한 장비 아이템.
References CrewBase.ApplyPersonalEquipment, Ship.GetAllCrew, GameManager.GetPlayerShip, GameManager.Instance.
Referenced by EquipmentUIHandler.OnClickBuy.
void EquipmentManager.PurchaseAndEquipPersonal(CrewBase crew, EquipmentItem eqItem)
개별 크루에게 장비를 구매하고 적용합니다. 전역 장비는 무시됩니다.
crew 장비를 적용할 크루. eqItem 구매한 장비 아이템.
References CrewBase.ApplyPersonalEquipment.
Referenced by EquipmentApplyHandler.OnClickStatApplyButton, EquipmentUIHandler.OnClickStatApplyButton.
List< EquipmentItem > EquipmentManager.GetEquipmentsByType(EquipmentType type)
장비 타입별로 필터링하는 유틸리티 메소드
type
EquipmentItem EquipmentManager.GetEquipmentByName(string name)
이름으로 장비 찾기
name
EquipmentItem EquipmentManager.GetEquipmentByTypeAndId(EquipmentType type, int id)
EquipmentItem EquipmentManager.GetDefaultEquipment(EquipmentType type)
기본 장비 반환
type
References defaultAssistant, defaultShield, defaultWeapon.
Referenced by EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip, EquipmentApplyHandler.OnClickStatApplyButton.
EquipmentItem EquipmentManager.GetNextLevelEquipment(EquipmentType type)