CrewMember
Vector2 CrewMember.movementDirection
현재 이동 방향 (normalized)
Referenced by CombatRoutine, FollowPathCoroutine, PlayAnimation.
List<Vector2Int> CrewMember.path
이동 경로
Referenced by AssignPathAndMove, CancelAndRedirect, FollowPathCoroutine.
Coroutine CrewMember.moveCoroutine
이동 수행 코루틴
Referenced by AssignPathAndMove, CancelAndRedirect.
bool CrewMember.wasMoving
움직이는 중이었다.
Referenced by Die, ImDying.
float CrewMember.attackBeforeDelay
애니메이션 발동 타이밍과 실제 데미지 적용 사이의 딜레이
Referenced by Start.
float CrewMember.attackAfterDelay
Room CrewMember.reservedRoom
최종 목적지 방
Referenced by AssignPathAndMove, CancelAndRedirect, FollowPathCoroutine, ImDying, RTSSelectionManager.IssueMoveCommand.
Room CrewMember.oldReservedRoom
새로운 이동 명령 전 기존 목적지 방
Referenced by CancelAndRedirect.
Vector2Int CrewMember.reservedTile
새로운 최종 목적지 타일
Referenced by AssignPathAndMove, CancelAndRedirect, ImDying.
Vector2Int CrewMember.oldReservedTile
새로운 이동 명령 전 기존 목적지 타일 (예약 됐다 취소된..)
Referenced by CancelAndRedirect.
Vector2Int CrewMember.originPosTile
이동 전 위치했던 타일
bool CrewMember.hasEnteredTPRoom
텔레포트 방에 입장 여부 (텔포 준비 완료 여부)
Referenced by FollowPathCoroutine.
bool CrewMember.inCombat
전투 상태 여부
Referenced by Attack, BackToThePeace, CombatRoutine, Die, DontTouchMe, FollowPathCoroutine, Freeze, EnemyController.IsDoingSomething.
Coroutine CrewMember.combatCoroutine
전투 코루틴
Referenced by CombatRoutine, DontTouchMe, FollowPathCoroutine, RepeatCombatRoutine.
Coroutine CrewMember.DieCoroutine
사망 코루틴
Room CrewMember.madRoom
파괴할 방
Referenced by Attack, CombatRoutine, DontTouchMe, Freeze, LookAtMe, RepeatCombatRoutine.
Coroutine CrewMember.repairCoroutine
수리 코루틴
Referenced by RepairRoutine, TryRepair.
float CrewMember.repairCoefficient
수리 효율
Referenced by RepairFacility.
float CrewMember.repairBeforeDelay
수리 간 딜레이
Referenced by RepairRoutine, Start.
float CrewMember.repairAfterDelay
bool CrewMember.isWorking
현재 작업 중인지 여부
Referenced by Die, DontTouchMe, EnemyController.IsDoingSomething, PlayAnimation, TryWork, WalkOut.
bool CrewMember.isTPing
CrewMember CrewMember.combatTarget
전투 대상
Referenced by Attack, CombatRoutine, DontTouchMe, Freeze, LookAtMe, RepeatCombatRoutine.
void CrewMember.Update()
Unity 생명주기 메서드. 매 프레임마다 선원 상태를 갱신합니다. (현재는 구현 미완료)
void CrewMember.EnsureHealthBarFollows()
체력바가 선원을 제대로 따라가도록 확인
Referenced by AssignPathAndMove, CancelAndRedirect.
IEnumerator CrewMember.FollowPathCoroutine()
경로를 따라 이동하는 코루틴
path
References BackToThePeace, combatCoroutine, CombatRoutine, CrewBase.currentRoom, CrewBase.currentShip, DontTouchMe, Freeze, GetCurrentTile, Ship.GetRoomAtPosition, Ship.GetWorldPositionFromGrid, hasEnteredTPRoom, inCombat, RTSSelectionManager.Instance, CrewBase.isMoving, Room< TData, TLevel >.IsOperational, IsOwnShip, isWithEnemy, LookAtMe, RTSSelectionManager.MoveForCombat, movementDirection, CrewBase.moveSpeed, Room< TData, TLevel >.OnCrewEnter, path, PlayAnimation, CrewBase.position, reservedRoom, Room< TData, TLevel >.roomType, TeleportAfterDelay.
Referenced by AssignPathAndMove, CancelAndRedirect.
void CrewMember.SetAnimationDirection(Vector2 direction)
애니메이션 방향 설정
direction
References CrewBase.animator.
Referenced by PlayAnimation, TryWork.
float CrewMember.GetEquipmentAttack()
현재 착용 중인 장비들의 공격력 수치 합계
References CrewBase.equippedShield, CrewBase.equippedWeapon.
Referenced by Attack.
float CrewMember.GetEquipmentDefense()
현재 착용 중인 장비들의 방어력 수치 합계
References CrewBase.equippedShield, CrewBase.equippedWeapon.
Referenced by TakeDamage.
void CrewMember.StopAllCrewCoroutine()
override void CrewMember.Start()
Scriptable Object로 수정 필요!!
References attackBeforeDelay, CrewBase.race, repairBeforeDelay.
override Dictionary< SkillType, float > CrewMember.GetCrewSkillValue()
현재 선원의 모든 스킬 값을 계산하여 반환합니다. 기본 숙련도, 장비 보너스, 사기 보너스를 포함합니다.
스킬 타입별 총 숙련도 값 딕셔너리.
References CrewBase.equipAdditionalSkills, MoraleManager.GetTotalMoraleBonus, CrewBase.skills.
Referenced by AmmunitionRoom.CanITouch, CockpitRoom.CanITouch, EngineRoom.CanITouch, MedBayRoom.CanITouch, PowerRoom.CanITouch, ShieldRoom.CanITouch, WeaponControlRoom.CanITouch, AmmunitionRoom.GetStatContributions, CockpitRoom.GetStatContributions, EngineRoom.GetStatContributions, MedBayRoom.GetStatContributions, PowerRoom.GetStatContributions, ShieldRoom.GetStatContributions, WeaponControlRoom.GetStatContributions, RepairFacility, TryRepair, MedBayRoom.Update.
Vector2Int CrewMember.GetCurrentTile()
현재 위치 반환 (가장 가까운 타일)
References CrewBase.position.
Referenced by AssignPathAndMove, CombatRoutine, CrewPathfinder.FindPathToTile, FollowPathCoroutine, GetCurrentTilePriorityIndex, ImDying, RTSSelectionManager.IssueMoveCommand, RTSSelectionManager.MoveForCombat, RTSSelectionManager.Select, RTSSelectionManager.SelectMultipleCrew, RTSSelectionManager.SelectSingleCrew.
void CrewMember.AssignPathAndMove(List< Vector2Int > newPath)
이동 경로를 명시하고 이동 시작 이동 시작 시 기존 점유 타일 해제, 새로운 목적지 타일 점유 등록
path
References CrewBase.currentRoom, CrewBase.currentShip, EnsureHealthBarFollows, FollowPathCoroutine, GetCurrentTile, moveCoroutine, path, reservedRoom, reservedTile.
void CrewMember.CancelAndRedirect(List< Vector2Int > newPath)
이동 중 새로운 이동 명령 수신 시 이전 목적지 타일 점유 해제 (체력바 follow)
newPath
References CrewBase.currentRoom, CrewBase.currentShip, EnsureHealthBarFollows, FollowPathCoroutine, moveCoroutine, oldReservedRoom, oldReservedTile, path, reservedRoom, reservedTile.
int CrewMember.GetCurrentTilePriorityIndex()
현재 방에서 선원이 점유 중인 타일의 우선순위 인덱스 반환
References CrewBase.currentRoom, GetCurrentTile, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority.
Referenced by RTSSelectionManager.IssueMoveCommand, TryWork.
EquipmentStats CrewMember.GetCombinedStats()
현재 선원의 스텟 반환
References CrewBase.attack, CrewBase.defense, CrewBase.health, CrewBase.skills.
Referenced by GetStatsIfEquipped, EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip, EquipmentApplyHandler.OnEquipmentIconSelected, EquipmentUIHandler.OnEquipmentIconSelected, EquipmentUIHandler.RefreshCrewDetailPanel, EquipmentApplyHandler.RefreshCrewDetailPanel.
EquipmentStats CrewMember.GetStatsIfEquipped(EquipmentItem newItem)
새로운 장비 착용 시뮬레이션
newItem
References CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, GetCombinedStats.
Referenced by EquipmentApplyHandler.OnClickPendingUnEquip, EquipmentUIHandler.OnClickPendingUnEquip, EquipmentApplyHandler.OnEquipmentIconSelected, EquipmentUIHandler.OnEquipmentIconSelected.
void CrewMember.PlayAnimation(string trigger)
animation 실행
trigger
References CrewBase.animator, CrewBase.isMoving, isWorking, movementDirection, SetAnimationDirection.
Referenced by BackToThePeace, CombatRoutine, Die, FollowPathCoroutine, Freeze, ImDying, RepairRoutine, TeleportAfterDelay, TryWork, WalkOut.
IEnumerator CrewMember.CombatRoutine()
전투 진입 코루틴 (타겟 설정 후 전투 시작, 타겟이 없고 적 함선일 경우 방 부수기 돌입)
References CrewBase.bullier, combatCoroutine, CombatRoutine, combatTarget, Room< TData, TLevel >.currentHitPoints, CrewBase.currentRoom, Freeze, GetCurrentTile, Room< TData, TLevel >.GetIsDamageable, CrewBase.health, inCombat, CrewBase.isAlive, IsOwnShip, madRoom, movementDirection, PlayAnimation.
Referenced by CombatRoutine, FollowPathCoroutine, RepeatCombatRoutine, EnemyController.Update.
void CrewMember.RepeatCombatRoutine()
CombatRoutine()은 1회 공격 -> 반복해라
References combatCoroutine, CombatRoutine, combatTarget, madRoom.
void CrewMember.Attack()
전투 메서드: 1 hit 당 피해량 계산 후 체력 차감, 체력이 0 이하이면 죽음 처리
attacker target 공격한 상대가 살아있는지 여부를 반환한다. True: 아직 살아있음 / False: 죽었음
References CrewBase.attack, combatTarget, Room< TData, TLevel >.currentHitPoints, CrewBase.currentShip, GetEquipmentAttack, inCombat, RTSSelectionManager.Instance, isWithEnemy, madRoom, RTSSelectionManager.MoveForCombat, TakeDamage, Room< TData, TLevel >.TakeDamage, Ship.TakeDamage.
void CrewMember.TakeDamage(float damage)
현재 선원의 방어력을 고려한 피해 발생
damage
References CrewBase.defense, Die, GetEquipmentDefense, CrewBase.health.
Referenced by Ship.ApplyDamageToCrewsAtPosition, Ship.ApplyDamageToCrewsInRoom, EventCrewEffectHandler.ApplyEffects, Attack.
void CrewMember.TakeOxygenDamage()
damage
References Die, CrewBase.health, CrewBase.maxHealth, CrewBase.needsOxygen.
void CrewMember.Die()
사망 시, 자신을 combatTarget으로 지정한 선원들에게서 자신을 할당 해제시키고 다른 목표를 탐색하도록한다. 또한 애니메이션 재생을 마친 후에 Destroy
References Ship.allCrews, Ship.allEnemies, CrewBase.currentRoom, CrewBase.currentShip, DontTouchMe, inCombat, RTSSelectionManager.Instance, CrewBase.isAlive, CrewBase.isMoving, CrewBase.isPlayerControlled, isWorking, PlayAnimation, RTSSelectionManager.selectedCrew, WalkOut, wasMoving.
Referenced by TakeDamage, TakeOxygenDamage.
void CrewMember.AfterDie()
void CrewMember.InstantKill()
void CrewMember.DontTouchMe()
전투 상황에서 자신이 이동했을 때, 자신을 공격하던 다른 선원들에게 자신을 공격하는 행위 이외의 다른 행동을 하도록 명령
References BackToThePeace, CrewBase.bullier, combatCoroutine, combatTarget, inCombat, RTSSelectionManager.Instance, isWithEnemy, isWorking, madRoom, RTSSelectionManager.MoveForCombat, WalkOut.
Referenced by Die, FollowPathCoroutine.
IEnumerator CrewMember.ImDying()
죽음 처리
References CrewBase.currentRoom, CrewBase.currentShip, GetCurrentTile, PlayAnimation, reservedRoom, reservedTile, wasMoving.
void CrewMember.LookAtMe()
선원이 진입한 방의 적이 멈춰 있고 전투 중이 아니라면, 모두 본인을 공격하도록 설정 (어그로)
References combatTarget, CrewBase.currentRoom, RTSSelectionManager.Instance, CrewBase.isPlayerControlled, madRoom, RTSSelectionManager.MoveForCombat, WalkOut.
Referenced by FollowPathCoroutine.
void CrewMember.BackToThePeace()
Idle 상태 이후
References CrewBase.currentRoom, inCombat, CrewBase.isAlive, CrewBase.isMoving, IsOwnShip, PlayAnimation, TryRepair, TryWork.
Referenced by CombatManager.BackToTheHome, DontTouchMe, CustomizeShipUIHandler.EnableCrews, FollowPathCoroutine, Room< TData, TLevel >.NotifyStateChanged, CrewSystem.RestoreCrewAfterBuild, EnemyController.Update.
bool CrewMember.isWithEnemy()
방 안의 적군 탐지
References CrewBase.currentRoom, CrewBase.isAlive, CrewBase.isPlayerControlled.
Referenced by Attack, DontTouchMe, FollowPathCoroutine, RepairRoutine, TryWork, EnemyController.Update.
void CrewMember.TryRepair()
본인 함선에서 수리 시도
References GetCrewSkillValue, IsOwnShip, repairCoroutine, RepairRoutine, TryWork.
Referenced by BackToThePeace.
IEnumerator CrewMember.RepairRoutine()
수리 루틴
References CrewBase.currentRoom, isWithEnemy, PlayAnimation, repairBeforeDelay, repairCoroutine, RepairFacility, RepairRoutine, TryWork.
Referenced by RepairRoutine, TryRepair.
void CrewMember.RepairFacility(Room room)
특정 방을 수리하며 수리 스킬을 향상시킵니다.
room 수리 대상 방. amount 수리량.
References GetCrewSkillValue, CrewBase.ImproveSkill, Room< TData, TLevel >.Repair, repairCoefficient.
Referenced by RepairRoutine.
void CrewMember.TryWork()
주변 적들의 유무와 현재 자신의 위치한 타일, 작업 가능한 방인지 여부에 따라 작업 행동을 시도한다. 선원의 작업 숙련도 유무와 숙련도 적용은 Room.CanITouch에서 작동된다.
References CrewBase.currentRoom, Room< TData, TLevel >.currentRotation, GetCurrentTilePriorityIndex, Room< TData, TLevel >.isActive, CrewBase.isPlayerControlled, isWithEnemy, isWorking, PlayAnimation, SetAnimationDirection, Room< TData, TLevel >.workDirection.
Referenced by BackToThePeace, RepairRoutine, TryRepair.
void CrewMember.Heal(float amount)
선원의 체력을 회복합니다. 최대 체력을 초과하지 않습니다.
amount 회복량.
References CrewBase.health, CrewBase.healthBarController, CrewBase.maxHealth.
Referenced by EventCrewEffectHandler.ApplyEffects.
bool CrewMember.NeedsHealing()
체력이 최대치보다 낮은지 여부를 반환합니다.
치료가 필요하면 true.
References CrewBase.health, CrewBase.maxHealth.
void CrewMember.Freeze()
현재 하던 행동을 모두 멈추고 애니메이션을 대기 상태로 전환시킨다.
References combatTarget, inCombat, CrewBase.isMoving, madRoom, PlayAnimation, WalkOut.
Referenced by CombatRoutine, CustomizeShipUIHandler.DisableCrews, FollowPathCoroutine, RTSSelectionManager.IssueMoveCommand, CrewSystem.RestoreCrewAfterBuild, EnemyController.WhereToGo.
void CrewMember.WalkOut()
현재 하던 작업 행동을 멈추고 자신을 Room.workingCrew로 할당한 Room을 찾아 할당 해제시키고 함선 능력치를 재계산한다.
References CrewBase.currentShip, Ship.GetAllRooms, isWorking, PlayAnimation, Ship.RecalculateAllStats.
Referenced by Die, DontTouchMe, Freeze, LookAtMe, Room< TData, TLevel >.NotifyStateChanged.
bool CrewMember.IsOwnShip()
현재 선원이 탑승해 있는 함선이 선원의 모선인지 확인 (상대 배에 타있으면 false)
References CrewBase.isPlayerControlled.
Referenced by BackToThePeace, CombatRoutine, FollowPathCoroutine, TeleportRoom.OnCrewEnter, TeleportAfterDelay, TryRepair, EnemyController.Update.
IEnumerator CrewMember.TeleportAfterDelay(CrewMember crew, float delay)
딜레이 후 텔레포트 진행
crew delay
References GameManager.currentEnemyShip, Ship.GetAllRooms, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, GameManager.Instance, RTSSelectionManager.Instance, IsOwnShip, CrewBase.isPlayerControlled, RTSSelectionManager.MoveForCombat, Room< TData, TLevel >.OnCrewEnter, PlayAnimation, GameManager.playerShip, RTSSelectionManager.selectedCrew.
Referenced by FollowPathCoroutine, RTSSelectionManager.IssueMoveCommand.