InvertedHorizontalScroll
float InvertedHorizontalScroll.scrollSpeed
bool InvertedHorizontalScroll.IsOnScrollbarHandle(PointerEventData eventData)
현재 포인터가 스크롤바 핸들 위에 있는지 여부를 판단
Referenced by OnBeginDrag, OnDrag, OnEndDrag.
override void InvertedHorizontalScroll.OnScroll(PointerEventData data)
휠 스크롤 반전 및 감도 적용
override void InvertedHorizontalScroll.OnBeginDrag(PointerEventData eventData)
핸들 위일 때만 드래그 시작 허용
References IsOnScrollbarHandle.
override void InvertedHorizontalScroll.OnDrag(PointerEventData eventData)
핸들 위일 때만 드래그 허용
References IsOnScrollbarHandle.
override void InvertedHorizontalScroll.OnEndDrag(PointerEventData eventData)
핸들 위일 때만 드래그 종료 허용
References IsOnScrollbarHandle.