EventTestTrigger
EventManager EventTestTrigger.eventManager
int EventTestTrigger.testYear
int EventTestTrigger.testCOMA
float EventTestTrigger.testFuel
bool EventTestTrigger.useRealGameState
bool EventTestTrigger.logEventDetails
int EventTestTrigger.specificEventId
string EventTestTrigger.exportFilePath
bool EventTestTrigger.appendDateToFileName
bool EventTestTrigger.exportAsCSV
void EventTestTrigger.Start()
RandomEvent EventTestTrigger.SelectTestEvent(EventType type)
테스트를 위한 이벤트 선택 도우미 메서드
References Ship.GetAllCrew, GameManager.GetPlayerShip, GameManager.Instance, EventManager.PlanetEvents, CrewBase.race.
Referenced by TriggerCosmicEvent, TriggerPlanetEvent, TriggerRandomEvent, TriggerShipEvent.
void EventTestTrigger.LogEventDetails(RandomEvent evt)
이벤트 세부 정보 로깅
References RandomEvent.requiredCrewRace.
Referenced by TriggerCosmicEvent, TriggerPlanetEvent, TriggerRandomEvent, TriggerShipEvent.
void EventTestTrigger.ExportEventTextsAsCSV(List< RandomEvent > events, string filePath)
모든 이벤트 텍스트를 CSV 형식으로 내보냅니다.
References EscapeCSVField.
Referenced by ExportAllEventTexts.
string EventTestTrigger.EscapeCSVField(string field)
CSV 필드를 위한 문자열 이스케이프 처리
Referenced by ExportEventTextsAsCSV.
void EventTestTrigger.ExportEventTextsAsTXT(List< RandomEvent > events, string filePath)
모든 이벤트 텍스트를 일반 텍스트 형식으로 내보냅니다.
Referenced by ExportAllEventTexts.
void EventTestTrigger.TriggerShipEvent()
ShipEvent 버튼 클릭 시: 항해 중 발생 가능한 이벤트 중 랜덤 1개 실행
References EventManager.GetEventById, LogEventDetails, SelectTestEvent, EventManager.TriggerEvent.
void EventTestTrigger.TriggerPlanetEvent()
PlanetEvent 버튼 클릭 시: 행성 도착 시 발생 가능한 이벤트 중 랜덤 1개 실행
References EventManager.GetEventById, LogEventDetails, SelectTestEvent, EventManager.TriggerEvent.
void EventTestTrigger.TriggerCosmicEvent()
CosmicEvent 버튼 클릭 시: 미스터리 이벤트 중 랜덤 1개 실행
References EventManager.GetEventById, LogEventDetails, SelectTestEvent, EventManager.TriggerEvent.
void EventTestTrigger.TriggerRandomEvent()
모든 이벤트 중 랜덤으로 하나 선택하여 실행합니다.
References EventManager.GetEventById, LogEventDetails, SelectTestEvent, EventManager.TriggerEvent.
void EventTestTrigger.PrintAllEvents()
모든 이벤트를 콘솔에 출력합니다.
References EventManager.AllEvents.
void EventTestTrigger.PrintAvailableEvents()
현재 조건에서 발생 가능한 이벤트를 콘솔에 출력합니다.
References EventManager.AllEvents, RandomEvent.minimumCOMA, RandomEvent.minimumFuel, RandomEvent.minimumYear.
void EventTestTrigger.ExportAllEventTexts()
모든 이벤트의 텍스트를 검사하고 파일로 내보냅니다.
References EventManager.AllEvents, ExportEventTextsAsCSV, ExportEventTextsAsTXT.
void EventTestTrigger.FindEventsByTextKeyPrefix(string prefix)
텍스트 키로 시작하는 이벤트들을 출력합니다.
References EventManager.AllEvents.
void EventTestTrigger.ValidateAllEventTextKeys()
모든 이벤트의 텍스트 키가 유효한지 검사합니다.
References EventManager.AllEvents.