EventTreeMap
NodeType
RectTransform EventTreeMap.treeContainer
GameObject EventTreeMap.eventNodePrefab
GameObject EventTreeMap.connectionLinePrefab
float EventTreeMap.minNodeDistance
int EventTreeMap.minNodesPerLayer
int EventTreeMap.maxNodesPerLayer
Color EventTreeMap.startNodeColor
Color EventTreeMap.endNodeColor
Color EventTreeMap.pirateNodeColor
Color EventTreeMap.spaceStationNodeColor
Color EventTreeMap.randomEventNodeColor
Color EventTreeMap.dangerNodeColor
readonly List<EventNode> EventTreeMap.allNodes
readonly List<GameObject> EventTreeMap.connectionLines
List<List<EventNode> > EventTreeMap.layerNodes
List<bool> EventTreeMap.layerDangerInfo
NodeSelectedHandler EventTreeMap.OnNodeSelected
delegate void EventTreeMap.NodeSelectedHandler(EventNode node)
void EventTreeMap.Initialize()
트리 맵 초기화. 기존 노드와 연결을 모두 제거합니다.
References ClearCurrentTree.
void EventTreeMap.GenerateTreeFromPath(List< Vector2 > pathNodes, List< bool > dangerInfo=null)
외부 경로 정보(pathNodes)와 위험 정보(dangerInfo)를 받아 트리를 생성합니다.
References ClearCurrentTree, GenerateImprovedTree.
void EventTreeMap.GenerateImprovedTree(int layers)
레이어 수(layers)를 기반으로 트리를 생성합니다. 각 레이어는 랜덤한 노드 개수를 갖고, 노드는 평면적으로 연결됩니다.
References ClearCurrentTree, CreateConnectionLines, CreateNode, CreateStrictlyPlanarConnections, DetermineNodeType.
Referenced by GenerateTreeFromPath.
NodeType EventTreeMap.DetermineNodeType(int layer, int totalLayers)
노드 타입을 결정합니다. 위치(layer)에 따라 우선순위를 다르게 적용합니다.
Referenced by GenerateImprovedTree.
EventNode EventTreeMap.CreateNode(Vector2 position, int layer, int index, NodeType type, bool isDangerous)
노드를 생성하고 위치, 색상, 클릭 이벤트 등을 설정합니다.
References ApplyNodeStyle, OnNodeClicked, EventNode.SetNodeData.
Referenced by GenerateImprovedTree.
void EventTreeMap.ApplyNodeStyle(GameObject nodeObj, NodeType type, bool isDangerous)
노드의 색상과 스타일을 적용합니다. 위험 지역 여부에 따라 색상이 다릅니다.
Referenced by CreateNode.
void EventTreeMap.CreateStrictlyPlanarConnections()
평면성을 유지하면서 노드들을 계층적으로 연결합니다. 연결 로직은 중복 방지, 균형 유지, 연결 누락 보정까지 처리합니다.
References EventNode.AddNextNode, EventNode.ClearConnections, VerifyAndFixConnections.
Referenced by GenerateImprovedTree.
void EventTreeMap.VerifyAndFixConnections()
모든 연결 관계를 검사하고, 연결이 없는 노드를 보정합니다.
References EventNode.AddNextNode.
Referenced by CreateStrictlyPlanarConnections.
void EventTreeMap.CreateConnectionLines()
생성된 노드 간의 연결선을 시각적으로 생성합니다. 중복 연결은 방지됩니다.
References CreateConnectionLine.
Referenced by GenerateImprovedTree.
GameObject EventTreeMap.CreateConnectionLine(RectTransform startNode, RectTransform endNode)
연결선 오브젝트를 생성하고, 위치/회전/길이를 자동으로 설정합니다.
References CalculateNodeEdgePosition.
Referenced by CreateConnectionLines.
Vector2 EventTreeMap.CalculateNodeEdgePosition(Vector2 nodeCenter, Vector2 direction, float halfWidth, float halfHeight)
노드의 중심 위치에서 가장자리까지의 연결 지점을 계산합니다.
Referenced by CreateConnectionLine.
void EventTreeMap.ClearCurrentTree()
트리 내부의 모든 노드와 연결선을 제거하고 초기화합니다.
Referenced by GenerateImprovedTree, GenerateTreeFromPath, Initialize.
void EventTreeMap.OnNodeClicked(EventNode node)
노드 클릭 시 발생하는 내부 메서드입니다. OnNodeSelected 이벤트를 트리거합니다.
Referenced by CreateNode.