MoraleSystem
override void MoraleSystem.Initialize(Ship ship)
시스템을 초기화합니다.
ship 초기화할 대상 함선 객체.
Referenced by Ship.InitializeSystems.
override void MoraleSystem.Update(float deltaTime)
매 프레임마다 호출되어 시스템 상태를 갱신합니다.
deltaTime 경과 시간 (초).
Referenced by Ship.Update.
float MoraleSystem.CalculateGlobalMorale()
현재 함선의 전체 사기 수치를 계산합니다. 생명유지실과 승무원 침실이 기여하며, 승무원 수가 수용 가능 인원을 초과할 경우 패널티가 적용됩니다.
계산된 전체 사기 수치.
References Ship.GetAllRooms, Ship.GetCrewCount, ShipSystem.parentShip.
Referenced by Ship.RecalculateAllStats.