MiddlePanelUI
TextMeshProUGUI MiddlePanelUI.selectedItemNameText
선택된 아이템 이름을 표시하는 텍스트 UI 요소입니다.
Referenced by SetSelectedItem.
TextMeshProUGUI MiddlePanelUI.selectedItemDescriptionText
선택된 아이템 설명을 표시하는 텍스트 UI 요소입니다.
Referenced by SetSelectedItem.
TextMeshProUGUI MiddlePanelUI.priceText
선택된 아이템 가격을 표시하는 텍스트 UI 요소입니다.
Referenced by SetSelectedItem.
TMP_InputField MiddlePanelUI.tradeNumInputField
거래 수량을 입력받는 텍스트 입력 필드입니다.
Referenced by OnBuyClicked, OnSellClicked, SetSelectedItem.
Button MiddlePanelUI.buyButton
구매 버튼입니다.
Referenced by Start.
Button MiddlePanelUI.sellButton
판매 버튼입니다.
Referenced by Start.
Image MiddlePanelUI.itemShapeImage
아이템 형태를 보여줄 UI Image입니다.
Referenced by SetSelectedItem.
List<Sprite> MiddlePanelUI.itemShapeSprites
아이템 모양에 해당하는 스프라이트 리스트입니다. itemShape enum 순서에 맞춰 등록해야 합니다.
Referenced by SetSelectedItem.
TextMeshProUGUI MiddlePanelUI.playerCOMAText
임시 테스트용 코마 관리 텍스트입니다.
Referenced by UpdatePlayerComa.
TradingItemData MiddlePanelUI.selectedItemData
현재 선택된 아이템 데이터입니다.
Referenced by OnBuyClicked, OnSellClicked, SetSelectedItem.
TradeManager MiddlePanelUI.tradeManager
거래 관련 로직을 담당하는 TradeManager 컴포넌트입니다.
Referenced by OnBuyClicked, OnSellClicked, Start.
void MiddlePanelUI.Awake()
시작시 비활성화 상태로 두는 코드입니다.
void MiddlePanelUI.Start()
초기화 작업을 수행하고 버튼 이벤트를 등록하는 메서드입니다.
References buyButton, OnBuyClicked, OnSellClicked, sellButton, tradeManager, UpdatePlayerComa.
void MiddlePanelUI.OnBuyClicked()
구매 버튼 클릭 시 호출되는 메서드입니다. 선택된 아이템의 구매를 시도하고, 성공 시 인벤토리 UI를 갱신합니다.
References TradeManager.BuyItem, InventoryUI.PopulateInventory, selectedItemData, tradeManager, tradeNumInputField, UpdatePlayerComa.
Referenced by Start.
void MiddlePanelUI.OnSellClicked()
판매 버튼 클릭 시 호출되는 메서드입니다. 선택된 아이템의 판매를 시도하고, 성공 시 인벤토리 UI를 갱신합니다.
References InventoryUI.PopulateInventory, selectedItemData, TradeManager.SellItem, tradeManager, tradeNumInputField, UpdatePlayerComa.
Referenced by Start.
void MiddlePanelUI.SetSelectedItem(TradingItemData itemData)
선택된 아이템의 상세 정보를 UI에 표시하는 메서드입니다.
itemData UI에 표시할 선택된 아이템 데이터입니다.
References itemShapeImage, itemShapeSprites, priceText, selectedItemData, selectedItemDescriptionText, selectedItemNameText, tradeNumInputField.
Referenced by InventoryItemUI.OnPointerClick, PlanetItemUI.OnPointerClick, TradeUIManager.OpenSellPanel.
void MiddlePanelUI.UpdatePlayerComa()
플레이어의 COMA(재화)를 UI에 갱신하는 메서드입니다.
References playerCOMAText.
Referenced by OnBuyClicked, InventoryItemUI.OnPointerClick, OnSellClicked, TradeUIManager.OpenBuyPanel, TradeUIManager.OpenSellPanel, Start.