Customize_2_Controller
BPPreviewCamera Customize_2_Controller.previewCam
GameObject Customize_2_Controller.customize0Panel
GameObject Customize_2_Controller.customize2Panel
Button Customize_2_Controller.outerhullbutton1
Button Customize_2_Controller.outerhullbutton2
Button Customize_2_Controller.outerhullbutton3
Button Customize_2_Controller.buyButton
Button Customize_2_Controller.cancelButton
GridPlacer Customize_2_Controller.gridPlacer
배치용 가이드라인
Referenced by MakeBPShipWithSaveData.
int Customize_2_Controller.totalBPCost
설계도 함선 가격
Referenced by OnEnable.
int Customize_2_Controller.originalShipCost
기존 사용 중인 함선 가격
Referenced by OnClickBuy, OnEnable.
BlueprintSaveData Customize_2_Controller.selectedData
슬롯에 저장된 도안 데이터
Referenced by MakeBPShipWithSaveData, OnClickBuy, OnClickCancel, OnEnable.
RawImage Customize_2_Controller.hullPreviewImage
외갑판 적용 preview 보여줄 이미지
Referenced by AdjustRawImageAspect.
bool Customize_2_Controller.buyClicked
int Customize_2_Controller.originHullLevel
int Customize_2_Controller.selectedHullLevel
TMP_Text Customize_2_Controller.currency
현재 보유 재화량
TMP_Text Customize_2_Controller.bpCostText
총 설계도 가격을 표시할 텍스트 UI.
TMP_Text Customize_2_Controller.originShipCostText
기존 함선 가격 텍스트
TMP_Text Customize_2_Controller.feedbackText
함선 교체 가능한지 여부 텍스트 (불가능 시 이유)
Ship Customize_2_Controller.playerShip
현재 커스터마이징 중인 플레이어 함선입니다.
Referenced by OnClickBuy, OnEnable.
BlueprintShip Customize_2_Controller.bpShip
제작한 설계도
Referenced by MakeBPShipWithSaveData, OnClickBuy, OnClickCancel, OnClickOuterHullButton, OnEnable.
GameObject Customize_2_Controller.previewOuterHullPrefab
외갑판 prefab (preview용)
Referenced by OnClickCancel, OnClickOuterHullButton, Customize_0_Controller.OnClickSlot.
void Customize_2_Controller.Start()
void Customize_2_Controller.OnEnable()
현재 설계도의 가격 지속 갱신 설계도로 함선 교체 가능 조건
(설계도 가격 - 기존 함선 가격) <= 보유 재화량 기존 함선 모든 방 내구도 100%
References AdjustRawImageAspect, bpShip, BlueprintSlotManager.GetBlueprintAt, BlueprintShip.GetTotalBPCost, Ship.GetTotalShipValue, BlueprintSlotManager.Instance, GameManager.Instance, Ship.IsFullHitPoint, MakeBPShipWithSaveData, originalShipCost, playerShip, GameManager.playerShip, selectedData, Ship.SetShipContentsActive, totalBPCost.
IEnumerator Customize_2_Controller.SaveAfterDelay()
void Customize_2_Controller.AdjustRawImageAspect()
Image 비율 조정
References hullPreviewImage.
Referenced by OnClickOuterHullButton, OnEnable.
BlueprintShip Customize_2_Controller.MakeBPShipWithSaveData()
BlueprintSaveData 기반으로 blueprintShip 생성
References BlueprintShip.AddPlaceable, BlueprintWeapon.ApplyAttachedDirectionSprite, bpShip, BlueprintShip.ClearRooms, BlueprintSlotManager.GetBlueprintAt, BlueprintWeapon.GetHullLevel, gridPlacer, BlueprintSlotManager.Instance, GridPlacer.PlacePreviewRoom, GridPlacer.PlacePreviewWeapon, selectedData, BlueprintWeapon.SetHullLevel.
Referenced by Customize_0_Controller.OnClickSlot, OnEnable.
void Customize_2_Controller.OnClickBuy()
'함선 제작' 버튼 클릭 시 호출. 조건 만족 시 기존 함선을 설계도의 함선으로 교체합니다. 이후 방, 문의 연결 유효성 검사 수행 후 만족 여부에 따라 실제 함선으로 교체, 다시 설계도로 복구를 수행
References BlueprintSlotManager.appliedSlotIndex, Ship.BackupAllCrews, Ship.backupCrewDatas, bpShip, OuterHullSystem.ClearExistingHulls, BlueprintSlotManager.GetBlueprintAt, BlueprintShip.GetTotalBPCost, Ship.GetTotalShipValue, BlueprintSlotManager.Instance, RTSSelectionManager.Instance, Customize_0_Controller.OnClickSlot, originalShipCost, playerShip, Ship.RecalculateAllStats, RTSSelectionManager.RefreshMovementData, Ship.ReplaceShipFromBlueprint, CrewSystem.RestoreCrewAfterBuild, selectedData, Ship.SetOuterHullLevel, Ship.SetShipContentsActive, BPPreviewArea.UpdateAndShow, Ship.UpdateOuterHullVisuals.
void Customize_2_Controller.OnClickCancel()
구매 취소 버튼 (customize_0_panel로 복귀)
References bpShip, BlueprintShip.ClearRooms, previewOuterHullPrefab, selectedData, BlueprintShip.SetBPHullLevel.
void Customize_2_Controller.OnClickOuterHullButton(int level)
외갑판 적용
level
References AdjustRawImageAspect, bpShip, previewOuterHullPrefab, BlueprintShip.SetBPHullLevel.