EquipmentApplyHandler
GameObject EquipmentApplyHandler.crewDetailPanel
개별 선원 디테일 정보 표시
GameObject EquipmentApplyHandler.allEquipmentPanel
보유 중인 전체 장비 나타내는 패널
HashSet<EquipmentItem> EquipmentApplyHandler.purchasedItems
구매한 장비 목록입니다. 중복 구매를 방지하기 위해 HashSet으로 관리됩니다.
CrewMember EquipmentApplyHandler.selectedCrew
장비 착용할 선택된 선원
Referenced by GetCurrentEquippedByType, OnClickPendingUnEquip, OnClickStatApplyButton, OnCrewIconSelected, OnEquipmentIconSelected, RefreshCrewDetailPanel.
GameObject EquipmentApplyHandler.equipmentIconPrefab
장비 Prefab
Referenced by PopulateEquipmentIcons.
Transform EquipmentApplyHandler.equipmentContent
각 장비가 설치될 content
Referenced by PopulateEquipmentIcons.
Image EquipmentApplyHandler.detailCrewImage
개별 선원 디테일 UI에서 선원 이미지
Button EquipmentApplyHandler.detailWeaponButton
개별 선원 디테일 UI에서 무기 장비 버튼
Referenced by OnCrewIconSelected, RefreshCrewDetailPanel.
Button EquipmentApplyHandler.detailShieldButton
개별 선원 디테일 UI에서 방어구 장비 버튼
Referenced by OnCrewIconSelected, RefreshCrewDetailPanel.
Button EquipmentApplyHandler.detailAssistButton
개별 선원 디테일 UI에서 보조 장비 버튼
Referenced by OnCrewIconSelected, RefreshCrewDetailPanel.
Sprite EquipmentApplyHandler.noneIcon
착용 중인 장비 없음을 나타내는 icon
Referenced by OnCrewIconSelected, RefreshCrewDetailPanel.
Button EquipmentApplyHandler.applyButton
선원에게 장비 적용 버튼
Button EquipmentApplyHandler.backButton
선원 리스트로 돌아가는 버튼
GameObject EquipmentApplyHandler.statComparePanel
스텟 비교 패널
TextMeshProUGUI EquipmentApplyHandler.baseStatsText
기존 스텟
TextMeshProUGUI EquipmentApplyHandler.newStatsText
장비 착용, 미착용 후 변화 스텟
TextMeshProUGUI EquipmentApplyHandler.statDiffText
차이
SlidePanelController EquipmentApplyHandler.slidePanelController
선원 패널
Referenced by OnClickStatApplyButton.
GameObject EquipmentApplyHandler.midArrows
변화 표시 오브젝트 (우측 화살표)
Referenced by OnClickBackPersonal, OnClickStatApplyButton, ShowStatComparison.
EquipmentItem EquipmentApplyHandler.pendingEquipItem
해제하는 장비
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
EquipmentType EquipmentApplyHandler.pendingEquipType
해제하는 장비 타입
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
bool EquipmentApplyHandler.isPendingRemoval
장비 해제 완료 여부
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
Image [] EquipmentApplyHandler.changeArrows
Image EquipmentApplyHandler.beforeEquipImage
Image EquipmentApplyHandler.afterEquipImage
Sprite EquipmentApplyHandler.increaseSprite
Sprite EquipmentApplyHandler.decreaseSprite
Sprite EquipmentApplyHandler.noChangeSprite
void EquipmentApplyHandler.OnEnable()
void EquipmentApplyHandler.PopulateEquipmentIcons()
보유 중인 전체 장비 리스트 갱신
References equipmentContent, equipmentIconPrefab, GameManager.Instance, OnEquipmentIconSelected, GameManager.playerShip, Ship.unUsedItems.
Referenced by OnClickStatApplyButton.
void EquipmentApplyHandler.ShowStatComparison(EquipmentStats before, EquipmentStats after)
장비 착용 / 해제 비교
before after
References midArrows.
Referenced by OnClickPendingUnEquip, OnEquipmentIconSelected.
void EquipmentApplyHandler.OnEquipmentIconSelected(EquipmentItem item)
장비 선택됨 (장비 착용, 미착용 등 스텟 비교)
item
References CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, CrewMember.GetCombinedStats, CrewMember.GetStatsIfEquipped, isPendingRemoval, pendingEquipItem, pendingEquipType, selectedCrew, ShowStatComparison.
Referenced by PopulateEquipmentIcons.
EquipmentItem EquipmentApplyHandler.GetCurrentEquippedByType(EquipmentType type)
현재 착용 중인 장비 반환
type
References CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, selectedCrew.
Referenced by OnClickStatApplyButton.
void EquipmentApplyHandler.RefreshCrewDetailPanel(EquipmentType type)
선원 개인 디테일 패널 정보 갱신
References detailAssistButton, detailShieldButton, detailWeaponButton, CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, CrewMember.GetCombinedStats, noneIcon, selectedCrew.
Referenced by OnClickStatApplyButton.
void EquipmentApplyHandler.Initialize()
void EquipmentApplyHandler.OnCrewIconSelected(CrewMember crew)
선원 선택됨
crew
References detailAssistButton, detailShieldButton, detailWeaponButton, noneIcon, CrewBase.portraitSprite, selectedCrew.
void EquipmentApplyHandler.OnClickPendingUnEquip(EquipmentType type)
장비 해제 예비 작업
type
References EquipmentManager.defaultAssistant, EquipmentManager.defaultShield, EquipmentManager.defaultWeapon, CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, CrewMember.GetCombinedStats, EquipmentManager.GetDefaultEquipment, CrewMember.GetStatsIfEquipped, EquipmentManager.Instance, isPendingRemoval, pendingEquipItem, pendingEquipType, selectedCrew, ShowStatComparison.
void EquipmentApplyHandler.OnClickUnEquipWeaponSlot()
void EquipmentApplyHandler.OnClickUnEquipShieldSlot()
void EquipmentApplyHandler.OnClickUnEquipAssistantSlot()
void EquipmentApplyHandler.OnClickStatApplyButton()
ok 버튼 눌러 장비를 선원에게 직접 적용 / 해제
References EquipmentManager.defaultAssistant, GetCurrentEquippedByType, EquipmentManager.GetDefaultEquipment, EquipmentManager.Instance, GameManager.Instance, isPendingRemoval, midArrows, pendingEquipItem, pendingEquipType, GameManager.playerShip, PopulateEquipmentIcons, EquipmentManager.PurchaseAndEquipPersonal, RefreshCrewDetailPanel, selectedCrew, slidePanelController, Ship.unUsedItems.
void EquipmentApplyHandler.OnClickBackPersonal()
선원 개인 디테일 panel 끄기
References midArrows.