EventPanelController
TextMeshProUGUI EventPanelController.eventTitleText
TextMeshProUGUI EventPanelController.eventDescriptionText
GameObject EventPanelController.choiceButtonPrefab
Button EventPanelController.continueButton
TextMeshProUGUI EventPanelController.outcomeText
GameObject EventPanelController.choiceContainer
float EventPanelController.textTypingSpeed
RandomEvent EventPanelController.currentEvent
void EventPanelController.Start()
void EventPanelController.SetupChoiceButtons(RandomEvent randomEvent)
선택지 버튼 설정
References ClearChoices, OnChoiceSelected.
Referenced by ShowEvent.
void EventPanelController.ClearChoices()
선택지 클리어
Referenced by SetupChoiceButtons, ShowEvent.
void EventPanelController.OnChoiceSelected(int choiceIndex)
선택지 선택 처리
References EventManager.ProcessChoice.
Referenced by SetupChoiceButtons.
IEnumerator EventPanelController.TypeText(TextMeshProUGUI textComponent, string text)
텍스트 타이핑 효과
Referenced by ShowEvent.
IEnumerator EventPanelController.TypeOutcomeText(TextMeshProUGUI textComponent, string text)
결과 텍스트 타이핑 효과 - 완료 후 계속하기 버튼 표시
Referenced by ShowOutcome.
void EventPanelController.ContinueButtonChange()
void EventPanelController.ShowEvent(RandomEvent randomEvent)
이벤트 표시 - UIManager에서 호출
References ClearChoices, GameManager.Instance, SetupChoiceButtons, TypeText.
Referenced by EventManager.ProcessNextEvent.
void EventPanelController.ShowOutcome(string text)
결과 표시
References TypeOutcomeText.
Referenced by EventManager.ProcessChoice.
void EventPanelController.CloseEventPanel()
이벤트 패널 닫기
References EventManager.EndEvent.