BlueprintRoom
RoomData BlueprintRoom.bpRoomData
RoomData 참조
Referenced by Initialize, Ship.ReplaceShipFromBlueprint, BlueprintShip.SetBPHullLevel, Update.
int BlueprintRoom.bpLevelIndex
선택된 레벨 인덱스 (0~2)
Referenced by Initialize, Ship.ReplaceShipFromBlueprint, BlueprintShip.SetBPHullLevel, Update.
Constants.Rotations.Rotation BlueprintRoom.bpRotation
회전 각
Referenced by GetRotation, Initialize, Ship.ReplaceShipFromBlueprint, Rotate, BlueprintShip.SetBPHullLevel, Update, UpdateOccupiedTiles.
Vector2Int BlueprintRoom.bpPosition
배치 위치
Referenced by GetGridPosition, Initialize, Ship.ReplaceShipFromBlueprint, BlueprintShip.SetBPHullLevel, SetGridPosition, Update, UpdateOccupiedTiles.
int BlueprintRoom.bpRoomCost
해당 레벨의 설치 비용
Referenced by GetCost, Initialize.
Vector2Int BlueprintRoom.bpRoomSize
해당 레벨의 크기
Referenced by Initialize, Rotate, Update, UpdateOccupiedTiles.
List<Vector2Int> BlueprintRoom.occupiedTiles
실제 점유 타일
Referenced by GetOccupiedTiles, Initialize, Update, UpdateOccupiedTiles.
BlueprintShip BlueprintRoom.blueprintShip
설계도 함선
Referenced by GetBlueprintShip, SetBlueprint.
bool BlueprintRoom.isDragging
드래그 중인지 여부
Referenced by SetDragMode, Update.
SpriteRenderer BlueprintRoom.sr
설계도 방의 Sprite Renderer
Referenced by Initialize, SetDragMode, Start.
Color BlueprintRoom.validColor
배치 가능을 나타내는 초록색 (alpha = 0.5)
Referenced by Update.
Color BlueprintRoom.invalidColor
배치 불가능을 나타내는 빨간색 (alpha = 0.5)
Referenced by Update.
Vector2Int BlueprintRoom.originalPos
이동 전 방 위치
Referenced by Update.
Constants.Rotations.Rotation BlueprintRoom.originalRot
이동 전 방 회전각
Referenced by Update.
GridPlacer BlueprintRoom.gridPlacer
그리드 타일 배치 작업을 위한 오브젝트
Referenced by SetGridPlacer, Update.
RoomData.RoomLevel BlueprintRoom.levelData
방 레벨 데이터
Referenced by Initialize, Rotate, Update.
GameObject BlueprintRoom.mouseDownTarget
마우스로 클릭한 오브젝트 (방 삭제 여부 활성화 조건을 위한 변수)
Referenced by Update.
void BlueprintRoom.Start()
collider size 맞춤
References sr.
void BlueprintRoom.Update()
방 배치와 관련된 모든 작업을 매 프레임 검사
References bpLevelIndex, bpPosition, bpRoomData, bpRoomSize, bpRotation, GridPlacer.CanPlaceRoom, RoomSelectionHandler.Deselect, GridPlacer.GetWorldPositionFromGrid, gridPlacer, RoomSelectionHandler.Instance, invalidColor, isDragging, IsPointerOverBlockingUI, IsPointerOverUIObject, levelData, GridPlacer.MarkObjectOccupied, mouseDownTarget, occupiedTiles, originalPos, originalRot, Rotate, RoomSelectionHandler.selectionUI, RoomSelectionHandler.SelectRoom, GridPlacer.UnMarkObjectOccupied, UpdateOccupiedTiles, validColor, GridPlacer.WorldToGridPosition.
bool BlueprintRoom.BlockBPMovement()
bool BlueprintRoom.IsPointerOverBlockingUI()
특정 UI 요소들 위에 마우스가 있는지 확인 특히 인벤토리 UI와 같은 방해가 되는 UI만 체크
Referenced by Update.
bool BlueprintRoom.IsPointerOverUIObject(GameObject rootUI)
마우스가 selectionUI 위에 있는지 확인
rootUI
Referenced by Update.
void BlueprintRoom.Initialize(RoomData data, int level, Vector2Int pos, Constants.Rotations.Rotation rot)
설치 시 초기화
References bpLevelIndex, bpPosition, bpRoomCost, bpRoomData, bpRoomSize, bpRotation, RoomData< T >.GetRoomDataByLevel, levelData, occupiedTiles, sr.
Referenced by GridPlacer.PlacePreviewRoom, GridPlacer.PlaceRoom.
void BlueprintRoom.SetDragMode(bool isDragging)
드래그 모드 설정 (BlueprintRoom은 드래그 모드에서 시각적 변경만 적용) IDraggableItem 인터페이스 구현
References isDragging, sr.
void BlueprintRoom.Rotate(Constants.Rotations.Rotation rotation)
오브젝트 회전
References bpRoomSize, bpRotation, levelData.
Referenced by Update.
object BlueprintRoom.GetRotation()
현재 회전 상태 반환
References bpRotation.
Vector2Int BlueprintRoom.GetGridPosition()
현재 그리드 위치 반환
References bpPosition.
void BlueprintRoom.SetGridPosition(Vector2Int position)
그리드 위치 설정
References bpPosition.
void BlueprintRoom.SetBlueprint(BlueprintShip bpShip)
설계도 함선 할당
bpShip
References blueprintShip.
Referenced by GridPlacer.PlaceRoom.
BlueprintShip BlueprintRoom.GetBlueprintShip()
설계도 함선 호출
References blueprintShip.
void BlueprintRoom.SetGridPlacer(GridPlacer placer)
그리드 배치 담당 오브젝트 세팅
placer
References gridPlacer.
Referenced by GridPlacer.PlaceRoom.
int BlueprintRoom.GetCost()
설치 비용 반환
References bpRoomCost.
List< Vector2Int > BlueprintRoom.GetOccupiedTiles()
Blueprint Room이 점유하고 있는 타일 반환
References occupiedTiles.
Referenced by GridPlacer.GetCameraStartPositionToOriginShip.
void BlueprintRoom.UpdateOccupiedTiles()
BPRoom의 점유 타일 업데이트
References bpPosition, bpRoomSize, bpRotation, occupiedTiles.
Referenced by Update.