ShipFactory
GameObject ShipFactory.shipPrefab
void ShipFactory.Awake()
Ship ShipFactory.CreateEmptyShipInstance(string shipName="Ship")
빈 함선 인스턴스 생성
shipName 함선 이름 (옵션) 생성된 함선 객체
Referenced by CloneShip, CreateShipFromTemplate, LoadShipFromSave.
Ship ShipFactory.CreateShipFromTemplate(ShipTemplate template)
템플릿을 기반으로 함선 생성
template 함선 템플릿 생성된 함선 객체
References Ship.AddCrew, Ship.AddRoom, CrewFactory.CreateCrewInstance, CreateEmptyShipInstance, RoomFactory.CreateRoomInstance, Room< TData, TLevel >.position.
Ship ShipFactory.CloneShip(Ship originalShip)
기존 함선을 복제하여 새 인스턴스 생성
originalShip 복제할 원본 함선 복제된 함선 인스턴스
References CrewFactory.CreateCrewInstance, CreateEmptyShipInstance, RoomFactory.CreateRoomObject.
Ship ShipFactory.LoadShipFromSave(string savePath)
저장된 함선 데이터에서 함선 복원
savePath 저장 파일 경로 복원된 함선 또는 null
References CreateEmptyShipInstance.