EventManager
EventManager EventManager.Instance
EventPanelController EventManager.EventPanelController
List<RandomEvent> EventManager.AllEvents
모든 이벤트 목록을 반환합니다.
Referenced by EventTestTrigger.ExportAllEventTexts, EventTestTrigger.FindEventsByTextKeyPrefix, EventTestTrigger.PrintAllEvents, EventTestTrigger.PrintAvailableEvents, EventTestTrigger.ValidateAllEventTextKeys.
List<RandomEvent> EventManager.ShipEvents
함선 이벤트 목록을 반환합니다.
List<RandomEvent> EventManager.PlanetEvents
행성 이벤트 목록을 반환합니다.
Referenced by EventTestTrigger.SelectTestEvent.
List<RandomEvent> EventManager.MysteryEvents
미스터리 이벤트 목록을 반환합니다.
EventDatabase EventManager.eventDatabase
RandomEvent EventManager.currentEvent
EventResourceEffectHandler EventManager.resourceEffectHandler
EventCrewEffectHandler EventManager.crewEffectHandler
EventPlanetEffectHandler EventManager.planetEffectHandler
SpecialEffectHandlerFactory EventManager.specialEffectHandlerFactory
List<int> EventManager.recentEventIds
Queue<RandomEvent> EventManager.pendingEvents
bool EventManager.isProcessingEvent
WarpNode EventManager.CurrentWarpNode
void EventManager.Awake()
void EventManager.Start()
IEnumerator EventManager.TryTriggerShipEventCoroutine()
IEnumerator EventManager.TryTriggerPlanetEventCoroutine()
void EventManager.ProcessNextEvent()
큐에서 다음 이벤트를 처리합니다.
References GameManager.Instance, EventPanelController.ShowEvent.
Referenced by EndEvent, TriggerEvent.
void EventManager.ApplyOutcomeEffects(EventOutcome outcome)
결과 효과를 적용합니다.
outcome 적용할 결과
References EventCrewEffectHandler.ApplyEffects, EventPlanetEffectHandler.ApplyEffects, EventResourceEffectHandler.ApplyEffects, SpecialEffectHandlerFactory.GetHandler.
Referenced by ProcessChoice.
RandomEvent EventManager.SelectAppropriateEvent(EventType type)
현재 게임 상태에 적합한 이벤트를 선택합니다.
type 이벤트 타입 선택된 이벤트 또는 null
References GameManager.CompletedMysteryEventIds, GameManager.CurrentYear, GetAvailableCrewRaces, EventDatabase.GetFilteredEvents, GameManager.Instance.
List< CrewRace > EventManager.GetAvailableCrewRaces()
현재 보유 중인 선원 종족 목록을 가져옵니다.
보유 중인 선원 종족 목록
References Ship.GetAllCrew, GameManager.GetPlayerShip, GameManager.Instance, CrewBase.race.
Referenced by SelectAppropriateEvent.
void EventManager.AddToRecentEvents(int eventId)
최근 발생한 이벤트 목록에 이벤트를 추가합니다.
eventId 추가할 이벤트 ID
Referenced by TriggerEvent.
RandomEvent EventManager.GetEventById(int id)
이벤트 ID로 이벤트를 검색합니다.
References EventDatabase.GetEvent.
Referenced by EventTestTrigger.TriggerCosmicEvent, EventTestTrigger.TriggerPlanetEvent, EventTestTrigger.TriggerRandomEvent, EventTestTrigger.TriggerShipEvent.
void EventManager.TryTriggerShipEvent(int year)
void EventManager.TryTriggerPlanetEvent(int year)
워프 시 이벤트 발생 여부를 체크하고 이벤트를 실행합니다.
이벤트가 발생했는지 여부
void EventManager.CombatOccur()
void EventManager.TriggerEvent(RandomEvent randomEvent)
이벤트를 트리거합니다. 이미 진행 중인 이벤트가 있다면 큐에 추가합니다.
References AddToRecentEvents, ProcessNextEvent.
Referenced by EventNextEventEffectHandler.HandleEffect, EventTestTrigger.TriggerCosmicEvent, TriggerEventById, EventTestTrigger.TriggerPlanetEvent, EventTestTrigger.TriggerRandomEvent, EventTestTrigger.TriggerShipEvent.
void EventManager.TriggerEventById(int eventId)
특정 ID의 이벤트를 강제로 실행합니다.
eventId 실행할 이벤트 ID
References EventDatabase.GetEvent, TriggerEvent.
void EventManager.ProcessChoice(RandomEvent randomEvent, int choiceIndex)
선택지 선택 시 처리합니다.
randomEvent 현재 이벤트 choiceIndex 선택한 선택지 인덱스
References GameManager.AddCompletedMysteryEvent, ApplyOutcomeEffects, GameManager.Instance, EventPanelController.ShowOutcome.
Referenced by EventPanelController.OnChoiceSelected.
void EventManager.EndEvent()
이벤트 종료 처리를 수행합니다.
References ProcessNextEvent.
Referenced by EventPanelController.CloseEventPanel.
void EventManager.ClearPendingEvents()
대기 중인 모든 이벤트를 취소합니다.
void EventManager.ClearRecentEvents()
최근 발생한 이벤트 목록을 초기화합니다.