EventNode
int EventNode.levelIndex
int EventNode.nodeIndex
bool EventNode.isDangerous
List<EventNode> EventNode.nextNodes
int EventNode.LevelIndex
int EventNode.NodeIndex
List<EventNode> EventNode.NextNodes
bool EventNode.IsDangerous
void EventNode.SetNodeData(int level, int index, bool dangerous=false)
노드 데이터를 설정합니다. (레벨, 인덱스, 위험 여부)
level 노드의 레벨 인덱스. index 노드의 고유 인덱스. dangerous 위험 지역 여부 (기본값: false).
Referenced by EventTreeMap.CreateNode.
void EventNode.AddNextNode(EventNode node)
연결된 다음 노드를 추가합니다. 중복 연결은 방지됩니다.
node 연결할 노드.
Referenced by EventTreeMap.CreateStrictlyPlanarConnections, EventTreeMap.VerifyAndFixConnections.
void EventNode.ClearConnections()
현재 연결된 모든 노드를 제거합니다.
Referenced by EventTreeMap.CreateStrictlyPlanarConnections.