SpecialEffectHandlerFactory
readonly Dictionary<SpecialEffectType, ISpecialEffectHandler> SpecialEffectHandlerFactory.handlers
SpecialEffectHandlerFactory.SpecialEffectHandlerFactory()
생성자: 모든 기본 SpecialEffectType에 대해 핸들러를 등록합니다.
References RegisterAllDefaultHandlers.
ISpecialEffectHandler SpecialEffectHandlerFactory.GetHandler(SpecialEffectType type)
특정 SpecialEffectType에 해당하는 핸들러를 반환합니다.
Referenced by EventManager.ApplyOutcomeEffects.
void SpecialEffectHandlerFactory.RegisterAllDefaultHandlers()
모든 기본 핸들러들을 등록합니다.
References RegisterHandler.
Referenced by SpecialEffectHandlerFactory.
void SpecialEffectHandlerFactory.RegisterHandler(SpecialEffectType type, ISpecialEffectHandler handler)
특정 SpecialEffectType에 해당하는 핸들러를 등록합니다.
Referenced by RegisterAllDefaultHandlers.