CrewDatabase
List<RaceStat> CrewDatabase.raceStats
종족별 기본 스탯 데이터 목록
Referenced by DeserializeFromJson, InitializeDefaultStats, InitializeDictionary, OnEnable, OnValidate.
Dictionary<CrewRace, RaceStat> CrewDatabase.raceStatsByType
런타임용 종족별 스탯 딕셔너리
Referenced by DeserializeFromJson, GetAllRaceStats, GetRaceStat, InitializeDefaultStats, InitializeDictionary.
Dictionary<CrewRace, RaceStat> CrewDatabase.ByRace
종족별 스탯 dictionary 제공
Referenced by DeserializeFromJson, SerializeToJson.
void CrewDatabase.InitializeDictionary()
데이터베이스 초기화
References raceStats, raceStatsByType.
Referenced by GetAllRaceStats, GetRaceStat, OnEnable.
void CrewDatabase.InitializeDefaultStats()
종족 별 기본값 초기화
References raceStats, raceStatsByType, CrewDatabase.RaceStat.SetMaxSkillValuesFromDictionary.
Referenced by OnEnable, OnValidate.
RaceStat CrewDatabase.GetRaceStat(CrewRace race)
특정 종족의 스탯 정보 반환
race 종족 타입 종족 스탯 정보
References InitializeDictionary, raceStatsByType.
Referenced by DoesRaceNeedOxygen, GetInitialSkillValue, GetMaxSkillValue, GetRaceLearningSpeed, CrewFactory.GetRaceStat, CrewFactory.InitializeCrewStats.
Dictionary< CrewRace, RaceStat > CrewDatabase.GetAllRaceStats()
모든 종족 스탯 정보 반환
종족별 스탯 정보 딕셔너리
References InitializeDictionary, raceStatsByType.
float CrewDatabase.GetMaxSkillValue(CrewRace race, SkillType skillType)
특정 스킬의 최대값 반환
race 종족 타입 skillType 스킬 타입 최대 스킬값 (종족 정보가 없으면 0 반환)
References CrewDatabase.RaceStat.GetMaxSkillValueDictionary, GetRaceStat.
float CrewDatabase.GetInitialSkillValue(CrewRace race, SkillType skillType)
특정 종족의 초기 스킬값 반환
race 종족 타입 skillType 스킬 타입 초기 스킬값
References GetRaceStat, CrewDatabase.RaceStat.initialPilotSkill.
bool CrewDatabase.DoesRaceNeedOxygen(CrewRace race)
특정 종족이 산소가 필요한지 여부 반환
race 종족 타입 산소 필요 여부
References GetRaceStat.
float CrewDatabase.GetRaceLearningSpeed(CrewRace race)
특정 종족의 학습 속도 반환
race 종족 타입 학습 속도
References GetRaceStat.
string CrewDatabase.SerializeToJson()
데이터베이스 전체 데이터를 JSON 형태로 직렬화
JSON 문자열
References ByRace, CrewDatabase.RaceStat.GetMaxSkillValueDictionary.
bool CrewDatabase.DeserializeFromJson(string json)
JSON 문자열에서 데이터베이스 데이터 복원
json JSON 문자열 성공 여부
References ByRace, CrewDatabase.RaceStat.initialPilotSkill, raceStats, raceStatsByType, CrewDatabase.RaceStat.SetMaxSkillValuesFromDictionary.
void CrewDatabase.OnValidate()
Unity 이벤트: 값이 변경될 때마다 호출됨
References InitializeDefaultStats, raceStats.
void CrewDatabase.OnEnable()
Unity 이벤트: ScriptableObject가 로드될 때 호출됨
References InitializeDefaultStats, InitializeDictionary, raceStats.