EquipmentUIHandler
GameObject EquipmentUIHandler.itemBuyPanel
장비 구매 팝업 패널입니다.
Referenced by OnClickBack, OnClickBuy, CrewUIHandler.ResetEquipmentUI, ShowItemTip, Start.
GameObject EquipmentUIHandler.allCrewPanel
보유 중인 전체 선원 나타내는 패널
Referenced by OnClickBack, OnClickBackPersonal, OnClickBuy, OnClickComplete, OnClickStatApplyButton, OnCrewIconSelected.
GameObject EquipmentUIHandler.allEquipmentPanel
보유 중인 전체 장비 나타내는 패널
Referenced by OnClickBack, OnClickBuy, OnClickComplete.
GameObject EquipmentUIHandler.crewDetailPanel
개별 선원 디테일 정보 표시
Referenced by OnClickBackPersonal, OnClickStatApplyButton, OnCrewIconSelected, PopulateCrewIcons.
Ship EquipmentUIHandler.playerShip
플레이어 함선
Referenced by OnClickBuy, OnClickStatApplyButton, PopulateCrewIcons, PopulateEquipmentIcons.
Image EquipmentUIHandler.tipItemImage
팝업 내 장비 아이콘 이미지입니다.
TextMeshProUGUI EquipmentUIHandler.tipItemName
팝업 내 장비 이름 텍스트입니다.
TextMeshProUGUI EquipmentUIHandler.tipItemPrice
팝업 내 장비 가격 텍스트입니다.
TextMeshProUGUI EquipmentUIHandler.tipItemDetails
팝업 내 장비 설명 텍스트입니다.
TextMeshProUGUI EquipmentUIHandler.tipCurrencyText
팝업 내 현재 보유 재화 표시 텍스트입니다.
Button EquipmentUIHandler.buyButton
구매 버튼입니다.
Button EquipmentUIHandler.backButton
뒤로 가기 버튼입니다.
Color EquipmentUIHandler.purchasedButtonColor
장비 구매 완료 시 버튼에 적용할 색상입니다.
Color EquipmentUIHandler.defaultButtonColor
장비 버튼의 기본 색상입니다.
EquipmentItem EquipmentUIHandler.currentSelectedItem
현재 선택된 장비 데이터입니다.
Referenced by OnClickBuy, ShowItemTip.
EquipmentButton EquipmentUIHandler.currentSelectedButton
현재 선택된 장비 버튼입니다.
Referenced by ShowItemTip.
HashSet<EquipmentItem> EquipmentUIHandler.purchasedItems
구매한 장비 목록입니다. 중복 구매를 방지하기 위해 HashSet으로 관리됩니다.
Referenced by OnClickBuy, ShowItemTip.
CrewMember EquipmentUIHandler.selectedCrew
장비 착용할 선택된 선원
Referenced by GetCurrentEquippedByType, OnClickPendingUnEquip, OnClickStatApplyButton, OnCrewIconSelected, OnEquipmentIconSelected, RefreshCrewDetailPanel.
int EquipmentUIHandler.currentCurrency
임시로 관리하는 플레이어 보유 재화(COMAs)입니다.
Referenced by OnClickBuy, OnEnable, ShowItemTip.
GameObject EquipmentUIHandler.crewIconPrefab
선원 리스트 UI에서 각 선원의 Prefab
Referenced by PopulateCrewIcons.
GameObject EquipmentUIHandler.equipmentIconPrefab
장비 Prefab
Referenced by PopulateEquipmentIcons.
Transform EquipmentUIHandler.crewContentParent
각 crew가 설치될 content
Referenced by PopulateCrewIcons.
Transform EquipmentUIHandler.equipmentContent
각 장비가 설치될 content
Referenced by PopulateEquipmentIcons.
Image EquipmentUIHandler.detailCrewImage
개별 선원 디테일 UI에서 선원 이미지
Image EquipmentUIHandler.detailWeaponImage
개별 선원 디테일 UI에서 무기 장비 이미지
Image EquipmentUIHandler.detailShieldImage
개별 선원 디테일 UI에서 방어구 장비 이미지
Image EquipmentUIHandler.detailAssistantImage
개별 선원 디테일 UI에서 보조 장비 이미지
Button EquipmentUIHandler.globalCompleteButton
완료 버튼 (global용)
Button EquipmentUIHandler.personalBackButton
뒤로 가기 버튼 (personal용)
Sprite EquipmentUIHandler.noneIcon
착용 중인 장비 없음을 나타내는 icon
Referenced by OnCrewIconSelected, RefreshCrewDetailPanel.
GameObject EquipmentUIHandler.appliedTagPrefab
장비 적용됨 알리는 tag
Referenced by PopulateCrewIcons.
GameObject EquipmentUIHandler.statComparePanel
스텟 비교 패널
TextMeshProUGUI EquipmentUIHandler.baseStatsText
기존 스텟
TextMeshProUGUI EquipmentUIHandler.newStatsText
장비 착용, 미착용 후 변화 스텟
TextMeshProUGUI EquipmentUIHandler.statDiffText
차이
GameObject EquipmentUIHandler.midArrows
변화 표시 오브젝트 (우측 화살표)
Referenced by OnClickStatApplyButton, ShowStatComparison.
List<GameObject> EquipmentUIHandler.activeAppliedTags
생성된 장비 적용 태그 추적 리스트
Referenced by OnClickComplete, PopulateCrewIcons.
EquipmentItem EquipmentUIHandler.pendingEquipItem
해제하는 장비
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
EquipmentType EquipmentUIHandler.pendingEquipType
해제하는 장비 타입
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
bool EquipmentUIHandler.isPendingRemoval
장비 해제 완료 여부
Referenced by OnClickPendingUnEquip, OnClickStatApplyButton, OnEquipmentIconSelected.
Image [] EquipmentUIHandler.changeArrows
Image EquipmentUIHandler.beforeEquipImage
Image EquipmentUIHandler.afterEquipImage
Sprite EquipmentUIHandler.increaseSprite
Sprite EquipmentUIHandler.decreaseSprite
Sprite EquipmentUIHandler.noChangeSprite
void EquipmentUIHandler.Start()
시작 시 장비 팝업을 비활성화합니다.
References itemBuyPanel.
void EquipmentUIHandler.OnEnable()
현재 재화 보유량 업데이트
References currentCurrency.
void EquipmentUIHandler.PopulateCrewIcons(EquipmentItem eq)
보유 중인 모든 선원 리스트 띄우기
eq
References activeAppliedTags, Ship.allCrews, appliedTagPrefab, crewContentParent, crewDetailPanel, crewIconPrefab, CrewIconButton.Initialize, OnCrewIconSelected, playerShip.
Referenced by OnClickBuy, OnClickStatApplyButton.
void EquipmentUIHandler.PopulateEquipmentIcons()
보유 중인 전체 장비 리스트 갱신
References equipmentContent, equipmentIconPrefab, OnEquipmentIconSelected, playerShip, Ship.unUsedItems.
Referenced by OnClickBuy, OnClickStatApplyButton.
void EquipmentUIHandler.OnCrewIconSelected(CrewMember crew)
선원 선택됨
crew
References allCrewPanel, crewDetailPanel, noneIcon, selectedCrew, CrewBase.spriteRenderer.
Referenced by PopulateCrewIcons.
void EquipmentUIHandler.OnEquipmentIconSelected(EquipmentItem item)
장비 선택됨 (장비 착용, 미착용 등 스텟 비교)
item
References CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, CrewMember.GetCombinedStats, CrewMember.GetStatsIfEquipped, isPendingRemoval, pendingEquipItem, pendingEquipType, selectedCrew, ShowStatComparison.
Referenced by PopulateEquipmentIcons.
void EquipmentUIHandler.ShowStatComparison(EquipmentStats before, EquipmentStats after)
장비 착용 / 해제 비교
before after
References midArrows.
Referenced by OnClickPendingUnEquip, OnEquipmentIconSelected.
EquipmentItem EquipmentUIHandler.GetCurrentEquippedByType(EquipmentType type)
현재 착용 중인 장비 반환
type
References CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, selectedCrew.
Referenced by OnClickStatApplyButton.
void EquipmentUIHandler.RefreshCrewDetailPanel()
선원 개인 디테일 패널 정보 갱신
References CrewMember.GetCombinedStats, noneIcon, selectedCrew.
Referenced by OnClickStatApplyButton.
void EquipmentUIHandler.ShowItemTip(EquipmentItem eqItem, EquipmentButton eqButton)
장비 버튼 클릭 시 팝업을 띄우고 UI 요소를 채웁니다. 이미 구매했거나 재화 부족 시 구매 불가 처리도 포함됩니다.
eqItem 선택된 장비 아이템. eqButton 선택된 장비 버튼.
References currentCurrency, currentSelectedButton, currentSelectedItem, itemBuyPanel, purchasedItems.
Referenced by EquipmentButton.OnClickItem.
void EquipmentUIHandler.OnClickBuy()
구매 버튼 클릭 시 호출됩니다. 재화를 차감하고, 장비 효과를 적용하며, 버튼 색상도 변경됩니다.
References allCrewPanel, allEquipmentPanel, currentCurrency, currentSelectedItem, EquipmentManager.Instance, itemBuyPanel, playerShip, PopulateCrewIcons, PopulateEquipmentIcons, EquipmentManager.PurchaseAndEquipGlobal, purchasedItems, Ship.unUsedItems.
void EquipmentUIHandler.OnClickBack()
장비 구매 팝업을 닫습니다.
References allCrewPanel, allEquipmentPanel, itemBuyPanel.
void EquipmentUIHandler.OnClickPendingUnEquip(EquipmentType type)
장비 해제 예비 작업
type
References EquipmentManager.defaultAssistant, EquipmentManager.defaultShield, EquipmentManager.defaultWeapon, CrewBase.equippedAssistant, CrewBase.equippedShield, CrewBase.equippedWeapon, CrewMember.GetCombinedStats, EquipmentManager.GetDefaultEquipment, CrewMember.GetStatsIfEquipped, EquipmentManager.Instance, isPendingRemoval, pendingEquipItem, pendingEquipType, selectedCrew, ShowStatComparison.
void EquipmentUIHandler.OnClickUnEquipWeaponSlot()
void EquipmentUIHandler.OnClickUnEquipShieldSlot()
void EquipmentUIHandler.OnClickUnEquipAssistantSlot()
void EquipmentUIHandler.OnClickStatApplyButton()
ok 버튼 눌러 장비를 선원에게 직접 적용 / 해제
References allCrewPanel, crewDetailPanel, EquipmentManager.defaultAssistant, GetCurrentEquippedByType, EquipmentManager.Instance, isPendingRemoval, midArrows, pendingEquipItem, pendingEquipType, playerShip, PopulateCrewIcons, PopulateEquipmentIcons, EquipmentManager.PurchaseAndEquipPersonal, RefreshCrewDetailPanel, selectedCrew, Ship.unUsedItems.
void EquipmentUIHandler.OnClickComplete()
선원에 장비 적용 마침
References activeAppliedTags, allCrewPanel, allEquipmentPanel.
void EquipmentUIHandler.OnClickBackPersonal()
선원 개인 디테일 panel 끄기
References allCrewPanel, crewDetailPanel.