RaceButtonController
CrewRace RaceButtonController.raceType
종족 타입
Referenced by CrewUIHandler.OnRaceButtonClicked, ShowTooltip.
CrewRaceStat RaceButtonController.crewRaceStat
종족 별 기본 스텟
Referenced by ShowTooltip.
GameObject RaceButtonController.raceTooltipPrefab
종족 선택 시 호출될 tooltip
Referenced by ShowTooltip.
Color RaceButtonController.highlightColor
GameObject RaceButtonController.activeTooltip
활성화 된 race tooltip
Referenced by HideTooltip, ShowTooltip.
Canvas RaceButtonController.mainCanvas
작업에 필요한 mainCanvas
Referenced by ShowTooltip.
Button RaceButtonController.button
버튼 highlight를 위한 참조
Referenced by SetHighlighted.
Color RaceButtonController.normalColor
void RaceButtonController.Awake()
void RaceButtonController.ShowTooltip()
실제 tooltip 게임 화면에 띄우기
References activeTooltip, crewRaceStat, mainCanvas, raceTooltipPrefab, raceType, RaceTooltip.SetupTooltip.
Referenced by OnPointerEnter.
void RaceButtonController.HideTooltip()
tooltip 가리기
References activeTooltip.
Referenced by OnPointerExit.
void RaceButtonController.OnPointerEnter(PointerEventData eventData)
마우스가 버튼에 들어왔을 때(hover)
eventData
References ShowTooltip.
void RaceButtonController.OnPointerExit(PointerEventData eventData)
마우스가 버튼에서 나갔을 때
eventData
References HideTooltip.
void RaceButtonController.OnPointerClick(PointerEventData eventData)
버튼 클릭
eventData
References CrewUIHandler.Instance, CrewUIHandler.OnRaceButtonClicked.
void RaceButtonController.SetHighlighted(bool highlighted)
현재 버튼이 선택되었을 때(하이라이트)
highlighted
References button.
Referenced by CrewUIHandler.OnRaceButtonClicked, CrewUIHandler.ResetCrewCreateUI.