WeaponSystem
bool WeaponSystem.autoFireEnabled
자동 발사 활성화 여부
Referenced by IsAutoFireEnabled, SetAutoFireEnabled, Update.
override void WeaponSystem.Update(float deltaTime)
매 프레임마다 호출되어 각 무기의 쿨다운 상태를 업데이트합니다.
deltaTime 경과 시간 (초).
References Ship.allWeapons, autoFireEnabled, ShipSystem.GetShipStat, ShipWeapon.IsReady, ShipSystem.parentShip, ShipWeapon.TryFire, UpdateWeaponCooldownWithBonus.
Referenced by Ship.Update.
void WeaponSystem.SetAutoFireEnabled(bool enabled)
자동 발사 활성화/비활성화
enabled 자동 발사 여부
References autoFireEnabled.
Referenced by CombatManager.Start.
bool WeaponSystem.IsAutoFireEnabled()
자동 발사 상태 반환
자동 발사 활성화 여부
References autoFireEnabled.
int WeaponSystem.FireWeapon(int weaponIndex=-1)
준비된 무기가 있는지 확인하고 발사를 시도합니다.
weaponIndex 발사할 무기의 인덱스. -1이면 준비된 첫 번째 무기를 발사 발사된 무기 수
References Ship.allWeapons, FireAllReadyWeapons, ShipSystem.parentShip, ShipWeapon.TryFire.
int WeaponSystem.FireAllReadyWeapons()
준비된 모든 무기를 발사합니다.
발사된 무기 수
References Ship.allWeapons, ShipSystem.parentShip, ShipWeapon.TryFire.
Referenced by FireWeapon.
int WeaponSystem.FireWeaponsByType(ShipWeaponType weaponType)
특정 타입의 무기만 발사합니다.
weaponType 발사할 무기 타입 발사된 무기 수
References Ship.allWeapons, ShipWeapon.GetWeaponType, ShipSystem.parentShip, ShipWeapon.TryFire.
ShipWeapon WeaponSystem.AddWeapon(int weaponId, Vector2Int gridPosition, ShipWeaponAttachedDirection direction)
새로운 무기를 시스템에 추가합니다.
weaponData 추가할 무기 데이터. gridPosition 추가할 그리드 좌표./param> 만들어진 새로운 무기의 참조.
References Ship.allWeapons, ShipWeapon.ApplyRotationSprite, ShipWeaponFactory.CreateWeaponInstance, Ship.GetOuterHullLevel, Ship.GetWorldPositionFromGrid, ShipSystem.parentShip, ShipWeapon.SetAttachedDirection, ShipWeapon.SetGridPosition.
ShipWeapon WeaponSystem.AddWeapon(ShipWeapon shipWeapon)
bool WeaponSystem.RemoveWeapon(ShipWeapon weapon)
float WeaponSystem.GetActualCooldown(float baseCooldown)
실제 적용될 쿨다운 시간을 계산합니다. 쿨다운 보너스를 고려하여 기본 쿨타임을 감소시킵니다.
baseCooldown 기본 쿨다운 시간. 보정된 쿨다운 시간.
References ShipSystem.GetShipStat.
float WeaponSystem.GetActualDamage(float damage)
실제 적용될 데미지를 계산합니다. 데미지 보너스를 적용하여 최종 데미지를 산출합니다.
damage 기본 데미지 값. 보정된 데미지 값.
References ShipSystem.GetShipStat.
Referenced by Ship.GetActualDamage.
List< ShipWeapon > WeaponSystem.GetWeapons()
현재 장착된 모든 무기 리스트를 반환합니다.
무기 리스트.
References Ship.allWeapons, ShipSystem.parentShip.
int WeaponSystem.GetWeaponCount()
현재 장착된 무기 수를 반환합니다.
무기 개수.
References Ship.allWeapons, ShipSystem.parentShip.
void WeaponSystem.RemoveAllWeapons()
모든 무기 삭제
References Ship.allWeapons, ShipSystem.parentShip.
ShipWeapon WeaponSystem.GetWeaponByIndex(int index)
인덱스로 무기를 가져옵니다.
index 무기 인덱스 해당 인덱스의 무기 또는 null
References Ship.allWeapons, ShipSystem.parentShip.
bool WeaponSystem.IsEveryWeaponReady()
모든 무기가 발사 가능한지 확인합니다.
발사 가능한 무기가 있으면 true
References Ship.allWeapons, ShipWeapon.IsEnabled, ShipWeapon.IsReady, ShipSystem.parentShip.
void WeaponSystem.UpdateWeaponCooldowns(float deltaTime)
모든 무기의 쿨다운을 업데이트합니다.
deltaTime 경과 시간
References Ship.allWeapons, ShipSystem.GetShipStat, ShipSystem.parentShip, UpdateWeaponCooldownWithBonus.
List< ShipWeapon > WeaponSystem.GetWeaponsByType(ShipWeaponType type)
특정 타입의 무기만 반환합니다.
type 무기 타입 해당 타입의 무기 목록
References Ship.allWeapons, ShipSystem.parentShip.
void WeaponSystem.ResetAllWeaponStats()
모든 무기의 통계 데이터를 초기화합니다.
References Ship.allWeapons, ShipSystem.parentShip, ShipWeapon.SetHits, ShipWeapon.SetTotalDamageDealt.
List< ShipWeapon > WeaponSystem.GetWeaponsByWarheadType(WarheadType warheadType)
선택한 타입의 탄두를 필요로 하는 무기 목록을 반환합니다.
warheadType 탄두 타입 해당 탄두 타입을 사용하는 무기 목록
References Ship.allWeapons, ShipSystem.parentShip.
List< ShipWeapon > WeaponSystem.GetWeaponsByEffect(ShipWeaponEffectType effectType)
void WeaponSystem.UpdateWeaponCooldownWithBonus(ShipWeapon weapon, float deltaTime, float reloadBonus)
재장전 보너스를 적용하여 무기의 쿨다운을 업데이트합니다.
weapon 업데이트할 무기 deltaTime 경과 시간 reloadBonus 재장전 보너스 (예: 1.2 = 20% 빠름)
Referenced by Update, UpdateWeaponCooldowns.