PlanetData
int PlanetData.planetId
행성 고유 ID
Referenced by CreateRandomData, EmployController.OnClickBuy.
string PlanetData.planetName
행성 이름
Referenced by SetRandomName.
PlanetRace PlanetData.planetRace
행성 종족
Referenced by CreateRandomData, SetRandomName.
ItemPlanet PlanetData.itemPlanet
무역 아이템 매칭에 필요한 행성 이름 정보
Referenced by CreateRandomData, SetItems.
Vector2 PlanetData.normalizedPosition
행성맵에 표시될 상대적인 좌표.
Referenced by SetRandomPosition.
Sprite PlanetData.currentSprite
행성 sprite
List<TradingItemData> PlanetData.itemsTier1
판매하는 티어 1 아이템 리스트
Referenced by TradeUIController.InitializeBuyPanel, SetItems.
List<TradingItemData> PlanetData.itemsTier2
판매하는 티어 2 아이템 리스트
Referenced by TradeUIController.InitializeBuyPanel, SetItems.
List<TradingItemData> PlanetData.itemsTier3
판매하는 티어 3 아이템 리스트
Referenced by TradeUIController.InitializeBuyPanel, SetItems.
int PlanetData.currentRevenue
현재까지 수익을 낸 총 판매액
Referenced by TradeUIController.BuyItem, CreateRandomData.
int PlanetData.currentFuelPrice
현재 연료 가격
Referenced by CreateRandomData.
int PlanetData.currentMissilePrice
현재 미사일 가격
int PlanetData.currentHypersonicPrice
현재 초음속탄 가격
List<RandomQuest> PlanetData.questList
현재 행성의 퀘스트 리스트.
Referenced by GameManager.CheckItemQuests, GameManager.CheckPirateQuests, FailQuest.
List<PlanetEffect> PlanetData.activeEffects
현재 적용 중인 행성 효과 데이터
Referenced by CheckEventExpirations, CreateRandomData, PrintAllEffects, RegisterPlanetEffect, ResetAllEffects.
Dictionary<ItemCategory, float> PlanetData.categoryPriceModifiers
이벤트로 변동되는 카테고리별 현재 가격 변동율 (%)
Referenced by ApplyPlanetEffectValue, GetCategoryPriceModifier, InitializeCategoryModifiers, PrintAllEffects, RemovePlanetEffectValue.
Dictionary<int, int> PlanetData.itemPriceDictionary
아이템의 현재 가격 딕셔너리
Referenced by SetItems.
EquipmentItem PlanetData.currentRandomEquipmentItem
현재 판매하고 있는 장비 아이템 (Trade 의 장비 거래 패널의 세 번째 슬롯).
bool PlanetData.isHome
ItemTierLevel PlanetData.CurrentTier
현재 해금되어있는 티어
Referenced by TradeUIController.UpdateBuyPanel.
PlanetRace PlanetData.PlanetRace
void PlanetData.CreateRandomData()
행성의 데이터를 랜덤으로 생성합니다. 게임 시작할 때 호출되며, 게임의 여러 요소가 한 쪽으로 편향되지 않게 적절한 설정이 적용.
References activeEffects, currentFuelPrice, currentRevenue, InitializeCategoryModifiers, GameManager.Instance, itemPlanet, planetId, planetRace, SetItems, SetRandomName, SetRandomPosition.
void PlanetData.LoadSprites()
string PlanetData.GetSpeciesPrefix(PlanetRace species)
종족 유형에 따라 행성 이름 접두어를 반환합니다.
species 종족 타입 종족 접두어 문자열
Referenced by SetRandomName.
void PlanetData.SetItems()
행성에서 판매하는 아이템들을 세팅합니다.
References itemPlanet, itemPriceDictionary, itemsTier1, itemsTier2, itemsTier3.
Referenced by CreateRandomData.
void PlanetData.ChangeItemPrice()
int PlanetData.GetItemPrice(int itemId)
int PlanetData.GetItemPrice(TradingItemData item)
void PlanetData.RegisterPlanetEffect(PlanetEffect effectData)
새로운 행성 효과 등록
effectData 등록할 효과 데이터
References activeEffects, ApplyPlanetEffectValue, PlanetEffect.categoryType, RemovePlanetEffectValue.
void PlanetData.CheckPirateQuests()
void PlanetData.CheckItemQuests(int itemId)
void PlanetData.CheckEventExpirations(int currentYear)
현재 이벤트 상태를 확인하고 만료된 효과를 제거합니다
currentYear 현재 게임 년도
References activeEffects, PlanetEffect.categoryType, PlanetEffect.EndYear, RemovePlanetEffectValue.
float PlanetData.GetCategoryPriceModifier(ItemCategory category)
특정 카테고리의 현재 가격 변동률 반환
category 확인할 아이템 카테고리 현재 가격 변동률 (%)
References categoryPriceModifiers.
Referenced by CalculateAdjustedPrice.
void PlanetData.ResetAllEffects()
모든 행성 효과 초기화
References activeEffects, InitializeCategoryModifiers.
int PlanetData.CalculateAdjustedPrice(int basePrice, ItemCategory category)
현재 가격 변동률을 고려하여 아이템 가격 계산
basePrice 기본 가격 category 아이템 카테고리 조정된 가격
References GetCategoryPriceModifier.
void PlanetData.PrintAllEffects()
현재 행성 효과 상태 출력 (디버깅용)
References activeEffects, categoryPriceModifiers.
void PlanetData.CheckQuestExpirations(int currentYear)
void PlanetData.ActivateQuest(RandomQuest quest)
void PlanetData.CompleteQuest(RandomQuest quest)
void PlanetData.FailQuest(RandomQuest quest)
퀘스트를 실패 처리합니다.
quest 실패할 퀘스트
References questList.
void PlanetData.TrySpawnQuest()
void PlanetData.RefreshEquipmentSelling()
void PlanetData.ChangeFuelPrice()
void PlanetData.SetPlanetRace(PlanetRace planetRace)
void PlanetData.InitializeCategoryModifiers()
카테고리별 가격 변동율 초기화
References categoryPriceModifiers.
Referenced by CreateRandomData, ResetAllEffects.
void PlanetData.SetRandomName()
행성 이름을 중복되지 않게 랜덤하게 생성합니다. (종족 접두어 + 숫자)
References GetSpeciesPrefix, planetName, planetRace.
Referenced by CreateRandomData.
void PlanetData.SetRandomPosition()
행성이 맵에 그려지는 상대적인 위치를 랜덤으로 생성. 다른 행성들과의 거리가 PlanetSpacingMin 이상 유지되도록 함.
References GameManager.Instance, GameManager.normalizedPlayerPosition, normalizedPosition.
Referenced by CreateRandomData.
void PlanetData.ApplyPlanetEffectValue(PlanetEffect effect)
행성 효과 값 적용
effect 적용할 효과
References categoryPriceModifiers, PlanetEffect.categoryType, PlanetEffect.changeAmount.
Referenced by RegisterPlanetEffect.
void PlanetData.RemovePlanetEffectValue(PlanetEffect effect)
행성 효과 값 제거
effect 제거할 효과
References categoryPriceModifiers, PlanetEffect.categoryType, PlanetEffect.changeAmount.
Referenced by CheckEventExpirations, RegisterPlanetEffect.
void PlanetData.CreateRandomQuest()