ShipValidationHelper
ValidationResult ShipValidationHelper.ValidateShipLayout(Ship ship)
함선 배치의 유효성 검사
ship
References Ship.backupCrewDatas, CheckAllRoomsPathConnectedByDoors, CheckOxygenBreathe, CheckRequiredRooms, CheckWeaponConnectivity, Ship.GetAllRooms, ValidationResult.IsValid, ValidateWeaponAttachmentDirection, ValidateWeaponPlacement.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_1_Controller.OnClickSave.
ValidationResult ShipValidationHelper.CheckOxygenBreathe(List< Room > rooms, List< BackupCrewData > crewDatas)
산소 호흡 종족 소유 여부에 따라 산소실 배치 체크
rooms crews
Referenced by ValidateShipLayout.
ValidationResult ShipValidationHelper.ValidateWeaponAttachmentDirection(Ship ship)
무기의 방향과 방 연결 상태를 검사합니다. 각 무기의 AttachedDirection에 따라 적절한 위치에 방이 있어야 합니다.
ship 검사할 함선 검증 결과
References Ship.GetAllRooms, Ship.GetAllWeapons, ShipWeapon.GetAttachedDirection, ShipWeapon.GetGridPosition, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetSize, Room< TData, TLevel >.position.
Referenced by ValidateShipLayout.
ValidationResult ShipValidationHelper.ValidateWeaponPlacement(Ship ship)
무기 설치 위치 유효성 검사 무기 우측(x 증가 방향)에 그리드 끝까지 방이나 다른 무기가 있는지 확인
ship 검사할 함선 검증 결과
References Ship.GetAllRooms, Ship.GetAllWeapons, ShipWeapon.GetGridPosition, Room< TData, TLevel >.OccupiesTile.
Referenced by ValidateShipLayout.
ValidationResult ShipValidationHelper.CheckWeaponConnectivity(Ship ship)
모든 무기가 방과 직접 또는 간접적으로 연결되어 있는지 확인합니다. BFS를 사용하여 무기와 방의 연결성을 검사합니다.
ship 검사할 함선 검증 결과
References AreAdjacent, Ship.GetAllRooms, Ship.GetAllWeapons, ShipWeapon.GetGridPosition, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetSize, IsAdjacentToRoomTiles, Room< TData, TLevel >.position.
Referenced by ValidateShipLayout.
ValidationResult ShipValidationHelper.CheckRequiredRooms(List< Room > rooms)
필수 방이 존재하는지 확인합니다.
Referenced by ValidateShipLayout.
ValidationResult ShipValidationHelper.CheckAllRoomsPathConnectedByDoors(List< Room > rooms, Vector2Int gridSize)
BFS + DFS 이용하여 방과 방의 연결성 및 이동 가능성 확인
rooms 검사할 방 목록 gridSize 그리드 크기 검증 결과
References Room< TData, TLevel >.currentRotation, DoorPosition.direction, DoorPositionMatch, GetAdjacentTile, Room< TData, TLevel >.GetCurrentLevel, RoomData< T >.GetDoorPositionsWithDirection, GetOppositeDoorDirection, GetOrCreateVisualizer, DoorPosition.position, Room< TData, TLevel >.position.
Referenced by ValidateShipLayout.
bool ShipValidationHelper.AreAdjacent(Vector2Int pos1, Vector2Int pos2, Vector2Int gridSize)
두 위치가 서로 인접해 있는지 확인합니다.
pos1 첫 번째 위치 pos2 두 번째 위치 gridSize 그리드 크기 인접 여부
Referenced by CheckWeaponConnectivity.
bool ShipValidationHelper.IsAdjacentToRoomTiles(Vector2Int pos, HashSet< Vector2Int > roomTiles, Vector2Int gridSize)
위치가 방 타일에 인접해 있는지 확인합니다.
pos 확인할 위치 roomTiles 방이 점유하는 타일 집합 gridSize 그리드 크기 인접 여부
Referenced by CheckWeaponConnectivity.
bool ShipValidationHelper.DoorPositionMatch(Vector2Int doorPosA, DoorDirection dirA, Vector2Int doorPosB, DoorDirection dirB, Vector2Int gridSize)
각 방의 문이 위치한 타일에 대해 문으로 이동 가능하도록 인접했는지 여부
doorPosA 현재 방 문 위치 dirA 현재 방 문 방향 doorPosB 반대 방 문 위치 dirB 반대 방 문 방향 gridSize 그리드 크기
References GetDirectionOffset.
Referenced by CheckAllRoomsPathConnectedByDoors.
Vector2Int ShipValidationHelper.GetDirectionOffset(DoorDirection dir)
문 방향에 따른 그리드 타일 위치 offset 세팅
dir
Referenced by DoorPositionMatch.
Vector2Int ShipValidationHelper.GetAdjacentTile(Vector2Int pos, DoorDirection dir)
인접 타일 위치 반환
pos dir
Referenced by CheckAllRoomsPathConnectedByDoors.
DoorDirection ShipValidationHelper.GetOppositeDoorDirection(DoorDirection dir)
현재 방 문의 반대 방향 반환
dir 현재 방의 문 방향
Referenced by CheckAllRoomsPathConnectedByDoors.
static ShipPathDebugVisualizer ShipValidationHelper.GetOrCreateVisualizer()
디버깅 시각화 오브젝트 생성 (삭제할 예정)
Referenced by CheckAllRoomsPathConnectedByDoors.