BlueprintInventoryUI
List<RoomData> BlueprintInventoryUI.allRooms
모든 방 종류
Referenced by FilterByCategory.
Transform BlueprintInventoryUI.contentRoot
모든 방 콘텐츠 넣을 공간
Referenced by FilterByCategory.
GameObject BlueprintInventoryUI.roomButtonPrefab
설치를 위한 방 버튼 prefab
Referenced by FilterByCategory.
BlueprintRoomDragHandler BlueprintInventoryUI.dragHandler
방 드래그 관리 handler
Referenced by FilterByCategory.
BlueprintCategoryButtonHandler BlueprintInventoryUI.categoryButtonHandler
카테고리 분류 handler
Referenced by Customize_1_Controller.OnEnable, Start.
void BlueprintInventoryUI.Start()
방 UI에 대해 항상 Essential 카테고리로 초기화
References categoryButtonHandler, FilterByCategory, BlueprintCategoryButtonHandler.SetButtonState.
void BlueprintInventoryUI.FilterByCategory(RoomCategory category)
카테고리 별 분류 후 인벤토리에 방 호출
category
References allRooms, RoomData< T >.RoomLevel.category, contentRoot, dragHandler, RoomData< T >.GetAllLevels, RoomInventoryButton.Initialize, roomButtonPrefab.
Referenced by Customize_1_Controller.OnEnable, BlueprintCategoryButtonHandler.ShowAuxiliary, BlueprintCategoryButtonHandler.ShowEssential, BlueprintCategoryButtonHandler.ShowEtc, BlueprintCategoryButtonHandler.ShowLiving, BlueprintCategoryButtonHandler.ShowStorage, Start.