CameraZoomController
float CameraZoomController.zoomSpeed
카메라 줌 속도
Referenced by HandleZoom.
float CameraZoomController.minSize
카메라 최대 확대 줌인
Referenced by HandleZoom.
float CameraZoomController.maxSize
카메라 최소치 줌 아웃
Referenced by HandleZoom.
Camera CameraZoomController.cam
조정할 메인 카메라
Referenced by CameraMove, HandleZoom, isMouseOverRoomOrGrid, OnEnable.
Ship CameraZoomController.targetShip
float CameraZoomController.lastZoomSize
가장 최신 줌 사이즈
Referenced by Customize_1_Controller.CenterCameraToBP, CustomizeShipUIHandler.CenterCameraToBP, HandleZoom.
void CameraZoomController.OnEnable()
함선 위치로 카메라 세팅, 줌 사이즈 = 5
References cam.
IEnumerator CameraZoomController.CameraCoroutine()
void CameraZoomController.Update()
설계도 작업 시에만 카메라 컨트롤 적용
References CameraMove, HandleZoom.
void CameraZoomController.HandleZoom()
화면을 확대/축소합니다. 마우스 휠 스크롤을 이용하여 확대/축소 가능하며 최대 확대 거리 : 4.5, 최대 축소 거리 : 15 입니다.
References cam, IsMouseInGameView, isMouseOverRoomOrGrid, lastZoomSize, maxSize, minSize, zoomSpeed.
Referenced by Update.
void CameraZoomController.CameraMove()
카메라 이동 구현 및 이동 제한
References cam, CheckBounds.
Referenced by Update.
bool CameraZoomController.IsMouseInGameView()
유저의 마우스가 GameView 내에 위치한지 확인합니다.
Referenced by HandleZoom.
bool CameraZoomController.isMouseOverRoomOrGrid()
방 ui 위에 있을 때는 줌 가능
References cam.
Referenced by HandleZoom.
bool CameraZoomController.CheckBounds(Vector3 simulatePos)
카메라 화면 이동 가능 영역을 제한합니다.
Referenced by CameraMove.
Vector3 CameraZoomController.GetCameraStartPositionToOriginShip()
기존 소유 함선을 이루는 방들의 중심으로 카메라 시작 위치 보정
References Ship.GetAllRooms, Ship.GetAllWeapons, ShipWeapon.GetGridPosition, Room< TData, TLevel >.GetOccupiedTiles, Ship.GetWorldPositionFromGrid.