ShipTemplateSaver
TMP_InputField ShipTemplateSaver.templateNameInput
탬플릿 이름을 입력받는 필드
Referenced by SaveShipTemplate, Start, UpdateSaveButtonState.
TMP_Text ShipTemplateSaver.feedbackText
저장 결과 피드백을 표시할 텍스트
Referenced by ClearFeedback, ShowFeedback.
Button ShipTemplateSaver.saveButton
저장 버튼
Referenced by Start, UpdateSaveButtonState.
BlueprintShip ShipTemplateSaver.targetBlueprintShip
블루프린트 함선 참조
Referenced by SaveShipTemplate, UpdateSaveButtonState.
Ship ShipTemplateSaver.playerShip
플레이어 함선 참조 (템플릿 로드 시 사용)
Referenced by LoadTemplate, SaveShipTemplate.
GridPlacer ShipTemplateSaver.gridPlacer
그리드 플레이서 참조
GameObject ShipTemplateSaver.templateListPanel
템플릿 목록 패널
Referenced by HideTemplateList, ShowTemplateList, Start.
Transform ShipTemplateSaver.templateListContent
템플릿 목록 콘텐츠 영역
Referenced by AddTemplateItem.
GameObject ShipTemplateSaver.templateItemPrefab
템플릿 아이템 프리팹
Referenced by AddTemplateItem.
Button ShipTemplateSaver.listButton
목록 버튼
Referenced by Start.
Button ShipTemplateSaver.closeListButton
닫기 버튼
Referenced by Start.
Button ShipTemplateSaver.refreshButton
새로고침 버튼
Referenced by Start.
readonly string ShipTemplateSaver.templateSavePath
템플릿 저장 경로 (기본값)
Referenced by EnsureTemplateSaveDirectory, GetTemplateFilePath, RefreshTemplateList.
List<GameObject> ShipTemplateSaver.activeTemplateItems
활성화된 템플릿 목록 아이템
Referenced by AddTemplateItem, ClearTemplateList.
void ShipTemplateSaver.Start()
초기화
References closeListButton, EnsureTemplateSaveDirectory, HideTemplateList, listButton, OnTemplateNameChanged, refreshButton, RefreshTemplateList, saveButton, SaveShipTemplate, ShowTemplateList, templateListPanel, templateNameInput, UpdateSaveButtonState.
void ShipTemplateSaver.EnsureTemplateSaveDirectory()
템플릿 저장 디렉토리 확인 및 생성
References templateSavePath.
Referenced by Start.
void ShipTemplateSaver.OnTemplateNameChanged(string newName)
템플릿 이름 변경 이벤트
References UpdateSaveButtonState.
Referenced by Start.
void ShipTemplateSaver.UpdateSaveButtonState()
저장 버튼 상태 업데이트
References saveButton, targetBlueprintShip, templateNameInput.
Referenced by OnTemplateNameChanged, Start, Update.
void ShipTemplateSaver.Update()
업데이트 호출마다 상태 검사
References UpdateSaveButtonState.
string ShipTemplateSaver.GetTemplateFilePath(string templateName)
템플릿 파일 경로 생성
templateName 템플릿 이름 전체 파일 경로
References templateSavePath.
Referenced by DeleteTemplate, LoadTemplate, SaveShipTemplate.
void ShipTemplateSaver.ClearTemplateList()
기존 템플릿 목록 아이템 제거
References activeTemplateItems.
Referenced by RefreshTemplateList.
void ShipTemplateSaver.AddTemplateItem(string templateName)
템플릿 목록 아이템 추가
templateName 템플릿 이름
References activeTemplateItems, DeleteTemplate, LoadTemplate, templateItemPrefab, templateListContent.
Referenced by RefreshTemplateList.
void ShipTemplateSaver.ShowFeedback(string message)
피드백 메시지 표시
message 표시할 메시지
References feedbackText.
Referenced by DeleteTemplate, LoadTemplate, RefreshTemplateList, SaveShipTemplate.
void ShipTemplateSaver.ClearFeedback()
피드백 메시지 지우기
References feedbackText.
void ShipTemplateSaver.SaveShipTemplate()
함선 템플릿 저장
References GetTemplateFilePath, playerShip, Ship.ReplaceShipFromBlueprint, ShowFeedback, targetBlueprintShip, templateNameInput, Ship.UpdateOuterHullVisuals.
Referenced by Start.
void ShipTemplateSaver.ShowTemplateList()
템플릿 목록 표시
References RefreshTemplateList, templateListPanel.
Referenced by Start.
void ShipTemplateSaver.HideTemplateList()
템플릿 목록 숨기기
References templateListPanel.
Referenced by LoadTemplate, Start.
void ShipTemplateSaver.RefreshTemplateList()
템플릿 목록 새로고침
References AddTemplateItem, ClearTemplateList, ShowFeedback, templateSavePath.
Referenced by DeleteTemplate, ShowTemplateList, Start.
void ShipTemplateSaver.LoadTemplate(string templateName)
템플릿 로드하여 함선에 적용
templateName 템플릿 이름
References GetTemplateFilePath, HideTemplateList, playerShip, ShowFeedback.
Referenced by AddTemplateItem.
void ShipTemplateSaver.DeleteTemplate(string templateName)
템플릿 삭제
templateName 삭제할 템플릿 이름
References GetTemplateFilePath, RefreshTemplateList, ShowFeedback.
Referenced by AddTemplateItem.