RoomDatabase
List<RoomDataEntry> RoomDatabase.roomEntries
List<StorageRoomDataEntry> RoomDatabase.storageRoomEntries
List<LifeSupportRoomDataEntry> RoomDatabase.lifeSupportRoomEntries
List<CrewQuartersDataEntry> RoomDatabase.crewQuartersDataEntries
Dictionary<RoomType, RoomData> RoomDatabase.roomDataMap
Dictionary<StorageType, Dictionary<StorageSize, StorageRoomBaseData> > RoomDatabase.storageDataMap
Dictionary<LifeSupportRoomType, LifeSupportRoomData> RoomDatabase.lifeSupportDataMap
Dictionary<CrewQuartersRoomSize, CrewQuartersRoomData> RoomDatabase.crewQuartersDataMap
void RoomDatabase.Initialize()
모든 딕셔너리 초기화
References InitializeLifeSupportDataMap, InitializeRoomDataMap, InitializeStorageDataMap.
Referenced by RoomFactory.InitializeRoomDatabase.
RoomData RoomDatabase.GetRoomData(RoomType roomType)
방 유형에 해당하는 데이터 반환
References InitializeRoomDataMap.
Referenced by RoomFactory.GetRoomData.
StorageRoomBaseData RoomDatabase.GetStorageRoomData(StorageType storageType, StorageSize size)
창고 데이터 반환
References InitializeStorageDataMap.
Referenced by RoomFactory.GetStorageRoomData.
LifeSupportRoomData RoomDatabase.GetLifeSupportRoomData(LifeSupportRoomType facilityType)
생활시설 데이터 반환
References InitializeLifeSupportDataMap.
Referenced by RoomFactory.GetLifeSupportRoomData.
CrewQuartersRoomData RoomDatabase.GetCrewQuartersRoomData(CrewQuartersRoomSize size)
List< RoomData > RoomDatabase.GetAllRoomData()
모든 방 데이터 반환
void RoomDatabase.InitializeRoomDataMap()
일반 방 데이터 맵 초기화
Referenced by GetRoomData, Initialize.
void RoomDatabase.InitializeStorageDataMap()
창고 데이터 맵 초기화
Referenced by GetStorageRoomData, Initialize.
void RoomDatabase.InitializeLifeSupportDataMap()
생활시설 데이터 맵 초기화
Referenced by GetLifeSupportRoomData, Initialize.
void RoomDatabase.InitializeCrewQuartersDataMap()