RTSSelectionManager
Texture2D RTSSelectionManager.selectionTexture
드래그 선택 시 표시할 텍스처입니다.
Referenced by DrawScreenRect, DrawScreenRectBorder.
Vector2 RTSSelectionManager.dragStartPos
드래그 시작 위치입니다.
Referenced by OnGUI, SelectMultipleCrew, Update.
Vector2 RTSSelectionManager.dragEndPos
드래그 종료 위치입니다.
Referenced by Update.
float RTSSelectionManager.clickThreshold
단일 클릭 임계값
Referenced by Update.
List<CrewMember> RTSSelectionManager.selectedCrew
선택된 선원 리스트
Referenced by CleanUpSelectedCrew, DeselectAll, CrewMember.Die, IssueMoveCommand, Select, SelectMultipleCrew, SelectSingleCrew, CrewMember.TeleportAfterDelay.
float RTSSelectionManager.tmpEquipmentAttack
임시 장비 공격력 변수
Ship RTSSelectionManager.playerShip
유저 함선
Referenced by GetMovementValidatorForCrew, GetPathfinderForCrew, MoveForCombat, RefreshMovementData, Start.
CrewPathfinder RTSSelectionManager.crewPathfinder
선원 경로 계산기
Referenced by GetPathfinderForCrew, RefreshMovementData.
CrewMovementValidator RTSSelectionManager.movementValidator
선원 이동 가능 검사기
Referenced by GetMovementValidatorForCrew, RefreshMovementData.
Ship RTSSelectionManager.enemyShip
적 함선
Referenced by GetMovementValidatorForCrew, GetPathfinderForCrew, RefreshMovementData.
CrewPathfinder RTSSelectionManager.enemyPathFinder
적 선원 경로 계산기
Referenced by GetPathfinderForCrew, RefreshMovementData.
CrewMovementValidator RTSSelectionManager.enemyMovementValidator
적 선원 이동 가능 검사기
Referenced by GetMovementValidatorForCrew, RefreshMovementData.
GameObject RTSSelectionManager.combatManager
전투 담당 매니저
Material RTSSelectionManager.outlineMaterial
Material RTSSelectionManager.defaultMaterial
bool RTSSelectionManager.isDragging
드래그 중인지 여부
Referenced by OnGUI, Update.
GraphicRaycaster RTSSelectionManager.combatUIGRC
전투 시 필요 canvas
RTSSelectionManager RTSSelectionManager.Instance
싱글톤 instance
Referenced by CrewMember.Attack, CombatManager.Awake, Awake, SceneChanger.BackToTheHome, CrewMember.Die, CrewMember.DontTouchMe, CrewMember.FollowPathCoroutine, CrewMember.LookAtMe, CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, CombatManager.Start, CrewMember.TeleportAfterDelay, EnemyController.Update.
void RTSSelectionManager.Awake()
싱글톤 instance 초기화
References Instance.
IEnumerator RTSSelectionManager.Start()
게임 오브젝트 연결 (RTS 이동 검사를 위한 오브젝트)
References GameManager.Instance, GameManager.playerShip, playerShip, RefreshMovementData.
void RTSSelectionManager.Update()
좌클릭 감지 - 다중 선택 시 영역 표시 우클릭 감지 - 선택한 선원 이동 명령
References BlockRTSSelection, clickThreshold, dragEndPos, dragStartPos, isDragging, SelectMultipleCrew, SelectSingleCrew.
void RTSSelectionManager.LateUpdate()
bool RTSSelectionManager.IsUIWithTagClicked(string tag)
bool RTSSelectionManager.BlockRTSSelection()
RTS 선원 선택 방지 코드
Referenced by Update.
bool RTSSelectionManager.BlockRTSNBPMove()
void RTSSelectionManager.OnGUI()
OnGUI를 이용하여 드래그 영역의 사각형 표시
References dragStartPos, DrawScreenRect, DrawScreenRectBorder, GetScreenRect, isDragging.
Rect RTSSelectionManager.GetScreenRect(Vector2 screenPosition1, Vector2 screenPosition2)
두 스크린 좌표로 사각형 영역 계산 (y좌표 보정 포함)
screenPosition1 screenPosition2
Referenced by OnGUI, SelectMultipleCrew.
void RTSSelectionManager.DrawScreenRect(Rect rect, Color color)
사각형 내부 채우기
rect color
References selectionTexture.
Referenced by OnGUI.
void RTSSelectionManager.DrawScreenRectBorder(Rect rect, float thickness, Color color)
사각형 테두리 그리기
rect thickness color
References selectionTexture.
Referenced by OnGUI.
CrewPathfinder RTSSelectionManager.GetPathfinderForCrew(CrewMember crew)
이동 경로 탐색기 설정
crew
References crewPathfinder, CrewBase.currentShip, enemyPathFinder, enemyShip, playerShip.
Referenced by IssueMoveCommand, MoveForCombat.
CrewMovementValidator RTSSelectionManager.GetMovementValidatorForCrew(CrewMember crew)
이동 가능 검사기 설정
crew
References CrewBase.currentShip, enemyMovementValidator, enemyShip, movementValidator, playerShip.
Referenced by IssueMoveCommand, MoveForCombat.
void RTSSelectionManager.SetOutline(CrewMember crew, bool onoff)
crew의 스프라이트 렌더러에 onoff값에 따라 Material을 변경하며 외곽선 효과를 준다.
crew onoff
Referenced by DeselectAll, Select, SelectMultipleCrew, SelectSingleCrew.
void RTSSelectionManager.SetGRC(GraphicRaycaster GRC)
void RTSSelectionManager.DeselectAll()
선택한 선원 모두 해제
References selectedCrew, SetOutline.
Referenced by Select, SelectSingleCrew.
void RTSSelectionManager.SelectSingleCrew()
단일 선원 선택
References DeselectAll, CrewMember.GetCurrentTile, CrewBase.isPlayerControlled, selectedCrew, SetOutline.
Referenced by Update.
void RTSSelectionManager.SelectMultipleCrew()
영역 내 선원 다중 선택
References dragStartPos, CrewMember.GetCurrentTile, GetScreenRect, CrewBase.isPlayerControlled, CrewBase.position, selectedCrew, SetOutline.
Referenced by Update.
void RTSSelectionManager.CleanUpSelectedCrew()
죽은 선원을 선택된 선원 리스트에서 제거 (갱신)
References selectedCrew.
void RTSSelectionManager.RefreshMovementData()
RTS 이동을 위한 기여 오브젝트 초기화
References crewPathfinder, enemyMovementValidator, enemyPathFinder, enemyShip, Ship.GetAllRooms, CrewMovementValidator.Initialize, movementValidator, playerShip.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, CombatManager.Start, Start.
void RTSSelectionManager.IssueMoveCommand(Room targetRoom=null, CrewMember crewByEnemyController=null)
선택된 선원들을 목적지 방의 우선순위 타일로 최단 경로 기반 배정 후 이동시킵니다.
targetRoom 목적지 방 crewByEnemyController 적 선원이 호출한 이동 명령일 경우 true
References CrewBase.currentRoom, CrewBase.currentShip, CrewPathfinder.FindPathToTile, CrewMember.Freeze, CrewMember.GetCurrentTile, CrewMember.GetCurrentTilePriorityIndex, GetMovementValidatorForCrew, GetPathfinderForCrew, GameManager.Instance, CrewBase.isAlive, CrewMovementValidator.IsTileWalkable, GameManager.playerShip, CrewMember.reservedRoom, selectedCrew, CrewMember.TeleportAfterDelay.
Referenced by EnemyController.Update.
void RTSSelectionManager.MoveForCombat(CrewMember readyCombatCrew)
같은 방 내에 적이 있다면 공격 AI
readyCombatCrew
References CrewBase.currentRoom, CrewPathfinder.FindPathToTile, CrewSystem.GetCrews, CrewMember.GetCurrentTile, GetMovementValidatorForCrew, GetPathfinderForCrew, CrewBase.isAlive, CrewBase.isMoving, CrewBase.isPlayerControlled, CrewMovementValidator.IsTileWalkable, playerShip.
Referenced by CrewMember.Attack, CrewMember.DontTouchMe, CrewMember.FollowPathCoroutine, CrewMember.LookAtMe, CrewMember.TeleportAfterDelay, EnemyController.Update.
void RTSSelectionManager.Select(CrewMember crew)
선원 리스트 UI에서 선원 선택
crew
References DeselectAll, CrewMember.GetCurrentTile, selectedCrew, SetOutline.
bool RTSSelectionManager.CallCombatManager(out CombatManager combat)