RoomData
List<T> RoomData< T >.RoomLevels
레벨별 방 데이터 리스트.
Referenced by RoomData< T >.CheckIfNeedsInitialization, RoomData< T >.GetAllLevels, RoomData< T >.GetTypedRoomData.
List< RoomLevel > RoomData< T >.GetAllLevels()
이 RoomData에 포함된 모든 레벨을 반환합니다.
Referenced by BlueprintInventoryUI.FilterByCategory.
RoomLevel RoomData< T >.GetRoomDataByLevel(int level)
주어진 레벨에 해당하는 RoomLevel 데이터를 반환합니다. 각 파생 클래스에서 구현해야 합니다.
level 조회할 레벨 번호. RoomLevel 데이터.
Referenced by Ship.AddRoom, Ship.AddRoom, GridPlacer.CanPlaceRoom, RoomData< T >.GetDoorPositionsWithDirection, Room< TData, TLevel >.GetHealthPercentage, Room< TData, TLevel >.GetMaxHitPoints, Room< TData, TLevel >.GetOccupiedTiles, Room< TData, TLevel >.GetPowerConsumption, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, Room< TData, TLevel >.GetSize, Room< TData, TLevel >.GetStatContributions, Ship.GetTotalShipValue, Room< TData, TLevel >.Initialize, BlueprintRoom.Initialize, GridPlacer.PlacePreviewRoom, GridPlacer.PlaceRoom, Room< TData, TLevel >.Repair, Ship.ReplaceShipFromBlueprint, BlueprintShip.SetBPHullLevel, Room< TData, TLevel >.Start, BlueprintRoomDragHandler.StartDragging, Room< TData, TLevel >.TakeDamage, Room< TData, TLevel >.UpdateRoomVisual.
RoomType RoomData< T >.GetRoomType()
List< DoorPosition > RoomData< T >.GetDoorPositionsWithDirection(int levelIndex, Vector2Int originalPos, Constants.Rotations.Rotation rotation)
회전 적용된 문 위치 리스트 반환 함수
levelIndex basePos rot
References DoorPosition.direction, RoomData< T >.GetRoomDataByLevel, DoorPosition.position, RoomData< T >.RoomLevel.possibleDoorPositions.
Referenced by CrewMovementValidator.AreRoomsConnectedThroughDoors, ShipValidationHelper.CheckAllRoomsPathConnectedByDoors, CrewMovementValidator.CorridorRoomConnectionValid.
override List< RoomLevel > RoomData< T >.GetAllLevels()
모든 레벨 반환
References RoomData< T >.RoomLevels.
override RoomLevel RoomData< T >.GetRoomDataByLevel(int level)
주어진 레벨에 해당하는 RoomLevel 데이터를 반환합니다.
level 조회할 레벨 번호. RoomLevel 데이터.
References RoomData< T >.GetTypedRoomData.
T RoomData< T >.GetTypedRoomData(int level)
제네릭 타입으로 명확하게 캐스팅된 RoomLevel 데이터를 반환합니다.
level 조회할 레벨 번호. T 타입의 RoomLevel 데이터.
References RoomData< T >.RoomLevels.
Referenced by RoomData< T >.GetRoomDataByLevel, AmmunitionRoom.GetStatContributions, CockpitRoom.GetStatContributions, EngineRoom.GetStatContributions, MedBayRoom.GetStatContributions, OxygenRoom.GetStatContributions, PowerRoom.GetStatContributions, ShieldRoom.GetStatContributions, TeleportRoom.GetStatContributions, WeaponControlRoom.GetStatContributions.
void RoomData< T >.InitializeDefaultLevels()
기본 레벨 데이터를 초기화합니다. 파생 클래스에서 구현합니다.
Referenced by RoomData< T >.OnEnable.
virtual void RoomData< T >.OnEnable()
ScriptableObject가 활성화될 때 호출되며, 필요한 경우 기본 데이터를 초기화합니다.
References RoomData< T >.CheckIfNeedsInitialization, RoomData< T >.InitializeDefaultLevels.
bool RoomData< T >.CheckIfNeedsInitialization()
데이터 초기화가 필요한지 판단하는 메서드입니다. 파생 클래스에서 구현합니다.
초기화 필요 여부.
Referenced by RoomData< T >.OnEnable.
override bool RoomData< T >.CheckIfNeedsInitialization()
RoomLevels 리스트가 비어 있거나 null인지 확인하여 초기화가 필요한지 판단합니다.
초기화 필요 여부.
References RoomData< T >.RoomLevels.
DoorDirection RoomData< T >.LocalDirToWorldDir(DoorDirection localDir, Constants.Rotations.Rotation rotation)