CrewMovementValidator
List<Vector2Int> CrewMovementValidator.inspectorWalkable
HashSet<Vector2Int> CrewMovementValidator.walkableTiles
List<Room> CrewMovementValidator.rooms
void CrewMovementValidator.Initialize(List< Room > allRooms)
초기화 - 방 리스트 등록
References Room< TData, TLevel >.GetOccupiedTiles.
Referenced by RTSSelectionManager.RefreshMovementData.
bool CrewMovementValidator.IsTileWalkable(Vector2Int tile)
타일이 이동 가능한 영역인가 (방/복도에 속하는가)
Referenced by RTSSelectionManager.IssueMoveCommand, RTSSelectionManager.MoveForCombat.
bool CrewMovementValidator.AreTilesConnected(Vector2Int from, Vector2Int to)
두 타일이 이동 가능한가 (같은 방 or 문을 통한 이동)
References AreRoomsConnectedThroughDoors, CorridorRoomConnectionValid, GetRoomAtTile, Room< TData, TLevel >.roomType.
Room CrewMovementValidator.GetRoomAtTile(Vector2Int tile)
특정 타일을 점유하고 있는 방 찾기
References Room< TData, TLevel >.GetOccupiedTiles.
Referenced by AreTilesConnected.
bool CrewMovementValidator.CorridorRoomConnectionValid(Room roomA, Room roomB, Vector2Int from, Vector2Int to)
복도 <-> 방 이동 시 문 연결성 검사
roomA roomB from to
References Room< TData, TLevel >.currentRotation, DoorPosition.direction, Room< TData, TLevel >.GetCurrentLevel, GetDirectionOffset, RoomData< T >.GetDoorPositionsWithDirection, Room< TData, TLevel >.position.
Referenced by AreTilesConnected.
bool CrewMovementValidator.AreRoomsConnectedThroughDoors(Room roomA, Room roomB, Vector2Int from, Vector2Int to)
방과 방 사이가 문으로 연결돼 있는지 검사 ShipValidationHelper.cs의 CheckAllRoomsPathConnectedByDoors 방식 반영
References Room< TData, TLevel >.currentRotation, DoorPosition.direction, DoorPositionMatch, Room< TData, TLevel >.GetCurrentLevel, RoomData< T >.GetDoorPositionsWithDirection, GetOppositeDoorDirection, DoorPosition.position, Room< TData, TLevel >.position.
Referenced by AreTilesConnected.
bool CrewMovementValidator.DoorPositionMatch(Vector2Int doorPosA, DoorDirection dirA, Vector2Int doorPosB, DoorDirection dirB)
두 문의 위치가 인접한지 검사
References GetDirectionOffset.
Referenced by AreRoomsConnectedThroughDoors.
Vector2Int CrewMovementValidator.GetDirectionOffset(DoorDirection dir)
문 방향에 따른 그리드 타일 위치 offset 세팅
dir
Referenced by CorridorRoomConnectionValid, DoorPositionMatch.
DoorDirection CrewMovementValidator.GetOppositeDoorDirection(DoorDirection dir)
현재 문의 반대 방향 반환
Referenced by AreRoomsConnectedThroughDoors.