ShipWeaponDatabase
List<ShipWeaponData> ShipWeaponDatabase.allWeapons
모든 무기 데이터 목록
Referenced by ShipWeaponFactory.GetAllWeaponData, GetWeaponsByEffectType, GetWeaponsByType, InitializeWeaponDictionary, BlueprintWeaponInventoryUI.LoadWeapons.
Dictionary<int, ShipWeaponData> ShipWeaponDatabase.weaponDictionary
void ShipWeaponDatabase.Initialize()
데이터베이스 초기화
References InitializeWeaponDictionary.
Referenced by ShipWeaponFactory.InitializeWeaponDatabase, BlueprintCategoryButtonHandler.ShowWeapons.
ShipWeaponData ShipWeaponDatabase.GetWeaponData(int id)
ID로 무기 데이터 검색
id 무기 ID 무기 데이터 또는 null
References InitializeWeaponDictionary.
Referenced by ShipWeaponFactory.GetWeaponData.
List< ShipWeaponData > ShipWeaponDatabase.GetWeaponsByType(ShipWeaponType type)
지정된 무기 타입의 무기 목록 반환
type 무기 타입 해당 타입의 무기 목록
References allWeapons, ShipWeaponData.weaponType, ShipWeaponTypeData.weaponType.
Referenced by ShipWeaponFactory.GetWeaponsByType, BlueprintWeaponInventoryUI.LoadWeapons.
List< ShipWeaponData > ShipWeaponDatabase.GetWeaponsByEffectType(ShipWeaponEffectType effectType)
효과 유형별 무기 목록 반환
effectType 효과 유형 해당 효과 유형을 가진 무기 목록
References allWeapons, ShipWeaponData.effectData, WeaponEffectData.effectType.
Referenced by ShipWeaponFactory.GetWeaponsByEffectType.
void ShipWeaponDatabase.InitializeWeaponDictionary()
무기 검색용 딕셔너리 초기화
References allWeapons, ShipWeaponData.id.
Referenced by GetWeaponData, Initialize.