RoomSelectionHandler
RoomSelectionHandler RoomSelectionHandler.Instance
싱글톤 인스턴스, 방/무기 삭제 담당 handler
Referenced by BlueprintRoomDragHandler.StartDragging, BlueprintWeaponDragHandler.StartDragging, BlueprintRoom.Update, BlueprintWeapon.Update.
GameObject RoomSelectionHandler.selectionUI
해당 위치에 오브젝트 확정, 삭제 물어보는 UI
Referenced by Deselect, SelectPlaceable, BlueprintRoom.Update, BlueprintWeapon.Update.
Button RoomSelectionHandler.confirmButton
확정 버튼
Button RoomSelectionHandler.cancelButton
삭제 버튼
GridPlacer RoomSelectionHandler.gridPlacer
그리드 타일 배치 작업을 위한 오브젝트
Referenced by ConfirmDelete.
IBlueprintPlaceable RoomSelectionHandler.selectedPlaceable
선택된 배치 가능 오브젝트
Referenced by ConfirmDelete, Deselect, SelectPlaceable.
void RoomSelectionHandler.Awake()
void RoomSelectionHandler.SelectRoom(BlueprintRoom room)
선택된 방에 대해 확정, 삭제할 UI 활성화, 색상 변경 (이전 버전과의 호환성 유지)
room
References SelectPlaceable.
Referenced by BlueprintRoom.Update.
void RoomSelectionHandler.SelectPlaceable(IBlueprintPlaceable placeable)
선택된 배치 가능 오브젝트에 대해 확정, 삭제할 UI 활성화, 색상 변경
placeable 배치 가능 오브젝트
References Deselect, selectedPlaceable, selectionUI.
Referenced by SelectRoom, BlueprintWeapon.Update.
void RoomSelectionHandler.Deselect()
선택 해제
References selectedPlaceable, selectionUI.
Referenced by ConfirmDelete, SelectPlaceable, BlueprintRoomDragHandler.StartDragging, BlueprintWeaponDragHandler.StartDragging, BlueprintRoom.Update, BlueprintWeapon.Update.
void RoomSelectionHandler.ConfirmDelete()
설계도 오브젝트 삭제
References Deselect, IBlueprintPlaceable.GetBlueprintShip, gridPlacer, BlueprintShip.RemovePlaceable, selectedPlaceable, GridPlacer.UnMarkObjectOccupied.