CrewSystem
override void CrewSystem.Initialize(Ship ship)
현재 배치된 크루들의 목록입니다.
시스템을 초기화합니다. 크루가 없는 경우 경고를 표시할 수 있습니다. ship 초기화할 대상 함선 객체.
Referenced by Ship.InitializeSystems.
override void CrewSystem.Refresh()
override void CrewSystem.Update(float deltaTime)
매 프레임마다 호출되어 시스템 상태를 갱신합니다.
deltaTime 경과 시간 (초).
Referenced by Ship.Update.
bool CrewSystem.AddCrew(CrewBase newCrew)
새로운 크루 멤버를 추가합니다.
newCrew 추가할 크루 멤버. 추가에 성공하면 true, 크루 정원이 초과되었으면 false.
References Ship.allCrews, Ship.GetAllRooms, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, ShipSystem.GetShipStat, Ship.GetWorldPositionFromGrid, CrewBase.isPlayerControlled, Room< TData, TLevel >.OnCrewEnter, ShipSystem.parentShip, Ship.RecalculateAllStats, Room< TData, TLevel >.roomType.
Referenced by Ship.AddCrew.
bool CrewSystem.RemoveCrew(CrewMember crewToRemove)
기존의 크루 멤버를 제거합니다. (아군, 적군 모두 제거)
crewToRemove 제거할 크루 멤버. 제거에 성공하면 true, 해당 크루가 존재하지 않으면 false.
References Ship.allCrews, Ship.allEnemies, ShipSystem.parentShip.
Referenced by RemoveAllCrews, Ship.RemoveCrew.
void CrewSystem.RemoveAllCrews()
소유하고 있는 모든 선원을 제거 (아군, 적군)
References Ship.allCrews, Ship.allEnemies, ShipSystem.parentShip, RemoveCrew.
int CrewSystem.GetCrewCount()
현재 탑승 중인 크루의 수를 반환합니다.
현재 크루 수.
References Ship.allCrews, ShipSystem.parentShip.
Referenced by Ship.GetCrewCount.
List< CrewMember > CrewSystem.GetCrews()
현재 탑승 중인 아군, 적군 포함 모든 크루 객체의 목록을 반환합니다.
크루 객체 리스트.
References Ship.allCrews, Ship.allEnemies, ShipSystem.parentShip.
Referenced by Ship.GetAllCrew, GetCrewsAtPosition, RTSSelectionManager.MoveForCombat, Ship.RecalculateAllStats.
List< CrewMember > CrewSystem.GetCrewsAtPosition(Vector2Int position)
특정 위치에 있는 모든 선원들을 반환합니다. (아군, 적군 모두)
position 확인할 격자 위치 해당 위치에 있는 선원들의 리스트
References GetCrews, CrewBase.position.
Referenced by Ship.ApplyDamageToCrewsAtPosition.
void CrewSystem.RevertOriginalCrews(List< BackupCrewData > backupDatas)
유효성 검사 실패 시, 기존 선원들을 백업된 위치 및 방으로 복구
References Ship.allCrews, CrewFactory.CreateCrewInstance, Ship.GetAllRooms, Ship.GetWorldPositionFromGrid, ShipSystem.parentShip.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_1_Controller.OnClickSave.
void CrewSystem.RestoreCrewAfterBuild(List< BackupCrewData > backupCrewDatas)
새로운 함선의 랜덤한 방의 랜덤 타일에 선원 배치 (겹치지 않게 타일 점유 등록)
backupCrewDatas
References Ship.allCrews, CrewMember.BackToThePeace, CrewFactory.CreateCrewInstance, CrewMember.Freeze, Ship.GetAllRooms, Room< TData, TLevel >.GetRotatedCrewEntryGridPriority, Ship.GetWorldPositionFromGrid, Room< TData, TLevel >.OnCrewEnter, ShipSystem.parentShip, Room< TData, TLevel >.roomType.
Referenced by CombatManager.BackToTheHome, CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy.