ES3Reader
ES3Settings ES3Reader.settings
The settings used to create this reader.
Referenced by Create, Create, Create, Read< T >, ReadInto< T >.
int ES3Reader.serializationDepth
string ES3Reader.overridePropertiesName
virtual ES3ReaderPropertyEnumerator ES3Reader.Properties
Allows you to enumerate over each field name. This should only be used within an ES3Type file.
virtual ES3ReaderRawEnumerator ES3Reader.RawEnumerator
int ES3Reader.Read_int()
float ES3Reader.Read_float()
bool ES3Reader.Read_bool()
char ES3Reader.Read_char()
decimal ES3Reader.Read_decimal()
double ES3Reader.Read_double()
long ES3Reader.Read_long()
ulong ES3Reader.Read_ulong()
byte ES3Reader.Read_byte()
sbyte ES3Reader.Read_sbyte()
short ES3Reader.Read_short()
ushort ES3Reader.Read_ushort()
uint ES3Reader.Read_uint()
string ES3Reader.Read_string()
byte[] ES3Reader.Read_byteArray()
long ES3Reader.Read_ref()
byte[] ES3Reader.ReadElement(bool skip=false)
virtual bool ES3Reader.Goto(string key)
virtual bool ES3Reader.StartReadObject()
virtual void ES3Reader.EndReadObject()
bool ES3Reader.StartReadDictionary()
void ES3Reader.EndReadDictionary()
bool ES3Reader.StartReadDictionaryKey()
void ES3Reader.EndReadDictionaryKey()
void ES3Reader.StartReadDictionaryValue()
bool ES3Reader.EndReadDictionaryValue()
bool ES3Reader.StartReadCollection()
void ES3Reader.EndReadCollection()
bool ES3Reader.StartReadCollectionItem()
bool ES3Reader.EndReadCollectionItem()
ES3Reader.ES3Reader(ES3Settings settings, bool readHeaderAndFooter=true)
Type ES3Reader.ReadType()
Type ES3Reader.ReadTypeFromHeader< T >()
string ES3Reader.ReadPropertyName()
void ES3Reader.Dispose()
Disposes of the reader and it's underlying stream.
virtual void ES3Reader.Skip()
Skips the current object in the stream.
virtual T ES3Reader.Read< T >()
Reads a value of type T from the reader.
References Read< T >.
Referenced by Read< T >, Read< T >, Read< T >.
virtual void ES3Reader.ReadInto< T >(object obj)
Reads a value of type T from the reader into an existing object.
obj The object we want to read our value into.
References ReadInto< T >.
Referenced by ReadInto< T >, ReadInto< T >.
T ES3Reader.ReadProperty< T >()
Reads a property (i.e. a property name and value) from the reader, ignoring the property name and only returning the value.
References ReadProperty< T >.
Referenced by ReadProperty< T >.
T ES3Reader.ReadProperty< T >(ES3Type type)
long ES3Reader.ReadRefProperty()
object ES3Reader.SetPrivateProperty(string name, object value, object objectContainingProperty)
Sets the value of a private property on an object.
name The name of the property we want to set. value The value we want to set the property to. objectContainingProperty The object containing the property we want to set. The objectContainingProperty object. This is helpful if you're setting a private property on a struct or other immutable type and need to return the boxed value.
object ES3Reader.SetPrivateField(string name, object value, object objectContainingField)
Sets the value of a private field on an object.
name The name of the field we want to set. value The value we want to set the field to. objectContainingField The object containing the field we want to set. The objectContainingField object. This is helpful if you're setting a private property on a struct or other immutable type and need to return the boxed value.
virtual T ES3Reader.Read< T >(string key)
Reads a value from the reader with the given key.
key The key which uniquely identifies our value.
References ES3Settings.FullPath, Read< T >, settings.
virtual T ES3Reader.Read< T >(string key, T defaultValue)
Reads a value from the reader with the given key, returning the default value if the key does not exist.
key The key which uniquely identifies our value. defaultValue The value we want to return if this key does not exist in the reader.
References Read< T >.
virtual void ES3Reader.ReadInto< T >(string key, T obj)
Reads a value from the reader with the given key into the provided object.
key The key which uniquely identifies our value. obj The object we want to load the value into.
References ES3Settings.FullPath, ReadInto< T >, settings.
virtual T ES3Reader.Read< T >(ES3Type type)
virtual void ES3Reader.ReadInto< T >(object obj, ES3Type type)
Type ES3Reader.ReadKeyPrefix(bool ignore=false)
void ES3Reader.ReadKeySuffix()
virtual void ES3Reader.ReadObject< T >(object obj, ES3Type type)
virtual T ES3Reader.ReadObject< T >(ES3Type type)
static void ES3Reader.TryOnAfterDeserialize(object obj)
static ES3Reader ES3Reader.Create(Stream stream, ES3Settings settings)
static ES3Reader ES3Reader.Create(Stream stream, ES3Settings settings, bool readHeaderAndFooter)
static ES3Reader ES3Reader.Create()
Creates a new ES3Reader and loads the default file into it.
References Create.
Referenced by Create, Create, Create, Create, ES3File.ES3File, ES3.GetKeys, ES3.KeyExists, ES3.Load< T >, ES3.Load< T >, ES3.LoadInto< T >, ES3File.SaveRaw.
static ES3Reader ES3Reader.Create(string filePath)
Creates a new ES3Reader and loads a file in storage into it.
filePath The relative or absolute path of the file we want to load into the reader.
References Create.
static ES3Reader ES3Reader.Create(string filePath, ES3Settings settings)
Creates a new ES3Reader and loads a file in storage into it.
filePath The relative or absolute path of the file we want to load into the reader. settings The settings we want to use to override the default settings.
References Create, settings.
static ES3Reader ES3Reader.Create(ES3Settings settings)
Creates a new ES3Reader and loads a file in storage into it.
settings The settings we want to use to override the default settings.
References ES3Settings.format, settings.
static ES3Reader ES3Reader.Create(byte[] bytes)
Creates a new ES3Reader and loads the bytes provided into it.
References Create.
static ES3Reader ES3Reader.Create(byte[] bytes, ES3Settings settings)
Creates a new ES3Reader and loads the bytes provided into it.
settings The settings we want to use to override the default settings.
References ES3Settings.format, settings.