ProjectileManager
ProjectileManager ProjectileManager.Instance
List<ProjectileData> ProjectileManager.projectileData
int ProjectileManager.poolSize
bool ProjectileManager.organizeIntoFolders
Dictionary<int, Queue<MyProjectile> > ProjectileManager.projectilePools
투사체 풀링 시스템 (ID 기반)
Referenced by CreateAdditionalProjectiles, GetProjectileFromPool, InitializePools, ReturnProjectileToPool.
Dictionary<int, ProjectileData> ProjectileManager.projectileDataCache
투사체 데이터 캐시 (ID로 빠른 접근)
Referenced by GetProjectileData, InitializePools.
List<MyProjectile> ProjectileManager.activeProjectiles
활성화된 투사체 목록
Referenced by FireProjectile, InitializePools, ReturnProjectileToPool, Update.
Transform ProjectileManager.effectsParent
Transform ProjectileManager.projectilePoolsParent
Transform ProjectileManager.activeProjectilesParent
void ProjectileManager.Awake()
void ProjectileManager.InitializeOrganization()
하이어라키 조직화 초기화
void ProjectileManager.InitializePools()
투사체 풀 초기화
References activeProjectiles, projectileDataCache, projectilePools.
MyProjectile ProjectileManager.GetProjectileFromPool(int projectileId)
풀에서 투사체 가져오기
References CreateAdditionalProjectiles, projectilePools.
Referenced by FireProjectile.
void ProjectileManager.CreateAdditionalProjectiles(int projectileId, int count)
풀이 부족할 때 추가 투사체 생성
References GetProjectileData, projectilePools.
Referenced by GetProjectileFromPool.
void ProjectileManager.Update()
모든 활성 투사체 업데이트
References activeProjectiles.
MyProjectile ProjectileManager.FireProjectile(Vector3 startPos, Vector3 targetWorldPos, int projectileId, Action onHitCallback)
투사체 발사 (단순화된 버전)
startPos 발사 위치 targetWorldPos 목표 위치 projectileId 투사체 ID onHitCallback 타격 시 호출될 콜백 발사된 투사체
References activeProjectiles, GetProjectileFromPool.
Referenced by ShipWeapon.Fire.
ProjectileData ProjectileManager.GetProjectileData(int projectileId)
투사체 ID로 데이터 찾기
projectileId 투사체 ID 해당 ID의 투사체 데이터
References projectileDataCache.
Referenced by CreateAdditionalProjectiles, ReturnProjectileToPool.
void ProjectileManager.ReturnProjectileToPool(MyProjectile projectile)
투사체를 풀로 반환
References activeProjectiles, GetProjectileData, projectilePools.
void ProjectileManager.CreateImpactEffect(GameObject effectPrefab, Vector3 position, float duration)
임팩트 이펙트 생성 (중앙 관리)
effectPrefab 이펙트 프리팹 position 생성 위치 duration 지속 시간
List< int > ProjectileManager.GetCompatibleProjectileIds(ShipWeaponType weaponType)
무기 타입과 호환되는 투사체 ID 목록 반환
weaponType 무기 타입 호환되는 투사체 ID 목록