BlueprintCategoryButtonHandler
BlueprintInventoryUI BlueprintCategoryButtonHandler.bpInventoryUI
설계도 UI 오브젝트
Referenced by ShowAuxiliary, ShowEssential, ShowEtc, ShowLiving, ShowStorage.
BlueprintWeaponInventoryUI BlueprintCategoryButtonHandler.bpWeaponInventoryUI
무기 인벤토리 UI
Referenced by ShowWeapons.
BlueprintHullLevelInventoryUI BlueprintCategoryButtonHandler.hullInventoryUI
List<Button> BlueprintCategoryButtonHandler.categoryButtons
카테고리 버튼들
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
Color BlueprintCategoryButtonHandler.selectedBG
선택 된 카테고리의 배경, 글자 색 조정
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
Color BlueprintCategoryButtonHandler.selectedText
Color BlueprintCategoryButtonHandler.defaultBG
기본 카테고리 배경, 글자 색 조정
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
Color BlueprintCategoryButtonHandler.defaultText
Transform BlueprintCategoryButtonHandler.contentRoot
내용 표시 영역 (방/무기 UI가 표시될 공간)
GameObject BlueprintCategoryButtonHandler.roomInventoryUIObject
방 인벤토리 UI 게임 오브젝트
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
GameObject BlueprintCategoryButtonHandler.weaponInventoryUIObject
무기 인벤토리 UI 게임 오브젝트
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
GameObject BlueprintCategoryButtonHandler.hullInventoryUIObject
외갑판 레벨 선택 패널
Referenced by SetButtonState, SetHullButtonState, SetWeaponButtonState.
void BlueprintCategoryButtonHandler.SetButtonState(RoomCategory selectedCategory)
카테고리 버튼의 상태 갱신
selectedCategory 선택된 카테고리
References categoryButtons, defaultBG, hullInventoryUIObject, roomInventoryUIObject, selectedBG, weaponInventoryUIObject.
Referenced by Customize_1_Controller.OnEnable, ShowAuxiliary, ShowEssential, ShowEtc, ShowLiving, ShowStorage, BlueprintInventoryUI.Start.
void BlueprintCategoryButtonHandler.SetWeaponButtonState()
무기 카테고리 선택 시 버튼 상태 갱신
References categoryButtons, defaultBG, hullInventoryUIObject, roomInventoryUIObject, selectedBG, weaponInventoryUIObject.
Referenced by ShowWeapons.
void BlueprintCategoryButtonHandler.SetHullButtonState()
외갑판 레벨 카테고리 선택 시 버튼 상태 갱신
References categoryButtons, defaultBG, hullInventoryUIObject, roomInventoryUIObject, selectedBG, weaponInventoryUIObject.
Referenced by ShowHull.
void BlueprintCategoryButtonHandler.ShowEssential()
필수 시설 - 인벤토리에 호출
References bpInventoryUI, BlueprintInventoryUI.FilterByCategory, SetButtonState.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowAuxiliary()
보조 시설 - 인벤토리에 호출
References bpInventoryUI, BlueprintInventoryUI.FilterByCategory, SetButtonState.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowLiving()
생활활 시설 - 인벤토리에 호출
References bpInventoryUI, BlueprintInventoryUI.FilterByCategory, SetButtonState.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowStorage()
저장고 - 인벤토리에 호출
References bpInventoryUI, BlueprintInventoryUI.FilterByCategory, SetButtonState.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowEtc()
복도 - 인벤토리에 호출
References bpInventoryUI, BlueprintInventoryUI.FilterByCategory, SetButtonState.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowWeapons()
무기 - 인벤토리에 호출
References bpWeaponInventoryUI, ShipWeaponDatabase.Initialize, BlueprintWeaponInventoryUI.LoadWeapons, SetWeaponButtonState, BlueprintWeaponInventoryUI.weaponDatabase.
Referenced by Customize_1_Controller.Start.
void BlueprintCategoryButtonHandler.ShowHull()
외갑판 카테고리 - 인벤토리에 호출
References BlueprintHullLevelInventoryUI.LoadHullLevelButtons, SetHullButtonState.