OuterHullData
List<OuterHullLevel> OuterHullData.OuterHullLevels
외갑판의 모든 레벨 데이터를 저장하는 리스트입니다.
Referenced by GetOuterHullData, InitializeDefaultLevels, OnEnable.
Sprite [] OuterHullData.level1Sprites
Sprite [] OuterHullData.level2Sprites
Sprite [] OuterHullData.level3Sprites
OuterHullLevel OuterHullData.GetOuterHullData(int level)
지정한 레벨에 해당하는 외갑판 데이터를 반환합니다.
level 가져올 외갑판 레벨 (0부터 시작하는 인덱스). 해당 레벨의 외갑판 데이터.
References OuterHullLevels.
Referenced by OuterHull.Initialize, OuterHull.Initialize, Ship.RecalculateAllStats, OuterHull.SetLevel, OuterHull.SetOuterHullData, OuterHull.Upgrade.
Sprite[] OuterHullData.GetHullSprites(int level)
지정한 레벨의 방향별 스프라이트 배열을 반환합니다.
level 외갑판 레벨 (0-2) 해당 레벨의 스프라이트 배열
Referenced by GetSpecificHullSprite.
Sprite OuterHullData.GetSpecificHullSprite(int level, int directionIndex)
특정 레벨과 방향에 해당하는 외갑판 스프라이트를 반환합니다.
level 외갑판 레벨 (0-2) directionIndex 방향 인덱스: 0-3: 하, 좌, 상, 우 (기본) 4-7: 하, 좌, 상, 우 (변형) 8-11: 하좌, 상좌, 상우, 하우 모서리 12-15: 내부 모서리 하좌, 내부 모서리 상좌, 내부 모서리 상우, 내부 모서리 하우 해당 스프라이트
References GetHullSprites.
Referenced by OuterHullSystem.CreateOuterHull, BlueprintShip.CreateOuterHull, OuterHull.SetLevel, OuterHull.UpdateSpriteByLevelAndDirection, OuterHull.Upgrade.
void OuterHullData.InitializeDefaultLevels()
기본 외갑판 레벨 데이터를 초기화합니다. 주로 에디터에서 ScriptableObject가 로드될 때 호출됩니다.
References OuterHullLevels.
Referenced by OnEnable.
virtual void OuterHullData.OnEnable()
ScriptableObject가 활성화될 때 자동으로 호출됩니다. 기본 레벨 데이터를 설정합니다.
References InitializeDefaultLevels, OuterHullLevels.