NodePlacementMap
RectTransform NodePlacementMap.mapContainer
GameObject NodePlacementMap.validRangeIndicatorPrefab
GameObject NodePlacementMap.nodePrefab
GameObject NodePlacementMap.planetPrefab
GameObject NodePlacementMap.tooltipPrefab
GameObject NodePlacementMap.dangerZonePrefab
float NodePlacementMap.maxPlacementDistance
int NodePlacementMap.numberOfPlanets
int NodePlacementMap.maxPlacementAttempts
float NodePlacementMap.minimumDistanceBetweenPlanets
int NodePlacementMap.numDangerZones
float NodePlacementMap.dangerZoneRadius
Color NodePlacementMap.dangerZoneColor
readonly List<RectTransform> NodePlacementMap.placedNodeObjects
readonly List<GameObject> NodePlacementMap.planets
readonly List<GameObject> NodePlacementMap.dangerZones
Vector2 NodePlacementMap.currentIndicatorPosition
GameObject NodePlacementMap.endPlanet
GameObject NodePlacementMap.startPlanet
GameObject NodePlacementMap.validRangeIndicatorInstance
EventSystem NodePlacementMap.eventSystem
bool NodePlacementMap.nodePlacementCompleted
List<Vector2> NodePlacementMap.pathNodes
List<bool> NodePlacementMap.pathDangerInfo
PathCompletedHandler NodePlacementMap.OnPathCompleted
delegate void NodePlacementMap.PathCompletedHandler(List< Vector2 > path, List< bool > dangerInfo)
void NodePlacementMap.Initialize()
외부에서 노드 맵을 초기화할 때 호출됩니다. 맵과 경로 데이터, 배치 상태를 초기화합니다.
References ClearMapContents.
void NodePlacementMap.InitializeMap(int planetCount, float maxDistance)
행성 개수 및 배치 거리 설정 후 맵을 초기화합니다.
planetCount 행성 개수 maxDistance 최대 배치 거리
References ClearMapContents, GenerateDangerZones, GenerateRandomPlanets, InitializeValidRangeIndicator.
void NodePlacementMap.OnMapClick(BaseEventData eventData)
맵 클릭 시 호출되어 노드 배치를 시도합니다.
eventData PointerEventData
References TryPlaceNode.
void NodePlacementMap.GenerateRandomPlanets(int count)
랜덤한 위치에 행성들을 배치합니다.
count 배치할 행성 수
Referenced by InitializeMap.
void NodePlacementMap.OnPlanetClickedFromComponent(GameObject planet)
Planet.cs에서 행성 클릭 시 호출되는 메서드입니다.
planet 클릭된 행성
References OnPlanetClicked.
void NodePlacementMap.Awake()
초기화 시 호출되어 EventSystem을 설정합니다.
void NodePlacementMap.Update()
매 프레임마다 유효 범위 표시기를 갱신합니다.
References UpdateValidRangeIndicator.
void NodePlacementMap.OnPlanetClicked(GameObject planet)
행성 클릭 시 경로에 추가하고 배치를 종료합니다.
planet 클릭된 행성 오브젝트
References CompletePlacementMap, IsPositionInDangerZone, UpdateValidRangeIndicator.
Referenced by OnPlanetClickedFromComponent.
void NodePlacementMap.TryPlaceNode(Vector2 position)
노드 배치를 시도합니다.
position 배치할 위치
References CreateNodeUI, IsPositionInDangerZone, IsValidPlacement, UpdateValidRangeIndicator.
Referenced by OnMapClick.
void NodePlacementMap.GenerateDangerZones()
위험지역을 생성합니다.
References ClearDangerZones, EnsurePlanetsOnTop, FindValidDangerZonePosition.
Referenced by InitializeMap.
void NodePlacementMap.InitializeValidRangeIndicator()
유효 범위 표시기를 초기화합니다.
References FindLeftmostPlanet.
Referenced by InitializeMap.
void NodePlacementMap.UpdateValidRangeIndicator(Vector2 localPosition)
유효 범위 표시기의 위치를 업데이트합니다.
localPosition 새 위치
Referenced by OnPlanetClicked, TryPlaceNode, Update.
void NodePlacementMap.ClearMapContents()
맵 요소(행성, 노드, 위험지역)를 초기화합니다.
References ClearDangerZones, ClearNodes, ClearPlanets.
Referenced by Initialize, InitializeMap.
void NodePlacementMap.ClearPlanets()
기존 행성들을 제거합니다.
Referenced by ClearMapContents.
void NodePlacementMap.ClearNodes()
배치된 노드를 초기화합니다.
Referenced by ClearMapContents.
void NodePlacementMap.ClearDangerZones()
기존 위험지역을 초기화합니다.
Referenced by ClearMapContents, GenerateDangerZones.
void NodePlacementMap.EnsurePlanetsOnTop()
행성들이 UI 상에서 가장 위에 표시되도록 합니다.
Referenced by GenerateDangerZones.
Vector2 NodePlacementMap.FindValidPlanetPosition(float width, float height)
행성을 배치할 수 있는 유효한 위치를 찾습니다.
References IsFarEnoughFromOtherPlanets.
bool NodePlacementMap.IsFarEnoughFromOtherPlanets(Vector2 position)
해당 위치가 다른 행성과 충분히 떨어져 있는지 확인합니다.
Referenced by FindValidPlanetPosition.
Vector2 NodePlacementMap.FindValidDangerZonePosition(float width, float height)
위험지역의 유효 위치를 찾습니다.
References IsFarEnoughFromOtherObjects.
Referenced by GenerateDangerZones.
bool NodePlacementMap.IsFarEnoughFromOtherObjects(Vector2 position)
해당 위치가 행성 또는 위험지역과 충돌하지 않는지 확인합니다.
Referenced by FindValidDangerZonePosition.
bool NodePlacementMap.IsPositionInDangerZone(Vector2 position)
주어진 위치가 위험지역 안에 있는지 확인합니다.
Referenced by CollectNodePath, OnPlanetClicked, TryPlaceNode.
GameObject NodePlacementMap.FindLeftmostPlanet()
가장 왼쪽에 있는 행성을 찾습니다.
Referenced by InitializeValidRangeIndicator.
GameObject NodePlacementMap.FindRightmostPlanet()
가장 오른쪽에 있는 행성을 찾습니다.
bool NodePlacementMap.IsValidPlacement(Vector2 position)
주어진 위치가 현재 배치 기준점으로부터 유효한 거리인지 확인합니다.
Referenced by TryPlaceNode.
void NodePlacementMap.CreateNodeUI(Vector2 position)
실제 노드를 생성하여 UI에 배치합니다.
Referenced by TryPlaceNode.
void NodePlacementMap.CompletePlacementMap()
노드 배치가 완료되었을 때 호출되며, 최종 경로를 생성합니다.
References CollectNodePath.
Referenced by OnPlanetClicked.
List< Vector2 > NodePlacementMap.CollectNodePath()
현재까지의 배치된 노드 경로를 수집합니다.
References IsPositionInDangerZone.
Referenced by CompletePlacementMap.