RoomFactory
RoomDatabase RoomFactory.roomDatabase
GameObject RoomFactory.roomPrefab
void RoomFactory.Awake()
void RoomFactory.InitializeRoomDatabase()
방 데이터베이스 초기화
References RoomDatabase.Initialize.
Room RoomFactory.AttachRoomComponent(GameObject roomObject, RoomType roomType)
방 유형에 따라 적절한 컴포넌트 부착
Referenced by CreateRoomInstance, CreateRoomObject.
StorageRoomBase RoomFactory.AttachStorageRoomComponent(GameObject roomObject, StorageType storageType)
창고 유형에 따라 적절한 컴포넌트 부착
Referenced by CreateRoomObject, CreateStorageRoomInstance.
RoomData RoomFactory.GetRoomData(RoomType roomType)
방 유형에 따른 데이터 반환
roomType 방 유형 해당 유형의 방 데이터
References RoomDatabase.GetRoomData.
Referenced by CreateRoomInstance.
StorageRoomBaseData RoomFactory.GetStorageRoomData(StorageType storageType, StorageSize size)
창고 데이터 반환
storageType 창고 유형 size 창고 크기 해당 유형과 크기의 창고 데이터
References RoomDatabase.GetStorageRoomData.
Referenced by CreateStorageRoomInstance.
LifeSupportRoomData RoomFactory.GetLifeSupportRoomData(LifeSupportRoomType facilityType)
생활시설 데이터 반환
facilityType 시설 유형 해당 유형의 생활시설 데이터
References RoomDatabase.GetLifeSupportRoomData.
Referenced by CreateLifeSupportRoomInstance.
CrewQuartersRoomData RoomFactory.GetCrewQuartersRoomData(CrewQuartersRoomSize size)
Room RoomFactory.CreateRoomInstance(RoomType roomType, int level=1)
지정된 방 유형의 인스턴스 생성
roomType 생성할 방 유형 level 방 레벨 생성된 방 인스턴스
References AttachRoomComponent, GetRoomData, Room< TData, TLevel >.Initialize.
Referenced by ShipFactory.CreateShipFromTemplate.
StorageRoomBase RoomFactory.CreateStorageRoomInstance(StorageType storageType, StorageSize size, int level=1)
창고 인스턴스 생성
storageType 창고 유형 size 창고 크기 level 방 레벨 생성된 창고 인스턴스
References AttachStorageRoomComponent, GetStorageRoomData, StorageRoomBase.Initialize.
Referenced by TradeUIController.Start.
LifeSupportRoom RoomFactory.CreateLifeSupportRoomInstance(LifeSupportRoomType facilityType, int level=1)
생활시설 인스턴스 생성
facilityType 시설 유형 level 방 레벨 생성된 생활시설 인스턴스
References GetLifeSupportRoomData, Room< TData, TLevel >.Initialize.
CrewQuartersRoom RoomFactory.CreateCrewQuartersRoomInstance(CrewQuartersRoomSize size, int level=1)
Room RoomFactory.CreateRoomObject(Room sourceRoom)
기존 방과 동일한 방 인스턴스 생성
sourceRoom 복제할 방 복제된 방 인스턴스
References AttachRoomComponent, AttachStorageRoomComponent, Room< TData, TLevel >.CopyFrom, Room< TData, TLevel >.GetCurrentLevel, Room< TData, TLevel >.Initialize.
Referenced by ShipFactory.CloneShip.