BlueprintWeapon
ShipWeaponData BlueprintWeapon.bpWeaponData
ShipWeaponData 참조
Referenced by ApplyAttachedDirectionSprite, Initialize, Ship.ReplaceShipFromBlueprint, Update.
ShipWeaponAttachedDirection BlueprintWeapon.bpAttachedDirection
무기 부착 방향
Referenced by ApplyAttachedDirectionSprite, GetRotation, Initialize, Ship.ReplaceShipFromBlueprint, RotateAttachedDirection, Update.
Vector2Int BlueprintWeapon.bpPosition
배치 위치
Referenced by GetGridPosition, Initialize, GridPlacer.PlacePreviewWeapon, Ship.ReplaceShipFromBlueprint, SetGridPosition, Update, UpdateOccupiedTiles.
int BlueprintWeapon.bpWeaponCost
해당 무기의 설치 비용
Referenced by GetCost, Initialize.
Vector2Int BlueprintWeapon.bpWeaponSize
무기 크기 (고정: 2x1)
Referenced by Initialize, Update, UpdateOccupiedTiles.
Constants.Rotations.Rotation BlueprintWeapon.bpRotation
회전각 고정 (0)
Referenced by Initialize, Update, UpdateOccupiedTiles.
List<Vector2Int> BlueprintWeapon.occupiedTiles
실제 점유 타일
Referenced by GetOccupiedTiles, Initialize, Update, UpdateOccupiedTiles.
BlueprintShip BlueprintWeapon.blueprintShip
설계도 함선
Referenced by GetBlueprintShip, GetHullLevel, SetBlueprint, Start.
bool BlueprintWeapon.isDragging
드래그 중인지 여부
Referenced by SetDragMode, Update.
SpriteRenderer BlueprintWeapon.sr
설계도 무기의 Sprite Renderer
Referenced by ApplyAttachedDirectionSprite, Initialize, SetDragMode, Start.
Color BlueprintWeapon.validColor
배치 가능을 나타내는 초록색 (alpha = 0.5)
Referenced by Update.
Color BlueprintWeapon.invalidColor
배치 불가능을 나타내는 빨간색 (alpha = 0.5)
Referenced by Update.
Vector2Int BlueprintWeapon.originalPos
이동 전 무기 위치
Referenced by Update.
ShipWeaponAttachedDirection BlueprintWeapon.originalDirection
이동 전 무기 부착 방향
Referenced by Update.
GridPlacer BlueprintWeapon.gridPlacer
그리드 타일 배치 작업을 위한 오브젝트
Referenced by SetGridPlacer, Update.
GameObject BlueprintWeapon.mouseDownTarget
마우스로 클릭한 오브젝트 (무기 삭제 여부 활성화 조건을 위한 변수)
Referenced by Update.
int BlueprintWeapon.hullLevel
함선 외갑판 레벨 (0: 레벨 1, 1: 레벨 2, 2: 레벨 3) 이 변수는 단지 캐싱 용도로만 사용됨. 실제 레벨은 blueprintShip.GetHullLevel()에서 가져와야 함
Referenced by ApplyAttachedDirectionSprite, GetHullLevel, SetHullLevel.
void BlueprintWeapon.Start()
collider size 맞춤, 외갑판 레벨로 무기 디자인 업데이트
References ApplyAttachedDirectionSprite, blueprintShip, BlueprintShip.GetHullLevel, SetHullLevel, sr.
void BlueprintWeapon.Update()
무기 배치와 관련된 모든 작업을 매 프레임 검사
References ApplyAttachedDirectionSprite, bpAttachedDirection, bpPosition, bpRotation, bpWeaponData, bpWeaponSize, GridPlacer.CanPlaceWeapon, RoomSelectionHandler.Deselect, GridPlacer.GetWorldPositionFromGrid, gridPlacer, RoomSelectionHandler.Instance, invalidColor, isDragging, IsPointerOverUIObject, GridPlacer.MarkObjectOccupied, mouseDownTarget, occupiedTiles, originalDirection, originalPos, RotateAttachedDirection, RoomSelectionHandler.selectionUI, RoomSelectionHandler.SelectPlaceable, GridPlacer.UnMarkObjectOccupied, UpdateOccupiedTiles, validColor, GridPlacer.WorldToGridPosition.
void BlueprintWeapon.LateUpdate()
bool BlueprintWeapon.BlockBPMovement()
bool BlueprintWeapon.IsPointerOverBlockingUI()
bool BlueprintWeapon.IsPointerOverUIObject(GameObject rootUI)
마우스가 selectionUI 위에 있는지 확인
rootUI
Referenced by Update.
void BlueprintWeapon.Initialize(ShipWeaponData data, Vector2Int pos, ShipWeaponAttachedDirection direction)
설치 시 초기화
References ApplyAttachedDirectionSprite, bpAttachedDirection, bpPosition, bpRotation, bpWeaponCost, bpWeaponData, bpWeaponSize, ShipWeaponData.cost, occupiedTiles, sr.
Referenced by GridPlacer.PlacePreviewWeapon, GridPlacer.PlaceWeapon.
void BlueprintWeapon.SetDragMode(bool isDragging)
드래그 모드 설정
References isDragging, sr.
void BlueprintWeapon.RotateAttachedDirection()
무기 부착 방향 회전
References ApplyAttachedDirectionSprite, bpAttachedDirection.
Referenced by Update.
object BlueprintWeapon.GetRotation()
현재 회전 상태 반환
References bpAttachedDirection.
Vector2Int BlueprintWeapon.GetGridPosition()
현재 그리드 위치 반환
References bpPosition.
Referenced by GridPlacer.GetCameraStartPositionToOriginShip.
void BlueprintWeapon.SetGridPosition(Vector2Int position)
그리드 위치 설정
References bpPosition.
void BlueprintWeapon.SetBlueprint(BlueprintShip bpShip)
설계도 함선 할당
bpShip
References ApplyAttachedDirectionSprite, blueprintShip, BlueprintShip.GetHullLevel, SetHullLevel.
Referenced by GridPlacer.PlaceWeapon.
BlueprintShip BlueprintWeapon.GetBlueprintShip()
설계도 함선 호출
References blueprintShip.
void BlueprintWeapon.SetGridPlacer(GridPlacer placer)
그리드 배치 담당 오브젝트 세팅
placer
References gridPlacer.
Referenced by GridPlacer.PlaceWeapon.
void BlueprintWeapon.ApplyAttachedDirectionSprite()
현재 부착 방향과 외갑판 레벨에 맞는 스프라이트 적용
References bpAttachedDirection, bpWeaponData, ShipWeaponData.flattenedSprites, hullLevel, sr, ShipWeaponData.weaponIcon.
Referenced by CustomizeShipUIHandler.GetSavedWeaponRooms, Initialize, Customize_2_Controller.MakeBPShipWithSaveData, RotateAttachedDirection, SetBlueprint, SetHullLevel, Start, Update.
int BlueprintWeapon.GetCost()
설치 비용 반환
References bpWeaponCost.
void BlueprintWeapon.SetHullLevel(int level)
함선 외갑판 레벨 설정 (내부적으로만 캐싱)
level 외갑판 레벨 (0-2)
References ApplyAttachedDirectionSprite, hullLevel.
Referenced by Customize_2_Controller.MakeBPShipWithSaveData, GridPlacer.PlacePreviewWeapon, GridPlacer.PlaceWeapon, Customize_1_Controller.ReloadBlueprintFromSlot, SetBlueprint, BlueprintShip.SetBPHullLevel, BlueprintShip.SetHullLevel, Start.
int BlueprintWeapon.GetHullLevel()
함선 외갑판 레벨 가져오기 실제로는 blueprintShip.GetHullLevel()을 우선적으로 사용해야 하며, 이 메서드는 blueprintShip이 null일 때의 레벨 값만 반환함
외갑판 레벨 (0-2)
References blueprintShip, BlueprintShip.GetHullLevel, hullLevel.
Referenced by Customize_2_Controller.MakeBPShipWithSaveData.
List< Vector2Int > BlueprintWeapon.GetOccupiedTiles()
점유 타일 목록 반환
References occupiedTiles.
void BlueprintWeapon.UpdateOccupiedTiles()
점유 타일 목록 업데이트
References bpPosition, bpRotation, bpWeaponSize, occupiedTiles.
Referenced by Update.