CustomizeShipUIHandler
GameObject CustomizeShipUIHandler.customizeUI
커스터마이즈 UI 화면입니다.
Referenced by Update.
GameObject CustomizeShipUIHandler.gridTiles
그리드 타일이 배치되는 부모 오브젝트입니다.
Referenced by OnDisable, OnEnable.
Button CustomizeShipUIHandler.buildButton
설계도 -> 실제 함선으로 교체 (bpRoom -> room)
Referenced by FlashBuildButtonColor.
TMP_Text CustomizeShipUIHandler.feedbackText
저장 또는 유효성 검사 결과를 표시할 텍스트입니다.
TMP_Text CustomizeShipUIHandler.currency
현재 보유 재화량
TMP_Text CustomizeShipUIHandler.originShipCost
기존 함선 가격
TMP_Text CustomizeShipUIHandler.totalCostText
총 설계도 가격을 표시할 텍스트 UI.
Ship CustomizeShipUIHandler.playerShip
현재 커스터마이징 중인 플레이어 함선입니다.
Referenced by DisableCrews, EnableCrews, OnClickBuild, OnDisable, OnEnable, SetPlayerShipCollidersActive, Update.
GridPlacer CustomizeShipUIHandler.gridPlacer
그리드 타일 배치 작업을 위한 오브젝트
Referenced by CenterCameraToBP, GetSavedBPRooms, GetSavedWeaponRooms, ResetCameraToOriginShip.
BlueprintShip CustomizeShipUIHandler.targetBlueprintShip
제작한 설계도
Referenced by OnClickBuild, OnClickClear, SaveBPRoomsandDestroy, Update.
int CustomizeShipUIHandler.originalShipCost
기존 사용 중인 함선 가격
Referenced by OnClickBuild, Update.
ValidationResult CustomizeShipUIHandler.validationResult
유효성 검사 결과
Referenced by OnClickBuild, Update.
int CustomizeShipUIHandler.totalBPCost
설계도 함선 가격
Referenced by Update.
Coroutine CustomizeShipUIHandler.flashCoroutine
build 빨간색 처리 코루틴
Referenced by FlashBuildButtonColor, OnClickBuild.
Color? CustomizeShipUIHandler.originButtonColor
버튼 기본 색상 저장
Referenced by FlashBuildButtonColor.
void CustomizeShipUIHandler.Update()
현재 설계도의 가격 지속 갱신 설계도로 함선 교체 가능 조건
(설계도 가격 - 기존 함선 가격) <= 보유 재화량 기존 함선 모든 방 내구도 100%
References customizeUI, DisableCrews, EnableCrews, BlueprintShip.GetTotalBPCost, Ship.GetTotalShipValue, Ship.IsFullHitPoint, originalShipCost, playerShip, SetPlayerShipCollidersActive, targetBlueprintShip, totalBPCost, validationResult.
void CustomizeShipUIHandler.OnEnable()
CustomizeShipUI 활성화 시 아래 작업 수행 : 그리드 생성 및 그리드 저장 오브젝트 활성화 작업하던 설계도 방 호출, 배치 카메라 중앙값 세팅
References CenterCameraToBP, Ship.ClearExistingHulls, GetSavedBPRooms, GetSavedWeaponRooms, gridTiles, playerShip, SetPlayerShipCollidersActive.
void CustomizeShipUIHandler.OnDisable()
CustomizeShipUI 비활성화 시 아래 작업 수행 : 그리드 저장 오브젝트 비활성화 설계도 설치한 방 데이터 모두 저장 후 제거
References gridTiles, playerShip, ResetCameraToOriginShip, SaveBPRoomsandDestroy, SetPlayerShipCollidersActive, Ship.UpdateOuterHullVisuals.
void CustomizeShipUIHandler.DisableCrews()
커스터마이징 UI 진입 시 선원 임시 비활성화
References Ship.allCrews, CrewMember.Freeze, playerShip.
Referenced by Update.
void CustomizeShipUIHandler.EnableCrews()
커스터마이징 UI 탈출 시 선원 재활성화
References Ship.allCrews, CrewMember.BackToThePeace, playerShip.
Referenced by Update.
void CustomizeShipUIHandler.CenterCameraToBP()
설계도 UI 호출 시 카메라 중앙값 보정
References GridPlacer.GetCameraStartPositionToBP, gridPlacer, CameraZoomController.lastZoomSize.
Referenced by OnEnable.
void CustomizeShipUIHandler.ResetCameraToOriginShip()
카메라 기본 세팅으로 복구
References GridPlacer.GetCameraStartPositionToOriginShip, gridPlacer.
Referenced by OnDisable.
void CustomizeShipUIHandler.GetSavedBPRooms()
기존에 작업중이던 설계도의 모든 방 데이터 호출 및 배치
References gridPlacer, GridPlacer.PlaceRoom.
Referenced by OnEnable.
void CustomizeShipUIHandler.GetSavedWeaponRooms()
기존에 작업 중이던 설계도의 모든 함선 무기 데이터 호출 및 배치
References BlueprintWeapon.ApplyAttachedDirectionSprite, gridPlacer, GridPlacer.PlaceWeapon.
Referenced by OnEnable.
void CustomizeShipUIHandler.SaveBPRoomsandDestroy()
작업중이던 설계도 저장 및 방 제거
References BlueprintShip.ClearRooms, targetBlueprintShip.
Referenced by OnDisable.
void CustomizeShipUIHandler.SetPlayerShipCollidersActive(bool active)
함선의 모든 방에 대해 collider 활성화/비활성화
active
References Ship.GetAllRooms, playerShip.
Referenced by OnDisable, OnEnable, Update.
IEnumerator CustomizeShipUIHandler.FlashBuildButtonColor(Color flashColor, float duration)
유효성 검사 실패 시 build button 일시적 빨간색
flashColor duration
References buildButton, flashCoroutine, originButtonColor.
Referenced by OnClickBuild.
void CustomizeShipUIHandler.OnClickBuild()
'함선 제작' 버튼 클릭 시 호출. 조건 만족 시 기존 함선을 설계도의 함선으로 교체합니다. 이후 방, 문의 연결 유효성 검사 수행 후 만족 여부에 따라 실제 함선으로 교체, 다시 설계도로 복구를 수행
References Ship.BackupAllCrews, Ship.backupCrewDatas, Ship.BackupCurrentShip, FlashBuildButtonColor, flashCoroutine, BlueprintShip.GetTotalBPCost, Ship.GetTotalShipValue, RTSSelectionManager.Instance, ValidationResult.IsValid, originalShipCost, playerShip, Ship.RecalculateAllStats, RTSSelectionManager.RefreshMovementData, Ship.ReplaceShipFromBlueprint, CrewSystem.RestoreCrewAfterBuild, CrewSystem.RevertOriginalCrews, Ship.RevertToOriginalShip, targetBlueprintShip, ShipValidationHelper.ValidateShipLayout, validationResult.
void CustomizeShipUIHandler.OnClickClear()
설계도 초기화 및 점유 타일 초기화
References BlueprintShip.ClearRooms, targetBlueprintShip.