BlueprintShip
Transform BlueprintShip.outerHulls
Vector2Int BlueprintShip.gridSize
List<IBlueprintPlaceable> BlueprintShip.placedBlueprintObjects
int BlueprintShip.currentHullLevel
함선 외갑판 레벨 (0: 레벨 1, 1: 레벨 2, 2: 레벨 3) - 함선 전체에 적용되는 하나의 값
Referenced by AddPlaceable, GetHullLevel, SetBPHullLevel, SetHullLevel.
List<GameObject> BlueprintShip.previewOuterHulls
int BlueprintShip.CurrentHullLevel
List<BlueprintRoom> BlueprintShip.PlacedBlueprintRooms
List<BlueprintWeapon> BlueprintShip.PlacedBlueprintWeapons
Vector2Int BlueprintShip.CenterPosition
유저가 배치한 모든 오브젝트의 중심값 호출 (함선의 중심을 기준으로 유저에게 보이는 UI 설계)
IReadOnlyList< BlueprintRoom > BlueprintShip.GetPlacedBlueprintRooms()
현재 설계도에 배치된 방 리스트
IReadOnlyList< BlueprintWeapon > BlueprintShip.GetPlacedBlueprintWeapons()
현재 설계도에 배치된 무기 리스트
int BlueprintShip.GetTotalBPCost()
함선 설계도의 총 가격 반환
References IBlueprintPlaceable.GetCost.
Referenced by CustomizeShipUIHandler.OnClickBuild, Customize_2_Controller.OnClickBuy, Customize_2_Controller.OnEnable, Customize_1_Controller.Update, CustomizeShipUIHandler.Update.
void BlueprintShip.ClearPlacedBPObjects()
설계도에 배치된 모든 오브젝트 리스트 초기화
void BlueprintShip.SetHullLevel(int level)
현재 함선의 외갑판 레벨 설정 - 모든 무기에 적용
level 설정할 외갑판 레벨 (0-2)
References currentHullLevel, BlueprintWeapon.SetHullLevel.
Referenced by Customize_1_Controller.ReloadBlueprintFromSlot, BlueprintHullLevelInventoryUI.SetHullLevel.
int BlueprintShip.GetHullLevel()
현재 함선의 외갑판 레벨 반환
현재 외갑판 레벨 (0-2)
References currentHullLevel.
Referenced by BlueprintWeapon.GetHullLevel, GridPlacer.PlacePreviewWeapon, GridPlacer.PlaceWeapon, BlueprintWeapon.SetBlueprint, BlueprintWeapon.Start, BlueprintWeaponDragHandler.StartDragging.
IBlueprintPlaceable BlueprintShip.GetObjectAt(Vector2Int gridPos)
인자 gridPos에 위치한 오브젝트 반환
gridPos
References IBlueprintPlaceable.GetOccupiedTiles.
void BlueprintShip.AddPlaceable(IBlueprintPlaceable placeable)
설계도에 오브젝트를 추가하고 가격을 갱신합니다.
placeable 배치 가능 오브젝트
References currentHullLevel.
Referenced by Customize_2_Controller.MakeBPShipWithSaveData, GridPlacer.PlaceRoom, GridPlacer.PlaceWeapon.
void BlueprintShip.RemovePlaceable(IBlueprintPlaceable placeable)
설계도에서 오브젝트를 제거하고 가격을 갱신합니다.
placeable 배치 가능 오브젝트
Referenced by RoomSelectionHandler.ConfirmDelete.
void BlueprintShip.ClearRooms()
설계도 초기화
Referenced by Customize_2_Controller.MakeBPShipWithSaveData, Customize_1_Controller.OnClickBack, Customize_2_Controller.OnClickCancel, Customize_1_Controller.OnClickClear, CustomizeShipUIHandler.OnClickClear, Customize_0_Controller.OnClickSlot, Customize_1_Controller.ReloadBlueprintFromSlot, CustomizeShipUIHandler.SaveBPRoomsandDestroy.
void BlueprintShip.SetBPHullLevel(int level, GameObject previewOuterHullPrefab)
외갑판 세팅
level previewOuterHullPrefab
References AddPlacementIfNotDuplicate, BlueprintRoom.bpLevelIndex, BlueprintRoom.bpPosition, BlueprintRoom.bpRoomData, BlueprintRoom.bpRotation, CalculateSpriteIndex, CreateOuterHull, currentHullLevel, RoomData< T >.GetRoomDataByLevel, GameManager.Instance, Ship.outerHullData, GameManager.playerShip, BlueprintWeapon.SetHullLevel, RoomData< T >.RoomLevel.size.
Referenced by Customize_2_Controller.OnClickCancel, Customize_2_Controller.OnClickOuterHullButton, Customize_0_Controller.OnClickSlot.
void BlueprintShip.ClearPreviewOuterHulls()
void BlueprintShip.AddPlacementIfNotDuplicate(List< HullPlacementInfo > placements, HullPlacementInfo newInfo)
중복 검사 후 배치 정보 추가
Referenced by SetBPHullLevel.
int BlueprintShip.CalculateSpriteIndex(HullPlacementInfo info)
외갑판 배치 정보에 따른 스프라이트 인덱스 계산
Referenced by SetBPHullLevel.
void BlueprintShip.CreateOuterHull(Vector2Int hullPosition, int spriteIndex, int level, OuterHullData hullData, GameObject hullPrefab, OuterHullSystem.HullType hullType)
지정된 위치에 외갑판을 생성합니다.
hullPosition 외갑판 위치 spriteIndex 스프라이트 인덱스 (0-3: 하좌상우 기본, 4-7: 하좌상우 변형, 8-11: 외부 모서리, 12-15: 내부 모서리) level 외갑판 레벨 (0-2) hullData 외갑판 데이터 hullPrefab 외갑판 프리팹 hullType 외갑판 유형
References OuterHullData.GetSpecificHullSprite, Ship.GetWorldPositionFromGrid, GameManager.Instance, GameManager.playerShip.
Referenced by SetBPHullLevel.