SceneChanger
SceneChanger SceneChanger.Instance
Image SceneChanger.fadeImage
float SceneChanger.fadeDuration
bool SceneChanger.IsTransitioning
void SceneChanger.Awake()
IEnumerator SceneChanger.FadeAndSwitchScene(string sceneName)
IEnumerator SceneChanger.stillStand()
IEnumerator SceneChanger.BackToTheHome(bool isDefeated)
모선으로 복귀하라
isDefeated
References GameManager.ChangeGameState, Fade, GameManager.Instance, RTSSelectionManager.Instance, GameManager.playerShip, GameManager.SaveGameData, SetInputBlocking.
Referenced by CombatDefeatedAndGoHome.
void SceneChanger.SetInputBlocking(bool blockInput)
입력 차단/해제 설정
Referenced by BackToTheHome.
IEnumerator SceneChanger.Fade(float targetAlpha)
알파값 0 → 1 또는 1 → 0 페이드 효과
Referenced by BackToTheHome.
void SceneChanger.LoadScene(string sceneName)
외부에서 호출하는 씬 전환 함수
References GameManager.Instance, GameManager.SaveGameData.
Referenced by GameManager.ContinueGame, TradeUIController.OnGoBackButtonClicked.
void SceneChanger.JustStay()
void SceneChanger.CombatDefeatedAndGoHome(bool isDefeated)
전투 종료 후 집으로 가라
isDefeated
References BackToTheHome.