GridPlacer
GameObject GridPlacer.tilePrefab
생성할 타일의 프리팹입니다.
Referenced by GenerateTiles.
Transform GridPlacer.gridTiles
생성된 그리드 타일들의 부모 오브젝트입니다.
Referenced by GenerateTiles.
BlueprintShip GridPlacer.targetBlueprintShip
배치가 이루어질 설계도
Referenced by GetCameraStartPositionToBP, PlacePreviewWeapon, PlaceRoom, PlaceWeapon.
Ship GridPlacer.playerShip
기존 함선
Referenced by GetCameraStartPositionToOriginShip, Start.
GameObject GridPlacer.roomPrefab
공통 roomPrefab
Referenced by PlaceRoom.
GameObject GridPlacer.weaponPrefab
공통 weaponPrefab
Referenced by PlaceWeapon.
HashSet<Vector2Int> GridPlacer.occupiedGridTiles
현재 도안 설계 상태에서 점유된 타일들 (모든 배치된 오브젝트 기준)
Referenced by GetAllOccupiedTiles, IsTileOccupied, MarkObjectOccupied, Customize_1_Controller.OnClickSave, UnMarkObjectOccupied.
GameObject GridPlacer.previewRoomPrefab
GameObject GridPlacer.previewWeaponPrefab
Vector2Int GridPlacer.gridSize
Vector3 GridPlacer.gridOrigin
void GridPlacer.Start()
게임 시작 시 그리드 타일을 생성합니다.
References GenerateTiles, GameManager.Instance, playerShip, GameManager.playerShip.
void GridPlacer.GenerateTiles()
함선 커스터마이징에 사용할 그리드 생성 모든 tile object는 gridTiles 오브젝트의 자식으로 생성됩니다.
References GetWorldPositionFromGrid, gridTiles, tilePrefab.
Referenced by Start.
Vector3 GridPlacer.GridToWorldPosition(Vector2Int gridPos)
그리드 좌표를 월드 좌표로 변환합니다.
gridPos 변환할 그리드 좌표. 해당 위치의 월드 좌표.
Referenced by GetWorldPositionFromGrid.
Vector3 GridPlacer.GetWorldPositionFromGrid(Vector2Int gridPos)
실제 월드 위치 반환
gridPos
References GridToWorldPosition.
Referenced by GenerateTiles, GetCameraStartPositionToBP, GetCameraStartPositionToOriginShip, PlacePreviewRoom, PlacePreviewWeapon, PlaceRoom, PlaceWeapon, BlueprintRoom.Update, BlueprintWeapon.Update.
Vector2Int GridPlacer.WorldToGridPosition(Vector2 worldPos)
월드 좌표를 그리드 좌표로 변환합니다.
worldPos 변환할 월드 좌표. 해당 위치의 그리드 좌표.
Referenced by BlueprintRoom.Update, BlueprintWeapon.Update.
Vector3 GridPlacer.GetCameraStartPositionToBP()
설게도 화면에서 camera의 시작 위치 보정 설계도에 방이 없을 시 그리드 중앙 시작 설계도에 방이 있을 경우 방 들의 중앙 위치에서 시작
References IBlueprintPlaceable.GetOccupiedTiles, GetWorldPositionFromGrid, targetBlueprintShip.
Referenced by Customize_1_Controller.CenterCameraToBP, CustomizeShipUIHandler.CenterCameraToBP.
Vector3 GridPlacer.GetCameraStartPositionToOriginShip()
기존 소유 함선을 이루는 방들의 중심으로 카메라 시작 위치 보정
References Ship.GetAllRooms, Ship.GetAllWeapons, BlueprintWeapon.GetGridPosition, BlueprintRoom.GetOccupiedTiles, GetWorldPositionFromGrid, playerShip.
Referenced by Customize_1_Controller.ResetCameraToOriginShip, CustomizeShipUIHandler.ResetCameraToOriginShip.
bool GridPlacer.IsInGrid(Vector2Int tile)
해당 타일이 그리드 범위 내에 있는지 검사
tile
Referenced by CanPlaceObject, CanPlaceRoom, CanPlaceWeapon.
bool GridPlacer.IsTileOccupied(Vector2Int tile)
해당 타일이 현재 다른 오브젝트에 의해 점유되어 있는지 검사
tile
References occupiedGridTiles.
Referenced by CanPlaceObject, CanPlaceRoom, CanPlaceWeapon.
void GridPlacer.MarkObjectOccupied(IBlueprintPlaceable placeable)
해당 오브젝트가 점유하고 있는 모든 타일을 전체 점유 목록에 추가
placeable 배치 가능 오브젝트
References IBlueprintPlaceable.GetOccupiedTiles, occupiedGridTiles.
Referenced by PlaceRoom, PlaceWeapon, BlueprintRoom.Update, BlueprintWeapon.Update.
void GridPlacer.UnMarkObjectOccupied(IBlueprintPlaceable placeable)
특정 오브젝트 제거 시 점유 타일 목록에서 제거
placeable 배치 가능 오브젝트
References IBlueprintPlaceable.GetOccupiedTiles, occupiedGridTiles.
Referenced by RoomSelectionHandler.ConfirmDelete, BlueprintRoom.Update, BlueprintWeapon.Update.
IEnumerable< Vector2Int > GridPlacer.GetAllOccupiedTiles()
디버깅 용 점유 타일 반환
References occupiedGridTiles.
bool GridPlacer.CanPlaceObject(IBlueprintPlaceable placeable, Vector2Int position, object rotation)
해당 오브젝트를 현재 위치와 회전 상태로 배치 가능한지 검사
References IBlueprintPlaceable.GetGridPosition, IBlueprintPlaceable.GetOccupiedTiles, IBlueprintPlaceable.GetRotation, IsInGrid, IsTileOccupied, IBlueprintPlaceable.SetGridPosition.
bool GridPlacer.CanPlaceRoom(RoomData data, int level, Vector2Int position, Constants.Rotations.Rotation rotation)
해당 방을 현재 위치와 회전 상태로 배치 가능한지 검사 (이전 버전과의 호환성 유지)
References RoomData< T >.GetRoomDataByLevel, IsInGrid, IsTileOccupied, RoomData< T >.RoomLevel.size.
Referenced by BlueprintRoom.Update.
bool GridPlacer.CanPlaceWeapon(ShipWeaponData data, Vector2Int position, ShipWeaponAttachedDirection direction)
해당 무기를 현재 위치와 부착 방향으로 배치 가능한지 검사
References IsInGrid, IsTileOccupied.
Referenced by BlueprintWeapon.Update.
void GridPlacer.PlaceRoom(RoomData data, int level, Vector2Int position, Constants.Rotations.Rotation rotation)
실제 방을 해당 위치에 배치함
References BlueprintShip.AddPlaceable, RoomData< T >.GetRoomDataByLevel, GetWorldPositionFromGrid, BlueprintRoom.Initialize, MarkObjectOccupied, roomPrefab, BlueprintRoom.SetBlueprint, BlueprintRoom.SetGridPlacer, RoomData< T >.RoomLevel.size, targetBlueprintShip.
Referenced by CustomizeShipUIHandler.GetSavedBPRooms, Customize_1_Controller.ReloadBlueprintFromSlot.
BlueprintWeapon GridPlacer.PlaceWeapon(ShipWeaponData data, Vector2Int position, ShipWeaponAttachedDirection direction)
실제 무기를 해당 위치에 배치함
생성된 BlueprintWeapon 인스턴스
References BlueprintShip.AddPlaceable, BlueprintShip.GetHullLevel, GetWorldPositionFromGrid, BlueprintWeapon.Initialize, MarkObjectOccupied, BlueprintWeapon.SetBlueprint, BlueprintWeapon.SetGridPlacer, BlueprintWeapon.SetHullLevel, targetBlueprintShip, weaponPrefab.
Referenced by CustomizeShipUIHandler.GetSavedWeaponRooms, Customize_1_Controller.ReloadBlueprintFromSlot.
GameObject GridPlacer.PlacePreviewRoom(RoomData data, int level, Vector2Int position, Constants.Rotations.Rotation rotation, Transform previewRoot, List< Vector2Int > tilePos)
실제 방을 해당 위치에 배치함
References RoomData< T >.GetRoomDataByLevel, GetWorldPositionFromGrid, BlueprintRoom.Initialize, RoomData< T >.RoomLevel.size.
Referenced by Customize_2_Controller.MakeBPShipWithSaveData, BPPreviewArea.UpdateAndShow.
GameObject GridPlacer.PlacePreviewWeapon(ShipWeaponData data, Vector2Int position, ShipWeaponAttachedDirection direction, Transform previewRoot, List< Vector2Int > tilePos)
실제 무기를 해당 위치에 배치함
생성된 BlueprintWeapon 인스턴스
References BlueprintWeapon.bpPosition, BlueprintShip.GetHullLevel, GetWorldPositionFromGrid, BlueprintWeapon.Initialize, BlueprintWeapon.SetHullLevel, targetBlueprintShip.
Referenced by Customize_2_Controller.MakeBPShipWithSaveData, BPPreviewArea.UpdateAndShow.