BPPreviewArea
Transform BPPreviewArea.previewRoot
BPPreviewCamera BPPreviewArea.previewCamera
GridPlacer BPPreviewArea.gridPlacer
List<GameObject> BPPreviewArea.spawnedPreviews
void BPPreviewArea.UpdateAndShow(BlueprintSaveData data)
도안 preview Area에 띄우기 (미리보기)
data
References Clear, BPPreviewCamera.FitToBlueprint, GridPlacer.PlacePreviewRoom, GridPlacer.PlacePreviewWeapon.
Referenced by Customize_2_Controller.OnClickBuy, Customize_0_Controller.OnClickSlot.
void BPPreviewArea.Clear()
생성된 preview 게임 오브젝트 모두 삭제
Referenced by Customize_0_Controller.OnClickSlot, UpdateAndShow.
Vector3 BPPreviewArea.GridToWorldPosition(Vector2Int gridPos)
그리드 좌표를 월드 좌표로 변환합니다.
gridPos 변환할 그리드 좌표. 해당 위치의 월드 좌표.
Referenced by GetWorldPositionFromGrid.
Vector3 BPPreviewArea.GetWorldPositionFromGrid(Vector2Int gridPos)
실제 월드 위치 반환
gridPos
References GridToWorldPosition.