BlueprintDragManager
DragType
BlueprintDragManager BlueprintDragManager.Instance
DragType BlueprintDragManager.currentDragType
현재 드래그 중인 오브젝트 타입
Referenced by StartRoomDrag, StartWeaponDrag, StopDrag.
bool BlueprintDragManager.IsDragging
현재 드래그 중인지 여부
Referenced by StartRoomDrag, StartWeaponDrag.
bool BlueprintDragManager.IsRoomBeingDragged
방 드래그 중인지 여부
bool BlueprintDragManager.IsWeaponBeingDragged
무기 드래그 중인지 여부
void BlueprintDragManager.Awake()
bool BlueprintDragManager.StartRoomDrag()
방 드래그 시작
드래그 시작 가능 여부
References currentDragType, IsDragging.
Referenced by BlueprintRoomDragHandler.StartDragging.
bool BlueprintDragManager.StartWeaponDrag()
무기 드래그 시작
드래그 시작 가능 여부
References currentDragType, IsDragging.
Referenced by BlueprintWeaponDragHandler.StartDragging.
void BlueprintDragManager.StopDrag()
드래그 종료
References currentDragType.
Referenced by BlueprintRoomDragHandler.StopDragging, BlueprintWeaponDragHandler.StopDragging.