BPPreviewCamera
Camera BPPreviewCamera.previewCamera
float BPPreviewCamera.padding
void BPPreviewCamera.RenderOnce()
void BPPreviewCamera.FitToBlueprint(List< Vector2Int > tilePositions)
preview Area 사이즈에 맞게 도안 띄우기
tilePositions
References GridToWorldPosition.
Referenced by BPPreviewArea.UpdateAndShow.
Vector3 BPPreviewCamera.GridToWorldPosition(Vector2 gridPos)
그리드 좌표를 월드 좌표로 변환합니다.
gridPos 변환할 그리드 좌표. 해당 위치의 월드 좌표.
Referenced by FitToBlueprint, GetWorldPositionFromGrid.
Vector3 BPPreviewCamera.GetWorldPositionFromGrid(Vector2 gridPos)
실제 월드 위치 반환
gridPos
References GridToWorldPosition.
IEnumerator BPPreviewCamera.RenderAtEndOfFrame()