ES3
Location
Directory
EncryptionType
CompressionType
Format
ReferenceMode
ImageType
static void ES3.Save(string key, object value)
key The key we want to use to identify our value in the file. value The value we want to save.
Referenced by GameManager.SavePlayerData.
static void ES3.Save(string key, object value, string filePath)
Saves the value to a file with the given key.
key The key we want to use to identify our value in the file. value The value we want to save. filePath The relative or absolute path of the file we want to store our value to.
static void ES3.Save(string key, object value, string filePath, ES3Settings settings)
Saves the value to a file with the given key.
key The key we want to use to identify our value in the file. value The value we want to save. filePath The relative or absolute path of the file we want to store our value to. settings The settings we want to use to override the default settings.
static void ES3.Save(string key, object value, ES3Settings settings)
Saves the value to a file with the given key.
key The key we want to use to identify our value in the file. value The value we want to save. settings The settings we want to use to override the default settings.
static void ES3.Save< T >(string key, T value)
Saves the value to the default file with the given key.
T The type of the data that we want to save. key The key we want to use to identify our value in the file. value The value we want to save.
References Save< T >.
Referenced by Save< T >, Save< T >, Save< T >.
static void ES3.Save< T >(string key, T value, string filePath)
Saves the value to a file with the given key.
T The type of the data that we want to save. key The key we want to use to identify our value in the file. value The value we want to save. filePath The relative or absolute path of the file we want to store our value to.
References Save< T >.
static void ES3.Save< T >(string key, T value, string filePath, ES3Settings settings)
Saves the value to a file with the given key.
T The type of the data that we want to save. key The key we want to use to identify our value in the file. value The value we want to save. filePath The relative or absolute path of the file we want to store our value to. settings The settings we want to use to override the default settings.
References Save< T >.
static void ES3.Save< T >(string key, T value, ES3Settings settings)
Saves the value to a file with the given key.
T The type of the data that we want to save. key The key we want to use to identify our value in the file. value The value we want to save. settings The settings we want to use to override the default settings.
References ES3Writer.Create, ES3Settings.location.
static void ES3.SaveRaw(byte[] bytes)
Creates or overwrites a file with the specified raw bytes.
bytes The bytes we want to store.
References SaveRaw.
Referenced by SaveImage, SaveRaw, SaveRaw, SaveRaw, SaveRaw, SaveRaw, SaveRaw, SaveRaw.
static void ES3.SaveRaw(byte[] bytes, string filePath)
Creates or overwrites a file with the specified raw bytes.
bytes The bytes we want to store. filePath The relative or absolute path of the file we want to store our bytes to.
References SaveRaw.
static void ES3.SaveRaw(byte[] bytes, string filePath, ES3Settings settings)
Creates or overwrites a file with the specified raw bytes.
bytes The bytes we want to store. filePath The relative or absolute path of the file we want to store our bytes to. settings The settings we want to use to override the default settings.
References SaveRaw.
static void ES3.SaveRaw(byte[] bytes, ES3Settings settings)
Creates or overwrites a file with the specified raw bytes.
bytes The bytes we want to store. settings The settings we want to use to override the default settings.
References ES3Settings.location, ES3File.SaveRaw.
static void ES3.SaveRaw(string str)
Creates or overwrites the default file with the specified raw bytes.
str The string we want to store.
References SaveRaw.
static void ES3.SaveRaw(string str, string filePath)
Creates or overwrites the default file with the specified raw bytes.
str The string we want to store. filePath The relative or absolute path of the file we want to store our bytes to.
References SaveRaw.
static void ES3.SaveRaw(string str, string filePath, ES3Settings settings)
Creates or overwrites a file with the specified raw bytes.
str The string we want to store. filePath The relative or absolute path of the file we want to store our bytes to. settings The settings we want to use to override the default settings.
References SaveRaw.
static void ES3.SaveRaw(string str, ES3Settings settings)
Creates or overwrites a file with the specified raw bytes.
str The string we want to store. settings The settings we want to use to override the default settings.
References ES3Settings.encoding, SaveRaw.
static void ES3.AppendRaw(byte[] bytes)
Creates or appends the specified bytes to a file.
bytes The bytes we want to append.
References AppendRaw.
Referenced by AppendRaw, AppendRaw, AppendRaw, AppendRaw, AppendRaw.
static void ES3.AppendRaw(byte[] bytes, string filePath, ES3Settings settings)
Creates or appends the specified bytes to a file.
bytes The bytes we want to append. filepath The relative or absolute path of the file we want to append our bytes to. settings The settings we want to use to override the default settings.
References AppendRaw.
static void ES3.AppendRaw(byte[] bytes, ES3Settings settings)
Creates or appends the specified bytes to a file.
bytes The bytes we want to append. settings The settings we want to use to override the default settings.
References ES3File.AppendRaw, ES3Settings.location, ES3Settings.path.
static void ES3.AppendRaw(string str)
Creates or appends the specified string to the default file.
str The string we want to append.
References AppendRaw.
static void ES3.AppendRaw(string str, string filePath)
Creates or appends the specified string to the default file.
str The string we want to append. filePath The relative or absolute path of the file we want to append our string to.
References AppendRaw.
static void ES3.AppendRaw(string str, string filePath, ES3Settings settings)
Creates or appends the specified string to the default file.
str The string we want to append. filePath The relative or absolute path of the file we want to append our string to. settings The settings we want to use to override the default settings.
References AppendRaw.
static void ES3.AppendRaw(string str, ES3Settings settings)
Creates or appends the specified string to the default file.
str The string we want to append. settings The settings we want to use to override the default settings.
References ES3Settings.encoding, ES3Settings.location, ES3Settings.path, ES3File.SaveRaw.
static void ES3.SaveImage(Texture2D texture, string imagePath)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. imagePath The relative or absolute path of the PNG or JPG file we want to create.
References SaveImage.
Referenced by SaveImage, SaveImage, SaveImage, SaveImage, SaveImage.
static void ES3.SaveImage(Texture2D texture, string imagePath, ES3Settings settings)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. imagePath The relative or absolute path of the PNG or JPG file we want to create.
References SaveImage.
static void ES3.SaveImage(Texture2D texture, ES3Settings settings)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. settings The settings we want to use to override the default settings.
References SaveImage.
static void ES3.SaveImage(Texture2D texture, int quality, string imagePath)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. quality Quality to encode with, where 1 is minimum and 100 is maximum. Note that this only applies to JPGs. imagePath The relative or absolute path of the PNG or JPG file we want to create.
References SaveImage.
static void ES3.SaveImage(Texture2D texture, int quality, string imagePath, ES3Settings settings)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. quality Quality to encode with, where 1 is minimum and 100 is maximum. Note that this only applies to JPGs. imagePath The relative or absolute path of the PNG or JPG file we want to create.
References SaveImage.
static void ES3.SaveImage(Texture2D texture, int quality, ES3Settings settings)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. quality Quality to encode with, where 1 is minimum and 100 is maximum. Note that this only applies to JPGs. settings The settings we want to use to override the default settings.
References ES3Settings.path, SaveRaw.
static byte[] ES3.SaveImageToBytes(Texture2D texture, int quality, ES3.ImageType imageType)
Saves a Texture2D as a PNG or JPG, depending on the file extension used for the filePath.
texture The Texture2D we want to save as a JPG or PNG. quality Quality to encode with, where 1 is minimum and 100 is maximum. Note that this only applies to JPGs.
static object ES3.Load(string key)
Loads the value from a file with the given key.
key The key which identifies the value we want to load.
Referenced by GameManager.LoadPlayerData, CrewFactory.RestoreCrewFromES3.
static object ES3.Load(string key, string filePath)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from.
static object ES3.Load(string key, string filePath, ES3Settings settings)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. settings The settings we want to use to override the default settings.
static object ES3.Load(string key, ES3Settings settings)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. settings The settings we want to use to override the default settings.
static object ES3.Load(string key, object defaultValue)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist.
static object ES3.Load(string key, string filePath, object defaultValue)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. defaultValue The value we want to return if the file or key does not exist.
static object ES3.Load(string key, string filePath, object defaultValue, ES3Settings settings)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. defaultValue The value we want to return if the file or key does not exist. settings The settings we want to use to override the default settings.
static object ES3.Load(string key, object defaultValue, ES3Settings settings)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist. settings The settings we want to use to override the default settings.
static T ES3.Load< T >(string key)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load.
References Load< T >.
Referenced by Load< T >, Load< T >, Load< T >, Load< T >, Load< T >, Load< T >.
static T ES3.Load< T >(string key, string filePath)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from.
References Load< T >.
static T ES3.Load< T >(string key, string filePath, ES3Settings settings)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. settings The settings we want to use to override the default settings.
References Load< T >.
static T ES3.Load< T >(string key, ES3Settings settings)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. settings The settings we want to use to override the default settings.
References ES3Reader.Create, ES3Settings.FullPath, ES3File.Load, ES3Settings.location.
static T ES3.Load< T >(string key, T defaultValue)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist.
References Load< T >.
static T ES3.Load< T >(string key, string filePath, T defaultValue)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. defaultValue The value we want to return if the file or key does not exist.
References Load< T >.
static T ES3.Load< T >(string key, string filePath, T defaultValue, ES3Settings settings)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. defaultValue The value we want to return if the file or key does not exist. settings The settings we want to use to override the default settings.
References Load< T >.
static T ES3.Load< T >(string key, T defaultValue, ES3Settings settings)
Loads the value from a file with the given key.
T The type of the data that we want to load. key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist. settings The settings we want to use to override the default settings.
References ES3Reader.Create, ES3File.Load, ES3Settings.location.
static void ES3.LoadInto< T >(string key, object obj)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
key The key which identifies the value we want to load. obj The object we want to load the value into.
Referenced by LoadInto< T >, LoadInto< T >, LoadInto< T >.
static void ES3.LoadInto(string key, string filePath, object obj)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. obj The object we want to load the value into.
static void ES3.LoadInto(string key, string filePath, object obj, ES3Settings settings)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. obj The object we want to load the value into. settings The settings we want to use to override the default settings.
static void ES3.LoadInto(string key, object obj, ES3Settings settings)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
key The key which identifies the value we want to load. obj The object we want to load the value into. settings The settings we want to use to override the default settings.
static void ES3.LoadInto< T >(string key, T obj)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
T The type of the data that we want to load. key The key which identifies the value we want to load. obj The object we want to load the value into.
References LoadInto< T >.
static void ES3.LoadInto< T >(string key, string filePath, T obj)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. obj The object we want to load the value into.
References LoadInto< T >.
static void ES3.LoadInto< T >(string key, string filePath, T obj, ES3Settings settings)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
T The type of the data that we want to load. key The key which identifies the value we want to load. filePath The relative or absolute path of the file we want to load from. obj The object we want to load the value into. settings The settings we want to use to override the default settings.
References LoadInto< T >.
static void ES3.LoadInto< T >(string key, T obj, ES3Settings settings)
Loads the value from a file with the given key into an existing object, rather than creating a new instance.
T The type of the data that we want to load. key The key which identifies the value we want to load. obj The object we want to load the value into. settings The settings we want to use to override the default settings.
References ES3Reader.Create.
static string ES3.LoadString(string key, string defaultValue, ES3Settings settings)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist. settings The settings we want to use to override the default settings.
static string ES3.LoadString(string key, string defaultValue, string filePath=null, ES3Settings settings=null)
Loads the value from a file with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the file or key does not exist. filePath The relative or absolute path of the file we want to load from. settings The settings we want to use to override the default settings.
static byte[] ES3.LoadRawBytes()
Loads the default file as a byte array.
References LoadRawBytes.
Referenced by LoadImage, LoadRawBytes, LoadRawBytes, LoadRawBytes, LoadRawString, ES3Cloud.UploadFile.
static byte[] ES3.LoadRawBytes(string filePath)
Loads a file as a byte array.
filePath The relative or absolute path of the file we want to load as a byte array.
References LoadRawBytes.
static byte[] ES3.LoadRawBytes(string filePath, ES3Settings settings)
Loads a file as a byte array.
filePath The relative or absolute path of the file we want to load as a byte array. settings The settings we want to use to override the default settings.
References LoadRawBytes.
static byte[] ES3.LoadRawBytes(ES3Settings settings)
Loads the default file as a byte array.
settings The settings we want to use to override the default settings.
References ES3Settings.FullPath, ES3File.LoadRawBytes, ES3Settings.location, ES3Settings.path.
static string ES3.LoadRawString()
Loads the default file as a byte array.
References LoadRawString.
Referenced by LoadRawString, LoadRawString, LoadRawString.
static string ES3.LoadRawString(string filePath)
Loads a file as a byte array.
filePath The relative or absolute path of the file we want to load as a byte array. settings The settings we want to use to override the default settings.
References LoadRawString.
static string ES3.LoadRawString(string filePath, ES3Settings settings)
Loads a file as a byte array.
filePath The relative or absolute path of the file we want to load as a byte array. settings The settings we want to use to override the default settings.
References LoadRawString.
static string ES3.LoadRawString(ES3Settings settings)
Loads the default file as a byte array.
settings The settings we want to use to override the default settings.
References ES3Settings.encoding, LoadRawBytes.
static Texture2D ES3.LoadImage(string imagePath)
Loads a PNG or JPG as a Texture2D.
imagePath The relative or absolute path of the PNG or JPG file we want to load as a Texture2D. settings The settings we want to use to override the default settings.
References LoadImage.
Referenced by LoadImage, LoadImage, LoadImage.
static Texture2D ES3.LoadImage(string imagePath, ES3Settings settings)
Loads a PNG or JPG as a Texture2D.
imagePath The relative or absolute path of the PNG or JPG file we want to load as a Texture2D. settings The settings we want to use to override the default settings.
References LoadImage.
static Texture2D ES3.LoadImage(ES3Settings settings)
Loads a PNG or JPG as a Texture2D.
settings The settings we want to use to override the default settings.
References LoadImage, LoadRawBytes.
static Texture2D ES3.LoadImage(byte[] bytes)
Loads a PNG or JPG as a Texture2D.
bytes The raw bytes of the PNG or JPG.
static AudioClip ES3.LoadAudio(string audioFilePath)
Loads an audio file as an AudioClip. Note that MP3 files are not supported on standalone platforms and Ogg Vorbis files are not supported on mobile platforms.
imagePath The relative or absolute path of the audio file we want to load as an AudioClip.
References LoadAudio.
Referenced by LoadAudio.
static AudioClip ES3.LoadAudio(string audioFilePath, ES3Settings settings)
Loads an audio file as an AudioClip. Note that MP3 files are not supported on standalone platforms and Ogg Vorbis files are not supported on mobile platforms.
imagePath The relative or absolute path of the audio file we want to load as an AudioClip. settings The settings we want to use to override the default settings.
static byte[] ES3.Serialize< T >(T value, ES3Settings settings=null)
static T ES3.Deserialize< T >(byte[] bytes, ES3Settings settings=null)
static void ES3.DeserializeInto< T >(byte[] bytes, T obj, ES3Settings settings=null)
static void ES3.DeserializeInto< T >(ES3Types.ES3Type type, byte[] bytes, T obj, ES3Settings settings=null)
static byte[] ES3.EncryptBytes(byte[] bytes, string password=null)
static byte[] ES3.DecryptBytes(byte[] bytes, string password=null)
static string ES3.EncryptString(string str, string password=null)
static string ES3.DecryptString(string str, string password=null)
static byte[] ES3.CompressBytes(byte[] bytes)
static byte[] ES3.DecompressBytes(byte[] bytes)
static string ES3.CompressString(string str)
static string ES3.DecompressString(string str)
static void ES3.DeleteFile()
Deletes the default file.
References DeleteFile.
Referenced by DeleteFile, DeleteFile, DeleteFile, ES3File.Sync.
static void ES3.DeleteFile(string filePath)
Deletes the file at the given path using the default settings.
filePath The relative or absolute path of the file we wish to delete.
References DeleteFile.
static void ES3.DeleteFile(string filePath, ES3Settings settings)
Deletes the file at the given path using the settings provided.
filePath The relative or absolute path of the file we wish to delete. settings The settings we want to use to override the default settings.
References DeleteFile.
static void ES3.DeleteFile(ES3Settings settings)
Deletes the file specified by the ES3Settings object provided as a parameter.
settings The settings we want to use to override the default settings.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.CopyFile(string oldFilePath, string newFilePath)
Copies a file from one path to another.
oldFilePath The relative or absolute path of the file we want to copy. newFilePath The relative or absolute path of the copy we want to create.
References CopyFile.
Referenced by CopyDirectory, CopyFile, CopyFile, CreateBackup.
static void ES3.CopyFile(string oldFilePath, string newFilePath, ES3Settings oldSettings, ES3Settings newSettings)
Copies a file from one location to another, using the ES3Settings provided to override any default settings.
oldFilePath The relative or absolute path of the file we want to copy. newFilePath The relative or absolute path of the copy we want to create. oldSettings The settings we want to use when copying the old file. newSettings The settings we want to use when creating the new file.
References CopyFile.
static void ES3.CopyFile(ES3Settings oldSettings, ES3Settings newSettings)
Copies a file from one location to another, using the ES3Settings provided to determine the locations.
oldSettings The settings we want to use when copying the old file. newSettings The settings we want to use when creating the new file.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.RenameFile(string oldFilePath, string newFilePath)
Renames a file.
oldFilePath The relative or absolute path of the file we want to rename. newFilePath The relative or absolute path we want to rename the file to.
References RenameFile.
Referenced by RenameFile, RenameFile, RestoreBackup.
static void ES3.RenameFile(string oldFilePath, string newFilePath, ES3Settings oldSettings, ES3Settings newSettings)
Renames a file.
oldFilePath The relative or absolute path of the file we want to rename. newFilePath The relative or absolute path we want to rename the file to. oldSettings The settings for the file we want to rename. newSettings The settings for the file we want our source file to be renamed to.
References RenameFile.
static void ES3.RenameFile(ES3Settings oldSettings, ES3Settings newSettings)
Renames a file.
oldSettings The settings for the file we want to rename. newSettings The settings for the file we want our source file to be renamed to.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.CopyDirectory(string oldDirectoryPath, string newDirectoryPath)
Copies a file from one path to another.
oldDirectoryPath The relative or absolute path of the directory we want to copy. newDirectoryPath The relative or absolute path of the copy we want to create.
References CopyDirectory.
Referenced by CopyDirectory, CopyDirectory, CopyDirectory.
static void ES3.CopyDirectory(string oldDirectoryPath, string newDirectoryPath, ES3Settings oldSettings, ES3Settings newSettings)
Copies a file from one location to another, using the ES3Settings provided to override any default settings.
oldDirectoryPath The relative or absolute path of the directory we want to copy. newDirectoryPath The relative or absolute path of the copy we want to create. oldSettings The settings we want to use when copying the old directory. newSettings The settings we want to use when creating the new directory.
References CopyDirectory.
static void ES3.CopyDirectory(ES3Settings oldSettings, ES3Settings newSettings)
Copies a file from one location to another, using the ES3Settings provided to determine the locations.
oldSettings The settings we want to use when copying the old file. newSettings The settings we want to use when creating the new file.
References CopyDirectory, CopyFile, DirectoryExists, ES3Settings.FullPath, GetDirectories, GetFiles, ES3Settings.location.
static void ES3.RenameDirectory(string oldDirectoryPath, string newDirectoryPath)
Renames a file.
oldDirectoryPath The relative or absolute path of the file we want to rename. newDirectoryPath The relative or absolute path we want to rename the file to.
References RenameDirectory.
Referenced by RenameDirectory, RenameDirectory.
static void ES3.RenameDirectory(string oldDirectoryPath, string newDirectoryPath, ES3Settings oldSettings, ES3Settings newSettings)
Renames a file.
oldDirectoryPath The relative or absolute path of the file we want to rename. newDirectoryPath The relative or absolute path we want to rename the file to. oldSettings The settings for the file we want to rename. newSettings The settings for the file we want our source file to be renamed to.
References RenameDirectory.
static void ES3.RenameDirectory(ES3Settings oldSettings, ES3Settings newSettings)
Renames a file.
oldSettings The settings for the file we want to rename. newSettings The settings for the file we want our source file to be renamed to.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.DeleteDirectory(string directoryPath)
Deletes the directory at the given path using the settings provided.
directoryPath The relative or absolute path of the folder we wish to delete.
References DeleteDirectory.
Referenced by DeleteDirectory, DeleteDirectory.
static void ES3.DeleteDirectory(string directoryPath, ES3Settings settings)
Deletes the directory at the given path using the settings provided.
directoryPath The relative or absolute path of the folder we wish to delete. settings The settings we want to use to override the default settings.
References DeleteDirectory.
static void ES3.DeleteDirectory(ES3Settings settings)
Deletes the directory at the given path using the settings provided.
settings The settings we want to use to override the default settings.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.DeleteKey(string key)
Deletes a key in the default file.
key The key we want to delete.
References DeleteKey.
Referenced by DeleteKey, DeleteKey.
static void ES3.DeleteKey(string key, string filePath)
static void ES3.DeleteKey(string key, string filePath, ES3Settings settings)
Deletes a key in the file specified.
key The key we want to delete. key The relative or absolute path of the file we want to delete the key from. settings The settings we want to use to override the default settings.
References DeleteKey.
static void ES3.DeleteKey(string key, ES3Settings settings)
Deletes a key in the file specified by the ES3Settings object.
key The key we want to delete. settings The settings we want to use to override the default settings.
References ES3Writer.Create, ES3File.DeleteKey, FileExists, ES3Settings.location.
static bool ES3.KeyExists(string key)
Checks whether a key exists in the default file.
key The key we want to check the existence of. True if the key exists, otherwise False.
References KeyExists.
Referenced by KeyExists, KeyExists, KeyExists, GameManager.LoadPlayerData, CrewFactory.RestoreCrewFromES3.
static bool ES3.KeyExists(string key, string filePath)
Checks whether a key exists in the specified file.
key The key we want to check the existence of. filePath The relative or absolute path of the file we want to search. True if the key exists, otherwise False.
References KeyExists.
static bool ES3.KeyExists(string key, string filePath, ES3Settings settings)
Checks whether a key exists in the default file.
key The key we want to check the existence of. filePath The relative or absolute path of the file we want to search. settings The settings we want to use to override the default settings. True if the key exists, otherwise False.
References KeyExists.
static bool ES3.KeyExists(string key, ES3Settings settings)
Checks whether a key exists in a file.
key The key we want to check the existence of. settings The settings we want to use to override the default settings. True if the file exists, otherwise False.
References ES3Reader.Create, ES3File.KeyExists, ES3Settings.location.
static bool ES3.FileExists()
Checks whether the default file exists.
filePath The relative or absolute path of the file we want to check the existence of. True if the file exists, otherwise False.
References FileExists.
Referenced by DeleteKey, FileExists, FileExists, FileExists, GameManager.LoadPlayerData, RestoreBackup, CrewFactory.RestoreCrewFromES3, ES3Cloud.Sync.
static bool ES3.FileExists(string filePath)
Checks whether a file exists.
filePath The relative or absolute path of the file we want to check the existence of. True if the file exists, otherwise False.
References FileExists.
static bool ES3.FileExists(string filePath, ES3Settings settings)
Checks whether a file exists.
filePath The relative or absolute path of the file we want to check the existence of. settings The settings we want to use to override the default settings. True if the file exists, otherwise False.
References FileExists.
static bool ES3.FileExists(ES3Settings settings)
Checks whether a file exists.
settings The settings we want to use to override the default settings. True if the file exists, otherwise False.
References ES3Settings.FullPath, ES3Settings.location.
static bool ES3.DirectoryExists(string folderPath)
Checks whether a folder exists.
folderPath The relative or absolute path of the folder we want to check the existence of. True if the folder exists, otherwise False.
References DirectoryExists.
Referenced by CopyDirectory, DirectoryExists, DirectoryExists.
static bool ES3.DirectoryExists(string folderPath, ES3Settings settings)
Checks whether a file exists.
folderPath The relative or absolute path of the folder we want to check the existence of. settings The settings we want to use to override the default settings. True if the folder exists, otherwise False.
References DirectoryExists.
static bool ES3.DirectoryExists(ES3Settings settings)
Checks whether a folder exists.
settings The settings we want to use to override the default settings. True if the folder exists, otherwise False.
References ES3Settings.FullPath, ES3Settings.location.
static string[] ES3.GetKeys()
Gets an array of all of the key names in the default file.
References GetKeys.
Referenced by GetKeys, GetKeys, GetKeys.
static string[] ES3.GetKeys(string filePath)
Gets an array of all of the key names in a file.
filePath The relative or absolute path of the file we want to get the key names from.
References GetKeys.
static string[] ES3.GetKeys(string filePath, ES3Settings settings)
Gets an array of all of the key names in a file.
filePath The relative or absolute path of the file we want to get the key names from. settings The settings we want to use to override the default settings.
References GetKeys.
static string[] ES3.GetKeys(ES3Settings settings)
Gets an array of all of the key names in a file.
settings The settings we want to use to override the default settings.
References ES3Reader.Create, ES3Settings.FullPath, ES3File.GetKeys, ES3Settings.location.
static string[] ES3.GetFiles()
Gets an array of all of the file names in a directory.
References GetFiles.
Referenced by CopyDirectory, GetFiles, GetFiles, GetFiles.
static string[] ES3.GetFiles(string directoryPath)
Gets an array of all of the file names in a directory.
directoryPath The relative or absolute path of the directory we want to get the file names from.
References GetFiles.
static string[] ES3.GetFiles(string directoryPath, ES3Settings settings)
Gets an array of all of the file names in a directory.
directoryPath The relative or absolute path of the directory we want to get the file names from. settings The settings we want to use to override the default settings.
References GetFiles.
static string[] ES3.GetFiles(ES3Settings settings)
Gets an array of all of the file names in a directory.
settings The settings we want to use to override the default settings.
References ES3Settings.FullPath, ES3Settings.location.
static string[] ES3.GetDirectories()
Gets an array of all of the sub-directory names in a directory.
References GetDirectories.
Referenced by CopyDirectory, GetDirectories, GetDirectories, GetDirectories.
static string[] ES3.GetDirectories(string directoryPath)
Gets an array of all of the sub-directory names in a directory.
directoryPath The relative or absolute path of the directory we want to get the sub-directory names from.
References GetDirectories.
static string[] ES3.GetDirectories(string directoryPath, ES3Settings settings)
Gets an array of all of the sub-directory names in a directory.
directoryPath The relative or absolute path of the directory we want to get the sub-directory names from. settings The settings we want to use to override the default settings.
References GetDirectories.
static string[] ES3.GetDirectories(ES3Settings settings)
Gets an array of all of the sub-directory names in a directory.
settings The settings we want to use to override the default settings.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.CreateBackup()
Creates a backup of the default file .
A backup is created by copying the file and giving it a .bak extension. If a backup already exists it will be overwritten, so you will need to ensure that the old backup will not be required before calling this method.
References CreateBackup.
Referenced by CreateBackup, CreateBackup, CreateBackup.
static void ES3.CreateBackup(string filePath)
Creates a backup of a file.
A backup is created by copying the file and giving it a .bak extension. If a backup already exists it will be overwritten, so you will need to ensure that the old backup will not be required before calling this method. filePath The relative or absolute path of the file we wish to create a backup of.
References CreateBackup.
static void ES3.CreateBackup(string filePath, ES3Settings settings)
Creates a backup of a file.
A backup is created by copying the file and giving it a .bak extension. If a backup already exists it will be overwritten, so you will need to ensure that the old backup will not be required before calling this method. filePath The relative or absolute path of the file we wish to create a backup of. settings The settings we want to use to override the default settings.
References CreateBackup.
static void ES3.CreateBackup(ES3Settings settings)
Creates a backup of a file.
A backup is created by copying the file and giving it a .bak extension. If a backup already exists it will be overwritten, so you will need to ensure that the old backup will not be required before calling this method. settings The settings we want to use to override the default settings.
References CopyFile, ES3Settings.path.
static bool ES3.RestoreBackup(string filePath)
Restores a backup of a file.
filePath The relative or absolute path of the file we wish to restore the backup of. True if a backup was restored, or False if no backup could be found.
References RestoreBackup.
Referenced by RestoreBackup, RestoreBackup.
static bool ES3.RestoreBackup(string filePath, ES3Settings settings)
Restores a backup of a file.
filePath The relative or absolute path of the file we wish to restore the backup of. settings The settings we want to use to override the default settings. True if a backup was restored, or False if no backup could be found.
References RestoreBackup.
static bool ES3.RestoreBackup(ES3Settings settings)
Restores a backup of a file.
settings The settings we want to use to override the default settings. True if a backup was restored, or False if no backup could be found.
References FileExists, ES3Settings.path, RenameFile.
static DateTime ES3.GetTimestamp()
static DateTime ES3.GetTimestamp(string filePath)
static DateTime ES3.GetTimestamp(string filePath, ES3Settings settings)
static DateTime ES3.GetTimestamp(ES3Settings settings)
Gets the date and time the file was last updated, in the UTC timezone.
settings The settings we want to use to override the default settings. A DateTime object represeting the UTC date and time the file was last updated.
References ES3Settings.FullPath, ES3Settings.location.
static void ES3.StoreCachedFile()
Stores the default cached file to persistent storage.
A backup is created by copying the file and giving it a .bak extension. If a backup already exists it will be overwritten, so you will need to ensure that the old backup will not be required before calling this method.
Referenced by StoreCachedFile, StoreCachedFile.
static void ES3.StoreCachedFile(string filePath)
Stores a cached file to persistent storage.
filePath The filename or path of the file we want to store the cached file to.
References StoreCachedFile.
static void ES3.StoreCachedFile(string filePath, ES3Settings settings)
Creates a backup of a file.
filePath The filename or path of the file we want to store the cached file to. settings The settings of the file we want to store to.
References StoreCachedFile.
static void ES3.StoreCachedFile(ES3Settings settings)
Stores a cached file to persistent storage.
settings The settings of the file we want to store to.
static void ES3.CacheFile()
Loads the default file in persistent storage into the cache.
References CacheFile.
Referenced by CacheFile, CacheFile, CacheFile.
static void ES3.CacheFile(string filePath)
Loads a file from persistent storage into the cache.
filePath The filename or path of the file we want to store the cached file to.
References CacheFile.
static void ES3.CacheFile(string filePath, ES3Settings settings)
Loads a file from persistent storage into the cache.
filePath The filename or path of the file we want to store the cached file to. settings The settings of the file we want to cache.
References CacheFile.
static void ES3.CacheFile(ES3Settings settings)
Loads a file from persistent storage into the cache.
settings The settings of the file we want to cache.
static void ES3.Init()
Initialises Easy Save. This happens automatically when any ES3 methods are called, but is useful if you want to perform initialisation before calling an ES3 method.
static byte[] ES3.Serialize(object value, ES3Types.ES3Type type, ES3Settings settings=null)
static object ES3.Deserialize(ES3Types.ES3Type type, byte[] bytes, ES3Settings settings=null)