ES3Writer
ES3Settings ES3Writer.settings
HashSet<string> ES3Writer.keysToDelete
int ES3Writer.serializationDepth
bool ES3Writer.writeHeaderAndFooter
bool ES3Writer.overwriteKeys
void ES3Writer.WriteNull()
virtual void ES3Writer.StartWriteFile()
virtual void ES3Writer.EndWriteFile()
virtual void ES3Writer.StartWriteObject(string name)
virtual void ES3Writer.EndWriteObject(string name)
virtual void ES3Writer.StartWriteProperty(string name)
virtual void ES3Writer.EndWriteProperty(string name)
virtual void ES3Writer.StartWriteCollection()
virtual void ES3Writer.EndWriteCollection()
void ES3Writer.StartWriteCollectionItem(int index)
void ES3Writer.EndWriteCollectionItem(int index)
void ES3Writer.StartWriteDictionary()
void ES3Writer.EndWriteDictionary()
void ES3Writer.StartWriteDictionaryKey(int index)
void ES3Writer.EndWriteDictionaryKey(int index)
void ES3Writer.StartWriteDictionaryValue(int index)
void ES3Writer.EndWriteDictionaryValue(int index)
void ES3Writer.WriteRawProperty(string name, byte[] bytes)
void ES3Writer.WritePrimitive(int value)
void ES3Writer.WritePrimitive(float value)
void ES3Writer.WritePrimitive(bool value)
void ES3Writer.WritePrimitive(decimal value)
void ES3Writer.WritePrimitive(double value)
void ES3Writer.WritePrimitive(long value)
void ES3Writer.WritePrimitive(ulong value)
void ES3Writer.WritePrimitive(uint value)
void ES3Writer.WritePrimitive(byte value)
void ES3Writer.WritePrimitive(sbyte value)
void ES3Writer.WritePrimitive(short value)
void ES3Writer.WritePrimitive(ushort value)
void ES3Writer.WritePrimitive(char value)
void ES3Writer.WritePrimitive(string value)
void ES3Writer.WritePrimitive(byte[] value)
virtual void ES3Writer.Write(string key, Type type, byte[] value)
virtual void ES3Writer.WriteRef(UnityEngine.Object obj)
virtual void ES3Writer.WriteRef(UnityEngine.Object obj, string propertyName)
virtual void ES3Writer.WriteRef(UnityEngine.Object obj, string propertyName, ES3ReferenceMgrBase refMgr)
void ES3Writer.Dispose()
virtual void ES3Writer.Write< T >(string key, object value)
Writes a value to the writer with the given key.
key The key which uniquely identifies this value. value The value we want to write.
virtual void ES3Writer.Write(Type type, string key, object value)
Writes a value to the writer with the given key, using the given type rather than the generic parameter.
key The key which uniquely identifies this value. value The value we want to write. type The type we want to use for the header, and to retrieve an ES3Type.
References ES3Settings.referenceMode, WriteProperty.
virtual void ES3Writer.Write(object value, ES3.ReferenceMode memberReferenceMode=ES3.ReferenceMode.ByRef)
Writes a value to the writer. Note that this should only be called within an ES3Type.
value The value we want to write. memberReferenceMode Whether we want to write UnityEngine.Object fields and properties by reference, by value, or both.
virtual void ES3Writer.Write(object value, ES3Type type, ES3.ReferenceMode memberReferenceMode=ES3.ReferenceMode.ByRef)
virtual void ES3Writer.WriteProperty(string name, object value)
Writes a field or property to the writer. Note that this should only be called within an ES3Type.
name The name of the field or property. value The value we want to write.
References ES3Settings.memberReferenceMode, WriteProperty.
Referenced by Write, WritePrivateField, WritePrivateProperty, WriteProperty, WriteProperty< T >.
virtual void ES3Writer.WriteProperty(string name, object value, ES3.ReferenceMode memberReferenceMode)
Writes a field or property to the writer. Note that this should only be called within an ES3Type.
name The name of the field or property. value The value we want to write. memberReferenceMode Whether we want to write the property by reference, by value, or both.
virtual void ES3Writer.WriteProperty< T >(string name, object value)
Writes a field or property to the writer. Note that this should only be called within an ES3Type.
name The name of the field or property. value The value we want to write.
References ES3Settings.memberReferenceMode, WriteProperty.
virtual void ES3Writer.WriteProperty(string name, object value, ES3Type type)
virtual void ES3Writer.WriteProperty(string name, object value, ES3Type type, ES3.ReferenceMode memberReferenceMode)
virtual void ES3Writer.WritePropertyByRef(string name, UnityEngine.Object value)
void ES3Writer.WritePrivateProperty(string name, object objectContainingProperty)
Writes a private property to the writer. Note that this should only be called within an ES3Type.
name The name of the property. objectContainingProperty The object containing the property we want to write.
References WriteProperty.
void ES3Writer.WritePrivateField(string name, object objectContainingField)
Writes a private field to the writer. Note that this should only be called within an ES3Type.
name The name of the field. objectContainingField The object containing the property we want to write.
References WriteProperty.
void ES3Writer.WritePrivateProperty(string name, object objectContainingProperty, ES3Type type)
void ES3Writer.WritePrivateField(string name, object objectContainingField, ES3Type type)
void ES3Writer.WritePrivatePropertyByRef(string name, object objectContainingProperty)
void ES3Writer.WritePrivateFieldByRef(string name, object objectContainingField)
void ES3Writer.WriteType(Type type)
virtual void ES3Writer.MarkKeyForDeletion(string key)
virtual void ES3Writer.Save()
Stores the contents of the writer and overwrites any existing keys if overwriting is enabled.
References Save.
Referenced by Save.
virtual void ES3Writer.Save(bool overwriteKeys)
Stores the contents of the writer and overwrites any existing keys if overwriting is enabled.
overwriteKeys Whether we should overwrite existing keys.
References ES3Settings.location.
ES3Writer.ES3Writer(ES3Settings settings, bool writeHeaderAndFooter, bool overwriteKeys)
bool ES3Writer.SerializationDepthLimitExceeded()
void ES3Writer.Merge()
void ES3Writer.Merge(ES3Reader reader)
static void ES3Writer.TryOnBeforeSerialize(object obj)
static ES3Writer ES3Writer.Create(ES3Settings settings, bool writeHeaderAndFooter, bool overwriteKeys, bool append)
static ES3Writer ES3Writer.Create(Stream stream, ES3Settings settings, bool writeHeaderAndFooter, bool overwriteKeys)
static ES3Writer ES3Writer.Create(string filePath, ES3Settings settings)
Creates a new ES3Writer.
filePath The relative or absolute path of the file we want to write to. settings The settings we want to use to override the default settings.
References Create.
Referenced by Create, Create, ES3.DeleteKey, ES3.Save< T >, ES3File.Sync.
static ES3Writer ES3Writer.Create(ES3Settings settings)
Creates a new ES3Writer.
settings The settings we want to use to override the default settings.
References Create.