ShipSystem
Ship ShipSystem.parentShip
이 시스템이 소속된 함선 객체입니다.
Referenced by CrewSystem.AddCrew, WeaponSystem.AddWeapon, MoraleSystem.CalculateGlobalMorale, OuterHullSystem.ClearExistingHulls, OuterHullSystem.CreateOuterHull, WeaponSystem.FireAllReadyWeapons, WeaponSystem.FireWeapon, WeaponSystem.FireWeaponsByType, CrewSystem.GetCrewCount, CrewSystem.GetCrews, GetShipStat, WeaponSystem.GetWeaponByIndex, WeaponSystem.GetWeaponCount, WeaponSystem.GetWeapons, WeaponSystem.GetWeaponsByType, WeaponSystem.GetWeaponsByWarheadType, Initialize, WeaponSystem.IsEveryWeaponReady, OuterHullSystem.IsOutOfBounds, OuterHullSystem.ReduceDamage, CrewSystem.RemoveAllCrews, WeaponSystem.RemoveAllWeapons, CrewSystem.RemoveCrew, PowerSystem.RequestPowerForRoom, WeaponSystem.ResetAllWeaponStats, CrewSystem.RestoreCrewAfterBuild, CrewSystem.RevertOriginalCrews, OuterHullSystem.SetOuterHullLevel, OxygenSystem.Update, WeaponSystem.Update, OuterHullSystem.UpdateVisuals, WeaponSystem.UpdateWeaponCooldowns.
virtual void ShipSystem.Initialize(Ship ship)
시스템을 초기화합니다. 함선 참조를 저장하여 시스템 동작에 사용됩니다.
ship 이 시스템이 속한 함선 객체.
References parentShip.
Referenced by Ship.InitializeSystems.
virtual void ShipSystem.Refresh()
void ShipSystem.Update(float deltaTime)
매 프레임마다 호출되는 시스템 업데이트 함수입니다. 구체적인 동작은 각 서브 클래스에서 구현됩니다.
deltaTime 경과 시간 (초).
float ShipSystem.GetShipStat(ShipStat stat)
현재 함선의 특정 스탯 값을 가져옵니다.
stat 조회할 스탯 종류. 해당 스탯의 현재 값.
References Ship.GetStat, parentShip.
Referenced by CrewSystem.AddCrew, OxygenSystem.CalculateOxygenChange, HitPointSystem.ChangeHitPoint, WeaponSystem.GetActualCooldown, WeaponSystem.GetActualDamage, HitPointSystem.GetHitPointPercentage, ShieldSystem.GetMaxShield, ShieldSystem.RegenerateShield, PowerSystem.RequestPowerForRoom, ShieldSystem.TakeDamage, ShieldSystem.Update, WeaponSystem.Update, WeaponSystem.UpdateWeaponCooldowns.