ShieldSystem
float ShieldSystem.currentShield
현재 쉴드 수치입니다.
Referenced by GetCurrentShield, IsShieldActive, RegenerateShield, TakeDamage, Update.
float ShieldSystem.shieldRespawnTimer
쉴드가 파괴된 후 재활성화까지 남은 시간입니다.
Referenced by TakeDamage, Update.
bool ShieldSystem.isShieldDestroyed
쉴드가 파괴된 상태인지 여부입니다.
Referenced by IsShieldActive, TakeDamage, Update.
override void ShieldSystem.Initialize(Ship ship)
시스템을 초기화하고 쉴드를 최대치로 설정합니다.
ship 초기화할 대상 함선 객체.
Referenced by Ship.InitializeSystems.
override void ShieldSystem.Refresh()
override void ShieldSystem.Update(float deltaTime)
매 프레임마다 호출되어 쉴드 상태를 갱신합니다. 파괴 상태일 경우 재활성화 타이머를 감소시키고, 파괴되지 않은 상태에서는 자동으로 쉴드를 재생성합니다.
deltaTime 경과 시간 (초).
References currentShield, ShipSystem.GetShipStat, isShieldDestroyed, RegenerateShield, shieldRespawnTimer.
Referenced by Ship.Update.
float ShieldSystem.GetCurrentShield()
현재 쉴드 수치를 반환합니다.
현재 쉴드 수치.
References currentShield.
Referenced by EnemyInfoPanel.UpdateInfoPanel.
float ShieldSystem.GetMaxShield()
쉴드의 최대 수치를 반환합니다.
최대 쉴드 수치.
References ShipSystem.GetShipStat.
float ShieldSystem.TakeDamage(float damage, ShipWeaponType shipWeaponType)
쉴드에 피해를 입히고, 남은 피해량을 반환합니다. 쉴드가 모두 소모되면 파괴 상태로 전환되며, 재활성화 타이머가 시작됩니다. 특정 무기 타입은 피해량 보정이 적용됩니다.
damage 입힌 총 피해량. shipWeaponType 공격 무기 유형. 쉴드를 뚫고 전달된 남은 피해량.
References currentShield, ShipSystem.GetShipStat, isShieldDestroyed, shieldRespawnTimer.
Referenced by Ship.TakeAttack.
bool ShieldSystem.IsShieldActive()
현재 쉴드가 활성화되어 있는지 여부를 반환합니다.
쉴드가 존재하고 파괴되지 않았으면 true.
References currentShield, isShieldDestroyed.
Referenced by Ship.TakeAttack.
void ShieldSystem.RegenerateShield(float deltaTime)
쉴드를 재생성합니다. 초당 재생 속도에 따라 현재 쉴드를 회복합니다.
deltaTime 경과 시간 (초).
References currentShield, ShipSystem.GetShipStat.
Referenced by Update.