CrewDatabase::RaceStat
CrewRace CrewDatabase.RaceStat.race
float CrewDatabase.RaceStat.maxHealth
float CrewDatabase.RaceStat.attack
float CrewDatabase.RaceStat.defense
float CrewDatabase.RaceStat.learningSpeed
bool CrewDatabase.RaceStat.needsOxygen
float CrewDatabase.RaceStat.initialPilotSkill
기관별 최초 숙련도 직렬화 가능한 개별 필드
Referenced by CrewDatabase.DeserializeFromJson, CrewDatabase.GetInitialSkillValue, CrewFactory.InitializeCrewStats.
float CrewDatabase.RaceStat.initialEngineSkill
float CrewDatabase.RaceStat.initialPowerSkill
float CrewDatabase.RaceStat.initialShieldSkill
float CrewDatabase.RaceStat.initialWeaponSkill
float CrewDatabase.RaceStat.initialAmmunitionSkill
float CrewDatabase.RaceStat.initialMedBaySkill
float CrewDatabase.RaceStat.initialRepairSkill
List<SkillValue> CrewDatabase.RaceStat.maxSkillValues
최대 숙련도 저장 리스트
Referenced by CrewDatabase.RaceStat.GetMaxSkillValueDictionary, CrewDatabase.RaceStat.SetMaxSkillValuesFromDictionary.
Dictionary< SkillType, float > CrewDatabase.RaceStat.GetMaxSkillValueDictionary()
숙련도 기관별 최대 숙련도를 호출합니다.
References CrewDatabase.RaceStat.maxSkillValues.
Referenced by CrewDatabase.GetMaxSkillValue, CrewFactory.InitializeCrewStats, CrewDatabase.SerializeToJson.
void CrewDatabase.RaceStat.SetMaxSkillValuesFromDictionary(Dictionary< SkillType, float > dictionary)
Dictionary에서 List로 값을 설정하는 메서드
References CrewDatabase.RaceStat.maxSkillValues.
Referenced by CrewDatabase.DeserializeFromJson, CrewDatabase.InitializeDefaultStats.