Customize_1_Controller
GameObject Customize_1_Controller.customize0Panel
GameObject Customize_1_Controller.customize1Panel
GameObject Customize_1_Controller.customize2Panel
GameObject Customize_1_Controller.gridTiles
그리드 타일이 배치되는 부모 오브젝트입니다.
Referenced by OnDisable, ReloadBlueprintFromSlot.
TMP_Text Customize_1_Controller.bpCostText
총 설계도 가격을 표시할 텍스트 UI.
TMP_Text Customize_1_Controller.feedbackText
저장 또는 유효성 검사 결과를 표시할 텍스트입니다.
GridPlacer Customize_1_Controller.gridPlacer
그리드 타일 배치 작업을 위한 오브젝트
Referenced by CenterCameraToBP, OnClickSave, ReloadBlueprintFromSlot, ResetCameraToOriginShip.
Ship Customize_1_Controller.playerShip
유저 함선
Referenced by OnClickSave, OnDisable, OnEnable, ReloadBlueprintFromSlot, Start.
BlueprintShip Customize_1_Controller.targetBlueprintShip
제작한 설계도
Referenced by OnClickBack, OnClickClear, OnClickSave, ReloadBlueprintFromSlot, Update.
BlueprintCategoryButtonHandler Customize_1_Controller.bcbHandler
Button Customize_1_Controller.backButton
Button Customize_1_Controller.clearButton
Button Customize_1_Controller.saveButton
Button Customize_1_Controller.essentialButton
Button Customize_1_Controller.auxiliaryButton
Button Customize_1_Controller.livingButton
Button Customize_1_Controller.storageButton
Button Customize_1_Controller.corridorButton
Button Customize_1_Controller.weaponButton
ValidationResult Customize_1_Controller.validationResult
유효성 검사 결과
Referenced by OnClickBack, OnClickClear, OnClickSave, Update.
int Customize_1_Controller.totalBPCost
설계도 함선 가격
Referenced by Update.
Coroutine Customize_1_Controller.flashCoroutine
build 빨간색 처리 코루틴
Referenced by FlashSaveButtonColor, OnClickBack, OnClickSave.
Color? Customize_1_Controller.originButtonColor
버튼 기본 색상 저장
Referenced by FlashSaveButtonColor, OnClickBack.
BlueprintInventoryUI Customize_1_Controller.blueprintInventoryUI
void Customize_1_Controller.Start()
button 클릭 함수 연결
References GameManager.Instance, OnClickBack, OnClickClear, OnClickSave, playerShip, GameManager.playerShip, BlueprintCategoryButtonHandler.ShowAuxiliary, BlueprintCategoryButtonHandler.ShowEssential, BlueprintCategoryButtonHandler.ShowEtc, BlueprintCategoryButtonHandler.ShowLiving, BlueprintCategoryButtonHandler.ShowStorage, BlueprintCategoryButtonHandler.ShowWeapons.
void Customize_1_Controller.Update()
현재 설계도의 가격 지속 갱신 설계도로 함선 교체 가능 조건
(설계도 가격 - 기존 함선 가격) <= 보유 재화량 기존 함선 모든 방 내구도 100%
References BlueprintShip.GetTotalBPCost, GameManager.Instance, GameManager.playerShip, targetBlueprintShip, totalBPCost, validationResult.
void Customize_1_Controller.OnEnable()
CustomizeShipUI 활성화 시 아래 작업 수행 : 그리드 생성 및 그리드 저장 오브젝트 활성화 작업하던 설계도 방 호출, 배치 카메라 중앙값 세팅
References BlueprintInventoryUI.categoryButtonHandler, CenterCameraToBP, Ship.ClearExistingHulls, BlueprintInventoryUI.FilterByCategory, BlueprintSlotManager.Instance, GameManager.Instance, playerShip, GameManager.playerShip, ReloadBlueprintFromSlot, BlueprintCategoryButtonHandler.SetButtonState, Ship.SetShipContentsActive.
void Customize_1_Controller.OnDisable()
CustomizeShipUI 비활성화 시 아래 작업 수행 : 그리드 저장 오브젝트 비활성화 설계도 설치한 방 데이터 모두 저장 후 제거
References gridTiles, GameManager.Instance, playerShip, GameManager.playerShip, ResetCameraToOriginShip, Ship.SetShipContentsActive, Ship.UpdateOuterHullVisuals.
void Customize_1_Controller.CenterCameraToBP()
설계도 UI 호출 시 카메라 중앙값 보정
References GridPlacer.GetCameraStartPositionToBP, gridPlacer, CameraZoomController.lastZoomSize.
Referenced by OnEnable, ReloadBlueprintFromSlot.
void Customize_1_Controller.ResetCameraToOriginShip()
카메라 기본 세팅으로 복구
References GridPlacer.GetCameraStartPositionToOriginShip, gridPlacer.
Referenced by OnDisable.
IEnumerator Customize_1_Controller.FlashSaveButtonColor(Color flashColor, float duration)
유효성 검사 실패 시 build button 일시적 빨간색
flashColor duration
References flashCoroutine, originButtonColor.
Referenced by OnClickSave.
void Customize_1_Controller.ReloadBlueprintFromSlot(int slotIndex)
클릭한 슬롯 도안 호출
slotIndex
References CenterCameraToBP, BlueprintShip.ClearRooms, BlueprintSlotManager.GetBlueprintAt, BlueprintSlotManager.GetOccupiedTiles, gridPlacer, gridTiles, BlueprintSlotManager.Instance, GridPlacer.PlaceRoom, GridPlacer.PlaceWeapon, playerShip, BlueprintShip.SetHullLevel, BlueprintWeapon.SetHullLevel, Ship.SetShipContentsActive, targetBlueprintShip.
Referenced by Customize_0_Controller.OnClickEdit, OnEnable.
void Customize_1_Controller.OnClickSave()
도안 저장 버튼 클릭 - 유효성 검사
References Ship.BackupAllCrews, Ship.backupCrewDatas, Ship.BackupCurrentShip, flashCoroutine, FlashSaveButtonColor, gridPlacer, BlueprintSlotManager.Instance, GameManager.Instance, ValidationResult.IsValid, BlueprintSlotManager.isValidBP, GridPlacer.occupiedGridTiles, playerShip, GameManager.playerShip, Ship.ReplaceShipFromBlueprint, CrewSystem.RevertOriginalCrews, Ship.RevertToOriginalShip, BlueprintSlotManager.SaveBlueprintToCurrentSlot, BlueprintSlotManager.SaveOccupiedTilesToCurrentSlot, Ship.SetShipContentsActive, targetBlueprintShip, Customize_0_Controller.UpdateSlotButtonColor, ShipValidationHelper.ValidateShipLayout, validationResult.
Referenced by Start.
void Customize_1_Controller.OnClickBack()
customize_0_panel로 복귀
References BlueprintShip.ClearRooms, flashCoroutine, BlueprintSlotManager.Instance, Customize_0_Controller.OnClickSlot, originButtonColor, targetBlueprintShip, validationResult.
Referenced by Start.
void Customize_1_Controller.OnClickClear()
설계도 초기화 및 점유 타일 초기화
References BlueprintShip.ClearRooms, targetBlueprintShip, validationResult.
Referenced by Start.