ShipCustomizationManager
float ShipCustomizationManager.cellSize
Vector2 ShipCustomizationManager.gridMin
Vector2 ShipCustomizationManager.gridMax
GameObject ShipCustomizationManager.corridorPrefab
GameObject ShipCustomizationManager.doorPrefab
Transform ShipCustomizationManager.modulesContainer
int ShipCustomizationManager.currency
int ShipCustomizationManager.corridorCost
int ShipCustomizationManager.doorCost
Dictionary<Vector2Int, GameObject> ShipCustomizationManager.placedModules
Dictionary<Vector2Int, GameObject> ShipCustomizationManager.PlacedModules
bool ShipCustomizationManager.PlaceModule(GameObject modulePrefab, Vector2 worldPosition)
주어진 월드 좌표에 모듈 프리팹을 배치합니다. 배치에 성공하면 재화를 차감하고 true를 반환합니다.
References GetModuleCost, GridCenter, IsWithinGrid, SnapToGrid.
bool ShipCustomizationManager.RemoveModule(Vector2 worldPosition)
주어진 월드 좌표에 배치된 모듈을 삭제합니다.
References SnapToGrid.
void ShipCustomizationManager.ClearAllModules()
모든 배치된 모듈을 삭제하고 재설정합니다.
void ShipCustomizationManager.PlaceSavedRoom(Room savedRoom)
저장된 room 배치
savedRoom
References GridCenter, Room< TData, TLevel >.position, Room< TData, TLevel >.roomType.
Vector2Int ShipCustomizationManager.SnapToGrid(Vector2 position)
월드 좌표를 그리드 좌표(Vector2Int)로 스냅합니다.
Referenced by PlaceModule, RemoveModule.
Vector3 ShipCustomizationManager.GridCenter(Vector2Int gridPos)
그리드 좌표의 셀 중앙 위치(월드 좌표)를 반환합니다.
Referenced by IsWithinGrid, PlaceModule, PlaceSavedRoom.
bool ShipCustomizationManager.IsWithinGrid(Vector2Int gridPos)
주어진 그리드 좌표가 설정된 grid 범위 내에 있는지 검사합니다.
References GridCenter.
Referenced by PlaceModule.
int ShipCustomizationManager.GetModuleCost(GameObject modulePrefab)
모듈 프리팹에 따라 설치 비용을 반환합니다.
Referenced by PlaceModule.
GameObject ShipCustomizationManager.GetPrefabByRoomType(RoomType type)