FuelPanelUI
TextMeshProUGUI FuelPanelUI.fuelPriceText
TextMeshProUGUI FuelPanelUI.fuelValueText
Button FuelPanelUI.buyButton
int FuelPanelUI.basePricePer100
int FuelPanelUI.fluctuatedPrice
float FuelPanelUI.fluctuationRange
int FuelPanelUI.lastPriceUpdateYear
마지막 가격 업데이트 된 연도입니다.
Referenced by Start, Update.
int FuelPanelUI.updateCycle
가격 업데이트 주기입니다.
Referenced by Update.
float FuelPanelUI.MaxFuelAmount
void FuelPanelUI.Start()
시작할때 실행되는 함수입니다.
References ApplyPriceFluctuation, BuyFuel, GameManager.CurrentYear, GameManager.Instance, lastPriceUpdateYear, UpdateFuelDisplay.
void FuelPanelUI.Update()
업데이트 함수입니다. 가격 변동을 업데이트 합니다.
References ApplyPriceFluctuation, GameManager.CurrentYear, GameManager.Instance, lastPriceUpdateYear, updateCycle.
void FuelPanelUI.ApplyPriceFluctuation()
연료 가격에 변동폭을 적용합니다.
Referenced by Start, Update.
void FuelPanelUI.UpdateFuelDisplay()
현재 연료량을 텍스트로 표시합니다.
Referenced by BuyFuel, Start.
void FuelPanelUI.BuyFuel()
연료를 구매하는 로직입니다.
References UpdateFuelDisplay.
Referenced by Start.