Storage
Storage Storage.Instance
싱글톤 인스턴스입니다.
Dictionary<int, StoredItem> Storage.storedItems
창고에 저장된 아이템 목록입니다. Key는 itemData.id이며, Value는 저장된 아이템 정보(수량 + 구매가)입니다.
Referenced by AddItem, CanAddItem, GetAllItems, GetItemQuantity, HasItem, RemoveItem.
TradingItemDataBase Storage.itemDatabase
퀘스트 연동용 TradingItemDataBase입니다.
Referenced by GetItemQuantityById.
Action<TradingItemData> Storage.OnStorageChanged
아이템 수량 변동 시 발생하는 이벤트입니다.
Referenced by AddItem, RemoveItem.
void Storage.Awake()
bool Storage.CanAddItem(TradingItemData itemData, int quantity)
해당 아이템을 추가할 수 있는지 검사합니다.
itemData 아이템 데이터 quantity 추가할 수량
References storedItems.
Referenced by AddItem, TradeManager.BuyItem.
bool Storage.AddItem(TradingItemData itemData, int quantity)
아이템을 창고에 추가합니다. (기본 구매가 사용)
itemData 아이템 데이터 quantity 수량
References AddItem.
Referenced by AddItem, TradeManager.BuyItem, TestStorageItemAdder.Start.
bool Storage.AddItem(TradingItemData itemData, int quantity, float purchasePrice)
아이템을 창고에 추가합니다. (구매 당시 가격 포함)
itemData 아이템 데이터 quantity 수량 purchasePrice 구매 당시 가격 (kg당)
References CanAddItem, OnStorageChanged, storedItems.
bool Storage.RemoveItem(TradingItemData itemData, int quantity)
아이템을 창고에서 제거합니다.
itemData 아이템 데이터 quantity 제거할 수량
References OnStorageChanged, storedItems.
Referenced by TradeManager.SellItem.
bool Storage.HasItem(TradingItemData itemData, int quantity)
아이템 보유 여부를 검사합니다.
References storedItems.
Referenced by TradeManager.SellItem.
int Storage.GetItemQuantity(TradingItemData itemData)
특정 아이템의 현재 보유 수량을 반환합니다.
References storedItems.
Referenced by GetItemQuantityById.
int Storage.GetItemQuantityById(string targetId)
퀘스트 UI용 ID 기반 수량 조회
References GetItemQuantity, itemDatabase.
List<(TradingItemData itemData, int quantity, float purchasePrice)> Storage.GetAllItems()
저장된 모든 아이템 목록을 반환합니다.
(아이템 데이터, 수량, 구매 당시 가격) 튜플 리스트
References storedItems.
Referenced by InventoryUI.PopulateInventory.