QuestManager
TradingItemDataBase QuestManager.itemDatabase
아이템 정보가 들어있는 데이터베이스
List<RandomQuest> QuestManager.activeQuests
List<RandomQuest> QuestManager.completedQuests
QuestManager QuestManager.Instance
퀘스트 매니저의 싱글톤 인스턴스
Referenced by AddQuestEffectHandler.HandleEffect.
QuestChangedHandler QuestManager.OnQuestAdded
퀘스트가 새로 추가될 때 발생하는 이벤트
Referenced by AddQuest.
QuestChangedHandler QuestManager.OnQuestUpdated
퀘스트가 갱신될 때 발생하는 이벤트
Referenced by UpdateQuestObjective.
QuestChangedHandler QuestManager.OnQuestCompleted
퀘스트가 완료될 때 발생하는 이벤트
Referenced by CompleteQuest, TriggerQuestCompleted.
QuestChangedHandler QuestManager.OnQuestFailed
퀘스트가 실패할 때 발생하는 이벤트
Referenced by FailQuest.
delegate void QuestManager.QuestChangedHandler(RandomQuest quest)
퀘스트 변경 이벤트 핸들러
void QuestManager.AddQuest(RandomQuest quest)
새로운 퀘스트를 추가합니다.
quest 추가할 퀘스트
References GameManager.CurrentYear, GameManager.Instance, OnQuestAdded.
Referenced by AddQuestEffectHandler.HandleEffect.
void QuestManager.TriggerQuestCompleted(RandomQuest quest)
외부에서 퀘스트 완료 처리를 강제로 호출할 때 사용합니다.
quest 완료된 퀘스트
References OnQuestCompleted.
void QuestManager.UpdateQuestObjective(string questId, int objectiveIndex, int amount)
특정 퀘스트 목표의 진행도를 갱신합니다.
questId 퀘스트 ID objectiveIndex 목표 인덱스 amount 추가할 수치
References QuestObjective.amount, QuestObjective.canComplete, RandomQuest.objectives, OnQuestUpdated.
void QuestManager.CompleteQuest(RandomQuest quest)
퀘스트를 완료 처리합니다. 완료 시 UI 패널 상태를 기억하고 완료 후 원래대로 복구합니다.
quest 완료된 퀘스트
References OnQuestCompleted.
void QuestManager.GrantRewardForQuest(RandomQuest quest)
퀘스트 보상을 지급하는 함수입니다.
quest
References QuestReward.amount, RandomQuest.rewards, RandomQuest.status.
void QuestManager.RequestFailQuest(RandomQuest quest)
외부에서 호출할 수 있는 퀘스트 실패 처리 함수입니다.
References FailQuest.
List< RandomQuest > QuestManager.GetActiveQuests()
현재 진행 중인 퀘스트 목록을 반환합니다.
진행 중인 퀘스트 리스트
Referenced by AddQuestEffectHandler.HandleEffect.
List< RandomQuest > QuestManager.GetCompletedQuests()
완료된 퀘스트 목록을 반환합니다.
완료된 퀘스트 리스트
void QuestManager.Awake()
void QuestManager.OnEnable()
void QuestManager.OnDisable()
void QuestManager.CheckQuestExpiration(int currentYear)
매년 호출되어 20년 이상 지난 퀘스트를 자동 실패 처리합니다.
currentYear 현재 연도
References FailQuest, RandomQuest.QuestExpiredYear.
void QuestManager.TrySpawnQuest(int year)
void QuestManager.CreateRandomQuest()
void QuestManager.FailQuest(RandomQuest quest)
퀘스트를 실패 처리합니다.
quest 실패할 퀘스트
References OnQuestFailed.
Referenced by CheckQuestExpiration, RequestFailQuest.