TradingItemDragHandler
TradingItemDragHandler TradingItemDragHandler.Instance
bool TradingItemDragHandler.IsItemRepositioningAllowed
Color TradingItemDragHandler.validPlacementColor
Color TradingItemDragHandler.invalidPlacementColor
Color TradingItemDragHandler.normalPreviewColor
GameObject TradingItemDragHandler.previewObject
SpriteRenderer TradingItemDragHandler.previewBoxRenderer
TradingItem TradingItemDragHandler.originalItem
StorageRoomBase TradingItemDragHandler.sourceStorage
Vector2Int TradingItemDragHandler.originalPosition
Constants.Rotations.Rotation TradingItemDragHandler.originalRotation
Constants.Rotations.Rotation TradingItemDragHandler.currentRotation
bool TradingItemDragHandler.lastLoggedDraggingState
bool TradingItemDragHandler.isDragging
Vector2 TradingItemDragHandler.dragOffset
Vector2Int TradingItemDragHandler.currentGridPosition
StorageRoomBase TradingItemDragHandler.currentTargetStorage
StorageRoomBase TradingItemDragHandler.previousTargetStorage
Coroutine TradingItemDragHandler.flashCoroutine
Coroutine TradingItemDragHandler.resetCoroutine
void TradingItemDragHandler.Awake()
void TradingItemDragHandler.CreatePreview(TradingItem item)
프리뷰 오브젝트 생성 - 프리팹 사용 없이 직접 생성
Referenced by StartDragging.
void TradingItemDragHandler.Update()
매 프레임 마우스 위치에 따라 프리뷰 업데이트
References StorageRoomBase.CanPlaceItem, EndDragging, RotatePreview, UpdatePreviewBoxSprite, UpdatePreviewPosition.
void TradingItemDragHandler.UpdatePreviewToGridPosition(StorageRoomBase storage, Vector2Int gridPos)
그리드 위치에 맞게 프리뷰 위치를 정확하게 업데이트합니다. 실제 배치와 동일한 로직을 사용합니다.
References StorageRoomBase.GetOccupiedTiles.
Referenced by RotatePreview, UpdatePreviewPosition.
void TradingItemDragHandler.RotatePreview()
프리뷰 회전 처리
References UpdatePreviewBoxSprite, UpdatePreviewToGridPosition.
Referenced by Update.
void TradingItemDragHandler.UpdatePreviewBoxSprite()
현재 회전 상태에 맞는 박스 스프라이트로 업데이트
References Room< TData, TLevel >.currentRotation.
Referenced by RotatePreview, StartDragging, Update.
void TradingItemDragHandler.UpdatePreviewPosition(Vector2 mouseWorldPos)
프리뷰 위치 업데이트
References GetStorageUnderMouse, UpdatePreviewToGridPosition, StorageRoomBase.WorldToGridPosition.
Referenced by StartDragging, Update.
void TradingItemDragHandler.EndDragging(Vector2 mouseWorldPos)
드래그 종료 처리 - 다른 창고로 이동하는 개선된 로직
References StorageRoomBase.AddItem, StorageRoomBase.CanPlaceItem, CleanupDrag, FlashInvalidPlacement, StorageRoomBase.GridToWorldPosition, StorageRoomBase.RemoveItem, ResetAllItemsInteractivity, TradingItem.Rotate, TradingItem.SetDragMode, StorageRoomBase.storedItems, StorageRoomBase.WorldToGridPosition.
Referenced by Update.
IEnumerator TradingItemDragHandler.ResetAllItemsInteractivity()
모든 아이템의 상호작용을 재활성화하는 코루틴
References TradingItem.SetDragMode, StorageRoomBase.storedItems.
Referenced by CancelDragging, EndDragging.
void TradingItemDragHandler.CleanupDrag()
드래그 관련 리소스 정리
Referenced by CancelDragging, EndDragging.
StorageRoomBase TradingItemDragHandler.GetStorageUnderMouse()
마우스 아래에 있는 스토리지 컴포넌트 반환
Referenced by UpdatePreviewPosition.
IEnumerator TradingItemDragHandler.FlashInvalidPlacement()
배치 불가능 상태 시각적 피드백
Referenced by EndDragging.
void TradingItemDragHandler.StartDragging(TradingItem item, StorageRoomBase storage, Vector2 mousePosition)
아이템 드래그 시작
References CancelDragging, CreatePreview, TradingItem.SetDragMode, UpdatePreviewBoxSprite, UpdatePreviewPosition.
void TradingItemDragHandler.CancelDragging()
드래그 취소 (ESC 키 등으로 취소하는 경우)
References StorageRoomBase.AddItem, CleanupDrag, StorageRoomBase.GridToWorldPosition, ResetAllItemsInteractivity, TradingItem.Rotate, TradingItem.SetDragMode, StorageRoomBase.storedItems.
Referenced by StartDragging.