PlanetItemUI
Image PlanetItemUI.iconImage
아이템 아이콘을 표시하는 Image 컴포넌트입니다.
Referenced by Setup.
Image PlanetItemUI.itemShapeImage
아이템 모양을 시각적으로 표시할 Image 컴포넌트입니다.
Referenced by Setup.
List<Sprite> PlanetItemUI.itemShapeSprites
아이템 모양 관련 List 컴포넌트입니다.
Referenced by Setup.
TextMeshProUGUI PlanetItemUI.itemNameText
아이템 이름을 표시하는 TextMeshProUGUI 컴포넌트입니다.
Referenced by ApplyColor, ApplyOriginalColor, Setup.
TextMeshProUGUI PlanetItemUI.categoryText
아이템 종류를 표시하는 TextMeshProUGUI 컴포넌트입니다.
Referenced by ApplyColor, ApplyOriginalColor, Setup.
TextMeshProUGUI PlanetItemUI.capacityText
아이템 최대 적재량을 표시하는 TextMeshProUGUI 컴포넌트입니다.
Referenced by ApplyColor, ApplyOriginalColor, Setup.
TextMeshProUGUI PlanetItemUI.priceText
아이템 가격을 표시하는 TextMeshProUGUI 컴포넌트입니다.
Referenced by ApplyColor, ApplyOriginalColor, Setup.
MiddlePanelUI PlanetItemUI.middlePanel
행성 물품과 연동된 Panel 컴포넌트 입니다.
Referenced by OnPointerClick.
TradingItemData PlanetItemUI.itemData
bool PlanetItemUI.isSelected
Color PlanetItemUI.highlightColor
마우스 오버 시 적용할 강조 색상입니다.
Referenced by OnPointerEnter, SetSelected.
Color PlanetItemUI.itemNameOriginalColor
아이템 이름 텍스트의 원래 색상입니다.
Referenced by ApplyOriginalColor, Setup.
Color PlanetItemUI.priceOriginalColor
아이템 가격 텍스트의 원래 색상입니다.
Referenced by ApplyOriginalColor, Setup.
PlanetItemUI PlanetItemUI._currentSelectedItem
string PlanetItemUI._currentlySelectedItemName
void PlanetItemUI.Setup(TradingItemData data)
PlanetItemUI를 초기화하고 텍스트 표시와 색상 초기 상태를 저장합니다.
References capacityText, categoryText, iconImage, itemNameOriginalColor, itemNameText, itemShapeImage, itemShapeSprites, priceOriginalColor, priceText, SetSelected.
void PlanetItemUI.OnPointerClick(PointerEventData eventData)
사용자가 이 슬롯을 클릭했을 때 호출됩니다. MiddlePanelUI에 상세 정보를 전달하고, 구매창 서브 패널을 활성화합니다.
References TradeUIManager.Instance, middlePanel, TradeUIManager.OnBuyItemSelected, SetSelected, MiddlePanelUI.SetSelectedItem.
void PlanetItemUI.OnPointerEnter(PointerEventData eventData)
마우스가 이 슬롯 위에 들어왔을 때 호출되며, 아이템 이름과 가격 텍스트의 색상을 강조 색상으로 변경합니다.
eventData 포인터 이벤트 데이터
References ApplyColor, highlightColor.
void PlanetItemUI.OnPointerExit(PointerEventData eventData)
마우스가 이 슬롯을 벗어났을 때 호출되며, 아이템 이름과 가격 텍스트의 색상을 원래 색상으로 복구합니다.
eventData 포인터 이벤트 데이터
References ApplyOriginalColor.
void PlanetItemUI.SetSelected(bool selected)
선택된 물품의 색상을 변경하는 함수입니다.
selected
References ApplyColor, ApplyOriginalColor, highlightColor.
Referenced by OnPointerClick, Setup.
void PlanetItemUI.ApplyColor(Color color)
색상 변경을 적용하는 함수입니다.
color
References capacityText, categoryText, itemNameText, priceText.
Referenced by OnPointerEnter, SetSelected.
void PlanetItemUI.ApplyOriginalColor()
원래의 텍스트 색상으로 되돌리는 함수입니다.
References capacityText, categoryText, itemNameOriginalColor, itemNameText, priceOriginalColor, priceText.
Referenced by OnPointerExit, SetSelected.