InventoryItemUI
bool InventoryItemUI.isInteractable
이 슬롯이 클릭 및 하이라이트 가능한지 여부입니다.
Referenced by OnPointerClick, OnPointerEnter, OnPointerExit.
Image InventoryItemUI.itemShapeImage
아이템 모양을 표시할 Image 컴포넌트입니다.
Referenced by Setup.
List<Sprite> InventoryItemUI.itemShapeSprites
아이템 모양별로 사용할 스프라이트 리스트입니다. shape enum 순서에 맞춰야 합니다.
Referenced by Setup.
Image InventoryItemUI.itemImage
아이템 이미지를 보여주는 UI 요소입니다.
Referenced by Setup.
TextMeshProUGUI InventoryItemUI.itemNameText
아이템 이름을 표시하는 텍스트 UI 요소입니다.
Referenced by ApplyColor, Setup.
TextMeshProUGUI InventoryItemUI.categoryText
아이템 종류를 표시하는 텍스트 UI 요소입니다.
Referenced by ApplyColor, Setup.
TextMeshProUGUI InventoryItemUI.quantityText
아이템 수량을 표시하는 텍스트 UI 요소입니다.
Referenced by ApplyColor, Setup.
TextMeshProUGUI InventoryItemUI.priceText
아이템 가격을 표시하는 텍스트 UI 요소입니다.
Referenced by ApplyColor, Setup.
MiddlePanelUI InventoryItemUI.middlePanel
아이템 선택 시 열리는 MiddlePanel UI입니다.
Referenced by OnPointerClick.
TradingItemData InventoryItemUI.currentItemData
현재 슬롯에 연결된 아이템 데이터입니다.
Referenced by GetItemData, GetStoredItemName, OnPointerClick, Setup.
int InventoryItemUI.currentQuantity
현재 슬롯의 수량입니다.
Referenced by GetQuantity, OnPointerClick, Setup.
float InventoryItemUI.currentPurchasePrice
현재 슬롯의 구매 당시 가격입니다.
Referenced by Setup.
bool InventoryItemUI.isSelected
현재 슬롯의 선택 상태입니다.
Referenced by OnPointerClick, OnPointerEnter, OnPointerExit, SetSelected, Setup.
Color InventoryItemUI.highlightColor
하이라이트 시 적용할 색상입니다.
Referenced by OnPointerEnter, SetSelected.
Color InventoryItemUI.itemNameOriginalColor
Color InventoryItemUI.priceOriginalColor
Color InventoryItemUI.quantityOriginalColor
Color InventoryItemUI.categoryOriginalColor
InventoryItemUI InventoryItemUI._currentSelectedItem
현재 선택된 슬롯 인스턴스입니다.
Referenced by GetCurrentSelectedItem, OnPointerClick, Setup.
string InventoryItemUI.currentlySelectedItemName
전역으로 저장된 선택된 아이템 이름입니다.
Referenced by OnPointerClick, TradeUIManager.OnSellItemSelected, TradeUIManager.OpenSellPanel, Setup.
void InventoryItemUI.ApplyColor(Color targetColor)
4개 텍스트 색상을 모두 지정된 색으로 설정합니다.
References categoryText, itemNameText, priceText, quantityText.
Referenced by OnPointerEnter, OnPointerExit, SetSelected.
void InventoryItemUI.Setup(TradingItemData itemData, int quantity, float purchasePrice)
아이템 데이터와 수량, 구매 당시 가격을 받아 UI를 초기화합니다.
itemData 아이템 데이터 quantity 아이템 수량 purchasePrice 구매 당시 가격 (kg당)
References _currentSelectedItem, categoryText, currentItemData, currentlySelectedItemName, currentPurchasePrice, currentQuantity, isSelected, itemImage, itemNameText, itemShapeImage, itemShapeSprites, priceText, quantityText, SetSelected.
Referenced by InventoryUI.PopulateInventory.
string InventoryItemUI.GetStoredItemName()
이 슬롯에 연결된 아이템 이름을 반환합니다.
References currentItemData.
void InventoryItemUI.OnPointerEnter(PointerEventData eventData)
마우스 오버 시 강조 색상 적용
References ApplyColor, highlightColor, isInteractable, isSelected.
void InventoryItemUI.OnPointerExit(PointerEventData eventData)
마우스 벗어날 때 원래 색상 복구
References ApplyColor, isInteractable, isSelected.
void InventoryItemUI.OnPointerClick(PointerEventData eventData)
슬롯 클릭 시 선택 토글 및 MiddlePanel/하이라이터 갱신
References _currentSelectedItem, currentItemData, currentlySelectedItemName, currentQuantity, StorageHighlightManager.HighlightItem, TradeUIManager.Instance, isInteractable, isSelected, middlePanel, TradeUIManager.OnSellItemSelected, SetSelected, MiddlePanelUI.SetSelectedItem, MiddlePanelUI.UpdatePlayerComa.
void InventoryItemUI.SetSelected(bool selected)
현재 슬롯의 선택 상태를 설정합니다.
References ApplyColor, highlightColor, isSelected.
Referenced by OnPointerClick, Setup.
TradingItemData InventoryItemUI.GetItemData()
현재 슬롯의 아이템 데이터를 반환합니다.
References currentItemData.
int InventoryItemUI.GetQuantity()
현재 슬롯의 수량을 반환합니다.
References currentQuantity.
static InventoryItemUI InventoryItemUI.GetCurrentSelectedItem()
현재 선택된 InventoryItemUI 슬롯을 반환합니다.
References _currentSelectedItem.
Referenced by TradeUIManager.OpenSellPanel.