HitPointSystem
float HitPointSystem.currentHitPoint
현재 체력 값입니다.
Referenced by ChangeHitPoint, GetHitPoint, GetHitPointPercentage.
override void HitPointSystem.Initialize(Ship ship)
시스템을 초기화하고 최대 체력으로 설정합니다.
ship 초기화 대상 함선 객체.
Referenced by Ship.InitializeSystems.
override void HitPointSystem.Refresh()
void HitPointSystem.RecalculateHitPoint()
override void HitPointSystem.Update(float deltaTime)
매 프레임마다 호출되어 시스템 상태를 갱신합니다.
deltaTime 경과 시간 (초).
Referenced by Ship.Update.
float HitPointSystem.GetHitPoint()
현재 체력 값을 반환합니다.
현재 체력.
References currentHitPoint.
Referenced by Ship.GetCurrentHitPoints, Ship.TakeDamage.
float HitPointSystem.GetHitPointPercentage()
현재 체력의 퍼센트 값을 반환합니다. (0 ~ 100)
현재 체력 / 최대 체력 * 100 값.
References currentHitPoint, ShipSystem.GetShipStat.
void HitPointSystem.ChangeHitPoint(float amount)
체력을 변경합니다. 양수이면 회복, 음수이면 피해를 의미합니다. 최대 체력을 초과하지 않으며, 0 아래로 내려가지 않습니다.
amount 변경할 체력량. (양수/음수)
References currentHitPoint, ShipSystem.GetShipStat.
Referenced by Ship.TakeDamage.