TradeUIManager
Transform TradeUIManager.inventoryPanelContent
TradeSellPanel 안의 InventoryPanel Content Transform입니다. Sell 시에만 상호작용을 허용합니다.
Referenced by CloseOverlayPanels.
InventoryUI TradeUIManager.sellInventoryUI
인벤토리 슬롯을 동적으로 생성/갱신해 주는 스크립트 참조입니다. Inspector에서 InventoryUI 컴포넌트를 드래그&드롭하세요.
Referenced by OpenSellPanel.
StorageHighlightManager TradeUIManager.highlighter
StorageHighlightManager 컴포넌트 참조입니다.
Referenced by OnBackPressed, OnSellItemSelected.
Vector2 TradeUIManager.sellPanelHiddenPosition
Vector2 TradeUIManager.sellPanelVisiblePosition
Vector2 TradeUIManager.buyPanelHiddenPosition
Vector2 TradeUIManager.buyPanelVisiblePosition
Coroutine TradeUIManager.sellSlideCoroutine
Coroutine TradeUIManager.buySlideCoroutine
RectTransform TradeUIManager.tradeTestPanel
메인 화면 패널. 모든 오버레이 창이 닫힐 때 다시 활성화합니다.
Referenced by ReenableMainPanelAfterClosing.
RectTransform TradeUIManager.tradeSellPanel
판매창(TradeSellPanel)의 RectTransform 참조입니다.
Referenced by CloseOverlayPanels, OpenBuyPanel, OpenSellPanel, Start.
RectTransform TradeUIManager.tradeBuyPanel
구매창(TradeBuyPanel)의 RectTransform 참조입니다.
Referenced by CloseOverlayPanels, OpenBuyPanel, OpenSellPanel, Start.
Button TradeUIManager.sellButton
메인 화면의 "Sell" 버튼. 클릭 시 판매창을 엽니다.
Referenced by CloseOverlayPanels, OpenBuyPanel, OpenSellPanel, Start.
Button TradeUIManager.buyButton
메인 화면의 "Buy" 버튼. 클릭 시 구매창을 엽니다.
Referenced by CloseOverlayPanels, OpenBuyPanel, OpenSellPanel, Start.
float TradeUIManager.slideSpeed
오버레이 패널 슬라이드 애니메이션 시간(초)입니다.
Referenced by ReenableMainPanelAfterClosing, SlidePanel.
GameObject TradeUIManager.planetItemPanel
구매창 내 행성 아이템 목록 패널입니다.
Referenced by Start.
GameObject TradeUIManager.buyMiddlePanel
구매창 내 상세 정보(MiddlePanel) 패널입니다.
Referenced by OnBackPressed, OnBuyItemSelected, Start.
GameObject TradeUIManager.storagePanel
구매창 내 StoragePanel(플레이어 인벤토리) 패널입니다.
Referenced by OnBackPressed, OnBuyItemSelected, Start.
Button TradeUIManager.buyBackButton
구매창 상세/Storage에서 뒤로 돌아갈 때 누르는 버튼입니다.
Referenced by Start.
GameObject TradeUIManager.inventoryPanel
판매창 내 플레이어 인벤토리 목록 패널입니다.
Referenced by Start.
GameObject TradeUIManager.sellMiddlePanel
판매창 내 상세 정보(MidSellPanel) 패널입니다.
Referenced by OnBackPressed, OnSellItemSelected, Start.
Button TradeUIManager.sellBackButton
판매창 상세에서 뒤로 돌아갈 때 누르는 버튼입니다.
Referenced by Start.
TradeUIManager TradeUIManager.Instance
이 클래스의 싱글톤 인스턴스입니다.
Referenced by Awake, InventoryItemUI.OnPointerClick, PlanetItemUI.OnPointerClick.
void TradeUIManager.Awake()
싱글톤 패턴을 설정합니다.
References Instance.
void TradeUIManager.Start()
초기화: 메인 버튼, 슬라이드 위치, 서브 패널/뒤로가기 버튼 리스너를 연결하고, 구매/판매창의 서브 패널 초기 상태를 설정합니다.
References buyBackButton, buyButton, buyMiddlePanel, inventoryPanel, OnBackPressed, OpenBuyPanel, OpenSellPanel, planetItemPanel, sellBackButton, sellButton, sellMiddlePanel, storagePanel, tradeBuyPanel, tradeSellPanel.
void TradeUIManager.OnBackPressed()
씬에 배치된 Back 버튼을 클릭했을 때 호출됩니다. 열려 있는 상세 패널을 닫고, 원래 목록 패널로 복귀시킵니다.
References buyMiddlePanel, StorageHighlightManager.ClearHighlights, highlighter, sellMiddlePanel, storagePanel.
Referenced by Start.
IEnumerator TradeUIManager.ReenableMainPanelAfterClosing()
슬라이드 애니메이션이 완료된 후, 메인 화면 패널(tradeTestPanel)을 활성화합니다.
References slideSpeed, tradeTestPanel.
Referenced by CloseOverlayPanels.
IEnumerator TradeUIManager.SlidePanel(RectTransform panel, Vector2 fromPos, Vector2 toPos)
지정된 RectTransform 패널을 fromPos 위치에서 toPos 위치로 slideSpeed 시간에 걸쳐 선형 보간(Lerp)하여 이동시킵니다.
panel 슬라이드할 RectTransform 패널 fromPos 시작 앵커드 위치 toPos 목표 앵커드 위치
References slideSpeed.
Referenced by CloseOverlayPanels, OpenBuyPanel, OpenSellPanel.
void TradeUIManager.OnBuyItemSelected()
행성 아이템 목록에서 아이템을 선택했을 때 호출합니다. 구매창의 상세 정보와 StoragePanel을 활성화합니다. Inspector에서 PlanetItemPanel 내 각 아이템 버튼의 OnClick에 연결하세요.
References buyMiddlePanel, storagePanel.
Referenced by PlanetItemUI.OnPointerClick.
void TradeUIManager.OnSellItemSelected()
인벤토리 목록에서 아이템을 선택했을 때 호출합니다. 판매창의 상세 정보 패널(MidSellPanel)을 활성화합니다. Inspector에서 InventoryPanel 내 각 아이템 버튼의 OnClick에 연결하세요.
References InventoryItemUI.currentlySelectedItemName, highlighter, StorageHighlightManager.HighlightItem, sellMiddlePanel.
Referenced by InventoryItemUI.OnPointerClick.
void TradeUIManager.OpenSellPanel()
메인 화면의 "Sell" 버튼 클릭 시 호출됩니다. 기존에 열려 있던 구매창이 있으면 닫고, 판매창을 슬라이드 인합니다.
References buyButton, InventoryItemUI.currentlySelectedItemName, InventoryItemUI.GetCurrentSelectedItem, InventoryUI.PopulateInventory, sellButton, sellInventoryUI, MiddlePanelUI.SetSelectedItem, SlidePanel, tradeBuyPanel, tradeSellPanel, MiddlePanelUI.UpdatePlayerComa.
Referenced by Start.
void TradeUIManager.OpenBuyPanel()
메인 화면의 "Buy" 버튼 클릭 시 호출됩니다. 기존에 열려 있던 판매창이 있으면 닫고, 구매창을 슬라이드 인합니다.
References buyButton, sellButton, SlidePanel, tradeBuyPanel, tradeSellPanel, MiddlePanelUI.UpdatePlayerComa.
Referenced by Start.
void TradeUIManager.CloseOverlayPanels()
현재 열려 있는 모든 오버레이 패널(구매/판매)을 순차적으로 닫습니다. 슬라이드 아웃 애니메이션 후 메인 패널을 다시 활성화합니다.
References buyButton, inventoryPanelContent, ReenableMainPanelAfterClosing, sellButton, SlidePanel, tradeBuyPanel, tradeSellPanel.