StorageRoomBase
List<TradingItem> StorageRoomBase.storedItems
저장된 아이템 목록.
Referenced by AddItem, TradingItemDragHandler.CancelDragging, CheckItemsAfterWarp, DestroyAllItems, DestroyItem, TradingItemDragHandler.EndDragging, TradeUIController.OnBuyCancelButtonClicked, TradeUIController.OnBuyConfirmButtonClicked, RemoveItem, TradingItemDragHandler.ResetAllItemsInteractivity, TradeUIController.SellItem.
TradingItem [,] StorageRoomBase.itemGrid
TradingItem StorageRoomBase.selectedItem
현재 선택된 아이템
Referenced by SelectItem.
BoxCollider2D StorageRoomBase.storageCollider
창고 콜라이더
Referenced by InitializeCollider.
override void StorageRoomBase.Start()
초기화 시 방 타입을 Storage로 설정합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::workDirection.
virtual void StorageRoomBase.InitializeCollider()
창고 영역을 위한 콜라이더 초기화
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize, storageCollider.
Referenced by Initialize.
virtual bool StorageRoomBase.IsValidStorageForItem(TradingItem item)
현재 창고가 해당 아이템에 적합한지 확인합니다. 기본적으로는 항상 적합하며, 온도 조절 창고 등에서 오버라이드합니다.
Referenced by CheckItemsAfterWarp.
virtual void StorageRoomBase.DegradeItemState(TradingItem item)
아이템의 상태를 저하시킵니다. 아이템은 점점 더 손상된 상태로 변경됩니다.
Referenced by CheckItemsAfterWarp.
override void StorageRoomBase.Initialize(int level)
방을 초기화합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize, InitializeCollider, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::roomType.
Referenced by RoomFactory.CreateStorageRoomInstance.
override Dictionary< ShipStat, float > StorageRoomBase.GetStatContributions()
이 방이 함선 스탯에 기여하는 값을 계산합니다. 작동 여부에 따라 전력 사용량을 기여합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::currentRoomLevelData, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::IsOperational.
StorageType StorageRoomBase.GetStorageType()
현재 창고의 저장 타입을 반환합니다.
void StorageRoomBase.SetStorageType(StorageType storageType)
bool StorageRoomBase.CanStoreItemType(ItemCategory itemType)
해당 아이템을 저장할 수 있는지 여부를 반환합니다. 파생 클래스에서 구현합니다.
Referenced by CanPlaceItem.
bool StorageRoomBase.CanPlaceItem(TradingItem item, Vector2Int position, Constants.Rotations.Rotation rotation)
아이템을 지정된 위치에 배치할 수 있는지 확인합니다.
References CanStoreItemType, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetOccupiedTiles, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::position.
Referenced by AddItem, TradingItemDragHandler.EndDragging, RotateItem, TradingItemDragHandler.Update.
virtual bool StorageRoomBase.AddItem(TradingItem item, Vector2Int position, Constants.Rotations.Rotation rotation)
아이템을 창고에 추가합니다.
References CanPlaceItem, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetOccupiedTiles, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::position, RemoveItem, TradingItem.SetDragMode, storedItems.
Referenced by TradingItemDragHandler.CancelDragging, TradingItemDragHandler.EndDragging, TradeUIController.OnBuyCheckBuyButtonClicked, RotateItem.
virtual bool StorageRoomBase.RemoveItem(TradingItem item)
아이템을 창고에서 제거합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize, storedItems.
Referenced by AddItem, DestroyItem, TradingItemDragHandler.EndDragging, TradeUIController.OnBuyCancelButtonClicked, RotateItem.
void StorageRoomBase.RemoveAllItems()
virtual bool StorageRoomBase.DestroyItem(TradingItem item)
아이템을 완전히 삭제합니다.
References RemoveItem, storedItems.
Referenced by DestroyAllItems.
void StorageRoomBase.DestroyAllItems()
창고의 모든 아이템을 완전히 삭제합니다.
References DestroyItem, storedItems.
virtual void StorageRoomBase.CheckItemsAfterWarp()
워프 후 아이템 상태를 확인 및 갱신합니다.
References DegradeItemState, IsValidStorageForItem, storedItems.
Referenced by StorageRoomTemperature.SetPowerStatus.
List< Vector2Int > StorageRoomBase.GetOccupiedTiles(TradingItem item, Vector2Int position, Constants.Rotations.Rotation rotation)
아이템이 점유하는 모든 타일의 좌표를 반환합니다.
Referenced by TradingItemDragHandler.UpdatePreviewToGridPosition.
Vector2Int StorageRoomBase.WorldToGridPosition(Vector2 worldPos)
월드 좌표를 그리드 좌표로 변환합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize.
Referenced by TradingItemDragHandler.EndDragging, TradingItemDragHandler.UpdatePreviewPosition.
Vector3 StorageRoomBase.GridToWorldPosition(Vector2Int gridPos)
그리드 좌표를 월드 좌표로 변환합니다.
References Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::GetSize.
Referenced by TradingItemDragHandler.CancelDragging, TradingItemDragHandler.EndDragging.
virtual void StorageRoomBase.SelectItem(TradingItem item)
선택된 아이템 설정
References selectedItem.
virtual bool StorageRoomBase.RotateItem(TradingItem item)
아이템 회전
References AddItem, CanPlaceItem, Room< StorageRoomBaseData, StorageRoomBaseData.StorageRoomBaseLevel >::currentRotation, RemoveItem, TradingItem.Rotate.
List< TradingItem > StorageRoomBase.GetStoredItems()
List< TradingItem > StorageRoomBase.GetStoredItemsById(int id)
List< TradingItem > StorageRoomBase.GetStoredItemsByName(string name)
List< TradingItem > StorageRoomBase.GetStoredItemsByCategory(ItemCategory category)
Vector2Int StorageRoomBase.FindBottomLeftTile(List< Vector2Int > tiles)