ES3File
Dictionary<string, ES3File> ES3File.cachedFiles
ES3Settings ES3File.settings
Dictionary<string, ES3Data> ES3File.cache
bool ES3File.syncWithFile
DateTime ES3File.timestamp
bool ES3File.dirty
ES3File.ES3File()
Creates a new ES3File and loads the default file into the ES3File if there is data to load.
ES3File.ES3File(string filePath)
Creates a new ES3File and loads the specified file into the ES3File if there is data to load.
filepath The relative or absolute path of the file in storage our ES3File is associated with.
ES3File.ES3File(string filePath, ES3Settings settings)
Creates a new ES3File and loads the specified file into the ES3File if there is data to load.
filepath The relative or absolute path of the file in storage our ES3File is associated with. settings The settings we want to use to override the default settings.
ES3File.ES3File(ES3Settings settings)
Creates a new ES3File and loads the specified file into the ES3File if there is data to load.
settings The settings we want to use to override the default settings.
ES3File.ES3File(bool syncWithFile)
Creates a new ES3File and only loads the default file into it if syncWithFile is set to true.
syncWithFile Whether we should sync this ES3File with the one in storage immediately after creating it.
ES3File.ES3File(string filePath, bool syncWithFile)
Creates a new ES3File and only loads the specified file into it if syncWithFile is set to true.
filepath The relative or absolute path of the file in storage our ES3File is associated with. syncWithFile Whether we should sync this ES3File with the one in storage immediately after creating it.
ES3File.ES3File(string filePath, ES3Settings settings, bool syncWithFile)
Creates a new ES3File and only loads the specified file into it if syncWithFile is set to true.
filepath The relative or absolute path of the file in storage our ES3File is associated with. settings The settings we want to use to override the default settings. syncWithFile Whether we should sync this ES3File with the one in storage immediately after creating it.
ES3File.ES3File(ES3Settings settings, bool syncWithFile)
Creates a new ES3File and loads the specified file into the ES3File if there is data to load.
settings The settings we want to use to override the default settings. syncWithFile Whether we should sync this ES3File with the one in storage immediately after creating it.
References ES3Reader.Create.
ES3File.ES3File(byte[] bytes, ES3Settings settings=null)
Creates a new ES3File and loads the bytes into the ES3File. Note the bytes must represent that of a file.
bytes The bytes representing our file. settings The settings we want to use to override the default settings. syncWithFile Whether we should sync this ES3File with the one in storage immediately after creating it.
References SaveRaw.
void ES3File.Sync()
Synchronises this ES3File with a file in storage.
References Sync.
Referenced by Sync, Sync.
void ES3File.Sync(string filePath, ES3Settings settings=null)
Synchronises this ES3File with a file in storage.
filepath The relative or absolute path of the file in storage we want to synchronise with. settings The settings we want to use to override the default settings.
References Sync.
void ES3File.Sync(ES3Settings settings=null)
Synchronises this ES3File with a file in storage.
settings The settings we want to use to override the default settings.
References ES3Writer.Create, ES3.DeleteFile.
void ES3File.Clear()
Removes the data stored in this ES3File. The ES3File will be empty after calling this method.
string[] ES3File.GetKeys()
Returns an array of all of the key names in this ES3File.
Referenced by ES3.GetKeys.
void ES3File.Save< T >(string key, T value)
Saves a value to a key in this ES3File.
key The key we want to use to identify our value in the file. value The value we want to save.
void ES3File.SaveRaw(byte[] bytes, ES3Settings settings=null)
Merges the data specified by the bytes parameter into this ES3File.
bytes The bytes we want to merge with this ES3File. settings The settings we want to use to override the default settings.
References ES3Reader.Create.
Referenced by AppendRaw, ES3.AppendRaw, ES3File, ES3.SaveRaw.
void ES3File.AppendRaw(byte[] bytes, ES3Settings settings=null)
Merges the data specified by the bytes parameter into this ES3File.
bytes The bytes we want to merge with this ES3File. settings The settings we want to use to override the default settings.
References SaveRaw.
Referenced by ES3.AppendRaw.
object ES3File.Load(string key)
Loads the value from this ES3File with the given key.
key The key which identifies the value we want to load.
Referenced by ES3.Load< T >, ES3.Load< T >.
object ES3File.Load(string key, object defaultValue)
Loads the value from this ES3File with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the key does not exist in this ES3File.
T ES3File.Load< T >(string key)
Loads the value from this ES3File with the given key.
key The key which identifies the value we want to load.
T ES3File.Load< T >(string key, T defaultValue)
Loads the value from this ES3File with the given key.
key The key which identifies the value we want to load. defaultValue The value we want to return if the key does not exist in this ES3File.
void ES3File.LoadInto< T >(string key, T obj)
Loads the value from this ES3File with the given key into an existing object.
key The key which identifies the value we want to load. obj The object we want to load the value into.
byte[] ES3File.LoadRawBytes()
Loads the ES3File as a raw, unencrypted, uncompressed byte array.
Referenced by ES3.LoadRawBytes, LoadRawString.
string ES3File.LoadRawString()
Loads the ES3File as a raw, unencrypted, uncompressed string, using the encoding defined in the ES3File's settings variable.
References ES3Settings.encoding, LoadRawBytes.
void ES3File.DeleteKey(string key)
Deletes a key from this ES3File.
key The key we want to delete.
Referenced by ES3.DeleteKey.
bool ES3File.KeyExists(string key)
Checks whether a key exists in this ES3File.
key The key we want to check the existence of. True if the key exists, otherwise False.
Referenced by ES3.KeyExists.
int ES3File.Size()
Gets the size of the cached data in bytes.
Type ES3File.GetKeyType(string key)
byte[] ES3File.GetBytes(ES3Settings settings=null)
static ES3File ES3File.GetCachedFile(ES3Settings settings)
static ES3File ES3File.GetOrCreateCachedFile(ES3Settings settings)
static ES3File ES3File.CacheFile(ES3Settings settings)
static void ES3File.Store(ES3Settings settings=null)
static void ES3File.StoreAll()
static void ES3File.RemoveCachedFile(ES3Settings settings)
static void ES3File.CopyCachedFile(ES3Settings oldSettings, ES3Settings newSettings)
static void ES3File.DeleteKey(string key, ES3Settings settings)
static bool ES3File.KeyExists(string key, ES3Settings settings)
static bool ES3File.FileExists(ES3Settings settings)
static string[] ES3File.GetKeys(ES3Settings settings)
static string[] ES3File.GetFiles()
static DateTime ES3File.GetTimestamp(ES3Settings settings)