InputSystem_Actions::IUIActions
void InputSystem_Actions.IUIActions.OnNavigate(InputAction.CallbackContext context)
Method invoked when associated input action "Navigate" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnSubmit(InputAction.CallbackContext context)
Method invoked when associated input action "Submit" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnCancel(InputAction.CallbackContext context)
Method invoked when associated input action "Cancel" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnPoint(InputAction.CallbackContext context)
Method invoked when associated input action "Point" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnClick(InputAction.CallbackContext context)
Method invoked when associated input action "Click" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnRightClick(InputAction.CallbackContext context)
Method invoked when associated input action "RightClick" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnMiddleClick(InputAction.CallbackContext context)
Method invoked when associated input action "MiddleClick" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnScrollWheel(InputAction.CallbackContext context)
Method invoked when associated input action "ScrollWheel" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnTrackedDevicePosition(InputAction.CallbackContext context)
Method invoked when associated input action "TrackedDevicePosition" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnTrackedDeviceOrientation(InputAction.CallbackContext context)
Method invoked when associated input action "TrackedDeviceOrientation" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.IUIActions.OnOpenQuestList(InputAction.CallbackContext context)
Method invoked when associated input action "OpenQuestList" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.