IBlueprintPlaceable
object IBlueprintPlaceable.GetRotation()
현재 회전 상태 반환
Referenced by GridPlacer.CanPlaceObject.
Vector2Int IBlueprintPlaceable.GetGridPosition()
현재 그리드 위치 반환
Referenced by GridPlacer.CanPlaceObject.
void IBlueprintPlaceable.SetGridPosition(Vector2Int position)
그리드 위치 설정
Referenced by GridPlacer.CanPlaceObject.
List< Vector2Int > IBlueprintPlaceable.GetOccupiedTiles()
점유하고 있는 타일 목록 반환
Referenced by GridPlacer.CanPlaceObject, GridPlacer.GetCameraStartPositionToBP, BlueprintShip.GetObjectAt, GridPlacer.MarkObjectOccupied, GridPlacer.UnMarkObjectOccupied.
void IBlueprintPlaceable.SetGridPlacer(GridPlacer placer)
그리드 배치 담당 오브젝트 세팅
void IBlueprintPlaceable.SetBlueprint(BlueprintShip bpShip)
설계도 함선 할당
BlueprintShip IBlueprintPlaceable.GetBlueprintShip()
설계도 함선 호출
Referenced by RoomSelectionHandler.ConfirmDelete.
int IBlueprintPlaceable.GetCost()
설치 비용 반환
Referenced by BlueprintShip.GetTotalBPCost.
void IBlueprintPlaceable.SetDragMode(bool isDragging)
드래그 모드 설정