IGameStateMachine
void IGameStateMachine.Enter()
상태에 진입할 때 호출됩니다. 상태를 초기화하거나 필요한 컴포넌트를 설정하는 등의 작업을 수행합니다.
Referenced by GameStateManager.ChangeState.
void IGameStateMachine.Update()
매 프레임 호출됩니다. 상태에 따른 업데이트 로직을 처리합니다.
Referenced by GameStateManager.Update.
void IGameStateMachine.Exit()
상태가 종료될 때 호출됩니다. 상태 종료 시 정리 작업이나 이벤트 구독 해제 등을 수행합니다.
Referenced by GameStateManager.ChangeState.