InputSystem_Actions::IPlayerActions
void InputSystem_Actions.IPlayerActions.OnMove(InputAction.CallbackContext context)
Method invoked when associated input action "Move" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnLook(InputAction.CallbackContext context)
Method invoked when associated input action "Look" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnAttack(InputAction.CallbackContext context)
Method invoked when associated input action "Attack" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnInteract(InputAction.CallbackContext context)
Method invoked when associated input action "Interact" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnCrouch(InputAction.CallbackContext context)
Method invoked when associated input action "Crouch" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnJump(InputAction.CallbackContext context)
Method invoked when associated input action "Jump" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnPrevious(InputAction.CallbackContext context)
Method invoked when associated input action "Previous" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnNext(InputAction.CallbackContext context)
Method invoked when associated input action "Next" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.IPlayerActions.OnSprint(InputAction.CallbackContext context)
Method invoked when associated input action "Sprint" is either UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed or UnityEngine.InputSystem.InputAction.canceled.
UnityEngine.InputSystem.InputAction.started, UnityEngine.InputSystem.InputAction.performed, UnityEngine.InputSystem.InputAction.canceled
Referenced by InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.