InputSystem_Actions::PlayerActions
InputSystem_Actions InputSystem_Actions.PlayerActions.m_Wrapper
InputAction InputSystem_Actions.PlayerActions.Move
Provides access to the underlying input action "Player/Move".
InputAction InputSystem_Actions.PlayerActions.Look
Provides access to the underlying input action "Player/Look".
InputAction InputSystem_Actions.PlayerActions.Attack
Provides access to the underlying input action "Player/Attack".
InputAction InputSystem_Actions.PlayerActions.Interact
Provides access to the underlying input action "Player/Interact".
InputAction InputSystem_Actions.PlayerActions.Crouch
Provides access to the underlying input action "Player/Crouch".
InputAction InputSystem_Actions.PlayerActions.Jump
Provides access to the underlying input action "Player/Jump".
InputAction InputSystem_Actions.PlayerActions.Previous
Provides access to the underlying input action "Player/Previous".
InputAction InputSystem_Actions.PlayerActions.Next
Provides access to the underlying input action "Player/Next".
InputAction InputSystem_Actions.PlayerActions.Sprint
Provides access to the underlying input action "Player/Sprint".
bool InputSystem_Actions.PlayerActions.enabled
InputSystem_Actions.PlayerActions.PlayerActions(@InputSystem_Actions wrapper)
Construct a new instance of the input action map wrapper class.
InputActionMap InputSystem_Actions.PlayerActions.Get()
Provides access to the underlying input action map instance.
Referenced by InputSystem_Actions.PlayerActions.Disable, InputSystem_Actions.PlayerActions.Enable.
void InputSystem_Actions.PlayerActions.Enable()
References InputSystem_Actions.PlayerActions.Get.
void InputSystem_Actions.PlayerActions.Disable()
References InputSystem_Actions.PlayerActions.Get.
void InputSystem_Actions.PlayerActions.AddCallbacks(IPlayerActions instance)
Adds InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
instance Callback instance. If instance is null or instance have already been added this method does nothing. PlayerActions
References InputSystem_Actions.IPlayerActions.OnAttack, InputSystem_Actions.IPlayerActions.OnCrouch, InputSystem_Actions.IPlayerActions.OnInteract, InputSystem_Actions.IPlayerActions.OnJump, InputSystem_Actions.IPlayerActions.OnLook, InputSystem_Actions.IPlayerActions.OnMove, InputSystem_Actions.IPlayerActions.OnNext, InputSystem_Actions.IPlayerActions.OnPrevious, InputSystem_Actions.IPlayerActions.OnSprint.
Referenced by InputSystem_Actions.PlayerActions.SetCallbacks.
void InputSystem_Actions.PlayerActions.RemoveCallbacks(IPlayerActions instance)
Unregisters and unregisters all input action callbacks via PlayerActions.UnregisterCallbacks(IPlayerActions).
PlayerActions.UnregisterCallbacks(IPlayerActions)
References InputSystem_Actions.PlayerActions.UnregisterCallbacks.
void InputSystem_Actions.PlayerActions.SetCallbacks(IPlayerActions instance)
Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via .
If instance is null, calling this method will only unregister all existing callbacks but not register any new callbacks. PlayerActions.AddCallbacks(IPlayerActions), PlayerActions.RemoveCallbacks(IPlayerActions), PlayerActions.UnregisterCallbacks(IPlayerActions)
References InputSystem_Actions.PlayerActions.AddCallbacks, InputSystem_Actions.PlayerActions.UnregisterCallbacks.
static implicit InputSystem_Actions.PlayerActions.operator InputActionMap(PlayerActions set)
Implicitly converts an to an instance.
void InputSystem_Actions.PlayerActions.UnregisterCallbacks(IPlayerActions instance)
Removes InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
Calling this method when instance have not previously been registered has no side-effects. PlayerActions
References InputSystem_Actions.IPlayerActions.OnAttack, InputSystem_Actions.IPlayerActions.OnCrouch, InputSystem_Actions.IPlayerActions.OnInteract, InputSystem_Actions.IPlayerActions.OnJump, InputSystem_Actions.IPlayerActions.OnLook, InputSystem_Actions.IPlayerActions.OnMove, InputSystem_Actions.IPlayerActions.OnNext, InputSystem_Actions.IPlayerActions.OnPrevious, InputSystem_Actions.IPlayerActions.OnSprint.
Referenced by InputSystem_Actions.PlayerActions.RemoveCallbacks, InputSystem_Actions.PlayerActions.SetCallbacks.