InputSystem_Actions::UIActions
InputSystem_Actions InputSystem_Actions.UIActions.m_Wrapper
InputAction InputSystem_Actions.UIActions.Navigate
Provides access to the underlying input action "UI/Navigate".
InputAction InputSystem_Actions.UIActions.Submit
Provides access to the underlying input action "UI/Submit".
InputAction InputSystem_Actions.UIActions.Cancel
Provides access to the underlying input action "UI/Cancel".
InputAction InputSystem_Actions.UIActions.Point
Provides access to the underlying input action "UI/Point".
InputAction InputSystem_Actions.UIActions.Click
Provides access to the underlying input action "UI/Click".
InputAction InputSystem_Actions.UIActions.RightClick
Provides access to the underlying input action "UI/RightClick".
InputAction InputSystem_Actions.UIActions.MiddleClick
Provides access to the underlying input action "UI/MiddleClick".
InputAction InputSystem_Actions.UIActions.ScrollWheel
Provides access to the underlying input action "UI/ScrollWheel".
InputAction InputSystem_Actions.UIActions.TrackedDevicePosition
Provides access to the underlying input action "UI/TrackedDevicePosition".
InputAction InputSystem_Actions.UIActions.TrackedDeviceOrientation
Provides access to the underlying input action "UI/TrackedDeviceOrientation".
InputAction InputSystem_Actions.UIActions.OpenQuestList
Provides access to the underlying input action "UI/OpenQuestList".
bool InputSystem_Actions.UIActions.enabled
InputSystem_Actions.UIActions.UIActions(@InputSystem_Actions wrapper)
Construct a new instance of the input action map wrapper class.
InputActionMap InputSystem_Actions.UIActions.Get()
Provides access to the underlying input action map instance.
Referenced by InputSystem_Actions.UIActions.Disable, InputSystem_Actions.UIActions.Enable.
void InputSystem_Actions.UIActions.Enable()
References InputSystem_Actions.UIActions.Get.
void InputSystem_Actions.UIActions.Disable()
References InputSystem_Actions.UIActions.Get.
void InputSystem_Actions.UIActions.AddCallbacks(IUIActions instance)
Adds InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
instance Callback instance. If instance is null or instance have already been added this method does nothing. UIActions
References InputSystem_Actions.IUIActions.OnCancel, InputSystem_Actions.IUIActions.OnClick, InputSystem_Actions.IUIActions.OnMiddleClick, InputSystem_Actions.IUIActions.OnNavigate, InputSystem_Actions.IUIActions.OnOpenQuestList, InputSystem_Actions.IUIActions.OnPoint, InputSystem_Actions.IUIActions.OnRightClick, InputSystem_Actions.IUIActions.OnScrollWheel, InputSystem_Actions.IUIActions.OnSubmit, InputSystem_Actions.IUIActions.OnTrackedDeviceOrientation, InputSystem_Actions.IUIActions.OnTrackedDevicePosition.
Referenced by InputSystem_Actions.UIActions.SetCallbacks.
void InputSystem_Actions.UIActions.RemoveCallbacks(IUIActions instance)
Unregisters and unregisters all input action callbacks via UIActions.UnregisterCallbacks(IUIActions).
UIActions.UnregisterCallbacks(IUIActions)
References InputSystem_Actions.UIActions.UnregisterCallbacks.
void InputSystem_Actions.UIActions.SetCallbacks(IUIActions instance)
Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via .
If instance is null, calling this method will only unregister all existing callbacks but not register any new callbacks. UIActions.AddCallbacks(IUIActions), UIActions.RemoveCallbacks(IUIActions), UIActions.UnregisterCallbacks(IUIActions)
References InputSystem_Actions.UIActions.AddCallbacks, InputSystem_Actions.UIActions.UnregisterCallbacks.
static implicit InputSystem_Actions.UIActions.operator InputActionMap(UIActions set)
Implicitly converts an to an instance.
void InputSystem_Actions.UIActions.UnregisterCallbacks(IUIActions instance)
Removes InputAction.started, InputAction.performed and InputAction.canceled callbacks provided via on all input actions contained in this map.
Calling this method when instance have not previously been registered has no side-effects. UIActions
References InputSystem_Actions.IUIActions.OnCancel, InputSystem_Actions.IUIActions.OnClick, InputSystem_Actions.IUIActions.OnMiddleClick, InputSystem_Actions.IUIActions.OnNavigate, InputSystem_Actions.IUIActions.OnOpenQuestList, InputSystem_Actions.IUIActions.OnPoint, InputSystem_Actions.IUIActions.OnRightClick, InputSystem_Actions.IUIActions.OnScrollWheel, InputSystem_Actions.IUIActions.OnSubmit, InputSystem_Actions.IUIActions.OnTrackedDeviceOrientation, InputSystem_Actions.IUIActions.OnTrackedDevicePosition.
Referenced by InputSystem_Actions.UIActions.RemoveCallbacks, InputSystem_Actions.UIActions.SetCallbacks.