name: Build and Push Doxygen Docs to gh-pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Install Graphviz
        run: sudo apt-get install graphviz -y

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Create combined documentation directory
        run: |
          mkdir -p ./docs/combined
          cp -r ./docs/html/* ./docs/combined/
          mkdir -p ./docs/combined/xml
          cp -r ./docs/xml/* ./docs/combined/xml/

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/combined
          publish_branch: gh-pages
          force_orphan: true