name: Build and Push Doxygen Docs to gh-pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Install Graphviz
        run: sudo apt-get install graphviz -y

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Create combined documentation directory
        run: |
          mkdir -p ./docs/combined
          cp -r ./docs/html/* ./docs/combined/
          mkdir -p ./docs/combined/xml
          cp -r ./docs/xml/* ./docs/combined/xml/

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/combined
          publish_branch: gh-pages
          force_orphan: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: pip install pandas openpyxl

      - name: Convert Excel to JSON
        run: python excel_to_json.py

      - name: Ensure StreamingAssets directory exists
        run: mkdir -p ./Assets/StreamingAssets

      - name: Copy JSON files to StreamingAssets
        run: cp -r json_output/*.json ./Assets/StreamingAssets/

      - name: Commit generated JSON to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git add ./Assets/StreamingAssets/*.json
          git commit -m "Auto-update JSON files from Excel" || echo "No changes to commit"
          git push origin main