name: Build and Push Doxygen Docs to gh-pages

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
