name: Build Doxygen Docs Only

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    
name: Checkout source
    uses: actions/checkout@v3

    
name: Install Doxygen
    run: sudo apt-get install doxygen -y

    
name: Generate Doxygen documentation
    run: doxygen Doxyfile

    
name: Archive generated docs
    uses: actions/upload-artifact@v3
    with:
      name: doxygen-docs
      path: ./docs/html